// Star Wars: Além da Fronteira — habilidades de classe, Grupo C
// Padawan Jedi, Acólito Sith, Andarilho da Força
//
// Sistema de Pools: `level` guarda o tier em que o pool abre (1/6/11/16), não um nível linear.
// Pools nunca fecham — ver POOL_CLASS_IDS/getRemainingPoolAbilities em lib/starwars/leveling.ts.
// As 7 Formas de Sabre viraram habilidades de pool normais (dado Base, sem ×atributo/×2) —
// não usam mais `weaponDamage`/`formTag`. Esses dois campos continuam existindo no tipo só
// porque as classes especiais em classGroupD.ts (fora deste redesenho) ainda os usam.

import type { ClassAbilityTable } from "./types";

export const CLASS_GROUP_C: ClassAbilityTable[] = [
  // ─── Classes-base ligadas à Força (aprendem Formas de Sabre) ────────────────
  {
    classId: "padawan_jedi",
    abilities: [
      { level: 1, name: "Forma de Sabre Shii-Cho (I)", combat: true, description: "Estilo fundamental e agressivo, focado em golpes amplos e controle de múltiplos oponentes.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Makashi (II)", combat: true, description: "Estilo elegante e preciso, especializado em duelos de sabre contra sabre.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Soresu (III)", combat: true, description: "Estilo defensivo e eficiente, focado em proteção e deflexão de ataques.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Ataru (IV)", combat: true, description: "Estilo acrobático e ofensivo, usando velocidade e saltos para pressionar o inimigo.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Djem So (V)", combat: true, description: "Estilo poderoso e dominante, baseado em contra-ataques pesados e controle do ritmo do combate.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Niman (VI)", combat: true, description: "Estilo equilibrado que combina sabre e poderes da Força de forma fluida.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Vaapad (VII)", combat: true, description: "Estilo caótico e intenso que canaliza emoções violentas e imprevisibilidade no combate.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Empurrão da Luz", combat: true, description: "Onda de Força controlada que repele e desequilibra inimigos sem feri-los desnecessariamente.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Foco Sereno", combat: false, description: "Aumenta drasticamente reflexos e velocidade de reação através de calma e clareza mental.", peCost: 1, dt: 15, skillId: "acrobacia" },
      { level: 1, name: "Salto da Luz", combat: true, description: "Impulso poderoso com a Força seguido de um ataque controlado ao aterrissar.", peCost: 1, damageDice: "2d6" },
      { level: 6, name: "Barreira Refletora", combat: true, description: "Reflete disparos de energia de volta ao atacante.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Sugestão Mental", combat: false, description: "Influencia mentes fracas para semear calma, dúvida ou obediência temporária, de forma sutil e não-violenta.", peCost: 2, dt: 17, skillId: "dominio_forca" },
      { level: 6, name: "Onda Serena", combat: true, description: "Explosão concêntrica de Força controlada que afasta múltiplos inimigos sem feri-los gravemente.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Grito Ressonante", combat: true, description: "Grito potencializado pela Força que causa dano sonoro e desorienta.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Presença Tranquila", combat: false, description: "Acalma aliados próximos e resiste a efeitos de medo e pânico.", peCost: 2, dt: 17, skillId: "vontade" },
      { level: 11, name: "Golpe Certeiro", combat: true, description: "Ataque de sabre que ignora parcialmente a defesa do oponente.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Lançamento de Sabre", combat: true, description: "Arremessa o sabre de luz controlado pela Força para atacar à distância.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Toque de Clareza", combat: false, description: "Ao tocar o alvo, dissipa raiva, medo ou confusão nele.", peCost: 2, dt: 20, skillId: "dominio_forca" },
      { level: 11, name: "Punho da Luz", combat: true, description: "Concentra energia luminosa em um soco ou golpe corpo a corpo extremamente poderoso.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Visão da Verdade", combat: false, description: "Enxerga através de ilusões e mentiras, revelando a real intenção ou localização do inimigo.", peCost: 2, dt: 20, skillId: "percepcao" },
      { level: 16, name: "Corrente de Luz", combat: true, description: "Dispara uma corrente de energia luminosa que pode prender e imobilizar o alvo sem feri-lo gravemente.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Presença Radiante", combat: false, description: "Projeta uma aura em área que fortalece aliados e impõe incerteza aos inimigos.", peCost: 3, dt: 20, skillId: "persuasao" },
      { level: 16, name: "Máscara da Presença", combat: false, description: "Esconde a própria presença na Força, dificultando detecção por outros sensíveis.", peCost: 3, dt: 20, skillId: "furtividade" },
      { level: 16, name: "Amplificação Corporal", combat: false, description: "Usa a Força para aumentar temporariamente força, resistência e agilidade.", peCost: 3, dt: 20, skillId: "atletismo" },
      { level: 16, name: "Contenção Gentil", combat: false, description: "Imobiliza o alvo à distância sem sufocá-lo — controle puro, sem dano.", peCost: 3, dt: 20, skillId: "dominio_forca" },
    ],
    milestones: [
      { level: 25, name: "Peso da Luz", description: "Aumenta drasticamente a gravidade em uma área, imobilizando e enfraquecendo inimigos sem esmagá-los brutalmente.", combat: false, peCost: 4, dt: 23, skillId: "dominio_forca" },
      { level: 30, name: "Serenidade Ardente", description: "Acelera reflexos e resistência através de foco absoluto sob pressão extrema.", combat: false, peCost: 5, dt: 23, skillId: "vontade" },
      { level: 35, name: "Explosão de Luz", description: "Libera uma explosão concentrada de energia luminosa a partir do corpo, empurrando e cegando todos ao redor.", combat: true, peCost: 6, damageDice: "9d6" },
      { level: 40, name: "Doação de Força", description: "Transfere parte da própria energia vital para fortalecer um aliado à distância.", combat: true, peCost: 7, damageDice: "10d6", heal: true },
    ],
  },
  {
    classId: "acolito_sith",
    abilities: [
      { level: 1, name: "Forma de Sabre Shii-Cho (I)", combat: true, description: "Estilo fundamental e agressivo, focado em golpes amplos e controle de múltiplos oponentes.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Makashi (II)", combat: true, description: "Estilo elegante e preciso, especializado em duelos de sabre contra sabre.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Soresu (III)", combat: true, description: "Estilo defensivo e eficiente, focado em proteção e deflexão de ataques.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Ataru (IV)", combat: true, description: "Estilo acrobático e ofensivo, usando velocidade e saltos para pressionar o inimigo.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Djem So (V)", combat: true, description: "Estilo poderoso e dominante, baseado em contra-ataques pesados e controle do ritmo do combate.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Niman (VI)", combat: true, description: "Estilo equilibrado que combina sabre e poderes da Força de forma fluida.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Vaapad (VII)", combat: true, description: "Estilo caótico e intenso que canaliza emoções violentas e imprevisibilidade no combate.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Empurrão Sombrio", combat: true, description: "Onda de Força bruta que empurra e derruba inimigos.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Aceleração Sombria", combat: false, description: "Aumenta drasticamente a velocidade de movimento e reação por um curto período.", peCost: 1, dt: 15, skillId: "acrobacia" },
      { level: 1, name: "Salto Predatório", combat: true, description: "Impulso poderoso com a Força seguido de ataque ao aterrissar.", peCost: 1, damageDice: "2d6" },
      { level: 6, name: "Relâmpago Menor", combat: true, description: "Descarga de energia elétrica de curto alcance lançada pelas mãos.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Domínio Mental Básico", combat: false, description: "Influencia mentes fracas para semear dúvida, medo ou obediência temporária.", peCost: 2, dt: 17, skillId: "dominio_forca" },
      { level: 6, name: "Deflexão Impiedosa", combat: true, description: "Defende ataques de energia e responde imediatamente com contra-ataque.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Onda de Ódio", combat: true, description: "Explosão concêntrica de energia sombria que afasta e fere múltiplos inimigos.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Grito da Força", combat: true, description: "Grito potencializado pela Força que causa dano sonoro e desorienta.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Golpe Impiedoso", combat: true, description: "Ataque de sabre que ignora parcialmente a defesa do oponente.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Lançamento de Sabre", combat: true, description: "Arremessa o sabre de luz controlado pela Força para atacar à distância.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Toque da Agonia", combat: false, description: "Ao tocar o alvo, provoca dor intensa e debilitante que dificulta qualquer ação.", peCost: 2, dt: 20, skillId: "dominio_forca" },
      { level: 11, name: "Punho da Força", combat: true, description: "Concentra energia sombria em um soco ou golpe corpo a corpo extremamente poderoso.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Ilusão do Medo", combat: false, description: "Cria ilusões mentais que exploram os medos mais profundos do inimigo.", peCost: 2, dt: 20, skillId: "enganacao" },
      { level: 16, name: "Corrente de Ódio", combat: true, description: "Dispara uma corrente de energia sombria que pode acorrentar e eletrocutar o alvo.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Presença Aterrorizante", combat: false, description: "Projeta medo e intimidação em uma área, fazendo inimigos hesitarem ou fugirem.", peCost: 3, dt: 20, skillId: "intimidacao" },
      { level: 16, name: "Máscara da Presença", combat: false, description: "Esconde a própria presença na Força, dificultando detecção por outros sensíveis.", peCost: 3, dt: 20, skillId: "furtividade" },
      { level: 16, name: "Amplificação Corporal", combat: false, description: "Usa a Força para aumentar temporariamente força, resistência e agilidade.", peCost: 3, dt: 20, skillId: "atletismo" },
      { level: 16, name: "Estrangulamento da Força", combat: true, description: "Aperta a garganta do alvo à distância, sufocando e imobilizando parcialmente.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Peso da Escuridão", description: "Aumenta drasticamente a gravidade em uma área, deixando inimigos lentos e vulneráveis.", combat: false, peCost: 4, dt: 23, skillId: "dominio_forca" },
      { level: 30, name: "Sangue Fervente", description: "Acelera o próprio sangue e adrenalina com a Força, aumentando resistência e poder de ataque sob pressão.", combat: false, peCost: 5, dt: 23, skillId: "vontade" },
      { level: 35, name: "Explosão de Ódio", description: "Libera uma explosão concentrada de energia negra a partir do corpo, empurrando e ferindo todos ao redor.", combat: true, peCost: 6, damageDice: "9d6" },
      { level: 40, name: "Drenar Vitalidade", description: "Absorve parte da energia vital de um alvo próximo para se fortalecer.", combat: true, peCost: 7, damageDice: "10d6" },
    ],
  },
  {
    classId: "andarilho_forca",
    abilities: [
      { level: 1, name: "Forma de Sabre Shii-Cho (I)", combat: true, description: "Estilo fundamental e agressivo, focado em golpes amplos e controle de múltiplos oponentes.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Makashi (II)", combat: true, description: "Estilo elegante e preciso, especializado em duelos de sabre contra sabre.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Soresu (III)", combat: true, description: "Estilo defensivo e eficiente, focado em proteção e deflexão de ataques.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Ataru (IV)", combat: true, description: "Estilo acrobático e ofensivo, usando velocidade e saltos para pressionar o inimigo.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Djem So (V)", combat: true, description: "Estilo poderoso e dominante, baseado em contra-ataques pesados e controle do ritmo do combate.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Niman (VI)", combat: true, description: "Estilo equilibrado que combina sabre e poderes da Força de forma fluida.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Forma de Sabre Vaapad (VII)", combat: true, description: "Estilo caótico e intenso que canaliza emoções violentas e imprevisibilidade no combate.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Empurrão da Força", combat: true, description: "Onda de Força bruta que empurra e derruba inimigos.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Aceleração da Força", combat: false, description: "Aumenta drasticamente a velocidade de movimento e reação por um curto período.", peCost: 1, dt: 15, skillId: "acrobacia" },
      { level: 1, name: "Salto da Força", combat: true, description: "Impulso poderoso com a Força seguido de ataque ao aterrissar.", peCost: 1, damageDice: "2d6" },
      { level: 6, name: "Sexto Sentido", combat: false, description: "Fica sempre alerta e não sofre ataques surpresa.", peCost: 2, dt: 17, skillId: "percepcao" },
      { level: 6, name: "Contra Energia", combat: false, description: "Consegue conter e dissipar relâmpagos menores.", peCost: 2, dt: 17, skillId: "vontade" },
      { level: 6, name: "Domínio Mental Básico", combat: false, description: "Influencia mentes fracas para semear dúvida, medo ou obediência temporária.", peCost: 2, dt: 17, skillId: "dominio_forca" },
      { level: 6, name: "Onda Concentrada", combat: true, description: "Explosão concêntrica de energia que afasta e fere múltiplos inimigos.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Rajada Sônica", combat: true, description: "Grito potencializado pela Força que causa dano sonoro e desorienta.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Golpe Duplo", combat: true, description: "Realiza dois ataques rápidos em sequência contra o mesmo alvo.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Lançamento de Sabre", combat: true, description: "Arremessa o sabre de luz controlado pela Força para atacar à distância.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Toque de Distúrbio", combat: false, description: "Ao tocar o alvo, provoca confusão intensa e dificulta qualquer ação.", peCost: 2, dt: 20, skillId: "dominio_forca" },
      { level: 11, name: "Punho da Força", combat: true, description: "Concentra energia da Força em um soco ou golpe corpo a corpo extremamente poderoso.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Ilusão", combat: false, description: "Cria ilusões mentais que exploram as dúvidas mais profundas do inimigo.", peCost: 2, dt: 20, skillId: "enganacao" },
      { level: 16, name: "Presença Gloriosa", combat: false, description: "Projeta uma aura de poder em uma área, fazendo inimigos se questionarem se o usuário é aliado ou ameaça.", peCost: 3, dt: 20, skillId: "intimidacao" },
      { level: 16, name: "Máscara da Presença", combat: false, description: "Esconde a própria presença na Força, dificultando detecção por outros sensíveis.", peCost: 3, dt: 20, skillId: "furtividade" },
      { level: 16, name: "Amplificação Corporal", combat: false, description: "Usa a Força para aumentar temporariamente força, resistência e agilidade.", peCost: 3, dt: 20, skillId: "atletismo" },
      { level: 16, name: "Estrangulamento da Força", combat: true, description: "Aperta a garganta do alvo à distância, sufocando e imobilizando parcialmente.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Controle de Energia", combat: false, description: "Controla qualquer tipo de energia elétrica que entre em contato ou se aproxime do usuário.", peCost: 3, dt: 20, skillId: "vontade" },
    ],
    milestones: [
      { level: 25, name: "Barreira Selvagem", description: "Cria uma proteção instável, porém resistente, usando a Força de forma bruta.", combat: false, peCost: 4, dt: 23, skillId: "vontade" },
      { level: 30, name: "Vontade Indomável", description: "Resiste temporariamente a efeitos mentais e de controle através de puro instinto.", combat: false, peCost: 5, dt: 23, skillId: "vontade" },
      { level: 35, name: "Explosão Instintiva", description: "Libera uma explosão concentrada de energia bruta a partir do corpo, empurrando e ferindo todos ao redor.", combat: true, peCost: 6, damageDice: "9d6" },
      { level: 40, name: "Drenar Força", description: "Drena toda a conexão com a Força de um alvo, deixando-o apenas com 1 ponto.", combat: true, peCost: 7, damageDice: "10d6" },
    ],
  },
];
