// Star Wars: Além da Fronteira — habilidades de classe, Grupo A
// Cientista, Diplomata, Engenheiro, Espião
//
// Sistema de Pools: `level` guarda o tier em que o pool abre (1/6/11/16), não um nível linear.
// Pools nunca fecham — ver POOL_CLASS_IDS/getRemainingPoolAbilities em lib/starwars/leveling.ts.

import type { ClassAbilityTable } from "./types";

export const CLASS_GROUP_A: ClassAbilityTable[] = [
  {
    classId: "cientista",
    abilities: [
      { level: 1, name: "Disparo Ácido", combat: true, description: "Dispara um composto corrosivo que danifica armadura e queima ao longo do tempo.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Carga Explosiva Calculada", combat: true, description: "Monta uma carga de precisão com timing e raio de efeito calculados matematicamente.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Leitura de Cena", combat: false, description: "Analisa uma cena (corpo, destroços, sangue, resíduos) e deduz o que aconteceu ali.", peCost: 1, dt: 15, skillId: "investigacao" },
      { level: 1, name: "Antídoto Rápido", combat: false, description: "Neutraliza veneno ou toxina em si ou em um aliado próximo.", peCost: 1, dt: 15, skillId: "medicina" },
      { level: 1, name: "Overclock Cognitivo", combat: false, description: "Acelera o próprio raciocínio por um instante, reagindo antes de qualquer outro.", peCost: 1, dt: 15, skillId: "percepcao" },
      { level: 1, name: "Perfil de Combate", combat: false, description: "Observa o oponente e prevê seu próximo movimento, ganhando vantagem tática.", peCost: 1, dt: 15, skillId: "investigacao" },
      { level: 1, name: "Amostra Letal", combat: false, description: "Colhe uma amostra biológica do inimigo (sangue, tecido) para sintetizar uma arma específica contra ele.", peCost: 1, dt: 15, skillId: "ciencias" },
      { level: 1, name: "Campo de Contenção", combat: false, description: "Ergue um campo de energia que prende ou desacelera o alvo por um curto período.", peCost: 1, dt: 15, skillId: "ciencias" },
      { level: 1, name: "Detonação Bioquímica", combat: true, description: "Libera um composto instável que explode em contato com o ar, causando dano em área.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Simulação Preditiva", combat: false, description: "Calcula probabilidades de combate em tempo real, corrigindo o próprio erro antes que aconteça.", peCost: 1, dt: 15, skillId: "ciencias" },
      { level: 6, name: "Toxina Sintética", combat: true, description: "Aplica uma toxina desenvolvida em laboratório que causa dano contínuo severo.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Rastro Invisível", combat: false, description: "Detecta resíduos químicos e biológicos deixados por qualquer ser vivo, permitindo segui-lo mesmo sem pista visual alguma.", peCost: 2, dt: 17, skillId: "investigacao" },
      { level: 6, name: "Escudo Molecular", combat: false, description: "Gera uma barreira de energia reativa que absorve parte do dano recebido.", peCost: 2, dt: 17, skillId: "ciencias" },
      { level: 6, name: "Sobrecarga Química", combat: true, description: "Injeta um composto que acelera o metabolismo do alvo até o ponto de colapso.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Detector de Mentira", combat: false, description: "Lê sinais fisiológicos (pulso, voz, postura) para saber quando alguém está mentindo.", peCost: 2, dt: 17, skillId: "investigacao" },
      { level: 11, name: "Bisturi de Plasma", combat: true, description: "Lâmina de energia de precisão cirúrgica que corta com dano elevado e causa sangramento.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Falha Estrutural", combat: false, description: "Identifica o ponto exato de colapso de uma estrutura, veículo ou mecanismo, permitindo destruí-lo com o mínimo de esforço.", peCost: 2, dt: 20, skillId: "ciencias" },
      { level: 11, name: "Nervo Exposto", combat: true, description: "Ataque que expõe terminações nervosas do alvo, causando dor extrema e reduzindo sua reação.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Carga Cirúrgica", combat: true, description: "Explosivo de dispersão controlada que atinge só os alvos marcados, poupando o resto da área.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Neutralização Total", combat: false, description: "Remove completamente qualquer veneno, doença ou efeito químico/biológico de si ou de um aliado.", peCost: 2, dt: 20, skillId: "medicina" },
      { level: 16, name: "Campo de Estase", combat: false, description: "Distorce o campo temporal ao redor do alvo, imobilizando-o por completo por um instante.", peCost: 3, dt: 20, skillId: "ciencias" },
      { level: 16, name: "Dedução Absoluta", combat: false, description: "Une todas as pistas disponíveis numa conclusão exata e instantânea sobre a situação.", peCost: 3, dt: 20, skillId: "investigacao" },
      { level: 16, name: "Arma Biológica Controlada", combat: true, description: "Libera um agente biológico de altíssimo dano, com risco calculado de dano colateral.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Sobrecarga Neural", combat: true, description: "Ataque direto ao sistema nervoso do alvo, causando dano e paralisando temporariamente.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Máscara Química", combat: false, description: "Altera o próprio odor, calor corporal e resíduos, tornando-se indetectável a sensores e faro.", peCost: 3, dt: 20, skillId: "furtividade" },
    ],
    milestones: [
      { level: 25, name: "Mente Além do Tempo", description: "Processa tantas variáveis simultâneas que passa a agir e reagir antes de qualquer inimigo em combate.", combat: false, peCost: 4, dt: 23, skillId: "percepcao" },
      { level: 30, name: "Peste Calculada", description: "Libera um composto biológico devastador, projetado para se espalhar e enfraquecer todos os inimigos em área.", combat: true, peCost: 5, damageDice: "8d6" },
      { level: 35, name: "Veredito Forense", description: "Aponta com certeza absoluta o ponto fraco exato de um alvo, baseado numa análise completa dele, garantindo um golpe crítico certeiro.", combat: false, peCost: 6, dt: 23, skillId: "investigacao" },
      { level: 40, name: "Singularidade Científica", description: "Combina toda descoberta, composto e cálculo numa única solução capaz de decidir o combate.", combat: true, peCost: 7, damageDice: "10d6" },
    ],
  },
  {
    classId: "diplomata",
    abilities: [
      { level: 1, name: "Voz de Comando", combat: false, description: "Fala com peso instantâneo, fazendo aliados e inimigos prestarem atenção imediata.", peCost: 1, dt: 15, skillId: "lideranca" },
      { level: 1, name: "Leitura de Intenções", combat: false, description: "Lê tensão, mentira e intenção oculta em qualquer interlocutor.", peCost: 1, dt: 15, skillId: "percepcao" },
      { level: 1, name: "Protocolo Universal", combat: false, description: "Adapta comportamento e discurso a qualquer cultura, corte ou facção instantaneamente.", peCost: 1, dt: 15, skillId: "diplomacia" },
      { level: 1, name: "Rede de Contatos", combat: false, description: "Aciona uma rede de informantes e aliados políticos para obter informação rápida.", peCost: 1, dt: 15, skillId: "diplomacia" },
      { level: 1, name: "Blindagem Mental", combat: false, description: "Resiste a blefe, intimidação e manipulação verbal.", peCost: 1, dt: 15, skillId: "vontade" },
      { level: 1, name: "Barganha Sob Pressão", combat: false, description: "Negocia vantagem concreta (recursos, passagem, trégua) mesmo em situação hostil.", peCost: 1, dt: 15, skillId: "persuasao" },
      { level: 1, name: "Apelo à Calma", combat: false, description: "Acalma uma multidão ou grupo alterado, evitando pânico ou motim.", peCost: 1, dt: 15, skillId: "diplomacia" },
      { level: 1, name: "Ultimato Calculado", combat: false, description: "Ameaça com consequências reais o suficiente para forçar o recuo do oponente.", peCost: 1, dt: 15, skillId: "intimidacao" },
      { level: 1, name: "Vínculo Formal", combat: false, description: "Sela um acordo ou juramento com peso quase impossível de quebrar.", peCost: 1, dt: 15, skillId: "diplomacia" },
      { level: 1, name: "Provocação Estratégica", combat: false, description: "Usa palavras para desestabilizar o inimigo, abrindo brecha para um aliado atacar.", peCost: 1, dt: 15, skillId: "enganacao" },
      { level: 6, name: "Presença de Autoridade", combat: false, description: "Impõe respeito instantâneo em qualquer ambiente, civil ou hostil.", peCost: 2, dt: 17, skillId: "lideranca" },
      { level: 6, name: "Fratura de Alianças", combat: false, description: "Semeia desconfiança entre inimigos, enfraquecendo a coesão do grupo adversário.", peCost: 2, dt: 17, skillId: "enganacao" },
      { level: 6, name: "Salvo-Conduto", combat: false, description: "Garante passagem segura por território hostil por tempo limitado.", peCost: 2, dt: 17, skillId: "diplomacia" },
      { level: 6, name: "Escuta Diplomática", combat: false, description: "Capta informações sigilosas através de canais oficiais e conversas privilegiadas.", peCost: 2, dt: 17, skillId: "investigacao" },
      { level: 6, name: "Compromisso Vinculante", combat: false, description: "Obriga uma facção ou pessoa a cumprir um acordo, sob risco de consequência severa.", peCost: 2, dt: 17, skillId: "diplomacia" },
      { level: 11, name: "Cerco Verbal", combat: false, description: "Encurrala o alvo em contradições até ele ceder ou se render.", peCost: 2, dt: 20, skillId: "persuasao" },
      { level: 11, name: "Golpe de Reputação", combat: false, description: "Destrói publicamente a credibilidade de um rival ou inimigo.", peCost: 2, dt: 20, skillId: "enganacao" },
      { level: 11, name: "Trégua Imposta", combat: false, description: "Força um cessar-fogo temporário mesmo em pleno combate.", peCost: 2, dt: 20, skillId: "diplomacia" },
      { level: 11, name: "Corretagem de Poder", combat: false, description: "Negocia recursos, tropas ou apoio de terceiros em tempo real durante uma crise.", peCost: 2, dt: 20, skillId: "persuasao" },
      { level: 11, name: "Máscara Perfeita", combat: false, description: "Assume a identidade e a posição social de outra pessoa ou facção sem levantar suspeita.", peCost: 2, dt: 20, skillId: "enganacao" },
      { level: 16, name: "Julgamento Público", combat: false, description: "Convence uma audiência inteira a julgar e agir contra um alvo específico.", peCost: 3, dt: 20, skillId: "persuasao" },
      { level: 16, name: "Manto de Imunidade", combat: false, description: "Torna-se, temporariamente, alguém intocável por lei, tradição ou acordo formal.", peCost: 3, dt: 20, skillId: "diplomacia" },
      { level: 16, name: "Colapso de Negociação", combat: false, description: "Vira qualquer negociação a seu favor no último instante, mesmo em desvantagem.", peCost: 3, dt: 20, skillId: "persuasao" },
      { level: 16, name: "Aliança de Sangue", combat: false, description: "Firma um pacto que une forças de dois lados opostos contra uma ameaça maior.", peCost: 3, dt: 20, skillId: "diplomacia" },
      { level: 16, name: "Voz que Ecoa", combat: false, description: "Sua palavra se espalha instantaneamente e influencia decisões em múltiplos lugares ao mesmo tempo.", peCost: 3, dt: 20, skillId: "lideranca" },
    ],
    milestones: [
      { level: 25, name: "Tratado Inquebrável", description: "Firma um acordo que nenhuma das partes consegue romper, nem por força nem por lei.", combat: false, peCost: 4, dt: 23, skillId: "diplomacia" },
      { level: 30, name: "Arquiteto da Paz", description: "Encerra um conflito armado inteiro através de um único acordo negociado.", combat: false, peCost: 5, dt: 23, skillId: "diplomacia" },
      { level: 35, name: "Embaixador Absoluto", description: "Sua presença sozinha basta para evitar guerra entre facções inimigas.", combat: false, peCost: 6, dt: 23, skillId: "lideranca" },
      { level: 40, name: "Voz da Galáxia", description: "Uma única declaração sua altera o rumo político de sistemas inteiros.", combat: false, peCost: 7, dt: 30, skillId: "persuasao" },
    ],
  },
  {
    classId: "engenheiro",
    abilities: [
      { level: 1, name: "Disparo de Ferramenta", combat: true, description: "Usa uma ferramenta de solda ou corte adaptada como arma de curto alcance.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Olho Técnico", combat: false, description: "Identifica falhas, pontos fracos e valor de qualquer máquina, droide, veículo ou estrutura.", peCost: 1, dt: 15, skillId: "mecanica" },
      { level: 1, name: "Reparo de Campo", combat: false, description: "Conserta rapidamente equipamento danificado, restaurando função parcial em pleno combate.", peCost: 1, dt: 15, skillId: "mecanica" },
      { level: 1, name: "Choque Dirigido", combat: true, description: "Descarrega energia de uma ferramenta ou bateria contra um alvo próximo.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Drone de Reconhecimento", combat: false, description: "Envia um pequeno drone para escanear a área e marcar inimigos ocultos.", peCost: 1, dt: 15, skillId: "percepcao" },
      { level: 1, name: "Modificação Rápida", combat: false, description: "Adapta uma arma ou equipamento para ganhar um efeito extra temporário.", peCost: 1, dt: 15, skillId: "mecanica" },
      { level: 1, name: "Hackeamento Básico", combat: false, description: "Assume controle temporário de um sistema simples (porta, câmera, droide fraco).", peCost: 1, dt: 15, skillId: "computacao" },
      { level: 1, name: "Blindagem Improvisada", combat: false, description: "Reforça armadura própria ou de aliado usando peças e sucata disponíveis.", peCost: 1, dt: 15, skillId: "mecanica" },
      { level: 1, name: "Torreta Portátil", combat: true, description: "Monta uma pequena torreta ou droide de defesa que atira automaticamente por um tempo.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Sobrecarga", combat: true, description: "Força um sistema, arma ou droide inimigo a sobrecarregar, causando dano e falha temporária.", peCost: 1, damageDice: "2d6" },
      { level: 6, name: "Enxame de Drones", combat: true, description: "Libera pequenos drones que atacam, distraem ou marcam alvos.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Manutenção de Combate", combat: false, description: "Repara e reenergiza equipamento aliado em pleno confronto.", peCost: 2, dt: 17, skillId: "mecanica" },
      { level: 6, name: "Sabotagem Remota", combat: false, description: "Desativa à distância uma arma, veículo ou sistema inimigo.", peCost: 2, dt: 17, skillId: "computacao" },
      { level: 6, name: "Exoesqueleto Tático", combat: false, description: "Veste um reforço mecânico temporário que aumenta força e resistência.", peCost: 2, dt: 17, skillId: "atletismo" },
      { level: 6, name: "Rede de Sensores", combat: false, description: "Espalha sensores que revelam a posição de inimigos numa área.", peCost: 2, dt: 17, skillId: "percepcao" },
      { level: 11, name: "Arsenal Modular", combat: false, description: "Equipa a arma própria com módulos intercambiáveis no meio do combate.", peCost: 2, dt: 20, skillId: "mecanica" },
      { level: 11, name: "Droide de Combate", combat: true, description: "Ativa um droide de ataque previamente preparado para lutar ao seu lado.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Escudo de Emergência", combat: false, description: "Cria um campo de proteção temporário para si ou para o grupo.", peCost: 2, dt: 20, skillId: "mecanica" },
      { level: 11, name: "Núcleo Instável", combat: true, description: "Transforma qualquer máquina ou veículo próximo numa bomba de tempo controlada.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Reprogramação Hostil", combat: false, description: "Vira um droide ou sistema inimigo contra os próprios aliados.", peCost: 2, dt: 20, skillId: "computacao" },
      { level: 16, name: "Rede de Combate", combat: true, description: "Sincroniza droides, torretas e drones próprios para atacar em conjunto.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Fabricação de Guerra", combat: false, description: "Monta um equipamento ofensivo especializado sob medida para a missão atual.", peCost: 3, dt: 20, skillId: "mecanica" },
      { level: 16, name: "Firewall Vivo", combat: false, description: "Proteção total contra hackeamento e interferência eletrônica sobre si e seus equipamentos.", peCost: 3, dt: 20, skillId: "computacao" },
      { level: 16, name: "Máquina de Guerra", combat: true, description: "Ativa uma unidade de combate pesada para lutar ao seu lado por tempo prolongado.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Colapso de Sistemas", combat: false, description: "Desliga em cadeia toda a tecnologia hostil numa área ampla.", peCost: 3, dt: 20, skillId: "computacao" },
    ],
    milestones: [
      { level: 25, name: "Oficina de Combate", description: "Cria e mantém múltiplas unidades ofensivas simultâneas, sustentando a guerra tecnológica.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 30, name: "Mente Mecânica", description: "Controla, repara e comanda qualquer tecnologia em campo quase instantaneamente.", combat: false, peCost: 5, dt: 23, skillId: "mecanica" },
      { level: 35, name: "Protótipo Devastador", description: "Ativa uma arma ou veículo experimental de altíssimo poder de fogo.", combat: true, peCost: 6, damageDice: "9d6" },
      { level: 40, name: "Singularidade Tecnológica", description: "Ativa uma criação lendária — arma, droide ou nave — capaz de decidir uma batalha inteira sozinha.", combat: true, peCost: 7, damageDice: "10d6" },
    ],
  },
  {
    classId: "espiao",
    abilities: [
      { level: 1, name: "Golpe Silencioso", combat: true, description: "Ataque furtivo com dano bônus contra alvo desprevenido.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Passo Invisível", combat: false, description: "Reduz drasticamente a chance de ser detectado ao se mover.", peCost: 1, dt: 15, skillId: "furtividade" },
      { level: 1, name: "Disfarce Rápido", combat: false, description: "Muda aparência ou identidade por um curto período.", peCost: 1, dt: 15, skillId: "enganacao" },
      { level: 1, name: "Escuta Discreta", combat: false, description: "Capta informação sigilosa a longa distância.", peCost: 1, dt: 15, skillId: "percepcao" },
      { level: 1, name: "Ponto Vital", combat: true, description: "Ataque preciso num local anatômico crítico, dano aumentado.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Acesso Forjado", combat: false, description: "Falsifica credenciais, portas e registros de identificação.", peCost: 1, dt: 15, skillId: "enganacao" },
      { level: 1, name: "Sombra Dupla", combat: false, description: "Cria uma distração ou falsa presença que desvia a atenção do alvo.", peCost: 1, dt: 15, skillId: "enganacao" },
      { level: 1, name: "Fuga Calculada", combat: false, description: "Escapa de perseguição ou cerco usando uma rota já mapeada mentalmente.", peCost: 1, dt: 15, skillId: "furtividade" },
      { level: 1, name: "Leitura de Vigilância", combat: false, description: "Identifica câmeras, sensores e sentinelas antes de agir.", peCost: 1, dt: 15, skillId: "percepcao" },
      { level: 1, name: "Corte de Vigilância", combat: true, description: "Neutraliza uma sentinela ou câmera com um ataque silencioso.", peCost: 1, damageDice: "2d6" },
      { level: 6, name: "Infiltração Profunda", combat: false, description: "Entra em áreas de alta segurança sem ser notado.", peCost: 2, dt: 17, skillId: "furtividade" },
      { level: 6, name: "Identidade Forjada", combat: false, description: "Assume a identidade de alguém já observado por tempo prolongado.", peCost: 2, dt: 17, skillId: "enganacao" },
      { level: 6, name: "Golpe Duplo Silencioso", combat: true, description: "Dois ataques furtivos em sequência, sem alertar ninguém.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Rede de Sombras", combat: true, description: "Coordena ataques furtivos simultâneos com aliados.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Fuga Fantasma", combat: false, description: "Desaparece completamente logo após um ataque, sem deixar rastro.", peCost: 2, dt: 17, skillId: "furtividade" },
      { level: 11, name: "Execução Rápida", combat: true, description: "Ataque combinado que ignora parte da defesa do alvo.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Ângulo Morto", combat: false, description: "Encontra e explora o ponto cego de qualquer sistema de segurança ou formação inimiga, permitindo agir sem ser detectado.", peCost: 2, dt: 20, skillId: "furtividade" },
      { level: 11, name: "Golpe Paralisante", combat: true, description: "Imobiliza o alvo por um tempo curto.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Rede de Contatos Sombrios", combat: false, description: "Obtém qualquer informação através do submundo.", peCost: 2, dt: 20, skillId: "investigacao" },
      { level: 11, name: "Contra-Vigilância", combat: false, description: "Detecta e neutraliza quem está te vigiando ou seguindo.", peCost: 2, dt: 20, skillId: "percepcao" },
      { level: 16, name: "Acesso Root", combat: false, description: "Obtém autorização total, física ou digital, dentro de qualquer organização, sem precisar convencer ninguém.", peCost: 3, dt: 20, skillId: "computacao" },
      { level: 16, name: "Assassinato Perfeito", combat: true, description: "Ataque de altíssimo dano contra um alvo isolado.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Sombra Absoluta", combat: false, description: "Torna-se completamente indetectável por um período prolongado.", peCost: 3, dt: 20, skillId: "furtividade" },
      { level: 16, name: "Manipulação de Registro", combat: false, description: "Apaga ou reescreve qualquer rastro de sua passagem.", peCost: 3, dt: 20, skillId: "computacao" },
      { level: 16, name: "Golpe Fantasma", combat: true, description: "Ataca e desaparece antes que o inimigo perceba o que aconteceu.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Fantasma Operacional", description: "Infiltra e ataca sem deixar rastro algum.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 30, name: "Mestre Assassino", description: "Um único golpe pode eliminar quase qualquer alvo.", combat: true, peCost: 5, damageDice: "8d6" },
      { level: 35, name: "Lâmina das Mil Faces", description: "Assume qualquer identidade e ataca com letalidade extrema.", combat: true, peCost: 6, damageDice: "9d6" },
      { level: 40, name: "A Sombra Perfeita", description: "Executa uma operação letal que muda o destino de uma facção inteira.", combat: true, peCost: 7, damageDice: "10d6" },
    ],
  },
];
