// Star Wars: Além da Fronteira — habilidades de classe, Grupo D
// Classes de Caminho (O Lado da Luz, O Equilíbrio, O Lado Negro — 30 habilidades, nível 1 a 30)
// e Classes de Profecia (O Cântico do Alvorecer, A Litania da Queda — 10 habilidades, só em níveis pares).
//
// Substituem as antigas "O Lado da Luz", "O Lado Negro" e "Xamã da Força" (classes avançadas
// removidas — ver classes.ts). Diferente do sistema anterior, aqui cada uma tem progressão
// própria completa (não depende de nenhuma classe-base) e não usa o sistema de Formas de
// Sabre circular (formTag) — as habilidades "Sabre" usam a regra padrão de sabre cru
// (6d6 × atributo + perícia, não escala por nível). Nas habilidades descritas na fonte como
// "Sabre + Dano NdM", o motor só rola um efeito por habilidade — mantido o dano numérico (que
// escala por nível), com a menção ao sabre só na descrição. Nos marcos "Ascensão" (compostos de
// DT + dano + cura ao mesmo tempo), o botão rola só o maior efeito numérico; o restante do
// efeito composto fica anotado na descrição pro mestre aplicar manualmente.

import type { ClassAbilityTable } from "./types";

export const CLASS_GROUP_D: ClassAbilityTable[] = [
  {
    classId: "lado_da_luz",
    abilities: [
      { level: 1, name: "Clarão da Aurora", combat: false, description: "Um flash de luz pura que ofusca e revela intenções ocultas.", peCost: 1, dt: 15 },
      { level: 1, name: "Toque de Serenidade", combat: true, description: "Toque suave que acalma a mente e restaura vitalidade.", peCost: 1, damageDice: "2d6", heal: true },
      { level: 2, name: "Escudo de Luz", combat: false, description: "Barreira luminosa que protege contra ataques físicos e da Força.", peCost: 1, dt: 15 },
      { level: 3, name: "Raio de Esperança", combat: true, description: "Feixe de energia luminosa que causa dano e inspira aliados.", peCost: 1, damageDice: "3d6" },
      { level: 4, name: "Passo Luminoso", combat: false, description: "Deslocamento rápido envolto em luz, difícil de rastrear.", peCost: 2, dt: 17 },
      { level: 5, name: "Julição Pura", combat: true, description: "Corte preciso de sabre imbuído de justiça e clareza.", peCost: 2, damageDice: "5d6" },
      { level: 6, name: "Voz da Harmonia", combat: false, description: "Palavras carregadas de Força que acalmam ou convencem.", peCost: 2, dt: 17 },
      { level: 7, name: "Manto de Proteção", combat: false, description: "Aura luminosa que reduz dano recebido por um curto período.", peCost: 2, dt: 17 },
      { level: 8, name: "Corte da Justiça", combat: true, description: "Golpe de sabre que prioriza alvos corrompidos ou agressivos.", peCost: 2, weaponDamage: "sabre" },
      { level: 9, name: "Ondas de Cura", combat: true, description: "Pulsos de energia curativa que afetam múltiplos aliados.", peCost: 2, damageDice: "4d6", heal: true },
      { level: 10, name: "Julição Tripla", combat: true, description: "Três cortes rápidos de sabre em sucessão fluida.", peCost: 2, damageDice: "7d6" },
      { level: 11, name: "Serenidade Absoluta", combat: false, description: "Estado de calma total que anula efeitos de medo e confusão.", peCost: 2, dt: 19 },
      { level: 12, name: "Lâmina da Ordem", combat: true, description: "Sabre que brilha com intensidade e corta com precisão absoluta.", peCost: 2, weaponDamage: "sabre" },
      { level: 13, name: "Barreira de Luz Pura", combat: false, description: "Muralha de energia luminosa que bloqueia ataques em área.", peCost: 3, dt: 21 },
      { level: 14, name: "Julição Celeste", combat: true, description: "Golpe poderoso que canaliza a vontade da Força luminosa.", peCost: 3, damageDice: "4d8" },
      { level: 15, name: "Chamado dos Mestres", combat: false, description: "Invoca a orientação espiritual de antigos mestres Jedi.", peCost: 3, dt: 21 },
      { level: 16, name: "Tempestade de Luz Suave", combat: true, description: "Rajada de energia luminosa que danifica sem crueldade excessiva.", peCost: 3, damageDice: "6d8" },
      { level: 17, name: "Domínio da Compaixão", combat: false, description: "Aumenta a capacidade de sentir e responder à dor alheia.", peCost: 3, dt: 23 },
      { level: 18, name: "Golpe da Aurora", combat: true, description: "Ataque de sabre que explode em luz ao acertar.", peCost: 3, weaponDamage: "sabre" },
      { level: 19, name: "Cura em Massa", combat: true, description: "Onda curativa ampla que restaura vários aliados simultaneamente.", peCost: 3, damageDice: "8d6", heal: true },
      { level: 20, name: "Presença Inabalável da Luz", combat: false, description: "Aura que fortalece a resistência mental de todos próximos.", peCost: 3, dt: 23 },
      { level: 21, name: "Lâmina dos Antigos", combat: true, description: "Sabre que ecoa o poder de gerações passadas de guardiões.", peCost: 3, weaponDamage: "sabre" },
      { level: 22, name: "Explosão de Esperança", combat: true, description: "Explosão de energia luminosa que empurra e danifica inimigos.", peCost: 4, damageDice: "8d8" },
      { level: 23, name: "Muralha de Luz Viva", combat: false, description: "Barreira quase indestrutível feita de luz pura da Força.", peCost: 4, dt: 25 },
      { level: 24, name: "Consagração Total", combat: true, description: "Ritual rápido que fortalece o sabre com energia sagrada.", peCost: 4, weaponDamage: "sabre" },
      { level: 25, name: "Domínio da Luz Eterna", combat: false, description: "Controle absoluto sobre a própria conexão com o lado luminoso.", peCost: 4, dt: 26 },
      { level: 26, name: "Julição Suprema", combat: true, description: "Corte devastador que combina força física e poder espiritual.", peCost: 5, damageDice: "12d8" },
      { level: 27, name: "Eco dos Guardiões", combat: true, description: "Invoca ecos de antigos Jedi para auxiliar em combate ou cura.", peCost: 5, damageDice: "6d8", heal: true },
      { level: 28, name: "Forma da Serenidade Final", combat: true, description: "Estilo de combate perfeito baseado em defesa e fluidez.", peCost: 5, weaponDamage: "sabre" },
      { level: 29, name: "Julição da Galáxia", combat: true, description: "Ataque de área que canaliza a vontade coletiva da luz.", peCost: 6, damageDice: "12d12" },
      { level: 30, name: "Ascensão da Luz", combat: true, description: "Transformação temporária em um farol vivo de poder luminoso. Também exige DT 30 de quem resiste e cura 12d6 simultânea em um aliado — aplique junto ao dano rolado abaixo.", peCost: 6, damageDice: "8d20" },
    ],
    milestones: [],
  },
  {
    classId: "equilibrio",
    abilities: [
      { level: 1, name: "Fluxo Neutro", combat: false, description: "Sintoniza o usuário com o fluxo natural da Força sem lado.", peCost: 1, dt: 15 },
      { level: 1, name: "Toque Dual", combat: true, description: "Toque que pode curar ou ferir dependendo da intenção.", peCost: 1, damageDice: "2d6", healOrDamage: true },
      { level: 2, name: "Passo do Meio", combat: false, description: "Movimento equilibrado que evita extremos de velocidade ou força.", peCost: 1, dt: 15 },
      { level: 3, name: "Corte Equilibrado", combat: true, description: "Golpe de sabre que combina precisão e poder sem excessos.", peCost: 1, weaponDamage: "sabre" },
      { level: 4, name: "Leitura de Ambos os Lados", combat: false, description: "Percebe simultaneamente influências de luz e escuridão.", peCost: 2, dt: 17 },
      { level: 5, name: "Impulso Harmônico", combat: true, description: "Empurrão de Força controlado e preciso.", peCost: 2, damageDice: "5d6" },
      { level: 6, name: "Escudo Cinza", combat: false, description: "Barreira que absorve tanto energia luminosa quanto sombria.", peCost: 2, dt: 17 },
      { level: 7, name: "Fusão de Forças", combat: true, description: "Combina energias opostas em um único efeito equilibrado.", peCost: 2, damageDice: "4d6", healOrDamage: true },
      { level: 8, name: "Forma do Centro", combat: true, description: "Estilo de sabre que flui entre ataque e defesa perfeitamente.", peCost: 2, weaponDamage: "sabre" },
      { level: 9, name: "Ondas de Equilíbrio", combat: false, description: "Pulsos que estabilizam a Força ao redor do usuário.", peCost: 2, dt: 19 },
      { level: 10, name: "Rajada Neutra", combat: true, description: "Rajada de energia que não favorece nenhum lado.", peCost: 2, damageDice: "7d6" },
      { level: 11, name: "Visão de Ambos os Caminhos", combat: false, description: "Antecipa ações baseadas em escolhas de luz ou escuridão.", peCost: 2, dt: 19 },
      { level: 12, name: "Lâmina do Meio", combat: true, description: "Sabre que se adapta ao fluxo do combate em tempo real.", peCost: 2, weaponDamage: "sabre" },
      { level: 13, name: "Barreira do Equilíbrio", combat: false, description: "Proteção que se ajusta automaticamente ao tipo de ameaça.", peCost: 3, dt: 21 },
      { level: 14, name: "Explosão Harmônica", combat: true, description: "Explosão de energia equilibrada que empurra sem destruir.", peCost: 3, damageDice: "4d8" },
      { level: 15, name: "Domínio do Fluxo", combat: false, description: "Controle consciente sobre o equilíbrio interno da Força.", peCost: 3, dt: 21 },
      { level: 16, name: "Tempestade Equilibrada", combat: true, description: "Tempestade de energia que danifica e cura ao mesmo tempo.", peCost: 3, damageDice: "6d8", healOrDamage: true },
      { level: 17, name: "Voz do Centro", combat: false, description: "Palavras que influenciam sem manipular ou dominar.", peCost: 3, dt: 23 },
      { level: 18, name: "Golpe da Harmonia", combat: true, description: "Ataque de sabre que restaura o equilíbrio do campo de batalha.", peCost: 3, weaponDamage: "sabre" },
      { level: 19, name: "Restauração Dual", combat: true, description: "Cura que também remove efeitos negativos de ambos os lados.", peCost: 3, damageDice: "8d6", heal: true },
      { level: 20, name: "Presença do Meio", combat: false, description: "Aura que reduz extremos emocionais em todos próximos.", peCost: 3, dt: 23 },
      { level: 21, name: "Forma do Equilíbrio Eterno", combat: true, description: "Estilo de combate que nunca se inclina para um lado.", peCost: 3, weaponDamage: "sabre" },
      { level: 22, name: "Explosão do Fluxo", combat: true, description: "Liberação poderosa de energia neutra em área.", peCost: 4, damageDice: "8d8" },
      { level: 23, name: "Muralha Cinza", combat: false, description: "Barreira quase impenetrável feita de energia equilibrada.", peCost: 4, dt: 25 },
      { level: 24, name: "Consagração do Meio", combat: true, description: "Fortalece o sabre com a essência pura do equilíbrio.", peCost: 4, weaponDamage: "sabre" },
      { level: 25, name: "Domínio Absoluto do Equilíbrio", combat: false, description: "Estado de perfeita neutralidade e controle total.", peCost: 4, dt: 26 },
      { level: 26, name: "Rajada do Centro", combat: true, description: "Rajada concentrada de poder neutro devastador.", peCost: 5, damageDice: "12d8" },
      { level: 27, name: "Cura do Fluxo Eterno", combat: true, description: "Cura profunda que restaura corpo e espírito.", peCost: 5, damageDice: "6d8", heal: true },
      { level: 28, name: "Forma Final do Meio", combat: true, description: "Aperfeiçoamento máximo do estilo de combate equilibrado.", peCost: 5, weaponDamage: "sabre" },
      { level: 29, name: "Tempestade do Equilíbrio", combat: true, description: "Tempestade massiva que equilibra o campo de batalha.", peCost: 6, damageDice: "12d12", healOrDamage: true },
      { level: 30, name: "Ascensão do Equilíbrio", combat: true, description: "Elevação temporária a um estado de harmonia absoluta. Também exige DT 30 de quem resiste, simultâneo à escolha de dano ou cura abaixo.", peCost: 6, damageDice: "8d20", healOrDamage: true },
    ],
    milestones: [],
  },
  {
    classId: "lado_negro",
    abilities: [
      { level: 1, name: "Sussurro da Raiva", combat: false, description: "Sussurro mental que desperta fúria e medo no alvo.", peCost: 1, dt: 15 },
      { level: 1, name: "Toque da Dor", combat: true, description: "Toque que causa dor intensa e enfraquece a vontade.", peCost: 1, damageDice: "2d6" },
      { level: 2, name: "Passo das Sombras", combat: false, description: "Movimento furtivo envolto em escuridão da Força.", peCost: 1, dt: 15 },
      { level: 3, name: "Lâmina da Fúria", combat: true, description: "Golpe de sabre alimentado por raiva pura.", peCost: 1, weaponDamage: "sabre" },
      { level: 4, name: "Presença Aterrorizante", combat: false, description: "Aura que causa medo e hesitação nos oponentes.", peCost: 2, dt: 17 },
      { level: 5, name: "Relâmpago Menor Sombrio", combat: true, description: "Descargas elétricas menores canalizadas pela raiva.", peCost: 2, damageDice: "5d6" },
      { level: 6, name: "Máscara do Ódio", combat: false, description: "Oculta emoções e intensifica a conexão com o lado sombrio.", peCost: 2, dt: 17 },
      { level: 7, name: "Drenar Vitalidade", combat: true, description: "Absorve energia vital do alvo para si mesmo.", peCost: 2, damageDice: "4d6" },
      { level: 8, name: "Forma da Crueldade", combat: true, description: "Estilo de sabre focado em causar sofrimento máximo.", peCost: 2, weaponDamage: "sabre" },
      { level: 9, name: "Ondas de Medo", combat: false, description: "Pulsos de terror que quebram a concentração inimiga.", peCost: 2, dt: 19 },
      { level: 10, name: "Relâmpago Duplo", combat: true, description: "Duas descargas de relâmpago simultâneas.", peCost: 2, damageDice: "7d6" },
      { level: 11, name: "Visão da Queda", combat: false, description: "Mostra ao alvo visões de sua própria ruína.", peCost: 2, dt: 19 },
      { level: 12, name: "Lâmina Impiedosa", combat: true, description: "Sabre que corta com precisão cruel e sem hesitação.", peCost: 2, weaponDamage: "sabre" },
      { level: 13, name: "Estrangulamento Aprimorado", combat: true, description: "Aperto de Força mais forte e prolongado.", peCost: 3, damageDice: "4d8" },
      { level: 14, name: "Tempestade de Ódio", combat: true, description: "Rajada caótica de energia sombria.", peCost: 3, damageDice: "6d8" },
      { level: 15, name: "Domínio da Fúria", combat: false, description: "Controle total sobre a própria raiva como fonte de poder.", peCost: 3, dt: 21 },
      { level: 16, name: "Drenar Força Maior", combat: true, description: "Absorção poderosa da Força vital do oponente.", peCost: 3, damageDice: "6d8" },
      { level: 17, name: "Voz da Escuridão", combat: false, description: "Comando vocal que domina mentes enfraquecidas.", peCost: 3, dt: 23 },
      { level: 18, name: "Golpe da Ruína", combat: true, description: "Ataque de sabre que deixa ferimentos profundos e duradouros.", peCost: 3, weaponDamage: "sabre" },
      { level: 19, name: "Explosão de Dor", combat: true, description: "Explosão de energia que causa agonia intensa.", peCost: 3, damageDice: "8d6" },
      { level: 20, name: "Presença do Senhor Sombrio", combat: false, description: "Aura opressora que enfraquece a vontade de todos próximos.", peCost: 3, dt: 23 },
      { level: 21, name: "Forma da Ira Eterna", combat: true, description: "Estilo de combate baseado em agressão constante.", peCost: 3, weaponDamage: "sabre" },
      { level: 22, name: "Relâmpago em Cadeia", combat: true, description: "Relâmpagos que saltam de um alvo para outro.", peCost: 4, damageDice: "8d8" },
      { level: 23, name: "Muralha de Trevas", combat: false, description: "Barreira de escuridão que consome ataques.", peCost: 4, dt: 25 },
      { level: 24, name: "Consagração Sombria", combat: true, description: "Imbui o sabre com poder corrupto e destrutivo.", peCost: 4, weaponDamage: "sabre" },
      { level: 25, name: "Domínio Absoluto da Escuridão", combat: false, description: "Controle total sobre o lado sombrio da Força.", peCost: 4, dt: 26 },
      { level: 26, name: "Tempestade de Relâmpagos", combat: true, description: "Tempestade devastadora de relâmpagos da Força.", peCost: 5, damageDice: "12d8" },
      { level: 27, name: "Drenar Alma", combat: true, description: "Absorção profunda que enfraquece o espírito do alvo.", peCost: 5, damageDice: "6d8" },
      { level: 28, name: "Forma Final da Fúria", combat: true, description: "Aperfeiçoamento máximo do estilo de combate sombrio.", peCost: 5, weaponDamage: "sabre" },
      { level: 29, name: "Apocalipse Sombrio", combat: true, description: "Liberação catastrófica de energia destrutiva.", peCost: 6, damageDice: "12d12" },
      { level: 30, name: "Ascensão do Lado Negro", combat: true, description: "Transformação temporária em um avatar da escuridão. Também exige DT 30 de quem resiste — aplique junto ao dano rolado abaixo.", peCost: 6, damageDice: "8d20" },
    ],
    milestones: [],
  },
  {
    classId: "cantico_alvorecer",
    abilities: [
      { level: 2, name: "Primeiro Verso da Aurora", combat: false, description: "Desperta a primeira conexão com a profecia de luz.", peCost: 2, dt: 18 },
      { level: 4, name: "Eco do Alvorecer", combat: true, description: "Ressoa a esperança da profecia, curando feridas.", peCost: 2, damageDice: "8d6", heal: true },
      { level: 6, name: "Cântico de Proteção", combat: false, description: "Canto interior que cria uma barreira de luz profética.", peCost: 3, dt: 23 },
      { level: 8, name: "Lâmina do Novo Dia", combat: true, description: "Sabre que brilha com a promessa de um novo começo.", peCost: 3, damageDice: "4d8" },
      { level: 10, name: "Verso da Esperança Eterna", combat: true, description: "Libera energia da profecia em forma de ataque luminoso.", peCost: 3, damageDice: "10d8" },
      { level: 12, name: "Harmonia do Cântico", combat: true, description: "Sincroniza o usuário com o fluxo da profecia de luz.", peCost: 4, damageDice: "10d10", heal: true },
      { level: 14, name: "Chamado dos Antigos Alvoreceres", combat: false, description: "Invoca ecos de antigos portadores da mesma profecia.", peCost: 4, dt: 27 },
      { level: 16, name: "Explosão do Amanhecer", combat: true, description: "Explosão poderosa de energia nascida da esperança.", peCost: 5, damageDice: "12d10" },
      { level: 18, name: "Forma do Cântico Final", combat: true, description: "Estilo de combate que personifica o destino luminoso.", peCost: 5, damageDice: "8d10" },
      { level: 20, name: "Ascensão do Alvorecer", combat: true, description: "Elevação completa ao papel de portador da profecia de luz. Também exige DT 32 de quem resiste e cura 12d12 simultânea em um aliado — aplique junto ao dano rolado abaixo.", peCost: 6, damageDice: "10d20" },
    ],
    milestones: [],
  },
  {
    classId: "litania_queda",
    abilities: [
      { level: 2, name: "Primeiro Verso da Queda", combat: false, description: "Desperta a primeira conexão com a profecia sombria.", peCost: 2, dt: 18 },
      { level: 4, name: "Eco da Ruína", combat: true, description: "Ressoa a inevitabilidade da queda, causando dano.", peCost: 2, damageDice: "8d6" },
      { level: 6, name: "Litania do Medo", combat: false, description: "Canto interior que espalha terror profético.", peCost: 3, dt: 23 },
      { level: 8, name: "Lâmina da Traição", combat: true, description: "Sabre que corta com o peso do destino sombrio.", peCost: 3, damageDice: "4d8" },
      { level: 10, name: "Verso da Escuridão Eterna", combat: true, description: "Libera energia da profecia em forma de ataque sombrio.", peCost: 3, damageDice: "10d8" },
      { level: 12, name: "Corrupção da Litania", combat: true, description: "Espalha a influência corruptora da profecia.", peCost: 4, damageDice: "10d10" },
      { level: 14, name: "Chamado dos Antigos Caídos", combat: false, description: "Invoca ecos de antigos portadores da mesma profecia sombria.", peCost: 4, dt: 27 },
      { level: 16, name: "Explosão da Queda", combat: true, description: "Explosão devastadora nascida do destino de ruína.", peCost: 5, damageDice: "12d10" },
      { level: 18, name: "Forma da Litania Final", combat: true, description: "Estilo de combate que personifica o destino sombrio.", peCost: 5, damageDice: "8d10" },
      { level: 20, name: "Ascensão da Queda", combat: true, description: "Elevação completa ao papel de portador da profecia da queda. Também exige DT 32 de quem resiste e um dano adicional de 12d12 simultâneo — aplique junto ao dano rolado abaixo.", peCost: 6, damageDice: "10d20" },
    ],
    milestones: [],
  },
];
