// Star Wars: Além da Fronteira — habilidades de classe, Grupo C
// Vigilante, Padawan Jedi, Acólito Sith, Andarilho da Força, O Lado da Luz, O Lado Negro, Xamã da Força

import type { ClassAbilityTable } from "./types";

export const CLASS_GROUP_C: ClassAbilityTable[] = [
  {
    classId: "vigilante",
    abilities: [
      { level: 1, name: "Golpe da Justiça", combat: true, description: "Ataque direto contra alvo claramente hostil/culpado.", peCost: 1, damageDice: "1d6" },
      { level: 1, name: "Olhar Vigilante", combat: false, description: "Identifica ameaças e injustiças em curso.", peCost: 1, dt: 15 },
      { level: 2, name: "Passo nas Sombras", combat: false, description: "Movimento silencioso em áreas urbanas.", peCost: 1, dt: 15 },
      { level: 3, name: "Intimidação Direta", combat: true, description: "Ataque de aviso que abala moral do alvo.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Rede de Informantes", combat: false, description: "Obtém pistas sobre alvos e crimes locais.", peCost: 2, dt: 17 },
      { level: 5, name: "Golpe Surpresa", combat: true, description: "Dano aumentado ao atacar de surpresa.", peCost: 2, damageDice: "2d6" },
      { level: 6, name: "Disfarce Urbano", combat: false, description: "Se mistura à população para observar sem ser notado.", peCost: 2, dt: 17 },
      { level: 8, name: "Contenção Forçada", combat: true, description: "Imobiliza alvo hostil sem matar.", peCost: 2, damageDice: "2d6" },
      { level: 9, name: "Instinto de Justiceiro", combat: false, description: "Prevê próximo movimento de criminosos/alvos.", peCost: 2, dt: 19 },
      { level: 10, name: "Golpe Implacável", combat: true, description: "Ataque de dano elevado contra alvo confirmado culpado.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Rede da Noite", combat: false, description: "Coordena com outros vigilantes/informantes na região.", peCost: 2, dt: 19 },
      { level: 12, name: "Emboscada Urbana", combat: true, description: "Ataque surpresa em ambiente urbano com dano extra.", peCost: 2, damageDice: "3d6" },
      { level: 13, name: "Presença Temida", combat: false, description: "Intimida criminosos apenas com sua reputação.", peCost: 3, dt: 21 },
      { level: 14, name: "Fúria da Justiça", combat: true, description: "Sequência de golpes contra alvo especialmente cruel/perigoso.", peCost: 3, damageDice: "4d6" },
      { level: 15, name: "Blindagem Improvisada", combat: false, description: "Proteção adaptada para combate urbano.", peCost: 3, dt: 21 },
      { level: 16, name: "Captura Decisiva", combat: true, description: "Ataque que neutraliza alvo de alto risco rapidamente.", peCost: 3, damageDice: "4d6" },
      { level: 17, name: "Lenda das Sombras", combat: false, description: "Reputação afasta criminosos comuns antes mesmo do confronto.", peCost: 3, dt: 23 },
      { level: 18, name: "Golpe Final da Justiça", combat: true, description: "Ataque de altíssimo dano contra alvo extremamente perigoso.", peCost: 3, damageDice: "5d6" },
      { level: 19, name: "Guardião da Cidade", combat: false, description: "Protege uma região inteira com eficiência conhecida.", peCost: 3, dt: 23 },
      { level: 20, name: "Justiça Absoluta", combat: true, description: "Ataque devastador contra o pior tipo de ameaça urbana.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Símbolo do Medo", description: "Criminosos hesitam ou fogem só ao saber que ele está por perto.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 35, name: "Justiceiro Implacável", description: "Ataques consecutivos de altíssimo dano contra alvos confirmados.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 30, name: "Lenda Urbana", description: "Torna-se figura quase mítica de justiça e combate.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 40, name: "Julgamento Final", description: "Executa o ataque mais decisivo contra a maior ameaça que a cidade já enfrentou.", combat: true, peCost: 8, damageDice: "18d6" },
    ],
  },

  // ─── Classes-base ligadas à Força (aprendem Formas de Sabre) ────────────────
  {
    classId: "padawan_jedi",
    abilities: [
      { level: 1, name: "Primeiras Formas", combat: true, formTag: "primeiras_formas", description: "Aprende Shii-Cho (I) e Soresu (III).", peCost: 1, weaponDamage: "sabre" },
      { level: 1, name: "Sentir a Força", combat: false, description: "Percebe perigo, emoções e presenças próximas.", peCost: 1, dt: 15 },
      { level: 2, name: "Empurrão da Força", combat: true, description: "Repele o inimigo com uma onda de energia.", peCost: 1, damageDice: "1d6" },
      { level: 3, name: "Salto da Força", combat: true, description: "Impulso que fecha distância com ataque de queda.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Segundas Formas", combat: true, formTag: "segundas_formas", description: "Aprende Makashi (II) e Ataru (IV).", peCost: 2, weaponDamage: "sabre" },
      { level: 5, name: "Puxão da Força", combat: true, description: "Arranca arma ou desequilibra o inimigo à distância.", peCost: 2, damageDice: "2d6" },
      { level: 6, name: "Premonição", combat: false, description: "Antecipa o próximo ataque inimigo (bônus defensivo).", peCost: 2, dt: 17 },
      { level: 8, name: "Investida de Sabre", combat: true, description: "Avanço rápido com golpe concentrado.", peCost: 2, weaponDamage: "sabre" },
      { level: 9, name: "Formas Completas", combat: true, formTag: "formas_completas", description: "Aprende Djem So (V), Niman (VI) e Vaapad (VII) — domina as 7 formas.", peCost: 2, weaponDamage: "sabre" },
      { level: 10, name: "Onda de Choque", combat: true, description: "Pulso de Força que derruba múltiplos inimigos próximos.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Salto Acrobático", combat: false, description: "Mobilidade extrema em combate.", peCost: 2, dt: 19 },
      { level: 12, name: "Corte Duplo", combat: true, description: "Sequência de golpes de sabre em dois alvos.", peCost: 2, weaponDamage: "sabre" },
      { level: 13, name: "Domínio: Soresu", combat: true, formTag: "dominio", description: "Soresu vira forma dominante — defesa quase impenetrável.", peCost: 3, weaponDamage: "sabre" },
      { level: 14, name: "Domínio: Ataru", combat: true, formTag: "dominio", description: "Ataru vira forma dominante — sequência acrobática de alto dano.", peCost: 3, weaponDamage: "sabre" },
      { level: 15, name: "Barreira da Força", combat: false, description: "Escudo que bloqueia ataques físicos e de energia por um tempo.", peCost: 3, dt: 21 },
      { level: 16, name: "Arremesso de Sabre", combat: true, description: "Lança o sabre controlado pela Força e o retorna à mão.", peCost: 3, weaponDamage: "sabre" },
      { level: 17, name: "Especialização de Forma", combat: false, formTag: "especializacao", description: "Escolhe 1 das 7 formas aprendidas como especialidade (igual nas 3 classes-base).", peCost: 3, dt: 23 },
      { level: 18, name: "Tempestade de Força", combat: true, description: "Combina golpes de sabre com empurrões/puxões em sequência.", peCost: 3, weaponDamage: "sabre" },
      { level: 19, name: "Serenidade Jedi", combat: false, description: "Recupera-se de efeitos negativos com foco mental.", peCost: 3, dt: 23 },
      { level: 20, name: "Golpe da Luz", combat: true, description: "Ataque final que une sabre e Força num só golpe decisivo.", peCost: 3, weaponDamage: "sabre" },
    ],
    milestones: [
      { level: 25, name: "Domínio Absoluto", description: "Maestria completa na forma especialista — reação quase automática nela.", combat: false, peCost: 4, dt: 26 },
      { level: 25, name: "Reflexo Perfeito", description: "Deflexão de sabre quase infalível; pode revidar automaticamente.", combat: true, peCost: 4, weaponDamage: "sabre" },
      { level: 25, name: "Chamado da Luz", description: "A conexão com o Lado da Luz amadureceu — abre caminho para se tornar O Lado da Luz.", combat: false, peCost: 4, dt: 27 },
      { level: 25, name: "Consagração do Sabre", description: "O sabre brilha mais intenso; dano extra contra alvos do Lado Sombrio.", combat: true, peCost: 4, weaponDamage: "sabre" },
      { level: 35, name: "Tempestade da Luz", description: "Sequência de golpes de sabre e Força que atinge todos ao redor.", combat: true, peCost: 5, weaponDamage: "sabre" },
      { level: 35, name: "Muralha de Luz", description: "Campo de proteção que também empurra e fere inimigos que o tocam.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 40, name: "Julgamento Sereno", description: "Ataque preciso que ignora parte da defesa do alvo.", combat: true, peCost: 5, damageDice: "10d6" },
      { level: 40, name: "Presença Inabalável", description: "Aura que fortalece aliados e enfraquece a moral dos inimigos.", combat: false, peCost: 5, dt: 30 },
      { level: 30, name: "Guardião da Ordem", description: "Poder de sabre e Força em nível de Cavaleiro Jedi consagrado.", combat: true, peCost: 6, weaponDamage: "sabre" },
      { level: 30, name: "Eco dos Mestres", description: "Canaliza a sabedoria de mestres Jedi passados num bônus temporário massivo.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 40, name: "Iluminação Jedi", description: "Clareza total que resolve o combate com precisão quase sobrenatural.", combat: false, peCost: 8, dt: 36 },
    ],
  },
  {
    classId: "acolito_sith",
    abilities: [
      { level: 1, name: "Primeiras Formas", combat: true, formTag: "primeiras_formas", description: "Aprende Djem So (V) e Vaapad (VII).", peCost: 1, weaponDamage: "sabre" },
      { level: 1, name: "Sentir a Raiva", combat: false, description: "Percebe fraquezas emocionais do oponente.", peCost: 1, dt: 15 },
      { level: 2, name: "Empurrão Sombrio", combat: true, description: "Onda de Força carregada de raiva, mais bruta que a versão Jedi.", peCost: 1, damageDice: "1d6" },
      { level: 3, name: "Salto da Força", combat: true, description: "Impulso que fecha distância com ataque de queda.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Segundas Formas", combat: true, formTag: "segundas_formas", description: "Aprende Makashi (II) e Shii-Cho (I).", peCost: 2, weaponDamage: "sabre" },
      { level: 5, name: "Relâmpago Menor", combat: true, description: "Descarga elétrica de curto alcance.", peCost: 2, damageDice: "2d6" },
      { level: 6, name: "Presença Sombria", combat: false, description: "Intimida inimigos próximos com aura de poder.", peCost: 2, dt: 17 },
      { level: 8, name: "Golpe Impiedoso", combat: true, description: "Ataque de sabre que ignora parte da defesa do inimigo.", peCost: 2, weaponDamage: "sabre" },
      { level: 9, name: "Formas Completas", combat: true, formTag: "formas_completas", description: "Aprende Soresu (III), Ataru (IV) e Niman (VI) — domina as 7 formas.", peCost: 2, weaponDamage: "sabre" },
      { level: 10, name: "Relâmpago da Força", combat: true, description: "Descarga elétrica de alcance médio, dano elevado.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Salto Predatório", combat: true, description: "Avanço agressivo com golpe de sabre ao aterrissar.", peCost: 2, weaponDamage: "sabre" },
      { level: 12, name: "Ilusão do Medo", combat: false, description: "Faz o inimigo hesitar ou fugir por instantes.", peCost: 2, dt: 19 },
      { level: 13, name: "Domínio: Djem So", combat: true, formTag: "dominio", description: "Djem So vira forma dominante — converte defesa em contra-ataque devastador.", peCost: 3, weaponDamage: "sabre" },
      { level: 14, name: "Domínio: Vaapad", combat: true, formTag: "dominio", description: "Vaapad vira forma dominante — sequência imprevisível de altíssimo dano.", peCost: 3, weaponDamage: "sabre" },
      { level: 15, name: "Estrangulamento", combat: true, description: "Sufoca o alvo à distância, causando dano e imobilização parcial.", peCost: 3, damageDice: "4d6" },
      { level: 16, name: "Drenar Força", combat: true, description: "Rouba energia/vitalidade do alvo para si.", peCost: 3, damageDice: "4d6" },
      { level: 17, name: "Especialização de Forma", combat: false, formTag: "especializacao", description: "Escolhe 1 das 7 formas aprendidas como especialidade (igual nas 3 classes-base).", peCost: 3, dt: 23 },
      { level: 18, name: "Fúria Desencadeada", combat: true, description: "Sequência devastadora de golpes de sabre com dano crescente.", peCost: 3, weaponDamage: "sabre" },
      { level: 19, name: "Máscara do Sombrio", combat: false, description: "Esconde presença na Força de sensitivos inimigos.", peCost: 3, dt: 23 },
      { level: 20, name: "Golpe da Escuridão", combat: true, description: "Ataque final que une sabre, relâmpago e fúria num só golpe brutal.", peCost: 3, weaponDamage: "sabre" },
    ],
    milestones: [
      { level: 25, name: "Domínio Absoluto", description: "Maestria completa na forma especialista.", combat: false, peCost: 4, dt: 26 },
      { level: 25, name: "Fome de Poder", description: "Cada inimigo abatido aumenta o dano dos próximos golpes.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 25, name: "Chamado da Escuridão", description: "A entrega ao Lado Sombrio amadureceu — abre caminho para se tornar O Lado Negro.", combat: false, peCost: 4, dt: 27 },
      { level: 25, name: "Onda de Dor", description: "Explosão de Força carregada de sofrimento que atinge todos ao redor.", combat: true, peCost: 4, damageDice: "8d6" },
      { level: 35, name: "Fúria Absoluta", description: "Estado de combate onde cada golpe aumenta o próximo.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 35, name: "Corrupção do Sabre", description: "A lâmina passa a causar dano adicional de energia sombria a cada golpe.", combat: true, peCost: 5, weaponDamage: "sabre" },
      { level: 40, name: "Julgamento Cruel", description: "Ataque que ignora defesa e resistência do alvo, guiado por ódio puro.", combat: true, peCost: 5, damageDice: "10d6" },
      { level: 40, name: "Domínio do Medo", description: "Aura que enfraquece a moral e a precisão dos inimigos próximos.", combat: false, peCost: 5, dt: 30 },
      { level: 30, name: "Senhor da Dor", description: "Drena vida e força do inimigo enquanto ataca sem piedade.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 30, name: "Legado Sombrio", description: "Canaliza o poder de antigos Sith num bônus temporário massivo.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 40, name: "Ira do Lado Sombrio", description: "Libera todo o ódio acumulado num ataque capaz de arrasar um campo de batalha inteiro.", combat: false, peCost: 8, dt: 36 },
    ],
  },
  {
    classId: "andarilho_forca",
    abilities: [
      { level: 1, name: "Primeiras Formas", combat: true, formTag: "primeiras_formas", description: "Aprende Ataru (IV) e Niman (VI).", peCost: 1, weaponDamage: "sabre" },
      { level: 1, name: "Instinto Aguçado", combat: false, description: "Percebe perigo antes que aconteça, sem entender a Força conscientemente.", peCost: 1, dt: 15 },
      { level: 2, name: "Empurrão Bruto", combat: true, description: "Explosão de Força não refinada que arremessa o inimigo.", peCost: 1, damageDice: "1d6" },
      { level: 3, name: "Salto da Força", combat: true, description: "Impulso que fecha distância com ataque de queda.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Segundas Formas", combat: true, formTag: "segundas_formas", description: "Aprende Soresu (III) e Djem So (V).", peCost: 2, weaponDamage: "sabre" },
      { level: 5, name: "Arremesso Cru", combat: true, description: "Atira objetos do ambiente com a Força contra o inimigo.", peCost: 2, damageDice: "2d6" },
      { level: 6, name: "Leitura Bruta", combat: false, description: "Sente intenções hostis próximas, sem a precisão de um Jedi/Sith.", peCost: 2, dt: 17 },
      { level: 8, name: "Golpe Ampliado", combat: true, description: "Soco/chute com força física amplificada pela Força.", peCost: 2, damageDice: "2d6" },
      { level: 9, name: "Formas Completas", combat: true, formTag: "formas_completas", description: "Aprende Shii-Cho (I), Makashi (II) e Vaapad (VII) — domina as 7 formas.", peCost: 2, weaponDamage: "sabre" },
      { level: 10, name: "Golpe Duplo Instintivo", combat: true, description: "Dois ataques corpo a corpo em sequência rápida.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Barreira Improvisada", combat: false, description: "Proteção instável com a Força, sem controle refinado.", peCost: 2, dt: 19 },
      { level: 12, name: "Investida Selvagem", combat: true, description: "Avanço com impacto de Força bruta no golpe final.", peCost: 2, damageDice: "3d6" },
      { level: 13, name: "Domínio: Niman", combat: true, formTag: "dominio", description: "Niman vira forma dominante — alterna estilos de forma imprevisível.", peCost: 3, weaponDamage: "sabre" },
      { level: 14, name: "Domínio: Djem So", combat: true, formTag: "dominio", description: "Djem So vira forma dominante — contra-ataque bruto e direto.", peCost: 3, weaponDamage: "sabre" },
      { level: 15, name: "Absorção de Impacto", combat: false, description: "Reduz dano de ataques físicos e de energia usando a Força instintivamente.", peCost: 3, dt: 21 },
      { level: 16, name: "Arremesso Devastador", combat: true, description: "Lança um objeto pesado ou o próprio inimigo com força bruta.", peCost: 3, damageDice: "4d6" },
      { level: 17, name: "Especialização de Forma", combat: false, formTag: "especializacao", description: "Escolhe 1 das 7 formas aprendidas como especialidade (igual nas 3 classes-base).", peCost: 3, dt: 23 },
      { level: 18, name: "Golpe Imparável", combat: true, description: "Sequência de ataques corpo a corpo amplificados sem padrão previsível.", peCost: 3, damageDice: "5d6" },
      { level: 19, name: "Eco da Força", combat: false, description: "Sente combates e presenças a grande distância.", peCost: 3, dt: 23 },
      { level: 20, name: "Fúria Desperta", combat: true, description: "Ataque final onde corpo e Força bruta se fundem num só golpe devastador.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Domínio Absoluto", description: "Maestria completa na forma especialista — reação quase automática nela.", combat: false, peCost: 4, dt: 26 },
      { level: 25, name: "Instinto Predatório Total", description: "Percepção quase onisciente de ameaças próximas, mesmo fora do campo de visão.", combat: false, peCost: 4, dt: 26 },
      { level: 25, name: "Despertar Latente", description: "O potencial bruto amadureceu — abre caminho para se tornar Xamã da Força.", combat: false, peCost: 4, dt: 27 },
      { level: 25, name: "Fúria da Terra", description: "Libera uma onda de Força bruta em área ao redor, sem refinamento mas devastadora.", combat: true, peCost: 4, damageDice: "8d6" },
      { level: 35, name: "Fúria Sem Controle", description: "Poder bruto cresce a cada golpe recebido ou desferido.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 35, name: "Corpo Inquebrável", description: "Resistência extrema a dano físico e efeitos debilitantes por tempo curto.", combat: false, peCost: 5, dt: 29 },
      { level: 40, name: "Golpe do Destino", description: "Ataque guiado por puro instinto que atinge o ponto mais vulnerável do alvo.", combat: true, peCost: 5, damageDice: "10d6" },
      { level: 40, name: "Eco Ancestral", description: "Canaliza a força de andarilhos que vieram antes dele.", combat: false, peCost: 5, dt: 30 },
      { level: 30, name: "Lenda Sem Nome", description: "Luta com poder equivalente a um mestre treinado, mas de forma completamente instintiva.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 30, name: "Vontade Selvagem", description: "Recupera-se de qualquer efeito negativo instantaneamente, por pura força de vontade.", combat: false, peCost: 6, dt: 32 },
      { level: 40, name: "Despertar Total", description: "Libera toda a Força latente acumulada a vida inteira num único ataque devastador.", combat: false, peCost: 8, dt: 36 },
    ],
  },
];

// Removidas do sistema (ver classes.ts) — nomes guardados pra referência futura:
// "O Lado da Luz", "O Lado Negro", "Xamã da Força".
