// Star Wars: Além da Fronteira — habilidades de classe, Grupo A
// Arqueólogo, Caçador de Recompensas, Cientista, Comerciante, Contrabandista, Diplomata, Engenheiro, Espião

import type { ClassAbilityTable } from "./types";

export const CLASS_GROUP_A: ClassAbilityTable[] = [
  {
    classId: "arqueologo",
    abilities: [
      { level: 1, name: "Golpe de Sucata", combat: true, description: "Arremessa peças, ferramentas ou fragmentos de ruína para causar dano leve e atrapalhar o alvo.", peCost: 1, damageDice: "1d6" },
      { level: 1, name: "Leitura de Campo", combat: false, description: "Identifica estruturas ocultas, cavidades e pontos frágeis do terreno.", peCost: 1, dt: 15 },
      { level: 2, name: "Ferramentas de Expedição", combat: false, description: "Usa kit arqueológico como arma improvisada ou ferramenta de ataque de curta distância.", peCost: 1, dt: 15 },
      { level: 3, name: "Impacto de Ruína", combat: true, description: "Faz desabar pedras, vigas ou detritos sobre o inimigo, causando dano em área pequena.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Decifração Sob Pressão", combat: false, description: "Lê painéis e inscrições durante combate para ativar mecanismos ofensivos antigos.", peCost: 2, dt: 17 },
      { level: 5, name: "Desarme Reverso", combat: false, description: "Converte uma armadilha antiga em ataque contra inimigos próximos.", peCost: 2, dt: 17 },
      { level: 6, name: "Pulso de Análise", combat: false, description: "Expõe fraquezas de armaduras, escudos e estruturas.", peCost: 2, dt: 17 },
      { level: 8, name: "Estouro de Fragmentos", combat: true, description: "Explode objetos, paredes frágeis ou sucata, causando dano e espalhando estilhaços.", peCost: 2, damageDice: "2d6" },
      { level: 9, name: "Mapeamento Tático", combat: false, description: "Marca linhas de tiro, emboscadas e pontos cegos no cenário para vantagem ofensiva.", peCost: 2, dt: 19 },
      { level: 10, name: "Raio de Restauro", combat: false, description: "Reativa parcialmente uma máquina antiga para que ela ataque ou defenda por um curto período.", peCost: 2, dt: 19 },
      { level: 11, name: "Armadilha Revertida", combat: true, description: "Redireciona dano e efeitos de armadilhas para atingir os inimigos.", peCost: 2, damageDice: "3d6" },
      { level: 12, name: "Cortina de Ruína", combat: true, description: "Derruba poeira, escombros e detritos para ferir, cegar e desorientar.", peCost: 2, damageDice: "3d6" },
      { level: 13, name: "Núcleo Recuperado", combat: true, description: "Extrai energia de relíquias ou motores mortos e libera uma descarga ofensiva.", peCost: 3, damageDice: "4d6" },
      { level: 14, name: "Arma Relíquia", combat: true, description: "Usa um artefato antigo como arma de combate, com dano elevado e efeito único.", peCost: 3, damageDice: "4d6" },
      { level: 15, name: "Fratura Estrutural", combat: false, description: "Ataca pontos de suporte para causar colapso parcial ou total do ambiente.", peCost: 3, dt: 21 },
      { level: 16, name: "Refúgio Hostil", combat: false, description: "Ergue proteção improvisada que também serve como cobertura de contra-ataque.", peCost: 3, dt: 21 },
      { level: 17, name: "Chave do Passado", combat: false, description: "Abre sistemas antigos durante combate para liberar armadilhas, drones ou torres hostis.", peCost: 3, dt: 23 },
      { level: 18, name: "Restauração Bélica", combat: false, description: "Devolve função ofensiva a uma relíquia, torre ou droid antigo por tempo limitado.", peCost: 3, dt: 23 },
      { level: 19, name: "Herança Cortante", combat: true, description: "Invoca o poder de um artefato recuperado para atacar com dano raro ou energético.", peCost: 3, damageDice: "5d6" },
      { level: 20, name: "Descoberta Letal", combat: true, description: "Revela uma estrutura, câmara ou mecanismo que vira o combate a seu favor de forma decisiva.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Ruína Explosiva", description: "Faz o cenário colapsar em cadeia, causando grande dano em área e controlando o campo.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 35, name: "Guardião do Templo", description: "Libera uma ofensiva antiga — droides, torres ou mecanismos de defesa — que atacam inimigos.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 30, name: "Cataclismo Arqueológico", description: "Provoca um colapso massivo ou ativação extrema de relíquia, causando dano devastador.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 40, name: "Relíquia do Fim dos Tempos", description: "Desperta uma arma ou artefato lendário capaz de alterar uma batalha inteira com um único uso.", combat: true, peCost: 8, damageDice: "18d6" },
    ],
  },
  {
    classId: "cacador_recompensas",
    abilities: [
      { level: 1, name: "Tiro de Pressão", combat: true, description: "Dispara para forçar o alvo a se abaixar, perder posição ou recuar.", peCost: 1, damageDice: "1d6" },
      { level: 1, name: "Rastro Quente", combat: false, description: "Segue sinais recentes de fuga, calor e movimento.", peCost: 1, dt: 15 },
      { level: 2, name: "Golpe de Contenção", combat: true, description: "Atinge para desarmar, derrubar ou imobilizar.", peCost: 1, damageDice: "1d6" },
      { level: 3, name: "Leitura de Alvo", combat: false, description: "Identifica postura, medo, agressividade e padrão de combate.", peCost: 1, dt: 15 },
      { level: 4, name: "Armadilha de Captura", combat: false, description: "Monta laços, fios, placas ou dispositivos para prender o inimigo.", peCost: 2, dt: 17 },
      { level: 5, name: "Mira Brutal", combat: true, description: "Aumenta o dano de tiros contra alvos marcados ou feridos.", peCost: 2, damageDice: "2d6" },
      { level: 6, name: "Cobertura Instintiva", combat: false, description: "Usa o terreno para reduzir dano e manter vantagem em tiroteios.", peCost: 2, dt: 17 },
      { level: 8, name: "Intimidação Fria", combat: false, description: "Abala a moral do inimigo, podendo forçar hesitação, erro ou rendição.", peCost: 2, dt: 17 },
      { level: 9, name: "Rajada de Supressão", combat: true, description: "Sequência de disparos que trava avanço inimigo e controla espaço.", peCost: 2, damageDice: "3d6" },
      { level: 10, name: "Rastreador Biométrico", combat: false, description: "Encontra alvos por calor, sangue, assinatura corporal ou rastros digitais.", peCost: 2, dt: 19 },
      { level: 11, name: "Captura Limpa", combat: true, description: "Executa uma neutralização precisa sem matar, ideal para contratos vivos.", peCost: 2, damageDice: "3d6" },
      { level: 12, name: "Movimento Predatório", combat: false, description: "Melhora reposicionamento, investida e perseguição em combate.", peCost: 2, dt: 19 },
      { level: 13, name: "Ferramentas de Guerra", combat: true, description: "Usa bombas, cabos, dardos e ganchos como ataque tático.", peCost: 3, damageDice: "4d6" },
      { level: 14, name: "Emboscada Perfeita", combat: true, description: "Ganha grande vantagem ao atacar de surpresa, de cima ou por flanco.", peCost: 3, damageDice: "4d6" },
      { level: 15, name: "Blindagem de Operação", combat: false, description: "Adapta a armadura para resistir a disparos, explosões e calor.", peCost: 3, dt: 21 },
      { level: 16, name: "Interrogação de Campo", combat: false, description: "Extrai informação de alvos capturados ou feridos sob pressão.", peCost: 3, dt: 21 },
      { level: 17, name: "Alvo Marcado", combat: false, description: "Escolhe um inimigo prioritário e passa a caçá-lo com eficiência extrema.", peCost: 3, dt: 23 },
      { level: 18, name: "Execução Técnica", combat: true, description: "Aplica um disparo ou golpe final com altíssima precisão e dano.", peCost: 3, damageDice: "5d6" },
      { level: 19, name: "Caçada Sem Fim", combat: false, description: "Mantém perseguição intensa sem perder o alvo.", peCost: 3, dt: 23 },
      { level: 20, name: "Predador da Galáxia", combat: true, description: "Entra em estado de caça total, unindo rastreamento, dano e contenção.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Caça Profissional", description: "Sua pressão ofensiva aumenta muito contra alvos contratados.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 35, name: "Arsenal Personalizado", description: "Seu equipamento de combate ganha modificações únicas e letais.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 30, name: "Lenda do Submundo", description: "Sua reputação faz inimigos hesitarem antes mesmo do primeiro tiro.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 40, name: "Predador Definitivo", description: "Executa uma caçada lendária com potencial de eliminar ou capturar alvos quase impossíveis.", combat: true, peCost: 8, damageDice: "18d6" },
    ],
  },
  {
    classId: "cientista",
    abilities: [
      { level: 1, name: "Pulso Analítico", combat: false, description: "Identifica a fraqueza técnica de um alvo, armadura ou aparelho.", peCost: 1, dt: 15 },
      { level: 1, name: "Reação Instável", combat: true, description: "Cria uma pequena descarga, ácido, gás ou explosão controlada.", peCost: 1, damageDice: "1d6" },
      { level: 2, name: "Diagnóstico de Combate", combat: false, description: "Detecta falhas em droides, escudos e armas inimigas.", peCost: 1, dt: 15 },
      { level: 3, name: "Protocolo de Emergência", combat: true, description: "Converte equipamentos científicos em defesa ou ataque improvisado.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Composto Hostil", combat: true, description: "Cria substâncias que queimam, cegam, travam ou enfraquecem.", peCost: 2, damageDice: "2d6" },
      { level: 5, name: "Campo Experimental", combat: false, description: "Altera uma pequena área para dificultar movimento, mira ou estabilidade.", peCost: 2, dt: 17 },
      { level: 6, name: "Biorresposta", combat: true, description: "Manipula venenos, sedativos e toxinas contra inimigos ou criaturas.", peCost: 2, damageDice: "2d6" },
      { level: 8, name: "Reação em Cadeia", combat: true, description: "Faz um artefato, tanque ou material reagir violentamente em combate.", peCost: 2, damageDice: "2d6" },
      { level: 9, name: "Sensor de Falha", combat: false, description: "Detecta o momento ideal para interromper o funcionamento de um sistema inimigo.", peCost: 2, dt: 19 },
      { level: 10, name: "Descarga Técnica", combat: true, description: "Libera um ataque energético ou químico de médio alcance.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Protótipo de Guerra", combat: true, description: "Cria um dispositivo ofensivo especializado para a missão.", peCost: 2, damageDice: "3d6" },
      { level: 12, name: "Estabilização Molecular", combat: false, description: "Trava ou enfraquece matéria, estrutura ou equipamento do alvo.", peCost: 2, dt: 19 },
      { level: 13, name: "Sabotagem Ativa", combat: false, description: "Faz armas, motores, escudos ou droides falharem em combate.", peCost: 3, dt: 21 },
      { level: 14, name: "Reação Dirigida", combat: true, description: "Lança uma fórmula ou pulso que causa dano direto e efeito secundário.", peCost: 3, damageDice: "4d6" },
      { level: 15, name: "Autópsia Tecnobiológica", combat: false, description: "Explora fraquezas de organismos, clones e ciborgues para atacar melhor.", peCost: 3, dt: 21 },
      { level: 16, name: "Queda de Sistema", combat: true, description: "Derruba tecnologia inimiga por sobrecarga ou interferência.", peCost: 3, damageDice: "4d6" },
      { level: 17, name: "Domínio da Hipótese", combat: false, description: "Prevê o comportamento inimigo e escolhe a melhor forma de ataque.", peCost: 3, dt: 23 },
      { level: 18, name: "Reconfiguração Total", combat: true, description: "Transforma um equipamento em arma ou solução de combate imediata.", peCost: 3, damageDice: "5d6" },
      { level: 19, name: "Síntese Avançada", combat: false, description: "Produz compostos raros e extremamente perigosos para uso tático.", peCost: 3, dt: 23 },
      { level: 20, name: "Descoberta Científica", combat: true, description: "Cria uma solução inédita com efeito devastador em campo.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Laboratório Autônomo", description: "Passa a criar ofensivas e contramedidas mesmo sob pressão.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 35, name: "Criação Avançada", description: "Gera protótipos altamente letais ou decisivos.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 30, name: "Mente de Fronteira", description: "Encontra soluções agressivas para problemas impossíveis.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 40, name: "Salto do Conhecimento", description: "Produz uma inovação de guerra capaz de mudar uma batalha inteira.", combat: true, peCost: 8, damageDice: "18d6" },
    ],
  },
  {
    classId: "comerciante",
    abilities: [
      { level: 1, name: "Leitura de Mercado", combat: false, description: "Identifica valor, escassez e oportunidade antes dos outros.", peCost: 1, dt: 15 },
      { level: 1, name: "Empurrão Comercial", combat: false, description: "Usa conversa e presença para obter vantagem social e abrir espaço.", peCost: 1, dt: 15 },
      { level: 2, name: "Cobrança Dura", combat: true, description: "Pressiona uma dívida, acordo ou rival com ameaça econômica ou social.", peCost: 1, damageDice: "1d6" },
      { level: 3, name: "Estoque Pronto", combat: true, description: "Entra em combate com recursos, munição e equipamentos já organizados.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Rede Comercial", combat: false, description: "Chama fornecedores, intermediários e contatos para apoiar a missão.", peCost: 2, dt: 17 },
      { level: 5, name: "Troca de Pressão", combat: true, description: "Oferece ou recusa recursos para enfraquecer a posição de um inimigo.", peCost: 2, damageDice: "2d6" },
      { level: 6, name: "Avaliação Rápida", combat: false, description: "Reconhece falsificações, peças valiosas e pontos fracos de mercadorias.", peCost: 2, dt: 17 },
      { level: 8, name: "Rotas Discretas", combat: false, description: "Move carga ou equipe por caminhos que evitam emboscadas e bloqueios.", peCost: 2, dt: 17 },
      { level: 9, name: "Barganha Hostil", combat: true, description: "Transforma negociação em arma, forçando vantagem sobre o oponente.", peCost: 2, damageDice: "3d6" },
      { level: 10, name: "Logística de Guerra", combat: false, description: "Mantém aliados abastecidos e o inimigo em desvantagem material.", peCost: 2, dt: 19 },
      { level: 11, name: "Estoque de Emergência", combat: true, description: "Libera recursos críticos no momento certo para sobreviver ou vencer.", peCost: 2, damageDice: "3d6" },
      { level: 12, name: "Mercado Cinza", combat: false, description: "Compra, vende ou movimenta itens estratégicos fora das regras comuns.", peCost: 2, dt: 19 },
      { level: 13, name: "Financiamento de Missão", combat: true, description: "Converte crédito em poder real no campo.", peCost: 3, damageDice: "4d6" },
      { level: 14, name: "Leilão Oportunista", combat: false, description: "Lucra e enfraquece rivais em meio à crise, guerra ou caos.", peCost: 3, dt: 21 },
      { level: 15, name: "Intermediação de Conflito", combat: false, description: "Usa posição econômica para influenciar facções e decisões.", peCost: 3, dt: 21 },
      { level: 16, name: "Carga Prioritária", combat: true, description: "Protege o recurso mais valioso da operação com foco absoluto.", peCost: 3, damageDice: "4d6" },
      { level: 17, name: "Monopólio Local", combat: false, description: "Domina um setor, rota ou produto, sufocando concorrentes.", peCost: 3, dt: 23 },
      { level: 18, name: "Crédito de Confiança", combat: false, description: "Obtém recursos e favores antes mesmo de pagar.", peCost: 3, dt: 23 },
      { level: 19, name: "Troca de Alto Valor", combat: true, description: "Movimenta itens raros ou proibidos com enorme vantagem.", peCost: 3, damageDice: "5d6" },
      { level: 20, name: "Império de Lucro", combat: true, description: "Transforma comércio em poder político, militar e logístico.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Rede de Distribuição", description: "Sua estrutura passa a sustentar a guerra de forma contínua.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 35, name: "Capital de Guerra", description: "Dinheiro vira vantagem ofensiva e defensiva imediata.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 30, name: "Senhor das Rotas", description: "Controla fluxos estratégicos e corta o inimigo de recursos.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 40, name: "Mão Invisível", description: "Manipula recursos e eventos de forma quase impossível de conter.", combat: true, peCost: 8, damageDice: "18d6" },
    ],
  },
  {
    classId: "contrabandista",
    abilities: [
      { level: 1, name: "Rota Clandestina", combat: false, description: "Encontra caminhos discretos para mover pessoas ou carga.", peCost: 1, dt: 15 },
      { level: 1, name: "Carga Oculta", combat: false, description: "Esconde armas, mercadorias ou passageiros em veículos e compartimentos.", peCost: 1, dt: 15 },
      { level: 2, name: "Despiste Rápido", combat: true, description: "Rompe perseguições com curvas, iscas ou manobras curtas.", peCost: 1, damageDice: "1d6" },
      { level: 3, name: "Leitura de Bloqueio", combat: false, description: "Percebe patrulhas, pontos de controle e zonas de risco antes de entrar.", peCost: 1, dt: 15 },
      { level: 4, name: "Documento Frio", combat: false, description: "Falsifica ou adapta documentos, selos e registros básicos.", peCost: 2, dt: 17 },
      { level: 5, name: "Negócio Sujo", combat: false, description: "Vende, troca ou negocia mercadorias proibidas com vantagem.", peCost: 2, dt: 17 },
      { level: 6, name: "Bunker Móvel", combat: true, description: "Protege carga e tripulação dentro da nave ou veículo.", peCost: 2, damageDice: "2d6" },
      { level: 8, name: "Fuga de Pista", combat: true, description: "Reduz drasticamente as chances de ser seguido por sensores e rastreadores.", peCost: 2, damageDice: "2d6" },
      { level: 9, name: "Corredor de Sombra", combat: false, description: "Atravessa áreas perigosas sem chamar atenção.", peCost: 2, dt: 19 },
      { level: 10, name: "Piloto de Risco", combat: true, description: "Melhora manobras em perseguições, obstáculos e terreno apertado.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Carga Sensível", combat: false, description: "Transporta itens frágeis, explosivos ou valiosos sem perder eficiência.", peCost: 2, dt: 19 },
      { level: 12, name: "Blecaute Tático", combat: true, description: "Corta luz, sinal ou comunicação para abrir caminho ou causar confusão.", peCost: 2, damageDice: "3d6" },
      { level: 13, name: "Mercado Negro", combat: false, description: "Acessa armas, peças, informações e contatos ilegais.", peCost: 3, dt: 21 },
      { level: 14, name: "Falso Positivo", combat: false, description: "Faz nave, carga ou equipe parecer sem importância para inspeções.", peCost: 3, dt: 21 },
      { level: 15, name: "Contrabando Vivo", combat: false, description: "Transporta pessoas, criaturas ou alvos de forma discreta e eficiente.", peCost: 3, dt: 21 },
      { level: 16, name: "Saída de Emergência", combat: true, description: "Cria rota de fuga mesmo quando tudo já está cercado.", peCost: 3, damageDice: "4d6" },
      { level: 17, name: "Rede de Rotas", combat: false, description: "Conhece múltiplas passagens, portos e contatos para mover qualquer coisa.", peCost: 3, dt: 23 },
      { level: 18, name: "Carga Inexpugnável", combat: true, description: "Protege mercadorias importantes contra roubo, dano e interceptação.", peCost: 3, damageDice: "5d6" },
      { level: 19, name: "Pilha de Favores", combat: false, description: "Usa dívidas, contatos e promessas como arma social e logística.", peCost: 3, dt: 23 },
      { level: 20, name: "Fantasma da Rota", combat: true, description: "Atravessa sistemas como se não existisse, quase impossível de rastrear.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Corredor Cego", description: "Atravessa bloqueios e inspeções com enorme facilidade.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 35, name: "Nave de Operação", description: "Transforma veículo ou nave em máquina ideal para fuga e transporte clandestino.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 30, name: "Mestre do Submundo", description: "Domina esconderijos, rotas e contatos em grande escala.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 40, name: "Rota Impossível", description: "Abre um caminho secreto quase inacreditável entre mundos ou setores.", combat: true, peCost: 8, damageDice: "18d6" },
    ],
  },
  {
    classId: "diplomata",
    abilities: [
      { level: 1, name: "Voz Controlada", combat: false, description: "Melhora presença, clareza e firmeza ao falar.", peCost: 1, dt: 15 },
      { level: 1, name: "Leitura Social", combat: false, description: "Identifica tensão, intenção e risco imediato em conversas.", peCost: 1, dt: 15 },
      { level: 2, name: "Abertura de Diálogo", combat: false, description: "Reduz hostilidade inicial e facilita o início de negociações.", peCost: 1, dt: 15 },
      { level: 3, name: "Tom Adequado", combat: true, description: "Adapta a abordagem ao tipo de cultura, autoridade ou facção — inclui coagir/desestabilizar um oponente na conversa.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Mediação Simples", combat: false, description: "Impede uma discussão de virar combate.", peCost: 2, dt: 17 },
      { level: 5, name: "Juramento Formal", combat: false, description: "Sela pactos com maior dificuldade de quebra.", peCost: 2, dt: 17 },
      { level: 6, name: "Status e Etiqueta", combat: false, description: "Domina protocolos, títulos e rituais sociais.", peCost: 2, dt: 17 },
      { level: 8, name: "Persuasão Direta", combat: true, description: "Faz o alvo ouvir, ceder, esperar, recuar ou hesitar em pleno confronto.", peCost: 2, damageDice: "2d6" },
      { level: 9, name: "Pressão Política", combat: true, description: "Usa reputação, leis e alianças para ganhar vantagem — inclusive isolar um alvo antes do combate.", peCost: 2, damageDice: "3d6" },
      { level: 10, name: "Defesa Verbal", combat: false, description: "Resiste a blefes, ameaças e manipulação.", peCost: 2, dt: 19 },
      { level: 11, name: "Ponte Cultural", combat: false, description: "Reduz conflitos entre povos com costumes diferentes.", peCost: 2, dt: 19 },
      { level: 12, name: "Proposta Irrecusável", combat: false, description: "Cria ofertas extremamente vantajosas para aliados ou autoridades.", peCost: 2, dt: 19 },
      { level: 13, name: "Acordo Estratégico", combat: false, description: "Transforma negociação em vantagem concreta de missão.", peCost: 3, dt: 21 },
      { level: 14, name: "Desescalada", combat: true, description: "Faz uma situação hostil perder força antes do combate, retirando inimigos do confronto.", peCost: 3, damageDice: "4d6" },
      { level: 15, name: "Testemunho de Peso", combat: false, description: "Sua palavra passa a pesar muito em decisões.", peCost: 3, dt: 21 },
      { level: 16, name: "Fronteira Segura", combat: false, description: "Garante passagem, abrigo ou tolerância em território hostil.", peCost: 3, dt: 21 },
      { level: 17, name: "Mesa de Guerra", combat: false, description: "Influencia líderes, capitães e conselhos inteiros.", peCost: 3, dt: 23 },
      { level: 18, name: "Pacto de Longa Duração", combat: false, description: "Cria alianças difíceis de romper e muito valiosas.", peCost: 3, dt: 23 },
      { level: 19, name: "Voz de Autoridade", combat: true, description: "Sua presença muda o peso de decisões sociais e políticas — pode forçar a rendição de um oponente.", peCost: 3, damageDice: "5d6" },
      { level: 20, name: "Harmonia de Facções", combat: false, description: "Une lados opostos em torno de um objetivo comum.", peCost: 3, dt: 23 },
    ],
    milestones: [
      { level: 25, name: "Tratado Menor", description: "Formaliza um acordo duradouro com forte valor estratégico.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 35, name: "Embaixador de Campo", description: "Representa seu grupo com legitimidade em qualquer mundo ou facção.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 30, name: "Arquitetura da Paz", description: "Costura alianças amplas e evita guerras grandes.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 40, name: "Voz da Galáxia", description: "Sua diplomacia pode alterar o destino de uma guerra ou civilização.", combat: true, peCost: 8, damageDice: "18d6" },
    ],
  },
  {
    classId: "engenheiro",
    abilities: [
      { level: 1, name: "Carga Improvisada", combat: true, description: "Monta uma pequena carga explosiva ou elétrica com peças do ambiente; dano leve em área curta.", peCost: 1, damageDice: "1d6" },
      { level: 1, name: "Olho Técnico", combat: false, description: "Identifica falhas, pontos fracos e valor de qualquer máquina, droide ou veículo.", peCost: 1, dt: 15 },
      { level: 2, name: "Reparo de Campo", combat: false, description: "Conserta rapidamente equipamento danificado, restaurando função parcial.", peCost: 1, dt: 15 },
      { level: 3, name: "Choque Dirigido", combat: true, description: "Descarrega energia de uma ferramenta ou bateria contra um alvo próximo.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Modificação Rápida", combat: false, description: "Adapta uma arma ou equipamento pra ganhar um efeito extra temporário.", peCost: 2, dt: 17 },
      { level: 5, name: "Torreta Portátil", combat: true, description: "Monta uma pequena torreta ou droide de defesa que atira automaticamente por um tempo.", peCost: 2, damageDice: "2d6" },
      { level: 6, name: "Blindagem Reforçada", combat: false, description: "Reforça armadura própria ou de aliado, reduzindo dano recebido.", peCost: 2, dt: 17 },
      { level: 8, name: "Sobrecarga", combat: true, description: "Força um sistema, arma ou droide inimigo a sobrecarregar, causando dano e falha temporária.", peCost: 2, damageDice: "2d6" },
      { level: 9, name: "Droide de Combate", combat: true, description: "Ativa um droide de ataque previamente preparado para lutar ao seu lado.", peCost: 2, damageDice: "3d6" },
      { level: 10, name: "Hackeamento Tático", combat: false, description: "Assume controle temporário de um sistema, droide ou torre inimiga.", peCost: 2, dt: 19 },
      { level: 11, name: "Explosivo Direcionado", combat: true, description: "Planta uma carga com detonação controlada, causando dano maior e mais preciso.", peCost: 2, damageDice: "3d6" },
      { level: 12, name: "Manutenção de Combate", combat: false, description: "Repara e reenergiza equipamento aliado em pleno confronto.", peCost: 2, dt: 19 },
      { level: 13, name: "Arsenal Modular", combat: true, description: "Equipa arma própria com módulos intercambiáveis no meio do combate.", peCost: 3, damageDice: "4d6" },
      { level: 14, name: "Enxame de Drones", combat: true, description: "Libera pequenos drones que atacam, distraem ou marcam alvos.", peCost: 3, damageDice: "4d6" },
      { level: 15, name: "Escudo de Emergência", combat: false, description: "Cria um campo de proteção temporário para si ou para o grupo.", peCost: 3, dt: 21 },
      { level: 16, name: "Sabotagem Letal", combat: true, description: "Reprograma uma arma, veículo ou droide inimigo pra virar-se contra seus próprios aliados.", peCost: 3, damageDice: "4d6" },
      { level: 17, name: "Fabricação de Guerra", combat: false, description: "Monta um equipamento ofensivo especializado sob medida pra missão atual.", peCost: 3, dt: 23 },
      { level: 18, name: "Rede de Combate", combat: true, description: "Sincroniza droides, torretas e drones próprios pra atacar em conjunto.", peCost: 3, damageDice: "5d6" },
      { level: 19, name: "Núcleo Instável", combat: true, description: "Transforma qualquer máquina ou veículo próximo numa bomba de tempo controlada.", peCost: 3, damageDice: "5d6" },
      { level: 20, name: "Máquina de Guerra", combat: true, description: "Monta ou ativa uma unidade de combate pesada pra lutar ao seu lado por tempo prolongado.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Oficina de Combate", description: "Cria e mantém múltiplas unidades ofensivas simultâneas, sustentando a guerra tecnológica.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 35, name: "Protótipo Devastador", description: "Ativa uma arma ou veículo experimental de altíssimo poder de fogo.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 30, name: "Mente Mecânica", description: "Controla, repara e comanda qualquer tecnologia em campo quase instantaneamente.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 40, name: "Singularidade Tecnológica", description: "Ativa uma criação lendária — arma, droide ou nave — capaz de decidir uma batalha inteira sozinha.", combat: true, peCost: 8, damageDice: "18d6" },
    ],
  },
  {
    classId: "espiao",
    abilities: [
      { level: 1, name: "Lâmina Silenciosa", combat: true, description: "Dano bônus contra alvo desprevenido.", peCost: 1, damageDice: "1d6" },
      { level: 1, name: "Passo Invisível", combat: false, description: "Reduz detecção.", peCost: 1, dt: 15 },
      { level: 2, name: "Disfarce Rápido", combat: false, description: "Muda aparência/identidade por tempo curto.", peCost: 1, dt: 15 },
      { level: 3, name: "Golpe Certeiro", combat: true, description: "Ataque preciso em ponto vital, dano aumentado.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Acesso Forjado", combat: false, description: "Falsifica credenciais/portas.", peCost: 2, dt: 17 },
      { level: 5, name: "Toxina de Contato", combat: true, description: "Veneno de ação lenta aplicado em arma corpo a corpo.", peCost: 2, damageDice: "2d6" },
      { level: 6, name: "Escuta Discreta", combat: false, description: "Capta informação de longe.", peCost: 2, dt: 17 },
      { level: 8, name: "Corte de Vigilância", combat: true, description: "Neutraliza sentinela/câmera com ataque silencioso.", peCost: 2, damageDice: "2d6" },
      { level: 9, name: "Sombra Dupla", combat: false, description: "Cria distração/falsa presença.", peCost: 2, dt: 19 },
      { level: 10, name: "Lâmina Envenenada", combat: true, description: "Aumenta efeito e dano de venenos aplicados.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Infiltração Profunda", combat: false, description: "Entra em áreas de alta segurança sem ser notado.", peCost: 2, dt: 19 },
      { level: 12, name: "Execução Rápida", combat: true, description: "Ataque combinado que ignora parte da defesa do alvo.", peCost: 2, damageDice: "3d6" },
      { level: 13, name: "Rede de Sombras", combat: true, description: "Coordena ataques furtivos simultâneos com aliados.", peCost: 3, damageDice: "4d6" },
      { level: 14, name: "Disfarce Perfeito", combat: false, description: "Se passa por qualquer figura conhecida.", peCost: 3, dt: 21 },
      { level: 15, name: "Golpe Paralisante", combat: true, description: "Imobiliza o alvo por um tempo curto.", peCost: 3, damageDice: "4d6" },
      { level: 16, name: "Fuga Fantasma", combat: false, description: "Desaparece completamente após um ataque.", peCost: 3, dt: 21 },
      { level: 17, name: "Mestre do Disfarce", combat: false, description: "Infiltra-se em qualquer organização.", peCost: 3, dt: 23 },
      { level: 18, name: "Assassinato Perfeito", combat: true, description: "Ataque de altíssimo dano contra alvo isolado.", peCost: 3, damageDice: "5d6" },
      { level: 19, name: "Rede de Contatos Sombrios", combat: false, description: "Obtém qualquer informação através do submundo.", peCost: 3, dt: 23 },
      { level: 20, name: "Sombra Letal", combat: true, description: "Combina furtividade e dano extremo num único golpe decisivo.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Fantasma Operacional", description: "Infiltra e ataca sem deixar rastro algum.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 35, name: "Lâmina das Mil Faces", description: "Assume qualquer identidade e ataca com letalidade extrema.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 30, name: "Mestre Assassino", description: "Um único golpe pode eliminar quase qualquer alvo.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 40, name: "A Sombra Perfeita", description: "Executa uma operação letal que muda o destino de uma facção inteira.", combat: true, peCost: 8, damageDice: "18d6" },
    ],
  },
];
