// Star Wars: Além da Fronteira — habilidades de classe, Grupo B
// Explorador, Mandaloriano, Médico, Piloto, Pirata Espacial, Soldado da República
//
// Sistema de Pools: `level` guarda o tier em que o pool abre (1/6/11/16), não um nível linear.
// Pools nunca fecham — ver POOL_CLASS_IDS/getRemainingPoolAbilities em lib/starwars/leveling.ts.

import type { ClassAbilityTable } from "./types";

export const CLASS_GROUP_B: ClassAbilityTable[] = [
  {
    classId: "explorador",
    abilities: [
      { level: 1, name: "Golpe de Trilha", combat: true, description: "Usa bordão, faca ou ferramenta de exploração como arma.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Instinto Selvagem", combat: false, description: "Percebe perigos e caminhos ocultos antes de qualquer outro.", peCost: 1, dt: 15, skillId: "percepcao" },
      { level: 1, name: "Passo Firme", combat: false, description: "Movimento superior em terrenos difíceis, sem perder ritmo.", peCost: 1, dt: 15, skillId: "atletismo" },
      { level: 1, name: "Armadilha Simples", combat: true, description: "Monta uma armadilha rústica que fere o inimigo.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Leitura de Fauna", combat: false, description: "Prevê o comportamento de criaturas antes que ajam.", peCost: 1, dt: 15, skillId: "sobrevivencia" },
      { level: 1, name: "Investida Selvagem", combat: true, description: "Ataque com impulso após uma corrida ou salto.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Abrigo Improvisado", combat: false, description: "Cria proteção temporária em qualquer ambiente.", peCost: 1, dt: 15, skillId: "sobrevivencia" },
      { level: 1, name: "Rota de Fuga", combat: false, description: "Conhece sempre uma saída, em qualquer terreno.", peCost: 1, dt: 15, skillId: "sobrevivencia" },
      { level: 1, name: "Resistência Extrema", combat: false, description: "Ignora fadiga, clima e fome por um período prolongado.", peCost: 1, dt: 15, skillId: "vontade" },
      { level: 1, name: "Faro de Perigo", combat: false, description: "Detecta emboscadas antes que aconteçam.", peCost: 1, dt: 15, skillId: "percepcao" },
      { level: 6, name: "Chamado da Natureza", combat: true, description: "Atrai uma criatura local para atacar o inimigo.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Cilada Natural", combat: true, description: "Usa o ambiente (queda, água, fauna) para ferir o inimigo.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Domínio do Terreno", combat: false, description: "Transforma qualquer ambiente em vantagem tática.", peCost: 2, dt: 17, skillId: "sobrevivencia" },
      { level: 6, name: "Rastro Impossível", combat: false, description: "Segue qualquer alvo por qualquer terreno, sem perder a pista.", peCost: 2, dt: 17, skillId: "investigacao" },
      { level: 6, name: "Golpe de Precisão Selvagem", combat: true, description: "Ataque que explora o ponto fraco de criaturas ou do próprio terreno.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Investida Predatória", combat: true, description: "Ataque forte após uma emboscada ou surpresa.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Aliado Selvagem", combat: true, description: "Convoca apoio temporário de uma criatura local.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Fúria da Trilha", combat: true, description: "Sequência de golpes rápidos após se mover em combate.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Camuflagem Total", combat: false, description: "Torna-se indetectável fundindo-se ao ambiente natural.", peCost: 2, dt: 20, skillId: "furtividade" },
      { level: 11, name: "Adaptação Extrema", combat: false, description: "Se ajusta instantaneamente a qualquer clima ou ambiente hostil, sem penalidade.", peCost: 2, dt: 20, skillId: "vontade" },
      { level: 16, name: "Golpe da Terra Selvagem", combat: true, description: "Dano aumentado ao lutar em ambiente natural hostil.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Fera Desperta", combat: false, description: "Luta com força e ferocidade sobre-humanas por um tempo curto.", peCost: 3, dt: 20, skillId: "atletismo" },
      { level: 16, name: "Manada", combat: true, description: "Convoca múltiplas criaturas para lutarem ao seu lado.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Trilha Ancestral", combat: false, description: "Encontra um atalho ou passagem que ninguém mais consegue achar.", peCost: 3, dt: 20, skillId: "sobrevivencia" },
      { level: 16, name: "Sentinela da Natureza", combat: false, description: "O ambiente ao redor avisa de qualquer ameaça se aproximando, a grande distância.", peCost: 3, dt: 20, skillId: "percepcao" },
    ],
    milestones: [
      { level: 25, name: "Senhor da Trilha", description: "Domina completamente qualquer ambiente natural em combate.", combat: false, peCost: 4, dt: 23, skillId: "sobrevivencia" },
      { level: 30, name: "Guardião Selvagem", description: "Comanda o ambiente e criaturas ao seu favor em larga escala.", combat: true, peCost: 5, damageDice: "8d6" },
      { level: 35, name: "Vontade da Terra", description: "O corpo se torna parte do ambiente: resistência quase absoluta a fadiga, veneno natural e dano físico por tempo prolongado.", combat: false, peCost: 6, dt: 23, skillId: "vontade" },
      { level: 40, name: "Ira da Fronteira Selvagem", description: "Desencadeia a força total da natureza contra os inimigos.", combat: true, peCost: 7, damageDice: "10d6" },
    ],
  },
  {
    classId: "mandaloriano",
    abilities: [
      { level: 1, name: "Golpe de Beskar", combat: true, description: "Ataque corpo a corpo com arma tradicional mandaloriana.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Instinto de Guerra", combat: false, description: "Percebe ameaças e avalia inimigos rapidamente.", peCost: 1, dt: 15, skillId: "percepcao" },
      { level: 1, name: "Armadura Ajustada", combat: false, description: "Melhora a proteção conforme a missão exige.", peCost: 1, dt: 15, skillId: "mecanica" },
      { level: 1, name: "Disparo de Pulso", combat: true, description: "Tiro de arma de punho embutida na armadura.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Jetpack Tático", combat: false, description: "Melhora mobilidade vertical e reposicionamento em combate.", peCost: 1, dt: 15, skillId: "acrobacia" },
      { level: 1, name: "Rajada de Flanco", combat: true, description: "Ataque rápido logo após um reposicionamento aéreo.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Honra do Clã", combat: false, description: "Ganha vantagem social e moral entre guerreiros e clãs.", peCost: 1, dt: 15, skillId: "diplomacia" },
      { level: 1, name: "Lança-Chamas de Pulso", combat: true, description: "Ataque em área curta com fogo ou energia.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Armadura Reforçada", combat: false, description: "Resistência elevada a dano físico e energético.", peCost: 1, dt: 15, skillId: "atletismo" },
      { level: 1, name: "Rastreador de Caça", combat: false, description: "Localiza e persegue um alvo marcado sem falhar.", peCost: 1, dt: 15, skillId: "investigacao" },
      { level: 6, name: "Combo de Combate", combat: true, description: "Sequência de golpes corpo a corpo e à distância.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Escudo de Punho", combat: true, description: "Bloqueia e revida um ataque com força extra.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Cabo de Gancho", combat: false, description: "Prende ou puxa o inimigo, ou se desloca rapidamente pelo ambiente.", peCost: 2, dt: 17, skillId: "atletismo" },
      { level: 6, name: "Munição Especializada", combat: true, description: "Troca o tipo de munição para um efeito situacional (perfurante, incendiária, atordoante).", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Sinal de Clã", combat: false, description: "Chama o reforço de outro guerreiro mandaloriano aliado.", peCost: 2, dt: 17, skillId: "diplomacia" },
      { level: 11, name: "Arsenal Completo", combat: false, description: "Alterna entre armas de combate sem perder ritmo.", peCost: 2, dt: 20, skillId: "mecanica" },
      { level: 11, name: "Fúria Mandaloriana", combat: true, description: "Sequência de ataques com dano crescente.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Blindagem de Batalha", combat: false, description: "Reduz drasticamente o dano crítico recebido.", peCost: 2, dt: 20, skillId: "atletismo" },
      { level: 11, name: "Investida Aérea", combat: true, description: "Ataque de cima usando o jetpack, dano em área de impacto.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Contramedida Ativa", combat: false, description: "Dispara chamariz, fumaça ou pulso eletromagnético que anula um ataque à distância ou uma perseguição.", peCost: 2, dt: 20, skillId: "mecanica" },
      { level: 16, name: "Código de Mandalore", combat: false, description: "Ganha respeito e autoridade entre guerreiros e facções.", peCost: 3, dt: 20, skillId: "diplomacia" },
      { level: 16, name: "Golpe do Guerreiro", combat: true, description: "Ataque de altíssima precisão e dano.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Armadura Lendária", combat: false, description: "Proteção quase impenetrável por tempo limitado.", peCost: 3, dt: 20, skillId: "atletismo" },
      { level: 16, name: "Artilharia Pessoal", combat: true, description: "Dispara o arsenal pesado embutido na armadura (mísseis, canhão) contra um alvo único ou uma área.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Caçador Sem Descanso", combat: false, description: "Ignora qualquer obstáculo, cansaço ou distração ao perseguir um alvo marcado.", peCost: 3, dt: 20, skillId: "investigacao" },
    ],
    milestones: [
      { level: 25, name: "Caçador Implacável", description: "Torna-se imparável ao perseguir um alvo marcado.", combat: false, peCost: 4, dt: 23, skillId: "investigacao" },
      { level: 30, name: "Lenda de Mandalore", description: "Combate com poder quase mítico, quase impossível de deter.", combat: true, peCost: 5, damageDice: "8d6" },
      { level: 35, name: "Fúria de Beskar", description: "Ataques consecutivos de altíssimo dano sem pausa.", combat: true, peCost: 6, damageDice: "9d6" },
      { level: 40, name: "O Último Guerreiro", description: "Desencadeia todo o arsenal e força em um ataque final devastador.", combat: true, peCost: 7, damageDice: "10d6" },
    ],
  },
  {
    classId: "medico",
    abilities: [
      { level: 1, name: "Golpe Cirúrgico", combat: true, description: "Ataque preciso em ponto vital usando ferramenta médica.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Diagnóstico Rápido", combat: false, description: "Identifica condição, ferimento e fraqueza física de alvo ou aliado.", peCost: 1, dt: 15, skillId: "medicina" },
      { level: 1, name: "Primeiros Socorros", combat: true, description: "Cura ferimentos leves rapidamente.", peCost: 1, damageDice: "2d6", heal: true },
      { level: 1, name: "Anestesia de Combate", combat: false, description: "Reduz drasticamente a reação e a dor do alvo, atordoando-o.", peCost: 1, dt: 15, skillId: "medicina" },
      { level: 1, name: "Estabilização de Campo", combat: true, description: "Recupera um aliado caído em combate.", peCost: 1, damageDice: "2d6", heal: true },
      { level: 1, name: "Pulso Vital", combat: true, description: "Transfere parte da própria energia vital para estabilizar um aliado crítico.", peCost: 1, damageDice: "2d6", heal: true },
      { level: 1, name: "Kit Avançado", combat: false, description: "Melhora a eficiência de cura e tratamento.", peCost: 1, dt: 15, skillId: "medicina" },
      { level: 1, name: "Antídoto Universal", combat: false, description: "Neutraliza venenos e toxinas em si ou em aliados.", peCost: 1, dt: 15, skillId: "medicina" },
      { level: 1, name: "Leitura Anatômica", combat: false, description: "Identifica o ponto fraco exato de qualquer ser vivo.", peCost: 1, dt: 15, skillId: "medicina" },
      { level: 1, name: "Reflexo Clínico", combat: true, description: "Reage instantaneamente a um ferimento próprio ou de aliado próximo, aplicando tratamento de emergência sem custar ação depois.", peCost: 1, damageDice: "2d6", heal: true },
      { level: 6, name: "Cura Sob Pressão", combat: true, description: "Trata múltiplos aliados rapidamente em combate.", peCost: 2, damageDice: "3d6", heal: true },
      { level: 6, name: "Golpe Paralisante", combat: true, description: "Ataque que afeta os nervos e o movimento do alvo.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Sedativo de Impacto", combat: false, description: "Reduz drasticamente a capacidade de ação do inimigo.", peCost: 2, dt: 17, skillId: "medicina" },
      { level: 6, name: "Reanimação de Emergência", combat: true, description: "Traz de volta um aliado à beira da morte, uma vez por combate.", peCost: 2, damageDice: "3d6", heal: true },
      { level: 6, name: "Triagem Tática", combat: false, description: "Decide instantaneamente quem tratar primeiro, otimizando toda a cura do grupo naquele momento.", peCost: 2, dt: 17, skillId: "medicina" },
      { level: 11, name: "Cirurgia de Guerra", combat: true, description: "Revive ou estabiliza um aliado gravemente ferido em pleno combate.", peCost: 2, damageDice: "4d6", heal: true },
      { level: 11, name: "Golpe Anatômico", combat: true, description: "Ataque de altíssima precisão contra ponto vital, ignorando parte da resistência do alvo.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Imunização de Grupo", combat: false, description: "Protege os aliados contra efeitos negativos temporariamente.", peCost: 2, dt: 20, skillId: "medicina" },
      { level: 11, name: "Prognóstico de Batalha", combat: false, description: "Prevê o desfecho de um ferimento e ajusta a própria ação para evitar o pior resultado.", peCost: 2, dt: 20, skillId: "medicina" },
      { level: 11, name: "Contenção de Hemorragia", combat: true, description: "Interrompe qualquer sangramento ou dano contínuo instantaneamente, em si ou em aliado.", peCost: 2, damageDice: "4d6", heal: true },
      { level: 16, name: "Overdose Controlada", combat: true, description: "Injeta uma substância que causa dano severo e progressivo.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Mestre da Cura", combat: true, description: "Restaura completamente a condição de um aliado.", peCost: 3, damageDice: "5d6", heal: true },
      { level: 16, name: "Equipe Estabilizada", combat: true, description: "Todo o grupo recebe suporte médico contínuo.", peCost: 3, damageDice: "5d6", heal: true },
      { level: 16, name: "Segunda Vida", combat: true, description: "Revive um aliado caído recentemente, trazendo-o de volta ao combate.", peCost: 3, damageDice: "5d6", heal: true },
      { level: 16, name: "Corte Sem Retorno", combat: true, description: "Um único golpe cirúrgico que garante dano crítico certeiro contra qualquer alvo vivo.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Anjo de Batalha", description: "Cura e sustenta o grupo inteiro em combates prolongados.", combat: true, peCost: 4, damageDice: "7d6", heal: true },
      { level: 30, name: "Mestre da Vida e da Morte", description: "Decide entre curar totalmente ou eliminar com precisão.", combat: true, peCost: 5, damageDice: "8d6", healOrDamage: true },
      { level: 35, name: "Bisturi da Morte", description: "Ataques cirúrgicos que ignoram quase toda a defesa do alvo.", combat: true, peCost: 6, damageDice: "9d6" },
      { level: 40, name: "Julgamento Clínico", description: "Um único procedimento que cura o grupo por completo ou elimina um alvo instantaneamente.", combat: true, peCost: 7, damageDice: "10d6", healOrDamage: true },
    ],
  },
  {
    classId: "piloto",
    abilities: [
      { level: 1, name: "Rasante de Combate", combat: true, description: "Manobra que atinge inimigos no chão ou próximos durante um voo baixo.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Olho de Piloto", combat: false, description: "Avalia rapidamente veículos, rotas e riscos.", peCost: 1, dt: 15, skillId: "percepcao" },
      { level: 1, name: "Manobra Evasiva", combat: false, description: "Reduz a chance de ser atingido em perseguições.", peCost: 1, dt: 15, skillId: "pilotagem_espacial" },
      { level: 1, name: "Tiro de Cockpit", combat: true, description: "Disparo rápido usando o armamento do próprio veículo.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Pilotagem Extrema", combat: false, description: "Realiza manobras impossíveis para pilotos comuns.", peCost: 1, dt: 15, skillId: "pilotagem_espacial" },
      { level: 1, name: "Investida Aérea", combat: true, description: "Colisão controlada ou rasante ofensivo contra um alvo.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Leitura de Rota", combat: false, description: "Encontra o melhor caminho em perseguições e fugas.", peCost: 1, dt: 15, skillId: "pilotagem_espacial" },
      { level: 1, name: "Disparo em Movimento", combat: true, description: "Ataque preciso mesmo em alta velocidade.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Domínio de Manobra", combat: false, description: "Controla o veículo com perfeição mesmo sob dano.", peCost: 1, dt: 15, skillId: "pilotagem_espacial" },
      { level: 1, name: "Rajada de Perseguição", combat: true, description: "Sequência de disparos contra um alvo em fuga ou perseguição.", peCost: 1, damageDice: "2d6" },
      { level: 6, name: "Piloto Fantasma", combat: false, description: "Desaparece de sensores por um curto período.", peCost: 2, dt: 17, skillId: "furtividade" },
      { level: 6, name: "Ataque em Rasante", combat: true, description: "Passa raspando sobre o alvo, causando dano direto.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Sincronia de Combate", combat: false, description: "Coordena um ataque aéreo com aliados em terra.", peCost: 2, dt: 17, skillId: "pilotagem_espacial" },
      { level: 6, name: "Reparo em Voo", combat: false, description: "Conserta danos do próprio veículo em pleno combate, sem precisar pousar.", peCost: 2, dt: 17, skillId: "mecanica" },
      { level: 6, name: "Leitura de Tráfego", combat: false, description: "Antecipa o movimento de múltiplos veículos numa área congestionada ou em batalha, ganhando vantagem posicional.", peCost: 2, dt: 17, skillId: "percepcao" },
      { level: 11, name: "Manobra Suicida", combat: true, description: "Ataque de altíssimo risco e dano contra um alvo grande.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Blindagem de Voo", combat: false, description: "Reduz o dano crítico ao veículo próprio.", peCost: 2, dt: 20, skillId: "mecanica" },
      { level: 11, name: "Interceptação Perfeita", combat: true, description: "Corta a rota de fuga do inimigo com dano garantido.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Ejeção Tática", combat: true, description: "Se ejeta do veículo em chamas no último instante sem sofrer dano da explosão, ainda atacando na queda.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Escolta Implacável", combat: false, description: "Protege um aliado específico (veículo ou pessoa) de qualquer ataque à distância por um tempo.", peCost: 2, dt: 20, skillId: "pilotagem_espacial" },
      { level: 16, name: "Mestre dos Céus", combat: false, description: "Controla qualquer veículo com perfeição absoluta.", peCost: 3, dt: 20, skillId: "pilotagem_espacial" },
      { level: 16, name: "Ataque Decisivo", combat: true, description: "Manobra ofensiva de altíssimo impacto contra um alvo prioritário.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Esquadrão Fantasma", combat: false, description: "Coordena múltiplos veículos aliados numa manobra só.", peCost: 3, dt: 20, skillId: "pilotagem_espacial" },
      { level: 16, name: "Rota Impossível", combat: false, description: "Atravessa qualquer obstáculo, bloqueio ou formação inimiga sem perder velocidade.", peCost: 3, dt: 20, skillId: "pilotagem_espacial" },
      { level: 16, name: "Disparo Calculado", combat: true, description: "Um único tiro certeiro que atinge o ponto exato de falha de qualquer veículo ou estrutura, à distância extrema.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Ás Lendário", description: "Torna-se praticamente intocável em combate aéreo ou espacial.", combat: false, peCost: 4, dt: 23, skillId: "pilotagem_espacial" },
      { level: 30, name: "Senhor dos Céus", description: "Domina completamente qualquer combate aéreo ou espacial.", combat: true, peCost: 5, damageDice: "8d6" },
      { level: 35, name: "Manobra Impossível", description: "Executa um ataque que nenhum outro piloto conseguiria replicar.", combat: true, peCost: 6, damageDice: "9d6" },
      { level: 40, name: "Voo Final", description: "Executa a manobra ofensiva mais arriscada e poderosa já registrada.", combat: true, peCost: 7, damageDice: "10d6" },
    ],
  },
  {
    classId: "pirata_espacial",
    abilities: [
      { level: 1, name: "Golpe de Saque", combat: true, description: "Ataque agressivo com arma improvisada ou branca.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Olho de Presa", combat: false, description: "Identifica alvos vulneráveis e valiosos rapidamente.", peCost: 1, dt: 15, skillId: "percepcao" },
      { level: 1, name: "Abordagem Rápida", combat: false, description: "Invade veículos e naves com eficiência.", peCost: 1, dt: 15, skillId: "atletismo" },
      { level: 1, name: "Tiro Sujo", combat: true, description: "Disparo sem regras, ignora qualquer convenção de combate justo.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Saque Relâmpago", combat: false, description: "Rouba recursos ou itens durante o próprio combate.", peCost: 1, dt: 15, skillId: "furtividade" },
      { level: 1, name: "Fúria de Bordo", combat: true, description: "Sequência de ataques ao invadir um veículo ou nave.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Rede de Piratas", combat: false, description: "Contata outros fora da lei para apoio ou informação.", peCost: 1, dt: 15, skillId: "enganacao" },
      { level: 1, name: "Emboscada Selvagem", combat: true, description: "Ataque surpresa com dano aumentado.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Terror da Rota", combat: false, description: "Intimida tripulações inteiras a se renderem sem luta.", peCost: 1, dt: 15, skillId: "intimidacao" },
      { level: 1, name: "Corte Cruel", combat: true, description: "Ataque que ignora parte da armadura do alvo.", peCost: 1, damageDice: "2d6" },
      { level: 6, name: "Fuga com Butim", combat: false, description: "Escapa com recursos roubados mesmo sob perseguição.", peCost: 2, dt: 17, skillId: "pilotagem_espacial" },
      { level: 6, name: "Caos Controlado", combat: true, description: "Ataque em área que desorganiza o grupo inimigo.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Sequestro Relâmpago", combat: true, description: "Captura um alvo vivo em pleno combate para resgate ou troca.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Marca de Pirata", combat: false, description: "Intimida um alvo específico de forma duradoura — ele hesita toda vez que o reconhece de novo.", peCost: 2, dt: 17, skillId: "intimidacao" },
      { level: 6, name: "Leitura de Presa", combat: false, description: "Avalia rapidamente riqueza, defesa e fraqueza de uma nave ou instalação antes de atacar.", peCost: 2, dt: 17, skillId: "investigacao" },
      { level: 11, name: "Bando de Saqueadores", combat: true, description: "Coordena um ataque com outros piratas ou aliados.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Fúria Sem Lei", combat: true, description: "Sequência de golpes brutais sem qualquer limite tático.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Blindagem de Saque", combat: false, description: "Proteção improvisada montada com itens roubados.", peCost: 2, dt: 20, skillId: "atletismo" },
      { level: 11, name: "Abordagem Brutal", combat: true, description: "Ataque de alto dano ao invadir um veículo ou base inimiga.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Resgate Forçado", combat: true, description: "Arranca um aliado capturado das mãos do inimigo em pleno combate.", peCost: 2, damageDice: "4d6" },
      { level: 16, name: "Rei dos Piratas", combat: false, description: "Comanda respeito e medo em qualquer rota conhecida.", peCost: 3, dt: 20, skillId: "intimidacao" },
      { level: 16, name: "Golpe Sem Piedade", combat: true, description: "Ataque de dano máximo contra alvo indefeso ou rendido.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Frota Pirata", combat: false, description: "Convoca apoio de outros piratas em grande escala.", peCost: 3, dt: 20, skillId: "diplomacia" },
      { level: 16, name: "Tempestade de Saque", combat: true, description: "Ataque devastador que combina caos, brutalidade e número.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Última Lei", combat: false, description: "Impõe suas próprias regras num território — ninguém ali ousa desobedecer sem consequência.", peCost: 3, dt: 20, skillId: "intimidacao" },
    ],
    milestones: [
      { level: 25, name: "Terror das Rotas", description: "Inimigos hesitam ou fogem só de reconhecê-lo.", combat: false, peCost: 4, dt: 23, skillId: "intimidacao" },
      { level: 30, name: "Lenda Pirata", description: "Comanda batalhas inteiras com brutalidade e carisma extremos.", combat: true, peCost: 5, damageDice: "8d6" },
      { level: 35, name: "Fúria Sem Lei Total", description: "Ataques consecutivos de altíssimo dano sem qualquer limite.", combat: true, peCost: 6, damageDice: "9d6" },
      { level: 40, name: "Saque Final", description: "Executa o assalto mais violento e lucrativo de sua vida, devastador em combate.", combat: true, peCost: 7, damageDice: "10d6" },
    ],
  },
  {
    classId: "soldado_republica",
    abilities: [
      { level: 1, name: "Disparo Regulamentar", combat: true, description: "Ataque padrão com arma de fogo militar.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Disciplina de Combate", combat: false, description: "Mantém foco e desempenho mesmo sob pressão.", peCost: 1, dt: 15, skillId: "vontade" },
      { level: 1, name: "Cobertura Tática", combat: false, description: "Melhora a defesa própria e a de aliados próximos.", peCost: 1, dt: 15, skillId: "lideranca" },
      { level: 1, name: "Rajada Curta", combat: true, description: "Sequência curta de disparos contra um alvo.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Formação de Combate", combat: false, description: "Coordena posicionamento com aliados para vantagem tática.", peCost: 1, dt: 15, skillId: "lideranca" },
      { level: 1, name: "Tiro de Supressão", combat: true, description: "Disparos que dificultam o avanço e a mira do inimigo.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Comunicação Tática", combat: false, description: "Troca informação de combate rapidamente com o esquadrão.", peCost: 1, dt: 15, skillId: "lideranca" },
      { level: 1, name: "Investida Coordenada", combat: true, description: "Ataque combinado com pelo menos um aliado.", peCost: 1, damageDice: "2d6" },
      { level: 1, name: "Linha de Frente", combat: false, description: "Resiste e sustenta posição sob fogo pesado.", peCost: 1, dt: 15, skillId: "vontade" },
      { level: 1, name: "Disparo Perfurante", combat: true, description: "Ataque que ignora parte da blindagem do alvo.", peCost: 1, damageDice: "2d6" },
      { level: 6, name: "Resgate sob Fogo", combat: false, description: "Retira um aliado ferido em pleno combate.", peCost: 2, dt: 17, skillId: "atletismo" },
      { level: 6, name: "Avanço Blindado", combat: true, description: "Ataque com proteção reforçada durante uma investida.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Reposicionamento Tático", combat: false, description: "Move todo o esquadrão para uma posição vantajosa instantaneamente.", peCost: 2, dt: 17, skillId: "lideranca" },
      { level: 6, name: "Fogo de Cobertura Cruzada", combat: true, description: "Dois ou mais aliados disparam em conjunto, cobrindo os pontos cegos um do outro.", peCost: 2, damageDice: "3d6" },
      { level: 6, name: "Leitura de Campo de Batalha", combat: false, description: "Identifica a melhor tática para a situação atual, prevendo o movimento inimigo.", peCost: 2, dt: 17, skillId: "percepcao" },
      { level: 11, name: "Comando de Esquadrão", combat: false, description: "Melhora o desempenho de todos os aliados próximos.", peCost: 2, dt: 20, skillId: "lideranca" },
      { level: 11, name: "Rajada Pesada", combat: true, description: "Sequência de disparos de alto dano contra múltiplos alvos.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Blindagem de Batalha", combat: false, description: "Reduz drasticamente o dano crítico recebido.", peCost: 2, dt: 20, skillId: "atletismo" },
      { level: 11, name: "Ataque Sincronizado", combat: true, description: "Ataque combinado com todo o esquadrão presente.", peCost: 2, damageDice: "4d6" },
      { level: 11, name: "Retomada de Posição", combat: true, description: "Reconquista terreno perdido com uma investida coordenada, restaurando a vantagem tática.", peCost: 2, damageDice: "4d6" },
      { level: 16, name: "Veterano de Guerra", combat: false, description: "Desempenho máximo mesmo em combates prolongados.", peCost: 3, dt: 20, skillId: "vontade" },
      { level: 16, name: "Disparo Decisivo", combat: true, description: "Ataque de altíssima precisão e dano contra alvo prioritário.", peCost: 3, damageDice: "5d6" },
      { level: 16, name: "Comando de Batalha", combat: false, description: "Coordena o esquadrão inteiro com eficiência máxima.", peCost: 3, dt: 20, skillId: "lideranca" },
      { level: 16, name: "Muralha Viva", combat: false, description: "Se posiciona para absorver o pior de um ataque em área, protegendo todo o esquadrão.", peCost: 3, dt: 20, skillId: "atletismo" },
      { level: 16, name: "Ofensiva Total", combat: true, description: "Ataque devastador que combina esquadrão, blindagem e armamento pesado.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Herói de Guerra", description: "Desempenho excepcional inspira e fortalece todo o esquadrão.", combat: false, peCost: 4, dt: 23, skillId: "lideranca" },
      { level: 30, name: "Lenda Militar", description: "Comanda e vence batalhas praticamente sozinho quando necessário.", combat: true, peCost: 5, damageDice: "8d6" },
      { level: 35, name: "Tática Perfeita", description: "Executa uma manobra de combate quase impossível de contra-atacar.", combat: true, peCost: 6, damageDice: "9d6" },
      { level: 40, name: "Última Linha de Defesa", description: "Um ataque final que pode decidir uma guerra inteira.", combat: true, peCost: 7, damageDice: "10d6" },
    ],
  },
];
