// Star Wars: Além da Fronteira — habilidades de classe, Grupo B
// Explorador, Guarda Planetário, Mandaloriano, Médico, Mercenário, Piloto, Pirata Espacial, Soldado da República

import type { ClassAbilityTable } from "./types";

export const CLASS_GROUP_B: ClassAbilityTable[] = [
  {
    classId: "explorador",
    abilities: [
      { level: 1, name: "Golpe de Trilha", combat: true, description: "Usa bordão, faca ou ferramenta de exploração como arma.", peCost: 1, damageDice: "1d6" },
      { level: 1, name: "Instinto Selvagem", combat: false, description: "Percebe perigos e caminhos ocultos.", peCost: 1, dt: 15 },
      { level: 2, name: "Passo Firme", combat: false, description: "Movimento superior em terrenos difíceis.", peCost: 1, dt: 15 },
      { level: 3, name: "Armadilha Simples", combat: true, description: "Monta armadilha rústica que fere o inimigo.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Leitura de Fauna", combat: false, description: "Prevê comportamento de criaturas.", peCost: 2, dt: 17 },
      { level: 5, name: "Investida Selvagem", combat: true, description: "Ataque com impulso após corrida/salto.", peCost: 2, damageDice: "2d6" },
      { level: 6, name: "Abrigo Improvisado", combat: false, description: "Cria proteção temporária em qualquer ambiente.", peCost: 2, dt: 17 },
      { level: 8, name: "Chamado da Natureza", combat: true, description: "Atrai criatura local para atacar o inimigo.", peCost: 2, damageDice: "2d6" },
      { level: 9, name: "Rota de Fuga", combat: false, description: "Conhece sempre uma saída em qualquer terreno.", peCost: 2, dt: 19 },
      { level: 10, name: "Golpe de Precisão Selvagem", combat: true, description: "Ataque que explora ponto fraco de criaturas/terreno.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Resistência Extrema", combat: false, description: "Ignora fadiga, clima e fome por período prolongado.", peCost: 2, dt: 19 },
      { level: 12, name: "Cilada Natural", combat: true, description: "Usa o ambiente (queda, água, fauna) para ferir o inimigo.", peCost: 2, damageDice: "3d6" },
      { level: 13, name: "Faro de Perigo", combat: false, description: "Detecta emboscadas antes que aconteçam.", peCost: 3, dt: 21 },
      { level: 14, name: "Fúria da Trilha", combat: true, description: "Sequência de golpes rápidos após se mover em combate.", peCost: 3, damageDice: "4d6" },
      { level: 15, name: "Domínio do Terreno", combat: false, description: "Transforma qualquer ambiente em vantagem tática.", peCost: 3, dt: 21 },
      { level: 16, name: "Investida Predatória", combat: true, description: "Ataque forte após emboscada ou surpresa.", peCost: 3, damageDice: "4d6" },
      { level: 17, name: "Rastro Impossível", combat: false, description: "Segue qualquer alvo por qualquer terreno.", peCost: 3, dt: 23 },
      { level: 18, name: "Golpe da Terra Selvagem", combat: true, description: "Dano aumentado ao lutar em ambiente natural hostil.", peCost: 3, damageDice: "5d6" },
      { level: 19, name: "Aliado Selvagem", combat: false, description: "Convoca apoio temporário de uma criatura local.", peCost: 3, dt: 23 },
      { level: 20, name: "Fúria da Natureza", combat: true, description: "Ataque devastador combinando terreno, força e velocidade.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Senhor da Trilha", description: "Domina completamente qualquer ambiente natural em combate.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 35, name: "Fera Desperta", description: "Luta com força e ferocidade sobre-humanas por tempo curto.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 50, name: "Guardião Selvagem", description: "Comanda o ambiente e criaturas ao seu favor em larga escala.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 99, name: "Ira da Fronteira Selvagem", description: "Desencadeia a força total da natureza contra os inimigos.", combat: true, peCost: 8, damageDice: "18d6" },
    ],
  },
  {
    classId: "guarda_planetario",
    abilities: [
      { level: 1, name: "Golpe de Contenção", combat: true, description: "Ataque padrão para conter e derrubar.", peCost: 1, damageDice: "1d6" },
      { level: 1, name: "Vigilância Constante", combat: false, description: "Percebe ameaças a civis/área antes que ajam.", peCost: 1, dt: 15 },
      { level: 2, name: "Escudo Padrão", combat: false, description: "Melhora defesa própria e de quem protege.", peCost: 1, dt: 15 },
      { level: 3, name: "Ordem de Parada", combat: true, description: "Ataque de aviso que força recuo do alvo.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Perímetro Seguro", combat: false, description: "Estabelece zona de proteção temporária.", peCost: 2, dt: 17 },
      { level: 5, name: "Golpe de Autoridade", combat: true, description: "Dano aumentado contra quem ameaça civis.", peCost: 2, damageDice: "2d6" },
      { level: 6, name: "Reforço Tático", combat: false, description: "Chama apoio local (patrulha, unidade próxima).", peCost: 2, dt: 17 },
      { level: 8, name: "Bloqueio de Área", combat: true, description: "Impede avanço inimigo com força controlada.", peCost: 2, damageDice: "2d6" },
      { level: 9, name: "Proteção Avançada", combat: false, description: "Reduz dano sofrido por aliados próximos.", peCost: 2, dt: 19 },
      { level: 10, name: "Golpe Decisivo", combat: true, description: "Ataque forte contra alvo prioritário/perigoso.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Comando de Emergência", combat: false, description: "Coordena civis e aliados em situação de crise.", peCost: 2, dt: 19 },
      { level: 12, name: "Contenção Total", combat: true, description: "Imobiliza ou neutraliza um alvo hostil sem matar.", peCost: 2, damageDice: "3d6" },
      { level: 13, name: "Escudo do Distrito", combat: false, description: "Proteção de área ampliada contra ataques.", peCost: 3, dt: 21 },
      { level: 14, name: "Golpe da Lei", combat: true, description: "Ataque que pune diretamente quem infringe a ordem.", peCost: 3, damageDice: "4d6" },
      { level: 15, name: "Resposta Rápida", combat: false, description: "Chega e age antes que o perigo se agrave.", peCost: 3, dt: 21 },
      { level: 16, name: "Supressão Tática", combat: true, description: "Neutraliza múltiplos alvos hostis em sequência.", peCost: 3, damageDice: "4d6" },
      { level: 17, name: "Guardião do Setor", combat: false, description: "Protege uma área inteira com eficiência máxima.", peCost: 3, dt: 23 },
      { level: 18, name: "Golpe Final da Ordem", combat: true, description: "Ataque de altíssimo impacto contra ameaça grave.", peCost: 3, damageDice: "5d6" },
      { level: 19, name: "Autoridade Inquestionável", combat: false, description: "Intimida e controla situações de crise instantaneamente.", peCost: 3, dt: 23 },
      { level: 20, name: "Escudo Absoluto", combat: true, description: "Protege e revida com força total contra qualquer ataque.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Lei Viva", description: "Torna-se a autoridade máxima e ofensiva do setor.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 35, name: "Muralha Inabalável", description: "Suporta e revida ataques em escala massiva.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 50, name: "Braço da Justiça", description: "Elimina ameaças graves com um só golpe decisivo.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 99, name: "A Ordem Absoluta", description: "Impõe paz e proteção total, neutralizando qualquer ameaça ao seu redor.", combat: true, peCost: 8, damageDice: "18d6" },
    ],
  },
  {
    classId: "mandaloriano",
    abilities: [
      { level: 1, name: "Golpe de Beskar", combat: true, description: "Ataque corpo a corpo com arma tradicional mandaloriana.", peCost: 1, damageDice: "1d6" },
      { level: 1, name: "Instinto de Guerra", combat: false, description: "Percebe ameaças e avalia inimigos rapidamente.", peCost: 1, dt: 15 },
      { level: 2, name: "Armadura Ajustada", combat: false, description: "Melhora proteção conforme a missão.", peCost: 1, dt: 15 },
      { level: 3, name: "Disparo de Pulso", combat: true, description: "Tiro de arma de punho embutida na armadura.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Jetpack Tático", combat: false, description: "Melhora mobilidade vertical e reposicionamento.", peCost: 2, dt: 17 },
      { level: 5, name: "Rajada de Flanco", combat: true, description: "Ataque rápido após reposicionamento aéreo.", peCost: 2, damageDice: "2d6" },
      { level: 6, name: "Honra do Clã", combat: false, description: "Ganha vantagem social/moral entre guerreiros e clãs.", peCost: 2, dt: 17 },
      { level: 8, name: "Lança-Chamas de Pulso", combat: true, description: "Ataque em área curta com fogo/energia.", peCost: 2, damageDice: "2d6" },
      { level: 9, name: "Armadura Reforçada", combat: false, description: "Resistência elevada a dano físico e energético.", peCost: 2, dt: 19 },
      { level: 10, name: "Combo de Combate", combat: true, description: "Sequência de golpes corpo a corpo e à distância.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Rastreador de Caça", combat: false, description: "Localiza e persegue alvo marcado sem falhar.", peCost: 2, dt: 19 },
      { level: 12, name: "Escudo de Punho", combat: true, description: "Bloqueia e revida ataque com força extra.", peCost: 2, damageDice: "3d6" },
      { level: 13, name: "Arsenal Completo", combat: false, description: "Alterna entre armas de combate sem perder ritmo.", peCost: 3, dt: 21 },
      { level: 14, name: "Fúria Mandaloriana", combat: true, description: "Sequência de ataques com dano crescente.", peCost: 3, damageDice: "4d6" },
      { level: 15, name: "Blindagem de Batalha", combat: false, description: "Reduz drasticamente dano crítico recebido.", peCost: 3, dt: 21 },
      { level: 16, name: "Investida Aérea", combat: true, description: "Ataque de cima usando jetpack, dano em área de impacto.", peCost: 3, damageDice: "4d6" },
      { level: 17, name: "Código de Mandalore", combat: false, description: "Ganha respeito e autoridade entre guerreiros e facções.", peCost: 3, dt: 23 },
      { level: 18, name: "Golpe do Guerreiro", combat: true, description: "Ataque de altíssima precisão e dano.", peCost: 3, damageDice: "5d6" },
      { level: 19, name: "Armadura Lendária", combat: false, description: "Proteção quase impenetrável por tempo limitado.", peCost: 3, dt: 23 },
      { level: 20, name: "Tempestade de Combate", combat: true, description: "Combina armas, jetpack e força bruta num ataque devastador.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Caçador Implacável", description: "Torna-se imparável ao perseguir um alvo marcado.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 35, name: "Fúria de Beskar", description: "Ataques consecutivos de altíssimo dano sem pausa.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 50, name: "Lenda de Mandalore", description: "Combate com poder quase mítico, quase impossível de deter.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 99, name: "O Último Guerreiro", description: "Desencadeia todo o arsenal e força em um ataque final devastador.", combat: true, peCost: 8, damageDice: "18d6" },
    ],
  },
  {
    classId: "medico",
    abilities: [
      { level: 1, name: "Golpe Cirúrgico", combat: true, description: "Ataque preciso em ponto vital usando ferramenta médica.", peCost: 1, damageDice: "1d6" },
      { level: 1, name: "Diagnóstico Rápido", combat: false, description: "Identifica condição, ferimento e fraqueza física de alvo/aliado.", peCost: 1, dt: 15 },
      { level: 2, name: "Primeiros Socorros", combat: false, description: "Cura ferimentos leves rapidamente.", peCost: 1, dt: 15 },
      { level: 3, name: "Injeção Neutralizante", combat: true, description: "Aplica substância que enfraquece o alvo.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Estabilização de Campo", combat: false, description: "Recupera aliado caído em combate.", peCost: 2, dt: 17 },
      { level: 5, name: "Toxina Cirúrgica", combat: true, description: "Ataque com substância que causa dano contínuo.", peCost: 2, damageDice: "2d6" },
      { level: 6, name: "Kit Avançado", combat: false, description: "Melhora eficiência de cura e tratamento.", peCost: 2, dt: 17 },
      { level: 8, name: "Golpe Paralisante", combat: true, description: "Ataque que afeta nervos/movimento do alvo.", peCost: 2, damageDice: "2d6" },
      { level: 9, name: "Cura Sob Pressão", combat: false, description: "Trata múltiplos aliados rapidamente em combate.", peCost: 2, dt: 19 },
      { level: 10, name: "Bisturi Certeiro", combat: true, description: "Ataque que ignora parte da resistência do alvo.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Antídoto Universal", combat: false, description: "Neutraliza venenos e toxinas em si ou aliados.", peCost: 2, dt: 19 },
      { level: 12, name: "Sedativo de Impacto", combat: true, description: "Ataque que reduz drasticamente a ação do inimigo.", peCost: 2, damageDice: "3d6" },
      { level: 13, name: "Cirurgia de Guerra", combat: false, description: "Revive/estabiliza aliado gravemente ferido em pleno combate.", peCost: 3, dt: 21 },
      { level: 14, name: "Golpe Anatômico", combat: true, description: "Ataque de altíssima precisão contra ponto vital.", peCost: 3, damageDice: "4d6" },
      { level: 15, name: "Imunização de Grupo", combat: false, description: "Protege aliados contra efeitos negativos temporariamente.", peCost: 3, dt: 21 },
      { level: 16, name: "Overdose Controlada", combat: true, description: "Injeta substância que causa dano severo e progressivo.", peCost: 3, damageDice: "4d6" },
      { level: 17, name: "Mestre da Cura", combat: false, description: "Restaura completamente a condição de um aliado.", peCost: 3, dt: 23 },
      { level: 18, name: "Golpe Fatal Preciso", combat: true, description: "Ataque que explora fraqueza anatômica com dano altíssimo.", peCost: 3, damageDice: "5d6" },
      { level: 19, name: "Equipe Estabilizada", combat: false, description: "Todo o grupo recebe suporte médico contínuo.", peCost: 3, dt: 23 },
      { level: 20, name: "Veneno Mortal", combat: true, description: "Aplica substância letal de ação rápida em alvo único.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Anjo de Batalha", description: "Cura e sustenta o grupo inteiro em combates prolongados.", combat: true, peCost: 4, damageDice: "7d6", heal: true },
      { level: 35, name: "Bisturi da Morte", description: "Ataques cirúrgicos que ignoram quase toda defesa do alvo.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 50, name: "Mestre da Vida e da Morte", description: "Decide entre curar totalmente ou eliminar com precisão.", combat: true, peCost: 6, damageDice: "12d6", healOrDamage: true },
      { level: 99, name: "Julgamento Clínico", description: "Um único procedimento que cura o grupo por completo ou elimina um alvo instantaneamente.", combat: true, peCost: 8, damageDice: "18d6", healOrDamage: true },
    ],
  },
  {
    classId: "mercenario",
    abilities: [
      { level: 1, name: "Golpe Contratado", combat: true, description: "Ataque básico versátil, corpo a corpo ou à distância.", peCost: 1, damageDice: "1d6" },
      { level: 1, name: "Avaliação de Alvo", combat: false, description: "Identifica valor, perigo e fraqueza do contrato/inimigo.", peCost: 1, dt: 15 },
      { level: 2, name: "Troca Rápida", combat: false, description: "Alterna entre armas sem perder tempo.", peCost: 1, dt: 15 },
      { level: 3, name: "Tiro de Abertura", combat: true, description: "Ataque à distância com bônus de dano no primeiro golpe.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Equipamento Versátil", combat: false, description: "Adapta arsenal para diferentes situações de contrato.", peCost: 2, dt: 17 },
      { level: 5, name: "Golpe Duplo", combat: true, description: "Ataque combinado corpo a corpo + arma de fogo.", peCost: 2, damageDice: "2d6" },
      { level: 6, name: "Rede de Contratos", combat: false, description: "Acessa informações e ofertas de trabalho rapidamente.", peCost: 2, dt: 17 },
      { level: 8, name: "Investida Paga", combat: true, description: "Ataque com dano extra contra alvo com recompensa.", peCost: 2, damageDice: "2d6" },
      { level: 9, name: "Instinto de Sobrevivência", combat: false, description: "Reage a emboscadas com vantagem.", peCost: 2, dt: 19 },
      { level: 10, name: "Rajada Mercenária", combat: true, description: "Sequência de disparos rápidos contra um ou mais alvos.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Negociação sob Mira", combat: false, description: "Força vantagem em negociação usando ameaça de combate.", peCost: 2, dt: 19 },
      { level: 12, name: "Golpe Sem Piedade", combat: true, description: "Dano aumentado contra alvo já ferido.", peCost: 2, damageDice: "3d6" },
      { level: 13, name: "Arsenal Completo", combat: false, description: "Equipamento adaptado para qualquer tipo de missão.", peCost: 3, dt: 21 },
      { level: 14, name: "Fúria Contratada", combat: true, description: "Sequência de ataques com dano crescente por combate.", peCost: 3, damageDice: "4d6" },
      { level: 15, name: "Blindagem Paga", combat: false, description: "Proteção temporária de alta qualidade.", peCost: 3, dt: 21 },
      { level: 16, name: "Execução Eficiente", combat: true, description: "Ataque de altíssima precisão contra alvo prioritário.", peCost: 3, damageDice: "4d6" },
      { level: 17, name: "Reputação de Elite", combat: false, description: "Contratos maiores e mais perigosos ficam acessíveis.", peCost: 3, dt: 23 },
      { level: 18, name: "Golpe Sem Limites", combat: true, description: "Ataque de dano máximo, sem restrições táticas.", peCost: 3, damageDice: "5d6" },
      { level: 19, name: "Rede de Elite", combat: false, description: "Acessa recursos e informações de alto nível.", peCost: 3, dt: 23 },
      { level: 20, name: "Fúria Total", combat: true, description: "Combina toda força, armamento e velocidade num ataque devastador.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Lenda dos Contratos", description: "Eficiência de combate aumenta drasticamente em qualquer missão paga.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 35, name: "Arsenal Lendário", description: "Acesso e domínio de armamento de altíssimo poder.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 50, name: "Mercenário Supremo", description: "Um dos combatentes mais temidos e eficientes da galáxia.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 99, name: "Contrato Final", description: "Executa o ataque mais letal de sua carreira, capaz de decidir qualquer conflito.", combat: true, peCost: 8, damageDice: "18d6" },
    ],
  },
  {
    classId: "piloto",
    abilities: [
      { level: 1, name: "Rasante de Combate", combat: true, description: "Manobra que atinge inimigos no chão/próximos durante voo baixo.", peCost: 1, damageDice: "1d6" },
      { level: 1, name: "Olho de Piloto", combat: false, description: "Avalia rapidamente veículos, rotas e riscos.", peCost: 1, dt: 15 },
      { level: 2, name: "Manobra Evasiva", combat: false, description: "Reduz chance de ser atingido em perseguições.", peCost: 1, dt: 15 },
      { level: 3, name: "Tiro de Cockpit", combat: true, description: "Disparo rápido usando armamento do próprio veículo.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Pilotagem Extrema", combat: false, description: "Realiza manobras impossíveis para pilotos comuns.", peCost: 2, dt: 17 },
      { level: 5, name: "Investida Aérea", combat: true, description: "Colisão controlada ou rasante ofensivo contra alvo.", peCost: 2, damageDice: "2d6" },
      { level: 6, name: "Leitura de Rota", combat: false, description: "Encontra o melhor caminho em perseguições e fugas.", peCost: 2, dt: 17 },
      { level: 8, name: "Disparo em Movimento", combat: true, description: "Ataque preciso mesmo em alta velocidade.", peCost: 2, damageDice: "2d6" },
      { level: 9, name: "Domínio de Manobra", combat: false, description: "Controla veículo com perfeição mesmo sob dano.", peCost: 2, dt: 19 },
      { level: 10, name: "Rajada de Perseguição", combat: true, description: "Sequência de disparos contra alvo em fuga/perseguição.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Piloto Fantasma", combat: false, description: "Desaparece de sensores por curto período.", peCost: 2, dt: 19 },
      { level: 12, name: "Ataque em Rasante", combat: true, description: "Passa raspando sobre o alvo, causando dano direto.", peCost: 2, damageDice: "3d6" },
      { level: 13, name: "Sincronia de Combate", combat: false, description: "Coordena ataque aéreo com aliados em terra.", peCost: 3, dt: 21 },
      { level: 14, name: "Manobra Suicida", combat: true, description: "Ataque de altíssimo risco e dano contra alvo grande.", peCost: 3, damageDice: "4d6" },
      { level: 15, name: "Blindagem de Voo", combat: false, description: "Reduz dano crítico ao veículo próprio.", peCost: 3, dt: 21 },
      { level: 16, name: "Interceptação Perfeita", combat: true, description: "Ataque que corta rota de fuga do inimigo com dano garantido.", peCost: 3, damageDice: "4d6" },
      { level: 17, name: "Mestre dos Céus", combat: false, description: "Controla qualquer veículo com perfeição absoluta.", peCost: 3, dt: 23 },
      { level: 18, name: "Ataque Decisivo", combat: true, description: "Manobra ofensiva de altíssimo impacto contra alvo prioritário.", peCost: 3, damageDice: "5d6" },
      { level: 19, name: "Esquadrão Fantasma", combat: false, description: "Coordena múltiplos veículos aliados numa manobra só.", peCost: 3, dt: 23 },
      { level: 20, name: "Tempestade Aérea", combat: true, description: "Ataque devastador combinando velocidade, precisão e armamento pesado.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Ás Lendário", description: "Torna-se praticamente intocável em combate aéreo/espacial.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 35, name: "Manobra Impossível", description: "Executa ataque que nenhum outro piloto conseguiria replicar.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 50, name: "Senhor dos Céus", description: "Domina completamente qualquer combate aéreo ou espacial.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 99, name: "Voo Final", description: "Executa a manobra ofensiva mais arriscada e poderosa já registrada.", combat: true, peCost: 8, damageDice: "18d6" },
    ],
  },
  {
    classId: "pirata_espacial",
    abilities: [
      { level: 1, name: "Golpe de Saque", combat: true, description: "Ataque agressivo com arma improvisada ou branca.", peCost: 1, damageDice: "1d6" },
      { level: 1, name: "Olho de Presa", combat: false, description: "Identifica alvos vulneráveis e valiosos rapidamente.", peCost: 1, dt: 15 },
      { level: 2, name: "Abordagem Rápida", combat: false, description: "Invade veículos/naves com eficiência.", peCost: 1, dt: 15 },
      { level: 3, name: "Tiro Sujo", combat: true, description: "Disparo sem regras, ignora convenções de combate justo.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Saque Relâmpago", combat: false, description: "Rouba recursos/itens durante o próprio combate.", peCost: 2, dt: 17 },
      { level: 5, name: "Fúria de Bordo", combat: true, description: "Sequência de ataques ao invadir um veículo/nave.", peCost: 2, damageDice: "2d6" },
      { level: 6, name: "Rede de Piratas", combat: false, description: "Contata outros fora da lei para apoio ou informação.", peCost: 2, dt: 17 },
      { level: 8, name: "Emboscada Selvagem", combat: true, description: "Ataque surpresa com dano aumentado.", peCost: 2, damageDice: "2d6" },
      { level: 9, name: "Terror da Rota", combat: false, description: "Intimida tripulações inteiras a se renderem sem luta.", peCost: 2, dt: 19 },
      { level: 10, name: "Corte Cruel", combat: true, description: "Ataque que ignora parte da armadura do alvo.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Fuga com Butim", combat: false, description: "Escapa com recursos roubados mesmo sob perseguição.", peCost: 2, dt: 19 },
      { level: 12, name: "Caos Controlado", combat: true, description: "Ataque em área que desorganiza grupo inimigo.", peCost: 2, damageDice: "3d6" },
      { level: 13, name: "Bando de Saqueadores", combat: true, description: "Coordena ataque com outros piratas/aliados.", peCost: 3, damageDice: "4d6" },
      { level: 14, name: "Fúria Sem Lei", combat: true, description: "Sequência de golpes brutais sem limite tático.", peCost: 3, damageDice: "4d6" },
      { level: 15, name: "Blindagem de Saque", combat: false, description: "Proteção improvisada com itens roubados.", peCost: 3, dt: 21 },
      { level: 16, name: "Abordagem Brutal", combat: true, description: "Ataque de alto dano ao invadir veículo/base inimiga.", peCost: 3, damageDice: "4d6" },
      { level: 17, name: "Rei dos Piratas", combat: false, description: "Comanda respeito e medo em qualquer rota conhecida.", peCost: 3, dt: 23 },
      { level: 18, name: "Golpe Sem Piedade", combat: true, description: "Ataque de dano máximo contra alvo indefeso ou rendido.", peCost: 3, damageDice: "5d6" },
      { level: 19, name: "Frota Pirata", combat: false, description: "Convoca apoio de outros piratas em grande escala.", peCost: 3, dt: 23 },
      { level: 20, name: "Tempestade de Saque", combat: true, description: "Ataque devastador que combina caos, brutalidade e número.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Terror das Rotas", description: "Inimigos hesitam ou fogem só de reconhecê-lo.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 35, name: "Fúria Sem Lei Total", description: "Ataques consecutivos de altíssimo dano sem qualquer limite.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 50, name: "Lenda Pirata", description: "Comanda batalhas inteiras com brutalidade e carisma extremos.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 99, name: "Saque Final", description: "Executa o assalto mais violento e lucrativo de sua vida, devastador em combate.", combat: true, peCost: 8, damageDice: "18d6" },
    ],
  },
  {
    classId: "soldado_republica",
    abilities: [
      { level: 1, name: "Disparo Regulamentar", combat: true, description: "Ataque padrão com arma de fogo militar.", peCost: 1, damageDice: "1d6" },
      { level: 1, name: "Disciplina de Combate", combat: false, description: "Mantém foco e desempenho mesmo sob pressão.", peCost: 1, dt: 15 },
      { level: 2, name: "Cobertura Tática", combat: false, description: "Melhora defesa própria e de aliados próximos.", peCost: 1, dt: 15 },
      { level: 3, name: "Rajada Curta", combat: true, description: "Sequência curta de disparos contra um alvo.", peCost: 1, damageDice: "1d6" },
      { level: 4, name: "Formação de Combate", combat: false, description: "Coordena posicionamento com aliados para vantagem tática.", peCost: 2, dt: 17 },
      { level: 5, name: "Tiro de Supressão", combat: true, description: "Disparos que dificultam avanço/mira do inimigo.", peCost: 2, damageDice: "2d6" },
      { level: 6, name: "Comunicação Tática", combat: false, description: "Troca informação de combate rapidamente com o esquadrão.", peCost: 2, dt: 17 },
      { level: 8, name: "Investida Coordenada", combat: true, description: "Ataque combinado com pelo menos um aliado.", peCost: 2, damageDice: "2d6" },
      { level: 9, name: "Linha de Frente", combat: false, description: "Resiste e sustenta posição sob fogo pesado.", peCost: 2, dt: 19 },
      { level: 10, name: "Disparo Perfurante", combat: true, description: "Ataque que ignora parte da blindagem do alvo.", peCost: 2, damageDice: "3d6" },
      { level: 11, name: "Resgate sob Fogo", combat: false, description: "Retira aliado ferido em pleno combate.", peCost: 2, dt: 19 },
      { level: 12, name: "Avanço Blindado", combat: true, description: "Ataque com proteção reforçada durante investida.", peCost: 2, damageDice: "3d6" },
      { level: 13, name: "Comando de Esquadrão", combat: false, description: "Melhora desempenho de todos os aliados próximos.", peCost: 3, dt: 21 },
      { level: 14, name: "Rajada Pesada", combat: true, description: "Sequência de disparos de alto dano contra múltiplos alvos.", peCost: 3, damageDice: "4d6" },
      { level: 15, name: "Blindagem de Batalha", combat: false, description: "Reduz drasticamente dano crítico recebido.", peCost: 3, dt: 21 },
      { level: 16, name: "Ataque Sincronizado", combat: true, description: "Ataque combinado com todo o esquadrão presente.", peCost: 3, damageDice: "4d6" },
      { level: 17, name: "Veterano de Guerra", combat: false, description: "Desempenho máximo mesmo em combates prolongados.", peCost: 3, dt: 23 },
      { level: 18, name: "Disparo Decisivo", combat: true, description: "Ataque de altíssima precisão e dano contra alvo prioritário.", peCost: 3, damageDice: "5d6" },
      { level: 19, name: "Comando de Batalha", combat: false, description: "Coordena esquadrão inteiro com eficiência máxima.", peCost: 3, dt: 23 },
      { level: 20, name: "Ofensiva Total", combat: true, description: "Ataque devastador combinando esquadrão, blindagem e armamento pesado.", peCost: 3, damageDice: "5d6" },
    ],
    milestones: [
      { level: 25, name: "Herói de Guerra", description: "Desempenho excepcional inspira e fortalece todo o esquadrão.", combat: true, peCost: 4, damageDice: "7d6" },
      { level: 35, name: "Tática Perfeita", description: "Executa manobra de combate quase impossível de contra-atacar.", combat: true, peCost: 5, damageDice: "9d6" },
      { level: 50, name: "Lenda Militar", description: "Comanda e vence batalhas praticamente sozinho quando necessário.", combat: true, peCost: 6, damageDice: "12d6" },
      { level: 99, name: "Última Linha de Defesa", description: "Um ataque final que pode decidir uma guerra inteira.", combat: true, peCost: 8, damageDice: "18d6" },
    ],
  },
];
