-- Converte colunas que guardavam JSON serializado em texto para JSONB nativo.
-- O cast USING preserva os dados existentes (ao contrario do DROP/ADD COLUMN
-- que o prisma migrate geraria sozinho).

ALTER TABLE "DndSheet" ALTER COLUMN "conditions" TYPE JSONB USING "conditions"::jsonb;
ALTER TABLE "DndSheet" ALTER COLUMN "spellSlotsUsed" TYPE JSONB USING "spellSlotsUsed"::jsonb;
ALTER TABLE "TormentaSheet" ALTER COLUMN "skills" TYPE JSONB USING "skills"::jsonb;
ALTER TABLE "TormentaSheet" ALTER COLUMN "schoolsChosen" TYPE JSONB USING "schoolsChosen"::jsonb;
ALTER TABLE "TormentaSheet" ALTER COLUMN "spellsKnown" TYPE JSONB USING "spellsKnown"::jsonb;
ALTER TABLE "TormentaSheet" ALTER COLUMN "powers" TYPE JSONB USING "powers"::jsonb;
ALTER TABLE "TormentaSheet" ALTER COLUMN "weapons" TYPE JSONB USING "weapons"::jsonb;
ALTER TABLE "TormentaSheet" ALTER COLUMN "equipment" TYPE JSONB USING "equipment"::jsonb;
ALTER TABLE "TormentaSheet" ALTER COLUMN "conditions" TYPE JSONB USING "conditions"::jsonb;
ALTER TABLE "TormentaSheet" ALTER COLUMN "background" TYPE JSONB USING "background"::jsonb;
ALTER TABLE "CthulhuSheet" ALTER COLUMN "skillChecks" TYPE JSONB USING "skillChecks"::jsonb;
ALTER TABLE "CthulhuSheet" ALTER COLUMN "skills" TYPE JSONB USING "skills"::jsonb;
ALTER TABLE "CthulhuSheet" ALTER COLUMN "background" TYPE JSONB USING "background"::jsonb;
ALTER TABLE "CthulhuSheet" ALTER COLUMN "weapons" TYPE JSONB USING "weapons"::jsonb;
ALTER TABLE "CthulhuSheet" ALTER COLUMN "insanityData" TYPE JSONB USING "insanityData"::jsonb;
ALTER TABLE "CthulhuSheet" ALTER COLUMN "spellsData" TYPE JSONB USING "spellsData"::jsonb;
ALTER TABLE "OrdemSheet" ALTER COLUMN "skills" TYPE JSONB USING "skills"::jsonb;
ALTER TABLE "OrdemSheet" ALTER COLUMN "abilities" TYPE JSONB USING "abilities"::jsonb;
ALTER TABLE "OrdemSheet" ALTER COLUMN "rituals" TYPE JSONB USING "rituals"::jsonb;
ALTER TABLE "OrdemSheet" ALTER COLUMN "inventory" TYPE JSONB USING "inventory"::jsonb;
ALTER TABLE "OrdemSheet" ALTER COLUMN "weapons" TYPE JSONB USING "weapons"::jsonb;
ALTER TABLE "OrdemSheet" ALTER COLUMN "background" TYPE JSONB USING "background"::jsonb;
ALTER TABLE "OrdemSheet" ALTER COLUMN "conditions" TYPE JSONB USING "conditions"::jsonb;
ALTER TABLE "OrdemSheet" ALTER COLUMN "insanity" TYPE JSONB USING "insanity"::jsonb;
ALTER TABLE "StarWarsSheet" ALTER COLUMN "classes" DROP DEFAULT;
ALTER TABLE "StarWarsSheet" ALTER COLUMN "classes" TYPE JSONB USING "classes"::jsonb;
ALTER TABLE "StarWarsSheet" ALTER COLUMN "classes" SET DEFAULT '{}';
ALTER TABLE "StarWarsSheet" ALTER COLUMN "humanAttrChoice" TYPE JSONB USING "humanAttrChoice"::jsonb;
ALTER TABLE "StarWarsSheet" ALTER COLUMN "unlockedProphecies" DROP DEFAULT;
ALTER TABLE "StarWarsSheet" ALTER COLUMN "unlockedProphecies" TYPE JSONB USING "unlockedProphecies"::jsonb;
ALTER TABLE "StarWarsSheet" ALTER COLUMN "unlockedProphecies" SET DEFAULT '[]';
ALTER TABLE "StarWarsSheet" ALTER COLUMN "skills" TYPE JSONB USING "skills"::jsonb;
ALTER TABLE "StarWarsSheet" ALTER COLUMN "classPowers" TYPE JSONB USING "classPowers"::jsonb;
ALTER TABLE "StarWarsSheet" ALTER COLUMN "generalPowers" TYPE JSONB USING "generalPowers"::jsonb;
ALTER TABLE "StarWarsSheet" ALTER COLUMN "equipment" TYPE JSONB USING "equipment"::jsonb;
ALTER TABLE "StarWarsSheet" ALTER COLUMN "weapons" TYPE JSONB USING "weapons"::jsonb;
ALTER TABLE "StarWarsSheet" ALTER COLUMN "conditions" TYPE JSONB USING "conditions"::jsonb;
ALTER TABLE "StarWarsSheet" ALTER COLUMN "background" TYPE JSONB USING "background"::jsonb;
ALTER TABLE "DndNpc" ALTER COLUMN "attacks" DROP DEFAULT;
ALTER TABLE "DndNpc" ALTER COLUMN "attacks" TYPE JSONB USING "attacks"::jsonb;
ALTER TABLE "DndNpc" ALTER COLUMN "attacks" SET DEFAULT '[]';
ALTER TABLE "DndCombatant" ALTER COLUMN "conditions" DROP DEFAULT;
ALTER TABLE "DndCombatant" ALTER COLUMN "conditions" TYPE JSONB USING "conditions"::jsonb;
ALTER TABLE "DndCombatant" ALTER COLUMN "conditions" SET DEFAULT '[]';
ALTER TABLE "CthulhuNpc" ALTER COLUMN "attacks" DROP DEFAULT;
ALTER TABLE "CthulhuNpc" ALTER COLUMN "attacks" TYPE JSONB USING "attacks"::jsonb;
ALTER TABLE "CthulhuNpc" ALTER COLUMN "attacks" SET DEFAULT '[]';
ALTER TABLE "CthulhuCombatant" ALTER COLUMN "conditions" DROP DEFAULT;
ALTER TABLE "CthulhuCombatant" ALTER COLUMN "conditions" TYPE JSONB USING "conditions"::jsonb;
ALTER TABLE "CthulhuCombatant" ALTER COLUMN "conditions" SET DEFAULT '[]';
ALTER TABLE "CthulhuInsanityRecord" ALTER COLUMN "phobias" DROP DEFAULT;
ALTER TABLE "CthulhuInsanityRecord" ALTER COLUMN "phobias" TYPE JSONB USING "phobias"::jsonb;
ALTER TABLE "CthulhuInsanityRecord" ALTER COLUMN "phobias" SET DEFAULT '[]';
ALTER TABLE "CthulhuInsanityRecord" ALTER COLUMN "manias" DROP DEFAULT;
ALTER TABLE "CthulhuInsanityRecord" ALTER COLUMN "manias" TYPE JSONB USING "manias"::jsonb;
ALTER TABLE "CthulhuInsanityRecord" ALTER COLUMN "manias" SET DEFAULT '[]';
ALTER TABLE "OrdemNpc" ALTER COLUMN "attacks" DROP DEFAULT;
ALTER TABLE "OrdemNpc" ALTER COLUMN "attacks" TYPE JSONB USING "attacks"::jsonb;
ALTER TABLE "OrdemNpc" ALTER COLUMN "attacks" SET DEFAULT '[]';
ALTER TABLE "OrdemCombatant" ALTER COLUMN "conditions" DROP DEFAULT;
ALTER TABLE "OrdemCombatant" ALTER COLUMN "conditions" TYPE JSONB USING "conditions"::jsonb;
ALTER TABLE "OrdemCombatant" ALTER COLUMN "conditions" SET DEFAULT '[]';
ALTER TABLE "OrdemSanityRecord" ALTER COLUMN "traumas" DROP DEFAULT;
ALTER TABLE "OrdemSanityRecord" ALTER COLUMN "traumas" TYPE JSONB USING "traumas"::jsonb;
ALTER TABLE "OrdemSanityRecord" ALTER COLUMN "traumas" SET DEFAULT '[]';
ALTER TABLE "TormentaNpc" ALTER COLUMN "attacks" DROP DEFAULT;
ALTER TABLE "TormentaNpc" ALTER COLUMN "attacks" TYPE JSONB USING "attacks"::jsonb;
ALTER TABLE "TormentaNpc" ALTER COLUMN "attacks" SET DEFAULT '[]';
ALTER TABLE "TormentaCombatant" ALTER COLUMN "conditions" DROP DEFAULT;
ALTER TABLE "TormentaCombatant" ALTER COLUMN "conditions" TYPE JSONB USING "conditions"::jsonb;
ALTER TABLE "TormentaCombatant" ALTER COLUMN "conditions" SET DEFAULT '[]';
ALTER TABLE "StarWarsNpc" ALTER COLUMN "attacks" DROP DEFAULT;
ALTER TABLE "StarWarsNpc" ALTER COLUMN "attacks" TYPE JSONB USING "attacks"::jsonb;
ALTER TABLE "StarWarsNpc" ALTER COLUMN "attacks" SET DEFAULT '[]';
ALTER TABLE "StarWarsNpc" ALTER COLUMN "skills" DROP DEFAULT;
ALTER TABLE "StarWarsNpc" ALTER COLUMN "skills" TYPE JSONB USING "skills"::jsonb;
ALTER TABLE "StarWarsNpc" ALTER COLUMN "skills" SET DEFAULT '[]';
ALTER TABLE "StarWarsCombatant" ALTER COLUMN "conditions" DROP DEFAULT;
ALTER TABLE "StarWarsCombatant" ALTER COLUMN "conditions" TYPE JSONB USING "conditions"::jsonb;
ALTER TABLE "StarWarsCombatant" ALTER COLUMN "conditions" SET DEFAULT '[]';
