// ─── ORDEM PARANORMAL — Bestiário completo (Livro de Regras, Cap. 7) ─────────
// Todas as ameaças do livro base, organizadas por elemento.

export type Element = "Sangue" | "Morte" | "Conhecimento" | "Energia" | "Realidade";

export interface OrdemCreature {
  name: string;
  element: Element;
  vd: string;
  size: string;
  sanLoss: string;     // dano mental da Presença Perturbadora
  pp: string;          // DT da Presença Perturbadora
  pv: number;
  defense: number;
  agi: number;
  forc: number;
  int: number;
  pre: number;
  vig: number;
  displacement: string;
  resistances: string;
  vulnerabilities: string;
  attacks: string[];
  abilities: string;
  description: string;
}

export const BESTIARY: OrdemCreature[] = [
  // ─────────────────────────────── SANGUE ───────────────────────────────
  {
    name: "Zumbi de Sangue", element: "Sangue", vd: "20", size: "Médio",
    pp: "15", sanLoss: "2d6", pv: 45, defense: 17, agi: 2, forc: 2, int: 0, pre: 1, vig: 2,
    displacement: "9m", resistances: "Balístico, impacto e perfuração 5, Sangue 10", vulnerabilities: "Morte",
    attacks: ["Garras (corpo a corpo x2, +5): 1d6+5 corte"],
    abilities: "Percepção às cegas (enxerga pela dor, detecta movimento do ar). NEX 25%+ é imune à Presença Perturbadora.",
    description: "Cadáver brutalmente morto, devorado e reanimado pela entidade de Sangue. Cego, bestial e movido por frenesi obsessivo de devorar carne. A criatura de Sangue mais comum.",
  },
  {
    name: "Aberração de Carne", element: "Sangue", vd: "40", size: "Grande",
    pp: "15", sanLoss: "3d6", pv: 70, defense: 19, agi: 1, forc: 3, int: 0, pre: 1, vig: 3,
    displacement: "9m", resistances: "Balístico, impacto, perfuração 5, Sangue 10", vulnerabilities: "Morte",
    attacks: ["Pancada (corpo a corpo x2, +10): 2d6+6 impacto", "Abocanhar: 3d6 perfuração por turno em agarrado (Fortitude DT 15 reduz à metade)"],
    abilities: "Agarrão (reação ao acertar pancada). Pode manter até 2 agarrados e levá-los à boca central. NEX 30%+ imune à PP.",
    description: "Dois (ou mais) corpos fundidos por um experimento fracassado, com pele vermelha, quatro pernas, quatro braços e uma boca circular dentada onde estavam os estômagos. Até 2,2m de altura.",
  },
  {
    name: "Dama de Sangue", element: "Sangue", vd: "60", size: "Enorme",
    pp: "20", sanLoss: "3d6", pv: 105, defense: 20, agi: 2, forc: 3, int: 1, pre: 2, vig: 2,
    displacement: "12m", resistances: "Balístico, impacto e perfuração 10, Sangue 20", vulnerabilities: "Morte",
    attacks: ["Tentáculo (corpo a corpo x2, +10): 2d6+5 impacto", "Sete flores: Arremessar, Chuva de Ácido, Espinhos, Grito Devastador, Miasma Fétido, Prisão de Tentáculos, Visão Macabra"],
    abilities: "Consumir: ganha habilidades de flor ao consumir 7 corpos. Cada flor tem uma fraqueza específica (Enigma de Medo). NEX 35%+ imune à PP.",
    description: "Corpo humano partido ao meio, com órgãos fundidos a plantas formando sete tentáculos com flores e espinhos. Ligada ao mito do Serafim Escarlate e ao culto da Dama das Flores.",
  },
  {
    name: "Zumbi de Sangue Bestial", element: "Sangue", vd: "100", size: "Grande",
    pp: "20", sanLoss: "4d6", pv: 200, defense: 23, agi: 2, forc: 3, int: 0, pre: 2, vig: 3,
    displacement: "12m", resistances: "Balístico, impacto e perfuração 5, Sangue 10", vulnerabilities: "Morte",
    attacks: ["Mordida de Sangue (corpo a corpo, +15): 2d10+5 perfuração", "Garras de Sangue (corpo a corpo x2, +15): 2d6+5 corte"],
    abilities: "Furtivo e Letal: contra alvo desprevenido, +bônus e +2 dados de dano. Instinto Predatório: sem penalidade em Furtividade ao mover. NEX 45%+ imune à PP.",
    description: "Versão maior e mais brutal do zumbi de Sangue, com o triplo da massa do cadáver e crânio partido numa enorme bocarra. Age com instinto predatório, à espreita de alvos desprevenidos.",
  },
  {
    name: "Mulher Afogada", element: "Sangue", vd: "140", size: "Grande",
    pp: "25", sanLoss: "4d8", pv: 240, defense: 28, agi: 4, forc: 3, int: 2, pre: 2, vig: 3,
    displacement: "9m (forma líquida 36m)", resistances: "Balístico, Energia, impacto e perfuração 10, Sangue 20", vulnerabilities: "Morte",
    attacks: ["Mordida (corpo a corpo, +15): 4d8+8 perfuração", "Garras (corpo a corpo x2, +15): 4d6+6 corte", "Jato de Sangue (distância curto, +10): 4d8+8 Sangue", "Afogar em Sangue / Arrancar Sangue / Invadir Órgãos (forma líquida)"],
    abilities: "Forma de Sangue: viaja por canos e orifícios, resistência 20. Enigma de Medo: bloquear todas as saídas de água e abrir torneiras força a forma física. NEX 50%+ imune à PP.",
    description: "Lenda urbana de mulheres mortas em afogamentos trágicos. Move-se como Sangue líquido pelos encanamentos, puxando vítimas para dentro dos canos para afogá-las e devorá-las.",
  },
  {
    name: "Enpap-X", element: "Sangue", vd: "180", size: "Grande",
    pp: "25", sanLoss: "6d6", pv: 360, defense: 36, agi: 2, forc: 4, int: 1, pre: 2, vig: 3,
    displacement: "12m", resistances: "Balístico, impacto e perfuração 10, Sangue 20", vulnerabilities: "Morte",
    attacks: ["Socão (corpo a corpo x4, +20): 2d10+10 impacto", "Correntes (distância curto x3, +15): 2d8+10 impacto"],
    abilities: "Transformação: começa como um existido (pág. 240) e, ao chegar a 0 PV, se transforma com PV cheios. Crescer: +1d6 cumulativo de dano a cada socão acertado. Acorrentar e estrangular. NEX 60%+ imune à PP.",
    description: "Aberração sumeriana nascida da dor de um prisioneiro torturado, obrigado a marcar na pele os feitos de seu soberano. Monstruosidade de quatro braços movida por vingança.",
  },
  {
    name: "Titã de Sangue", element: "Sangue", vd: "220", size: "Colossal",
    pp: "30", sanLoss: "7d6", pv: 550, defense: 35, agi: 2, forc: 5, int: 1, pre: 1, vig: 4,
    displacement: "12m", resistances: "Balístico, impacto e perfuração 20, Sangue 20", vulnerabilities: "Morte",
    attacks: ["Mordida (corpo a corpo, +25): 4d12+10 perfuração", "Garras (corpo a corpo x2, +25): 4d8+10 corte", "Estraçalhar: 4d12+10 perfuração + sangrando (Reflexos DT 30)"],
    abilities: "Sede de Sangue: +4d6 de dano contra alvos machucados ou sangrando. NEX 70%+ imune à PP.",
    description: "A maior versão de um zumbi de Sangue, com mais de 4m. Massa de carne endurecida com veias saltadas e uma boca de quatro quelíceras gigantes. Forma-se de vários corpos ou de alguém com exposição paranormal elevada.",
  },
  {
    name: "Minotauro", element: "Sangue", vd: "280", size: "Grande",
    pp: "35", sanLoss: "8d6", pv: 750, defense: 44, agi: 4, forc: 5, int: 1, pre: 3, vig: 5,
    displacement: "12m", resistances: "Balístico, impacto e perfuração 20, Sangue 20", vulnerabilities: "Morte",
    attacks: ["Chifres (corpo a corpo, +30): 6d12+20 perfuração", "Machado (corpo a corpo x2, +32): 4d12+20 corte", "Cravar Chifres: agarra o alvo na investida, 4d12+20 Sangue por turno"],
    abilities: "Investidas brutais quase impossíveis de conter. NEX 80%+ imune à PP.",
    description: "Animal bípede furioso de mais de 3m, infectado por pústulas de Sangue, com um machado de lâmina dupla fundido ao braço. Das lendas gregas do monstro do labirinto.",
  },
  {
    name: "Carente", element: "Sangue", vd: "300", size: "Grande",
    pp: "35", sanLoss: "7d8", pv: 700, defense: 40, agi: 4, forc: 4, int: 2, pre: 3, vig: 4,
    displacement: "12m", resistances: "Balístico, impacto e perfuração 20, Sangue 20", vulnerabilities: "Morte",
    attacks: ["Garras de Sangue (corpo a corpo x2, +35): 2d8+20 Sangue", "Ferrão de Sangue (corpo a corpo, +35): 2d12+20 Sangue", "Tentáculo (corpo a corpo, +35): 2d8+20 Sangue"],
    abilities: "Regeneração de Sangue: Cura Acelerada 20 (cessa com dano de Energia ou inconsciência). Forma Infantil: simula uma criança para enganar; não abre a primeira porta sozinho. NEX 90%+ imune à PP.",
    description: "Criatura de Daniel Hartmann nascida da inveja de quem nunca sentiu amor. Toma a forma de uma criança perdida batendo à porta; quando atendida, revela um inseto monstruoso de 3m com ferrão.",
  },
  {
    name: "Kerberos", element: "Sangue", vd: "340", size: "Enorme",
    pp: "35", sanLoss: "10d6", pv: 1150, defense: 46, agi: 4, forc: 5, int: 0, pre: 3, vig: 5,
    displacement: "18m", resistances: "Balístico, impacto e perfuração 20, Sangue 20", vulnerabilities: "Morte",
    attacks: ["Mordida (corpo a corpo, +40): 4d12+30 Sangue", "Disparo de Espinhos (distância médio, +35): 4d8+20 Sangue", "Devorar: mata alvo a 0 PV e recupera metade dos PV dele (Fortitude DT 40)"],
    abilities: "Ataque Flexível: até 4 ataques por rodada (máx. 3 iguais). Só se manifesta em um 'Inferno' tomado pelo Sangue, guardando a origem da distorção. NEX 99%+ imune à PP.",
    description: "O cão de três cabeças, guardião do portão do inferno. Besta de mais de 3m de altura e 7m de comprimento, seis patas, espinhos e três cabeças com bocas asquerosas.",
  },
  {
    name: "Aniquilação", element: "Sangue", vd: "380", size: "Colossal",
    pp: "45", sanLoss: "9d8", pv: 1200, defense: 58, agi: 4, forc: 5, int: 3, pre: 4, vig: 5,
    displacement: "15m", resistances: "Dano 50", vulnerabilities: "Morte",
    attacks: ["Garras (corpo a corpo x2, +40): 4d10+30 Sangue", "Tentáculos Espinhentos (corpo a corpo x2, +40): 2d12+30 Sangue", "Disparo de Espinhos (distância médio x3, +40): 2d10+20 Sangue", "Tempestade de Espinhos (1x/cena): 20d6+20 Sangue em alcance médio (Reflexos DT 40)"],
    abilities: "Agarrão (até 4 alvos). Instinto Aniquilador: ataca quem se mover >3m perto. Bater as Asas: 8d6 mental + atordoa em alcance longo. NEX imune (PP DT 45).",
    description: "A maior criatura já registrada — um apocalipse paranormal de mais de 10m. Inúmeros braços que brotam uns dos outros, espinhos, tentáculos e uma bocarra com dentes do tamanho de adultos.",
  },
  {
    name: "O Diabo", element: "Sangue", vd: "400", size: "Médio",
    pp: "45", sanLoss: "10d8", pv: 1666, defense: 66, agi: 6, forc: 6, int: 6, pre: 6, vig: 6,
    displacement: "18m", resistances: "Balístico, impacto e perfuração 20 (Imune a dano e efeitos de Sangue, atordoamento e paralisia)", vulnerabilities: "Morte",
    attacks: ["Arma Sangrenta (corpo a corpo x2 / distância médio, +45, crítico x3): 2d10+50 Sangue", "Chifre do Diabo (corpo a corpo, +45, crítico x3): 2d8+50 Sangue", "Explodir em Sangue (2x/turno): 10d6 Sangue"],
    abilities: "Senhor do Sangue: invoca criaturas de Sangue de até 400 VD total. Pacto: 10d6 mental; quem enlouquece vira servo. Potência de Sangue: recupera 50 PV/turno. Ardiloso: pode esconder a PP.",
    description: "O Príncipe do Ódio, o Sangue Encarnado. Manifestação que nunca foi derrotada, controla qualquer criatura irracional de Sangue. Pele vermelha, chifres e sorriso macabro. NÃO se envolva com o Diabo.",
  },

  // ─────────────────────────────── MORTE ────────────────────────────────
  {
    name: "Esqueleto de Lodo", element: "Morte", vd: "20", size: "Médio",
    pp: "14", sanLoss: "2d4", pv: 40, defense: 14, agi: 2, forc: 2, int: 0, pre: 1, vig: 1,
    displacement: "6m", resistances: "Corte, impacto e perfuração 5, Morte 10", vulnerabilities: "Energia",
    attacks: ["Garras (corpo a corpo x2, +5): 2d6+2 corte", "Espiral de Lodo: 2d10 Morte em linha de 9m (Reflexos DT 14)"],
    abilities: "Imortalidade: ao morrer vira poça de Lodo e volta em 1d3 rodadas com 20 PV; destruído de vez por fogo/Energia na forma de poça. NEX 25%+ imune à PP.",
    description: "Cadáver consumido pela Morte, esquelético e acinzentado, com Lodo escorrendo dos orifícios. Emite sons invertidos e se regenera, salvo se queimado ou exposto a Energia.",
  },
  {
    name: "Succ", element: "Morte", vd: "40", size: "Médio",
    pp: "15", sanLoss: "3d6", pv: 65, defense: 20, agi: 4, forc: 2, int: 0, pre: 1, vig: 1,
    displacement: "12m", resistances: "Corte, impacto e perfuração 5, Morte 10", vulnerabilities: "Energia",
    attacks: ["Mordida (corpo a corpo, +10): 2d8+2 perfuração", "Sucção: prende no rosto e suga o ar; falha em Fortitude DT 17 = inconsciente e reduzido a 0 PV no turno seguinte"],
    abilities: "NEX 30%+ imune à PP. Solta a vítima se sofrer 10+ de dano numa rodada.",
    description: "Quadrúpede de patas pontudas e pescoço longo invertebrado terminando numa boca circular de dentes em camadas. Suga o ar dos pulmões e emite um ruído de aspirador de pó.",
  },
  {
    name: "Aracnasita", element: "Morte", vd: "80", size: "Grande",
    pp: "20", sanLoss: "4d6", pv: 140, defense: 23, agi: 3, forc: 2, int: 1, pre: 1, vig: 2,
    displacement: "12m", resistances: "Imune a dano", vulnerabilities: "Energia",
    attacks: ["Mordida (corpo a corpo, +15): 2d10+10 perfuração", "Estacar: +1d10 Morte e agarra (Atletismo DT 20 escapa)", "Disparar Teia: área 3m, agarra (Reflexos DT 20) e 2d8+10 Morte/turno"],
    abilities: "Imune a dano (Lodo protetor) — o Enigma de Medo permite feri-la. Percepção Tátil pela teia. Desovar Aranhas ao ficar machucada. NEX 40%+ imune à PP.",
    description: "Aranha exposta ao Lodo da Morte que cresce parasitando um humano vivo em seu abdômen. Quanto mais absorve, maior fica, gerando cópias menores de si mesma.",
  },
  {
    name: "Enraizado", element: "Morte", vd: "120", size: "Médio",
    pp: "20", sanLoss: "4d6", pv: 140, defense: 28, agi: 3, forc: 3, int: 1, pre: 1, vig: 3,
    displacement: "9m", resistances: "Corte, impacto e perfuração 10, Morte 20", vulnerabilities: "Energia",
    attacks: ["Punho Espinhento (corpo a corpo x2, +15): 2d8+8 impacto + 2d12 Morte", "Veneno Pútrido: envenenado, 4d12 Morte/turno (Fortitude DT 23)"],
    abilities: "Imortalidade: ao morrer vira poça de Lodo e volta em 1d2 rodadas com 70 PV; destruído por 20 de fogo/Energia na forma de poça. NEX 50%+ imune à PP.",
    description: "Cadáver enterrado perto de vegetação infestada pela Morte, invadido por raízes grossas que movem seus membros como um esqueleto de armadura vegetal.",
  },
  {
    name: "Escutado", element: "Morte", vd: "160", size: "Médio",
    pp: "25", sanLoss: "4d8", pv: 290, defense: 29, agi: 4, forc: 3, int: 1, pre: 2, vig: 3,
    displacement: "12m", resistances: "Imune a dano", vulnerabilities: "—",
    attacks: ["Mordida (corpo a corpo x2, +20): 3d6+10 perfuração", "Cabeça Arremessada (distância curto x2, +15): 1d10+10 impacto", "Vomitar Lodo: 4d10+10 Morte + lento (Reflexos DT 25)"],
    abilities: "Imune a dano; só ferível após ouvir a 'Spiralem Melodiam' por 4 rodadas (Enigma de Medo). Multiplicação Melódica: cria cópias com 145 PV enquanto a melodia toca. NEX 55%+ imune à PP.",
    description: "Corpo retorcido e magro de quem ouviu a Melodia Espiral proibida. Anda invertido e quadrúpede, com a cabeça destacável deixando rastro de Lodo. Atraído por toda melodia.",
  },
  {
    name: "Carniçal Preto da Morte", element: "Morte", vd: "200", size: "Médio",
    pp: "30", sanLoss: "6d6", pv: 400, defense: 38, agi: 4, forc: 4, int: 3, pre: 3, vig: 3,
    displacement: "12m", resistances: "Imune a balístico; corte, impacto e perfuração 10, Morte 20", vulnerabilities: "Energia",
    attacks: ["Garra da Morte (corpo a corpo x2, +25): 4d10+20 Morte", "Hipnose (Vontade DT 29): controla até 3 seres", "Reanimar Corpos (1x/cena): 2d4+2 esqueletos de Lodo"],
    abilities: "Físico Paranormal (salta o dobro). Instinto Mortal: machucado (≤200 PV) usa Hipnose grátis e ataque extra. Corpo Fechado: mirar na cabeça ignora a imunidade balística. NEX 65%+ imune à PP.",
    description: "Lodo entrelaçado a partir de um crânio apodrecido, com forma muscular humana exposta. Caminha com arrogância e domina mentes pelo símbolo hipnótico cravado na cabeça.",
  },
  {
    name: "Múmia Xipófaga", element: "Morte", vd: "240", size: "Médio",
    pp: "30", sanLoss: "6d8", pv: 400, defense: 35, agi: 5, forc: 4, int: 2, pre: 3, vig: 4,
    displacement: "9m", resistances: "Corte, impacto e perfuração 10, Morte 20", vulnerabilities: "Energia, fogo",
    attacks: ["Garra Enfaixada (corpo a corpo x2, +30): 4d8+30 corte", "Vomitar Lodo (distância curto x2, +25): 3d6+30 Morte + 3d8 mental", "Agarrada Mumificadora: 4d8+30 Morte/turno e cura a múmia"],
    abilities: "Faixas da Permanência: a 0 PV continua agindo até o fim do próximo turno. Amalgamar: a 0 PV funde-se a mortos, recupera 200 PV e ganha ataques extras. NEX 75%+ imune à PP.",
    description: "Mumificação egípcia em busca da imortalidade que deu errado. Devora a vida das vítimas e transforma reduzidos a 0 PV em esqueletos de Lodo.",
  },
  {
    name: "Marionete", element: "Morte", vd: "280", size: "Médio",
    pp: "35", sanLoss: "8d6", pv: 700, defense: 40, agi: 3, forc: 5, int: 1, pre: 5, vig: 2,
    displacement: "6m", resistances: "Corte, impacto e perfuração 20, Morte 20", vulnerabilities: "Energia",
    attacks: ["Foice Óssea (corpo a corpo x2, +30): 10d8+10 Morte", "Reflexos Guiados por Corda: ataque de foice ao ser que fica adjacente", "Ironia do Destino: agarra e divide o dano sofrido com a vítima"],
    abilities: "Momento Passivo: deslocamento não reduzível, ignora terreno difícil, imune a efeitos que dependam de tocar o chão. NEX 85%+ imune à PP.",
    description: "Esqueleto retorcido preenchido por Lodo, nascido da rejeição do luto e da tentativa de trazer alguém de volta dos mortos. Mostra traços familiares de quem se foi.",
  },
  {
    name: "Nidere", element: "Morte", vd: "320", size: "Grande",
    pp: "35", sanLoss: "8d6", pv: 800, defense: 50, agi: 5, forc: 5, int: 3, pre: 4, vig: 5,
    displacement: "24m", resistances: "Corte, impacto e perfuração 20, Morte 20", vulnerabilities: "Energia",
    attacks: ["Garra Invertida (corpo a corpo x2, +35): 4d10+40 Morte", "Mordida Invertida (corpo a corpo, +35): 4d12+40 Morte", "Rastrear e Abater: +6d6 contra desprevenidos"],
    abilities: "Caçador Veloz (sem penalidade de Furtividade). Regeneração Acelerada: Cura Acelerada 50. Senso de Direção Perfeito. Só derrotável encontrando seu covil (Enigma de Medo). NEX 95%+ imune à PP.",
    description: "'O lobo invertido' do folclore sul-americano. Lobo atroz desfigurado, predador alfa das criaturas paranormais, responsável por desaparecimentos de campistas. Sempre estará te caçando.",
  },
  {
    name: "Sempiternal", element: "Morte", vd: "360", size: "Médio",
    pp: "40", sanLoss: "8d8", pv: 990, defense: 53, agi: 5, forc: 5, int: 4, pre: 5, vig: 4,
    displacement: "12m", resistances: "Corte, impacto e perfuração 20 (Imune a dano e efeitos de Morte, lento e paralisia)", vulnerabilities: "Energia",
    attacks: ["Dedos Alongados (corpo a corpo x4, +40): 4d10 Morte + envelhecimento", "Correntes de Lodo: 20d6 Morte em alcance médio (Fortitude DT 40)"],
    abilities: "Toque Acelerador: envelhece a vítima 1d10 anos por golpe (40 anos = debilitado, 60 = morte). Manipula a percepção do tempo. NEX imune (PP DT 40).",
    description: "Resultado de gerações de uma civilização isolada exposta à Morte. Figura esquelética acinzentada de olhos pretos que fala uma língua invertida. Não come, não bebe, não dorme.",
  },
  {
    name: "Ceifador Espiral", element: "Morte", vd: "380", size: "Grande",
    pp: "45", sanLoss: "9d8", pv: 999, defense: 58, agi: 5, forc: 5, int: 5, pre: 5, vig: 5,
    displacement: "15m", resistances: "Dano 50 (Imune a efeitos e dano de Morte, paralisia e lento)", vulnerabilities: "Energia",
    attacks: ["Foice da Morte (corpo a corpo x2, +40): 5d10+20 Morte", "Contemplar a Espiral: 10d10+30 mental em alcance médio (Vontade DT 43)", "Cinzas das Terras Desoladas: 10d10+20 Morte em alcance longo (Fortitude DT 43)"],
    abilities: "Decepar: acerto crítico reduz alvo a 25 PV e -1 atributo permanente; ao matar, +50 PV temp e +1d10 de dano. Transporte pelo Pó. NEX imune (PP DT 45).",
    description: "O rosto da Morte, visto por quem teve experiências de quase morte. Onde se manifesta, tudo é levado: ninguém sobrevive, restando apenas desertos de cinzas com dunas espiraladas.",
  },
  {
    name: "O Deus da Morte", element: "Morte", vd: "400", size: "Grande",
    pp: "45", sanLoss: "10d8", pv: 2000, defense: 60, agi: 6, forc: 6, int: 5, pre: 5, vig: 7,
    displacement: "15m", resistances: "Corte, impacto e perfuração 20 (Imune a dano e efeitos de Morte, atordoamento e paralisia)", vulnerabilities: "Energia",
    attacks: ["Soco Espiral (corpo a corpo x2, +45): 5d10+50 Morte", "Espiral Destrutiva: 10d10+50 Morte em raio 12m (Fortitude DT 45)", "Espiral Descendente: envelhece o agarrado 3d20 anos"],
    abilities: "Ciclo Infinito: recupera 50 PV/turno; a 0 PV renasce no cadáver/maior NEX próximo. Senhor do Tempo: turno extra a cada rodada (1d20). Potência de Morte. Único capaz de resolver o Enigma do Diabo. PP DT 45.",
    description: "O Parasita de Dimensões, manifestação primordial da Morte. Consome a entropia e o tempo de vida. Viaja pelo tempo, podendo existir em várias formas e pontos da Realidade ao mesmo tempo.",
  },

  // ──────────────────────────── CONHECIMENTO ────────────────────────────
  {
    name: "Existido", element: "Conhecimento", vd: "20", size: "Médio",
    pp: "14", sanLoss: "1d6", pv: 36, defense: 13, agi: 1, forc: 1, int: 4, pre: 2, vig: 2,
    displacement: "9m", resistances: "Balístico, corte e impacto 5, Conhecimento 10", vulnerabilities: "Sangue",
    attacks: ["Pancada (corpo a corpo, +5): 1d4+1 impacto", "Brilho Enlouquecedor: 1d6 mental em alcance médio (Vontade DT 14)"],
    abilities: "Fortalecimento Paranormal: após causar dano mental, ganha bônus físico e +2d4 Conhecimento nas pancadas. NEX 25%+ imune à PP.",
    description: "Um humano que foi longe demais e entendeu o Outro Lado por completo. Hoje uma casca que repete o próprio nome para ser lembrada, coberta de frases que originaram Medo na história.",
  },
  {
    name: "Vulto", element: "Conhecimento", vd: "40", size: "Médio",
    pp: "15", sanLoss: "3d6", pv: 60, defense: 19, agi: 4, forc: 2, int: 2, pre: 2, vig: 1,
    displacement: "12m", resistances: "Balístico, corte e perfuração 5, Conhecimento 10", vulnerabilities: "Sangue",
    attacks: ["Toque Macabro (corpo a corpo x2, +10): 2d6 Conhecimento", "Plantar Paranoia: abalado/apavorado em alcance médio (Vontade DT 15)"],
    abilities: "Aura Tangível: +2d6 Conhecimento contra alvos sob condição de medo. NEX 30%+ imune à PP.",
    description: "Manifestação nascida do susto de uma possibilidade em ambientes com a Membrana danificada. Criatura humanoide de névoa sólida criada pela imaginação assustada de um observador.",
  },
  {
    name: "Parasita de Culpa", element: "Conhecimento", vd: "60", size: "Médio",
    pp: "20", sanLoss: "2d6", pv: 90, defense: 15, agi: 2, forc: 0, int: 4, pre: 4, vig: 1,
    displacement: "6m", resistances: "Imune a dano (exceto causado pelo hospedeiro)", vulnerabilities: "—",
    attacks: ["Pancada (corpo a corpo): 1d4 impacto", "Atormentar: 2d6 mental no sonho (Vontade DT 20)", "Cópias do Hospedeiro: até 4 cópias com 20 PV"],
    abilities: "Devorar Culpa: fixa-se em quem dorme e prende todos num sonho compartilhado. Só morto pelo hospedeiro confrontando a culpa dentro do sonho (Enigma de Medo). NEX 35%+ imune à PP.",
    description: "Criatura disforme que se alimenta da culpa de suas vítimas através de pesadelos e ilusões baseadas em traumas não resolvidos. Tende a se dissipar após se alimentar.",
  },
  {
    name: "Lembrado", element: "Conhecimento", vd: "100", size: "Médio",
    pp: "20", sanLoss: "4d6", pv: 180, defense: 22, agi: 2, forc: 2, int: 4, pre: 2, vig: 2,
    displacement: "9m", resistances: "Balístico, corte e impacto 10, Conhecimento 20", vulnerabilities: "Sangue",
    attacks: ["Pancada (corpo a corpo x2, +5): 2d4+7 impacto", "Expandir Aura: 6d6 mental em alcance curto (Vontade DT 20)"],
    abilities: "Aura Manifestada: faces gritantes impõem penalidade em todos os testes de quem se aproxima. NEX 45%+ imune à PP.",
    description: "Versão amplificada do existido, formada quando a barreira psicológica de alguém com alta exposição se quebra. Comete atrocidades apenas para jamais ser esquecido.",
  },
  {
    name: "Rastejador Sombrio", element: "Conhecimento", vd: "180", size: "Médio",
    pp: "25", sanLoss: "6d6", pv: 330, defense: 41, agi: 4, forc: 3, int: 3, pre: 3, vig: 3,
    displacement: "12m", resistances: "Balístico, corte e impacto 10, Conhecimento 20", vulnerabilities: "Sangue",
    attacks: ["Toque da Dor (corpo a corpo x3, +20): 4d8+5 Conhecimento", "Desespero: dano mental igual ao do toque (Vontade DT 25)", "Tentáculos das Sombras: agarra até 3 alvos, 4d6 mental/turno"],
    abilities: "Vulnerabilidade a Luz: sob luz forte perde -10 Defesa e habilidades de sombra. NEX 60%+ imune à PP.",
    description: "Entidade sádica que se esconde em sombras distorcidas. Humanoide de sobretudo e chapéu escondendo uma enorme boca acinzentada e tentáculos que rastejam pelo chão e paredes.",
  },
  {
    name: "Espreitador", element: "Conhecimento", vd: "220", size: "Médio",
    pp: "30", sanLoss: "7d6", pv: 500, defense: 34, agi: 4, forc: 2, int: 3, pre: 3, vig: 2,
    displacement: "12m", resistances: "Imune a dano", vulnerabilities: "Sangue",
    attacks: ["Pancada (corpo a corpo x2, +10): 1d6+2 impacto", "Espreitar (1x/cena): 10d6 mental em quem dorme (Vontade DT 30)", "Cópia Observada: copia quem enlouquece"],
    abilities: "Imune a dano; só ferível quando encurralado às 2h11 ao fechar seu esconderijo (Enigma de Medo). Corre pelas Frestas (teletransporte). NEX 70%+ imune à PP.",
    description: "Forma curvada e cinza coberta de dezenas de olhos amarelos que se multiplicam, com um grande olho na boca. Assombra um alvo, devorando sua sanidade ao impedir o sono.",
  },
  {
    name: "Ocioso", element: "Conhecimento", vd: "260", size: "Grande",
    pp: "35", sanLoss: "8d6", pv: 390, defense: 37, agi: 1, forc: 5, int: 1, pre: 5, vig: 3,
    displacement: "Voo 0m", resistances: "Balístico, corte e impacto 20, Conhecimento 20", vulnerabilities: "Sangue",
    attacks: ["Retaliação (reação): teletransporta e ataca quem o atacou, 4d10+20 impacto não letal", "Aterrorizar: 4d10+10 mental se adjacente"],
    abilities: "Sempre Presente: escolhe um alvo que é o único capaz de vê-lo (invisível aos demais). Permanecer Próximo (teletransporte no campo de visão). NEX 80%+ imune à PP.",
    description: "Manifestação que apenas observa, parada, em todo ambiente. Só o alvo a vê, como alucinação constante. Não ataca, mas reage se atacada, incapacitando sem matar — para observar até o fim.",
  },
  {
    name: "Bicho-Papão", element: "Conhecimento", vd: "300", size: "Grande",
    pp: "35", sanLoss: "7d8", pv: 750, defense: 41, agi: 5, forc: 4, int: 3, pre: 5, vig: 4,
    displacement: "15m", resistances: "Balístico, corte e impacto 20, Conhecimento 20", vulnerabilities: "Sangue",
    attacks: ["Garras Atormentadoras (corpo a corpo x3, +35): 4d10+10 Conhecimento", "Atormentar: 3d8 mental (Vontade DT 30)", "Saltar e Assustar: 10d8 mental se escondido (Vontade DT 35)"],
    abilities: "Tamanho Adaptável (se esconde em qualquer lugar). Tormento Infantil: distraído por cantigas, enfurecido por choro. Destruir Mente: +1d8 mental contra perturbados. NEX 90%+ imune à PP.",
    description: "Figura encapuzada e alongada como uma centopeia de membros humanoides, que rasteja por telhados e dutos. Implanta medos e paranoias durante o sono das crianças.",
  },
  {
    name: "Estrangeiro", element: "Conhecimento", vd: "340", size: "Grande",
    pp: "40", sanLoss: "10d6", pv: 750, defense: 50, agi: 3, forc: 5, int: 5, pre: 5, vig: 3,
    displacement: "Voo 15m", resistances: "Imune a dano", vulnerabilities: "Sangue",
    attacks: ["Toque Sutil (corpo a corpo x3, +35): 4d8+10 Conhecimento", "Rajada Psíquica (distância extremo x2, +35): 4d10+20 Conhecimento", "Comandar: domina mentes inferiores (Vontade DT 35)"],
    abilities: "Imune a dano até decifrar suas intenções (Enigma de Medo). Oblívio (faz esquecerem dele). Incubar: planta larva que eclode novo Estrangeiro ao zerar a SAN. NEX 99%+ imune à PP.",
    description: "Manifestação inteligentíssima de linguagem própria, ligada a abduções e sinais alienígenas. Faz dispositivos digitais exibirem sigilos. Parece estar em vários lugares ao mesmo tempo.",
  },
  {
    name: "Silhueta", element: "Conhecimento", vd: "360", size: "Médio",
    pp: "40", sanLoss: "8d8", pv: 500, defense: 55, agi: 4, forc: 4, int: 5, pre: 5, vig: 4,
    displacement: "12m", resistances: "Dano 30 (Imune a dano e efeitos de Conhecimento, paralisia, manobras)", vulnerabilities: "Sangue",
    attacks: ["Toque Devastador (até 2 alvos/objetos): dano da Aura Tangível", "Aura Tangível: 20d12 Conhecimento ao toque (Fortitude DT 42), desintegra a 0 PV"],
    abilities: "Conhecimento Verdadeiro: sabe tudo (+25 Int/Pre, +20 demais). Reescrever a Realidade: transforma objetos ao se mover. PP DT 40.",
    description: "A ausência consciente de si — alguém inexistido pelo Conhecimento que perdura pelo eco das memórias. Forma humanoide vazia cercada de sigilos que reescrevem a Realidade.",
  },
  {
    name: "Anjo", element: "Conhecimento", vd: "380", size: "Enorme",
    pp: "40", sanLoss: "10d6", pv: 1111, defense: 57, agi: 4, forc: 5, int: 5, pre: 5, vig: 5,
    displacement: "Voo 24m", resistances: "Dano 50 (Imune a dano e efeitos de Conhecimento, paralisia)", vulnerabilities: "Sangue",
    attacks: ["Asas do Conhecimento (corpo a corpo x2, +40): 4d10+40 Conhecimento", "Olhares do Saber (distância longo x2, +40): 6d8+20 Conhecimento", "Raio Dourado (1x/cena): 15d8+50 Conhecimento em linha"],
    abilities: "Julgamento: dano de Conhecimento causa metade em dano mental; SAN 0 = morte instantânea. Chamas Reveladoras (auréola). Enganável pela Justiça Perfeita (Enigma de Medo). PP DT 40.",
    description: "'O rosto da verdade impossível.' Criatura tão poderosa que desmantela a sanidade só de ser observada, derretendo os olhos em lágrimas douradas. Sem registros desde o século XIII.",
  },
  {
    name: "Máscara do Desespero", element: "Conhecimento", vd: "400", size: "Minúsculo (Relíquia)",
    pp: "45", sanLoss: "10d8", pv: 1200, defense: 55, agi: 4, forc: 4, int: 6, pre: 6, vig: 5,
    displacement: "Voo 12m", resistances: "Imune a dano e condições", vulnerabilities: "Sangue",
    attacks: ["Reescrever Realidade: 10d6 Conhecimento + 10d6 mental + condição (Vontade DT 45)", "Conjuração Verdadeira: 1 ritual de Conhecimento de qualquer círculo por turno (DT 45)"],
    abilities: "Onipresença: vai a qualquer sombra da Realidade e sabe tudo. Potência do Conhecimento. O portador vira a Magistrada, guardiã do Equilíbrio. Só neutralizável pelo Diabo ou abalando o Equilíbrio (Enigma de Medo). PP DT 45.",
    description: "A Relíquia do Conhecimento, indestrutível e antiquíssima. Contém toda a verdade do Outro Lado. Quem a usa tem o ego inexistido e se torna a Magistrada, que altera a Realidade à vontade.",
  },

  // ─────────────────────────────── ENERGIA ──────────────────────────────
  {
    name: "Anárquico", element: "Energia", vd: "20", size: "Médio",
    pp: "14", sanLoss: "2d6", pv: 30, defense: 21, agi: 3, forc: 2, int: 0, pre: 0, vig: 1,
    displacement: "9m", resistances: "Energia 5", vulnerabilities: "Conhecimento",
    attacks: ["Pancada Errática (corpo a corpo, +5): 2d12 impacto", "Luz Prismática: 2d8 Energia + atordoa", "Explosão: 2d6 Energia em alcance curto"],
    abilities: "Comportamento Errático: no início do turno rola 1d6 e age aleatoriamente (investe, projeta luz, explode, etc.). NEX 25%+ imune à PP.",
    description: "Corpo distorcido pela Energia, tomado por um fluxo caótico que o faz agir de modo imprevisível e aleatório a cada turno.",
  },
  {
    name: "Perturbado de Energia", element: "Energia", vd: "40", size: "Médio",
    pp: "15", sanLoss: "2d8", pv: 60, defense: 19, agi: 4, forc: 1, int: 0, pre: 0, vig: 0,
    displacement: "9m", resistances: "Balístico, corte e perfuração 5, Energia 10", vulnerabilities: "Conhecimento",
    attacks: ["Toque Plasmático (corpo a corpo x2, +10): 2d12 Energia", "Implantar Confusão: agarra e 2d8 mental + vulnerabilidade a Energia (Vontade DT 15)"],
    abilities: "NEX 30%+ imune à PP.",
    description: "Alma enlouquecida de forma brusca, virando uma forma plasmática inconsistente e desesperada que se agarra a consciências próximas para aliviar sua discórdia mental.",
  },
  {
    name: "Ciborgue", element: "Energia", vd: "80", size: "Grande",
    pp: "15", sanLoss: "2d6", pv: 160, defense: 25, agi: 3, forc: 3, int: 2, pre: 2, vig: 3,
    displacement: "9m", resistances: "Balístico, corte e perfuração 10, Energia 20 (Imune a paralisia)", vulnerabilities: "Conhecimento",
    attacks: ["Braço Laminado / Alpha (corpo a corpo x2, +10): 1d12+10 corte", "Punho Energizado / Beta: 2d8+10 impacto", "Canhão / Gama (distância longo): 4d12+5 Energia", "Raio Energético / Delta (distância médio): 1d12+5 Energia"],
    abilities: "Estado de Combate: assume Alpha/Beta/Gama/Delta a cada turno, cada um com uma fraqueza (Enigma de Medo). Regeneração Energética: +20 PV/turno. NEX 40%+ imune à PP.",
    description: "Cientista que amputou os próprios membros por mecanismos movidos a Energia paranormal. A dor o distorceu numa criatura de partes mecânicas e orgânicas que muda de comportamento.",
  },
  {
    name: "Anárquico Descontrolado", element: "Energia", vd: "120", size: "Médio",
    pp: "21", sanLoss: "4d6", pv: 120, defense: 28, agi: 4, forc: 3, int: 2, pre: 2, vig: 3,
    displacement: "12m", resistances: "Balístico, corte e perfuração 10, Energia 20", vulnerabilities: "Conhecimento",
    attacks: ["Pancada Energética (corpo a corpo x2, +15): 4d12 impacto", "Autodestruição: 8d12 Energia em alcance curto (Reflexos DT 25), morre ao usar"],
    abilities: "Aceleração: alvo da pancada sofre 4d12 Energia extra se gastar ações no turno seguinte. NEX 50%+ imune à PP.",
    description: "Versão hiperativa e translúcida do anárquico, originada de alguém de alta exposição. Vibra e flutua em euforia caótica e pode estourar o próprio corpo em explosão de Energia.",
  },
  {
    name: "Sukkalgir", element: "Energia", vd: "160", size: "Médio",
    pp: "25", sanLoss: "4d8", pv: 220, defense: 34, agi: 3, forc: 2, int: 3, pre: 3, vig: 2,
    displacement: "Voo 18m", resistances: "Imune a balístico, corte e perfuração; impacto e Energia 10", vulnerabilities: "Conhecimento",
    attacks: ["Mordida do Outro Lado (corpo a corpo x2, +15): 2d12 mental", "Grito de Desespero: 3d12 mental em alcance médio (Vontade DT 20)"],
    abilities: "Aura Desesperada: 2d12 mental a quem começa o turno em alcance curto. Espírito Plasmático (atravessa paredes). NEX 55%+ imune à PP.",
    description: "Alma torturada pelo fogo na antiga Suméria, com textos cravados a brasa na pele. Corpo de labareda de cores impossíveis e um sorriso rasgado que emite um grito enlouquecedor constante.",
  },
  {
    name: "Viajante", element: "Energia", vd: "200", size: "Médio",
    pp: "20", sanLoss: "6d6", pv: 360, defense: 34, agi: 4, forc: 2, int: 3, pre: 4, vig: 2,
    displacement: "9m (escalada 9m)", resistances: "Balístico, corte e perfuração 10, Energia 20", vulnerabilities: "Conhecimento",
    attacks: ["Pancada (corpo a corpo x2, +15): 2d12+10 impacto", "Devorar Memória: 4d12 mental e esquece uma pessoa (Vontade DT 29)"],
    abilities: "Invisibilidade Permanente: camuflagem total, +15 Furtividade; só visível ao ser fotografado (Enigma de Medo). NEX 60%+ imune à PP.",
    description: "O viajante das Polaroids. Corpo esbranquiçado de membros longos e cabeça de incontáveis rostos. Invisível, anda por paredes e tetos, devorando memórias e rostos das fotografias.",
  },
  {
    name: "Anomiático", element: "Energia", vd: "240", size: "Médio",
    pp: "30", sanLoss: "6d8", pv: 600, defense: 41, agi: 5, forc: 3, int: 1, pre: 4, vig: 3,
    displacement: "18m", resistances: "Balístico, corte e perfuração 10, Energia 20", vulnerabilities: "Conhecimento",
    attacks: ["Garra Desintegradora (corpo a corpo x2, +30): 4d12+20 Energia", "Explosão (adjacente): 10d12+20 Energia (Fortitude DT 30)"],
    abilities: "Comportamento Errático: 3 comportamentos aleatórios por turno (1d6). NEX 75%+ imune à PP.",
    description: "Corpo de altíssima exposição multiplicado em caos infinito. Vulto de luz que se teleporta desenfreadamente, rindo caoticamente enquanto se desintegra e ataca de forma aleatória.",
  },
  {
    name: "Infecticídio", element: "Energia", vd: "280", size: "Enorme",
    pp: "35", sanLoss: "8d6", pv: 600, defense: 25, agi: 3, forc: 5, int: 1, pre: 1, vig: 5,
    displacement: "9m", resistances: "Balístico, corte, perfuração e Energia 20", vulnerabilities: "Conhecimento",
    attacks: ["Pancadas Infectadas (corpo a corpo x3, +30): 4d12+20 Energia", "Infecção: doença viral (Fortitude DT 30)", "Atropelar: percorre o dobro atacando todos no caminho"],
    abilities: "Horda: metade do dano de efeitos de alvo único, dobro de efeitos de área; mesmo errando causa metade do dano. Consumação Insidiosa (+50 PV). NEX 85%+ imune à PP.",
    description: "Doença paranormal que nasce como vírus digital e infecta seres vivos, formando uma horda de mente compartilhada. Espalha-se por sangue, saliva e dispositivos eletrônicos.",
  },
  {
    name: "Telopsia", element: "Energia", vd: "340", size: "Médio",
    pp: "40", sanLoss: "10d6", pv: 560, defense: 48, agi: 4, forc: 2, int: 3, pre: 5, vig: 2,
    displacement: "12m", resistances: "Balístico, corte, perfuração e Energia 20 (Imune a paralisia)", vulnerabilities: "Conhecimento",
    attacks: ["Toque Desintegrador (corpo a corpo x3, +35): 6d12+30 Energia", "Tela Zumbificadora: 6d6 mental + confuso (Vontade DT 30)", "Prender na Tela: paralisa dentro da tela (Fortitude DT 30)"],
    abilities: "Viajar pela Tela (teletransporte entre telas). Só destruída com a fita VHS amaldiçoada (Enigma de Medo). NEX 99%+ imune à PP.",
    description: "Criatura da fita amaldiçoada 'telopsia'. Homem de sobretudo preto, corpo esquelético e cabeça de televisão antiga transmitindo imagens enlouquecedoras. Assiste e desintegra suas vítimas.",
  },
  {
    name: "Tempestuoso", element: "Energia", vd: "360", size: "Médio",
    pp: "40", sanLoss: "8d8", pv: 950, defense: 56, agi: 5, forc: 4, int: 2, pre: 5, vig: 4,
    displacement: "24m", resistances: "Balístico, corte, perfuração e Energia 20 (Imune a paralisia)", vulnerabilities: "Conhecimento",
    attacks: ["Garras Radioativas (corpo a corpo/curto x2, +40): 4d20+20 Energia", "Expandir em Radiação: 10d20+20 Energia em alcance longo (Reflexos DT 40), perde 100 PV"],
    abilities: "Aura Radioativa: 2d20+20 Energia a quem começa o turno em alcance curto. Espectro Radioativo (alcance estendido). PP DT 40.",
    description: "Tempestade do caos: nuvem de Energia como uma supernova implodindo em forma humanoide, contida por cabos metálicos. Emite radiação paranormal muito mais perigosa que a nuclear.",
  },
  {
    name: "Anomalia", element: "Energia", vd: "380", size: "Médio",
    pp: "45", sanLoss: "9d8", pv: 1000, defense: 0, agi: 0, forc: 0, int: 5, pre: 5, vig: 0,
    displacement: "0m", resistances: "Imune a dano e todas as condições", vulnerabilities: "Conhecimento",
    attacks: ["Romper Consciência: 10d6 mental no alvo (Vontade DT 41), absorve quem insana", "Manipular Ondas: sobrecarrega aparelhos, 2d12 Energia por objeto", "Manifestar o Impossível: invoca criaturas de Energia até 240 VD"],
    abilities: "Imaterial: imune a dano e condições, não faz testes. Existência Impossível: só existe dentro de objetos com porta aberta; só derrotável mergulhando nela (Enigma de Medo). PP DT 45.",
    description: "Manifestação do caos que a Realidade tenta esconder atrás da menor das possibilidades. Surge ao abrir uma porta errada e persegue quem a manifestou, levando à loucura. Indescritível.",
  },
  {
    name: "Anfitrião", element: "Energia", vd: "413", size: "Médio",
    pp: "45", sanLoss: "10d8", pv: 1413, defense: 59, agi: 7, forc: 5, int: 6, pre: 6, vig: 5,
    displacement: "12m", resistances: "Imune a dano e efeitos de Energia, paralisia", vulnerabilities: "Conhecimento",
    attacks: ["Corte Caótico / Liber (corpo a corpo, +45): 3d12+20 Energia", "Corte de Água / Silenus (+45): 5d12+20 Energia + asfixia", "Queimar / Aeneas: 10d6+20 Energia em cone", "Teatro / Amphitruo: 10d6 mental"],
    abilities: "Ato 1: divide-se em 5 facetas (250 PV cada). Ato 2: forma única, 3 ações padrão/turno, Trilha Sonora (2d10 mental) e Roleta Maluca. Potência de Energia. Só enfrentável sob proteção da Máscara do Desespero (Enigma de Medo). PP DT 45.",
    description: "A personificação do caos e da irracionalidade, capaz de transformar tudo que toca de forma incompreensível. Manifesta-se como cinco facetas teatrais antes de assumir sua forma única.",
  },

  // ──────────────────────────── MEDO / REALIDADE ────────────────────────
  {
    name: "Degolificada", element: "Realidade", vd: "320", size: "Médio",
    pp: "40", sanLoss: "9d6", pv: 850, defense: 45, agi: 3, forc: 5, int: 3, pre: 4, vig: 4,
    displacement: "6m", resistances: "Imune a dano (até resolver o Enigma de Medo). Reúne Energia, Conhecimento, Sangue e Morte", vulnerabilities: "Confronto com a origem",
    attacks: ["Pancada (corpo a corpo x2, +35): 8d8+20 impacto", "Grito Rasgado: 4d10+10 mental + surdez (Vontade DT 35)", "Desfiguramento Capilar: 10d6+20 perfuração + 6d10 mental no agarrado"],
    abilities: "Criatura de Medo: imune a dano até resolver o mistério da origem (confrontá-la com a causa da morte). Metamorfose: vira Conturbada (Energia), Gnóstica (Conhecimento), Devoradora (Sangue) ou Decrépita (Morte). NEX 95%+ imune à PP.",
    description: "Uma das criaturas mais temidas, formada por todos os elementos. Figura fantasmagórica de longos cabelos pretos cobrindo o rosto, cercada de neblina com almas torturadas. \"Se vir cabelos pretos flutuando... CORRA.\"",
  },

  // ──────────────────── AMEAÇAS DA REALIDADE (mundanas) ─────────────────
  {
    name: "Bandido", element: "Realidade", vd: "10", size: "Médio",
    pp: "—", sanLoss: "—", pv: 8, defense: 14, agi: 2, forc: 2, int: 1, pre: 1, vig: 1,
    displacement: "9m", resistances: "—", vulnerabilities: "—",
    attacks: ["Faca (corpo a corpo, +5): 1d4+2 perfuração"],
    abilities: "Ataque Furtivo: +1d6 contra alvos desprevenidos ou flanqueados.",
    description: "Um criminoso típico, como um ladrão ou assaltante.",
  },
  {
    name: "Capanga", element: "Realidade", vd: "20", size: "Médio",
    pp: "—", sanLoss: "—", pv: 17, defense: 13, agi: 1, forc: 2, int: 1, pre: 1, vig: 2,
    displacement: "9m", resistances: "—", vulnerabilities: "—",
    attacks: ["Bastão (corpo a corpo, +5): 1d8+7 impacto", "Revólver (distância curto, +5, crít 19/x3): 2d6+5 balístico"],
    abilities: "Ataque Furtivo: +2d6 contra alvos desprevenidos ou flanqueados.",
    description: "Pessoas embrutecidas que vivem pela violência — membros de gangue, executores da máfia, leões de chácara.",
  },
  {
    name: "Soldado de Aluguel", element: "Realidade", vd: "40", size: "Médio",
    pp: "—", sanLoss: "—", pv: 25, defense: 18, agi: 2, forc: 2, int: 1, pre: 1, vig: 2,
    displacement: "9m", resistances: "—", vulnerabilities: "—",
    attacks: ["Machete (corpo a corpo, +10, crít 19): 1d6+9 corte", "Fuzil de Assalto (distância médio, +10, crít 19/x3): 2d8+9 balístico"],
    abilities: "Ataque em Movimento: percorre o deslocamento e ataca em qualquer ponto.",
    description: "Um combatente profissional que trabalha para quem pagar mais.",
  },
  {
    name: "Assassino", element: "Realidade", vd: "80", size: "Médio",
    pp: "—", sanLoss: "—", pv: 90, defense: 26, agi: 4, forc: 2, int: 3, pre: 3, vig: 2,
    displacement: "9m", resistances: "—", vulnerabilities: "—",
    attacks: ["Faca (corpo a corpo x2, +17, crít 19): 1d4+11 corte", "Pistola (distância curto x2, +15, crít 16/x4): 1d12+14 balístico"],
    abilities: "Evasão (sem dano se passar no Reflexos). Ataque Furtivo +4d6. Assassinar: dobra os dados extras do primeiro furtivo contra o alvo analisado.",
    description: "Matador habilidoso e furtivo, chamado quando alguém precisa ser eliminado de forma discreta e eficiente.",
  },
  {
    name: "Comandante Mercenário", element: "Realidade", vd: "120", size: "Médio",
    pp: "—", sanLoss: "—", pv: 145, defense: 29, agi: 3, forc: 3, int: 2, pre: 2, vig: 3,
    displacement: "6m", resistances: "Balístico, corte, impacto e perfuração 5", vulnerabilities: "—",
    attacks: ["Machete (corpo a corpo x2, +17, crít 19): 1d6+15 corte", "Metralhadora (distância médio x2, +17, crít 19/x3): 3d12+15 balístico"],
    abilities: "Sadismo (+dado de dano após ferir). Ordens: alia bônus aos aliados em alcance médio.",
    description: "Homem ou mulher endurecido por anos de conflito — oficial competente e combatente perigoso por si só.",
  },
  {
    name: "Iniciado (Cultista)", element: "Realidade", vd: "20", size: "Médio",
    pp: "—", sanLoss: "—", pv: 15, defense: 16, agi: 1, forc: 1, int: 2, pre: 2, vig: 1,
    displacement: "9m", resistances: "—", vulnerabilities: "—",
    attacks: ["Faca (corpo a corpo, crít 19): 1d4+1 corte"],
    abilities: "Conjurador: dois rituais de 1º círculo sem custo (até 3 PE), DT 15.",
    description: "Cultista iniciante no caminho da adoração às entidades, mas já capaz de conjurar rituais.",
  },
  {
    name: "Investido (Cultista)", element: "Realidade", vd: "40", size: "Médio",
    pp: "—", sanLoss: "—", pv: 35, defense: 17, agi: 2, forc: 1, int: 2, pre: 2, vig: 1,
    displacement: "9m", resistances: "—", vulnerabilities: "—",
    attacks: ["Faca (corpo a corpo, +5, crít 19): 1d4+1 corte", "Revólver (distância curto, crít 19/x3): 2d6 balístico"],
    abilities: "Conjurador: dois rituais de 1º e dois de 2º círculo sem custo (até 5 PE), DT 17.",
    description: "Cultista que cumpriu os ritos de admissão e provou lealdade ao seu Elemento.",
  },
  {
    name: "Líder de Culto", element: "Realidade", vd: "140", size: "Médio",
    pp: "—", sanLoss: "—", pv: 150, defense: 27, agi: 2, forc: 1, int: 3, pre: 3, vig: 2,
    displacement: "9m", resistances: "—", vulnerabilities: "—",
    attacks: ["Faca (corpo a corpo, +10, crít 19): 1d4+1 corte", "Revólver (distância curto, +5, crít 19/x3): 2d6 balístico"],
    abilities: "Conjurador: dois rituais de 1º, 2º e 3º círculo sem custo (até 10 PE), DT 25.",
    description: "Cultista experiente, mestre que mantém disfarce de bom cidadão — pode ser qualquer um, até alguém próximo dos agentes.",
  },
  {
    name: "Policial", element: "Realidade", vd: "20", size: "Médio",
    pp: "—", sanLoss: "—", pv: 15, defense: 19, agi: 2, forc: 2, int: 1, pre: 1, vig: 2,
    displacement: "9m", resistances: "—", vulnerabilities: "—",
    attacks: ["Bastão (corpo a corpo, +5): 1d8+7 impacto", "Pistola (distância curto, +5, crít 18): 1d12+5 balístico"],
    abilities: "Serve também para vigias, seguranças e pessoas com treinamento básico em armas.",
    description: "O policial padrão, patrulhando as ruas. Provavelmente nunca teve um encontro com o paranormal.",
  },
  {
    name: "Policial de Elite", element: "Realidade", vd: "60", size: "Médio",
    pp: "—", sanLoss: "—", pv: 40, defense: 27, agi: 3, forc: 3, int: 1, pre: 1, vig: 3,
    displacement: "6m", resistances: "Balístico, corte, impacto e perfuração 5", vulnerabilities: "—",
    attacks: ["Bastão (corpo a corpo x2, +10): 1d8+13 impacto", "Fuzil de Assalto (distância médio, +10, crít 17/x3): 2d8+13 balístico", "Lança-Granadas (1x/cena): 8d6 impacto em raio 6m"],
    abilities: "Fortificação: 50% de chance de ignorar dano extra de crítico/furtivo.",
    description: "Treinados e equipados para situações extremas — os primeiros a aparecer quando a investigação vira confronto armado.",
  },
  {
    name: "Chefe de Polícia", element: "Realidade", vd: "100", size: "Médio",
    pp: "—", sanLoss: "—", pv: 105, defense: 25, agi: 2, forc: 3, int: 2, pre: 3, vig: 3,
    displacement: "9m", resistances: "—", vulnerabilities: "—",
    attacks: ["Bastão (corpo a corpo x2, +15): 1d8+8 impacto", "Espingarda (distância curto x2, +17, crít x3): 4d6+12 balístico"],
    abilities: "Teimoso (1x/cena): ignora um efeito com teste de resistência ou reduz um dano à metade.",
    description: "Um delegado ou coronel que já passou por situações difíceis e não se intimida facilmente.",
  },
  {
    name: "Cão de Guarda", element: "Realidade", vd: "10", size: "Médio",
    pp: "—", sanLoss: "—", pv: 12, defense: 14, agi: 2, forc: 2, int: 0, pre: 1, vig: 2,
    displacement: "12m", resistances: "—", vulnerabilities: "—",
    attacks: ["Mordida (corpo a corpo, +5): 1d6+2 corte"],
    abilities: "Derrubar ao acertar mordida. Faro e visão na penumbra. Serve para cães policiais ou lobos.",
    description: "Cães treinados para guarda, capazes de causar problemas a um grupo que precisa ser furtivo.",
  },
  {
    name: "Enxame de Abelhas", element: "Realidade", vd: "10", size: "Médio",
    pp: "—", sanLoss: "—", pv: 10, defense: 15, agi: 1, forc: 0, int: 0, pre: 1, vig: 0,
    displacement: "3m (voo 9m)", resistances: "Metade do dano de armas; +50% de efeitos de área", vulnerabilities: "Efeitos de área",
    attacks: ["Enxame: 2d6 perfuração automático a quem estiver no espaço"],
    abilities: "Zumbido Nauseante: dano deixa enjoado 1 rodada (Fortitude DT 15). Imune a manobras e efeitos de alvo único.",
    description: "Abelhas que se tornam agressivas se a colmeia for ameaçada, em zonas rurais, parques ou casas abandonadas.",
  },
  {
    name: "Enxame de Ratos", element: "Realidade", vd: "10", size: "Médio",
    pp: "—", sanLoss: "—", pv: 15, defense: 13, agi: 1, forc: 0, int: 0, pre: 1, vig: 1,
    displacement: "9m (escalar/nadar 6m)", resistances: "Metade do dano de armas; +50% de efeitos de área", vulnerabilities: "Efeitos de área",
    attacks: ["Enxame: 2d6 perfuração automático a quem estiver no espaço"],
    abilities: "Doença: dano transmite febre hemorrágica (Fortitude DT 15). Imune a manobras e efeitos de alvo único.",
    description: "Ratos que se unem em enxames perigosos quando movidos por fome intensa ou energias paranormais.",
  },
  {
    name: "Javaporco", element: "Realidade", vd: "20", size: "Médio",
    pp: "—", sanLoss: "—", pv: 35, defense: 14, agi: 1, forc: 2, int: 0, pre: 1, vig: 3,
    displacement: "12m", resistances: "—", vulnerabilities: "—",
    attacks: ["Mordida (corpo a corpo, +5): 1d8+4 corte", "Mordida Final: ataca um alvo aleatório ao chegar a 0 PV"],
    abilities: "Ferocidade: ao sofrer dano, +dado de dano até o fim da cena.",
    description: "Cruzamento de javali com porco doméstico, praga voraz e agressiva de regiões rurais.",
  },
  {
    name: "Jacaré", element: "Realidade", vd: "40", size: "Grande",
    pp: "—", sanLoss: "—", pv: 40, defense: 16, agi: 1, forc: 3, int: 0, pre: 1, vig: 2,
    displacement: "6m (nadar 9m)", resistances: "—", vulnerabilities: "—",
    attacks: ["Mordida (corpo a corpo, +5): 1d8+8 corte", "Cauda (corpo a corpo, +5): 1d12 impacto"],
    abilities: "Agarrão ao acertar mordida. Giro da Morte: +2d8 ao agarrar dentro d'água.",
    description: "Espécime grande de jacaré, perigoso para agentes, encontrado até em áreas urbanas.",
  },
  {
    name: "Onça-Pintada", element: "Realidade", vd: "40", size: "Grande",
    pp: "—", sanLoss: "—", pv: 55, defense: 16, agi: 3, forc: 3, int: 0, pre: 1, vig: 2,
    displacement: "12m (escalar/nadar 6m)", resistances: "—", vulnerabilities: "—",
    attacks: ["Mordida (corpo a corpo, +10): 1d8+5 corte", "Garras (corpo a corpo x2, +10, crít 19): 1d6+5 corte", "Bote: investida com mordida e garras no mesmo alvo"],
    abilities: "Agarrão ao acertar mordida. Furtividade alta.",
    description: "O maior felino das Américas, principal predador das selvas brasileiras e oponente mortal em seu território.",
  },
  {
    name: "Sucuri", element: "Realidade", vd: "40", size: "Grande",
    pp: "—", sanLoss: "—", pv: 68, defense: 16, agi: 2, forc: 3, int: 0, pre: 1, vig: 3,
    displacement: "6m (escalar/nadar 9m)", resistances: "—", vulnerabilities: "—",
    attacks: ["Mordida (corpo a corpo, +10): 1d6+8 corte", "Constrição: 2d6+8 impacto/turno em quem estiver agarrado"],
    abilities: "Agarrão ao acertar mordida.",
    description: "Grande cobra constritora das selvas amazônicas, por vezes mascote perigoso de cultistas excêntricos.",
  },
];
