// ─── ORDEM PARANORMAL RPG — Rituais ──────────────────────────────────────────
// Fonte: Livro de Regras v1.3, Capítulo 5: O Outro Lado
// Custo base: 1º=1PE, 2º=3PE, 3º=6PE, 4º=10PE

import type { Element } from "./data";

export type RitualCircle = 1 | 2 | 3 | 4;
export type RitualExecution = "reação" | "livre" | "padrão" | "completa" | "1 minuto" | "10 minutos" | "1 hora";
export type RitualRange = "pessoal" | "toque" | "curto" | "médio" | "longo" | "extremo" | "ilimitado";

export interface Ritual {
  id: string;
  name: string;
  element: Element;
  circle: RitualCircle;
  execution: RitualExecution;
  range: RitualRange;
  duration: string;
  target?: string;
  area?: string;
  resistance?: string;
  description: string;
  upgrade?: string;
  trueForm?: string;
}

// Custo em PE base por círculo
export const RITUAL_COST: Record<RitualCircle, number> = {
  1: 1,
  2: 3,
  3: 6,
  4: 10,
};

// ─── TODOS OS RITUAIS ─────────────────────────────────────────────────────────

export const RITUALS: Ritual[] = [

  // ════════════════════════════════════════════════════════════════════════════
  // 1º CÍRCULO
  // ════════════════════════════════════════════════════════════════════════════

  // CONHECIMENTO
  {
    id: "amaldicaoar_arma_con",
    name: "Amaldiçoar Arma",
    element: "conhecimento",
    circle: 1,
    execution: "padrão",
    range: "toque",
    target: "1 arma corpo a corpo ou pacote de munição",
    duration: "cena",
    description: "Ao aprender, escolha um elemento entre Conhecimento, Energia, Morte e Sangue — o ritual passa a ser desse elemento. Imbui a arma/munições, fazendo-as causar +1d6 de dano do elemento escolhido.",
    upgrade: "Discente (+2 PE): dano +2d6. Requer 2º círculo.",
    trueForm: "Verdadeiro (+5 PE): dano +4d6. Requer 3º círculo e afinidade.",
  },
  {
    id: "compreensao_paranormal",
    name: "Compreensão Paranormal",
    element: "conhecimento",
    circle: 1,
    execution: "padrão",
    range: "toque",
    target: "1 ser ou objeto",
    duration: "cena",
    resistance: "Vontade anula (alvo involuntário)",
    description: "Entenda qualquer linguagem escrita humana tocando o objeto. Tocando uma pessoa, comunique-se como se falassem o mesmo idioma. Tocando animal, perceba sentimentos básicos.",
    upgrade: "Discente (+2 PE): alcance curto, alvos à escolha. Requer 2º círculo.",
    trueForm: "Verdadeiro (+5 PE): pessoal, você entende e escreve qualquer idioma humano. Requer 3º círculo.",
  },
  {
    id: "enfeiticar",
    name: "Enfeitiçar",
    element: "conhecimento",
    circle: 1,
    execution: "padrão",
    range: "curto",
    target: "1 pessoa",
    duration: "cena",
    resistance: "Vontade parcial",
    description: "O alvo fica fascinado por você, tratando-o com amizade e confiança. Não obedece ordens perigosas. Se falhar no teste de Vontade, fica fascinado. Se passar, fica indiferente.",
    upgrade: "Discente (+2 PE): alcance médio, até 3 pessoas. Requer 2º círculo.",
  },
  {
    id: "perturbacao",
    name: "Perturbação",
    element: "conhecimento",
    circle: 1,
    execution: "padrão",
    range: "curto",
    target: "1 pessoa",
    duration: "instantânea",
    resistance: "Vontade anula",
    description: "Você força o alvo a obedecer a uma ordem simples, de uma palavra, como 'corra', 'pare' ou 'durma'. A ordem não pode causar dano ao alvo.",
    upgrade: "Discente (+3 PE): a ordem pode ter até uma frase completa. Requer 2º círculo.",
    trueForm: "Verdadeiro (+5 PE): a ordem pode ser complexa e durar até 1 hora. Requer 3º círculo.",
  },
  {
    id: "ouvir_sussurros",
    name: "Ouvir os Sussurros",
    element: "conhecimento",
    circle: 1,
    execution: "completa",
    range: "pessoal",
    target: "você",
    duration: "instantânea",
    description: "Você comunica-se com vozes do Outro Lado para receber informações. Faça uma pergunta ao mestre; ele responde com uma pista útil, podendo ser vaga. Limite: uma vez por cena.",
    upgrade: "Discente (+2 PE): até duas perguntas. Requer 2º círculo.",
  },
  {
    id: "tecer_ilusao",
    name: "Tecer Ilusão",
    element: "conhecimento",
    circle: 1,
    execution: "padrão",
    range: "curto",
    area: "cubo 3m",
    duration: "cena",
    description: "Cria ilusão visual ou sonora. A ilusão não causa dano e não pode mover objetos. Seres que interagirem com ela têm direito a teste de Ocultismo (DT do ritual) para discerni-la.",
    upgrade: "Discente (+3 PE): ilusão combina visual e sonora e pode se mover. Requer 2º círculo.",
    trueForm: "Verdadeiro (+5 PE): ilusão também inclui cheiro e temperatura, e pode ter efeitos mecânicos simples. Requer 3º círculo.",
  },
  {
    id: "terceiro_olho",
    name: "Terceiro Olho",
    element: "conhecimento",
    circle: 1,
    execution: "padrão",
    range: "pessoal",
    target: "você",
    duration: "cena",
    description: "Você vê manifestações paranormais, criaturas do Outro Lado (mesmo incorpóreas) e itens amaldiçoados, mesmo que estejam ocultos ou invisíveis. Recebe +5 em Ocultismo.",
    upgrade: "Discente (+2 PE): também detecta portais e locais de alta atividade paranormal. Requer 2º círculo.",
  },

  // ENERGIA
  {
    id: "amaldicooar_tecnologia",
    name: "Amaldiçoar Tecnologia",
    element: "energia",
    circle: 1,
    execution: "padrão",
    range: "toque",
    target: "1 acessório ou arma de fogo",
    duration: "cena",
    description: "Imbui o item com Energia, fazendo-o funcionar acima da capacidade. Recebe uma modificação à sua escolha.",
    upgrade: "Discente (+2 PE): duas modificações. Requer 2º círculo.",
    trueForm: "Verdadeiro (+5 PE): três modificações. Requer 3º círculo e afinidade.",
  },
  {
    id: "coincidencia_forcada",
    name: "Coincidência Forçada",
    element: "energia",
    circle: 1,
    execution: "padrão",
    range: "curto",
    target: "1 ser",
    duration: "cena",
    description: "Manipula os caminhos do caos para que o alvo tenha mais sorte. O alvo recebe +2 em testes de perícias.",
    upgrade: "Discente (+2 PE): alvos à escolha. Requer 2º círculo.",
    trueForm: "Verdadeiro (+5 PE): alvos à escolha com bônus +5. Requer 3º círculo e afinidade.",
  },
  {
    id: "eletrocussao",
    name: "Eletrocussão",
    element: "energia",
    circle: 1,
    execution: "padrão",
    range: "curto",
    target: "1 ser",
    duration: "instantânea",
    resistance: "Reflexos reduz à metade",
    description: "Uma corrente voltaica atinge o alvo, causando 2d6 pontos de dano de Energia. Se falhar no teste, fica atordoado por 1 rodada.",
    upgrade: "Discente (+2 PE): dano aumenta para 4d6. Requer 2º círculo.",
    trueForm: "Verdadeiro (+5 PE): dano 8d6, área esfera 3m. Requer 3º círculo e afinidade.",
  },
  {
    id: "embaralhar",
    name: "Embaralhar",
    element: "energia",
    circle: 1,
    execution: "padrão",
    range: "pessoal",
    target: "você",
    duration: "cena",
    description: "Cria duplicatas caóticas de você mesmo. Você recebe +5 em Defesa. Quando sofrer um ataque, role 1d4: em 1, a imagem selecionada era você; em 2-4, era uma duplicata (o ataque erra). Começa com 3 duplicatas.",
    upgrade: "Discente (+2 PE): começa com 5 duplicatas e bônus +10 em Defesa. Requer 2º círculo.",
  },
  {
    id: "luz",
    name: "Luz",
    element: "energia",
    circle: 1,
    execution: "livre",
    range: "toque",
    target: "1 objeto",
    duration: "cena",
    description: "O objeto brilha com a intensidade de uma lâmpada elétrica, iluminando área de 9m de raio. Pode ser deslumbrador se apontado diretamente nos olhos (Reflexos DT ritual ou fica ofuscado por 1 rodada).",
    upgrade: "Discente (+1 PE): o objeto emite luz de 18m de raio. Requer 2º círculo.",
  },
  {
    id: "polarizacao_caotica",
    name: "Polarização Caótica",
    element: "energia",
    circle: 1,
    execution: "padrão",
    range: "curto",
    target: "objetos metálicos",
    duration: "cena",
    description: "Objetos metálicos em alcance curto são atraídos ou repelidos conforme sua vontade. Pode desarmar (Força vs. DT) ou empurrar portadores metálicos.",
    upgrade: "Discente (+2 PE): alcance médio, até 3 objetos simultaneamente. Requer 2º círculo.",
  },

  // MORTE
  {
    id: "cicatrizacao",
    name: "Cicatrização",
    element: "morte",
    circle: 1,
    execution: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "instantânea",
    description: "Acelera o tempo ao redor das feridas do alvo. Recupera 3d8+3 PV, mas o alvo envelhece 1 ano automaticamente.",
    upgrade: "Discente (+2 PE): cura 5d8+5 PV. Requer 2º círculo.",
    trueForm: "Verdadeiro (+9 PE): alcance curto, alvos escolhidos, cura 7d8+7 PV. Requer 4º círculo e afinidade.",
  },
  {
    id: "consumir_manancial",
    name: "Consumir Manancial",
    element: "morte",
    circle: 1,
    execution: "padrão",
    range: "pessoal",
    target: "você",
    duration: "instantânea",
    description: "Suga porção do tempo de vida de plantas, insetos e solo próximos. Você recebe 3d6 PV temporários (desaparecem no fim da cena).",
    upgrade: "Discente (+2 PE): 6d6 PV temporários. Requer 2º círculo.",
    trueForm: "Verdadeiro (+5 PE): esfera 6m de raio — 3d6 dano de Morte em seres vivos na área; você ganha PV temporários iguais ao dano causado. Requer 3º círculo e afinidade.",
  },
  {
    id: "decadencia",
    name: "Decadência",
    element: "morte",
    circle: 1,
    execution: "padrão",
    range: "curto",
    target: "1 ser vivo",
    duration: "instantânea",
    resistance: "Fortitude parcial",
    description: "Acelera o envelhecimento dos órgãos internos. Se falhar, o alvo sofre 2d6 dano de Morte e fica fatigado. Se passar, sofre metade do dano.",
    upgrade: "Discente (+3 PE): dano 4d6. Requer 2º círculo.",
  },
  {
    id: "definhar",
    name: "Definhar",
    element: "morte",
    circle: 1,
    execution: "padrão",
    range: "curto",
    target: "1 ser",
    duration: "cena",
    resistance: "Fortitude parcial",
    description: "O alvo fica vulnerável (–2 em Defesa) e fatigado. Se passar no teste de resistência, apenas fica vulnerável.",
    upgrade: "Discente (+2 PE): o alvo fica exausto se falhar. Requer 2º círculo.",
  },
  {
    id: "espirais_perdicao",
    name: "Espirais da Perdição",
    element: "morte",
    circle: 1,
    execution: "padrão",
    range: "curto",
    area: "esfera 6m de raio",
    duration: "cena",
    description: "Espirais de Morte surgem ao redor dos inimigos na área. Inimigos sofrem –5 em testes de ataque enquanto estiverem na área.",
    upgrade: "Discente (+2 PE): penalidade –10. Requer 2º círculo.",
  },
  {
    id: "nuvem_cinzas",
    name: "Nuvem de Cinzas",
    element: "morte",
    circle: 1,
    execution: "padrão",
    range: "curto",
    area: "nuvem esfera 6m de raio",
    duration: "cena",
    description: "Uma nuvem de cinzas preenche a área. Seres dentro dela têm camuflagem (50% de chance de errar ataques).",
    upgrade: "Discente (+2 PE): a nuvem bloqueia visão completamente (cegueira para quem estiver dentro). Requer 2º círculo.",
  },

  // SANGUE
  {
    id: "arma_atroz",
    name: "Arma Atroz",
    element: "sangue",
    circle: 1,
    execution: "padrão",
    range: "toque",
    target: "1 arma corpo a corpo",
    duration: "sustentada",
    description: "A arma é recoberta por veias carmesim. Fornece +2 em testes de ataque e +1 na margem de ameaça.",
    upgrade: "Discente (+2 PE): +5 em testes de ataque. Requer 2º círculo.",
    trueForm: "Verdadeiro (+5 PE): +5 em ataque, +2 na margem de ameaça e multiplicador de crítico. Requer 3º círculo e afinidade.",
  },
  {
    id: "armadura_sangue",
    name: "Armadura de Sangue",
    element: "sangue",
    circle: 1,
    execution: "padrão",
    range: "pessoal",
    target: "você",
    duration: "cena",
    description: "Seu sangue cobre o corpo sob forma de carapaça: +5 em Defesa (cumulativo com rituais, mas não com equipamento).",
    upgrade: "Discente (+5 PE): +10 em Defesa e RD 5 contra balístico, corte, impacto e perfuração. Requer 3º círculo.",
    trueForm: "Verdadeiro (+9 PE): +15 em Defesa e RD 10 contra os mesmos tipos. Requer 4º círculo e afinidade.",
  },
  {
    id: "corpo_adaptado",
    name: "Corpo Adaptado",
    element: "sangue",
    circle: 1,
    execution: "padrão",
    range: "pessoal",
    target: "você",
    duration: "cena",
    description: "Seu corpo se adapta ao ambiente. Você ignora penalidades de frio e calor extremos e pode respirar debaixo d'água.",
    upgrade: "Discente (+2 PE): toque, um aliado. Requer 2º círculo.",
  },
  {
    id: "distorcer_aparencia",
    name: "Distorcer Aparência",
    element: "sangue",
    circle: 1,
    execution: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "cena",
    description: "Altera a aparência física do alvo, mudando cor de cabelo, formato do rosto, voz e biometria. Pode disfarçar o alvo como outra pessoa específica (mas exige conhecer a pessoa).",
    upgrade: "Discente (+2 PE): alcance curto, até 3 alvos. Requer 2º círculo.",
    trueForm: "Verdadeiro (+5 PE): o alvo se torna completamente idêntico a uma pessoa conhecida. Requer 3º círculo.",
  },
  {
    id: "fortalecimento_sensorial",
    name: "Fortalecimento Sensorial",
    element: "sangue",
    circle: 1,
    execution: "padrão",
    range: "pessoal",
    target: "você",
    duration: "cena",
    description: "Seus sentidos são amplificados pelo Sangue. Você recebe +5 em Percepção e pode ouvir/cheirar seres a até 18m mesmo sem visão.",
    upgrade: "Discente (+2 PE): toque, um aliado. Requer 2º círculo.",
  },
  {
    id: "odio_incontrolavel",
    name: "Ódio Incontrolável",
    element: "sangue",
    circle: 1,
    execution: "padrão",
    range: "pessoal",
    target: "você",
    duration: "cena",
    description: "O Sangue exalta sua agressividade. +5 em testes de Luta, Atletismo e Fortitude; –5 em testes de Ocultismo, Medicina, Investigação e Tecnologia. Dano corpo a corpo +1d6.",
    upgrade: "Discente (+3 PE): bônus e penalidades aumentam para +10/–10. Requer 3º círculo.",
  },

  // MEDO
  {
    id: "cineraria",
    name: "Cinerária",
    element: "medo",
    circle: 1,
    execution: "padrão",
    range: "curto",
    area: "nuvem esfera 6m de raio",
    duration: "cena",
    description: "Uma névoa carregada de essência paranormal cobre a área. Rituais conjurados dentro da névoa têm DT aumentada em +5.",
    upgrade: "Discente (+2 PE): rituais dentro da névoa também custam –2 PE.",
    trueForm: "Verdadeiro (+5 PE): rituais dentro da névoa causam dano maximizado.",
  },

  // ════════════════════════════════════════════════════════════════════════════
  // 2º CÍRCULO
  // ════════════════════════════════════════════════════════════════════════════

  // CONHECIMENTO
  {
    id: "aprimorar_mente",
    name: "Aprimorar Mente",
    element: "conhecimento",
    circle: 2,
    execution: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "cena",
    description: "A mente do alvo é energizada por Conhecimento. Recebe +1 em Intelecto ou Presença (não fornece PE ou perícias extras).",
    upgrade: "Discente (+3 PE): bônus +2. Requer 3º círculo.",
    trueForm: "Verdadeiro (+7 PE): bônus +3. Requer 4º círculo e afinidade.",
  },
  {
    id: "deteccao_ameacas",
    name: "Detecção de Ameaças",
    element: "conhecimento",
    circle: 2,
    execution: "padrão",
    range: "pessoal",
    area: "esfera 18m de raio",
    duration: "cena",
    description: "Você detecta personagens hostis e armadilhas na área. Você sabe a posição aproximada de cada ameaça, mas não os detalhes.",
    upgrade: "Discente (+3 PE): detalhes completos sobre as ameaças detectadas. Requer 3º círculo.",
  },
  {
    id: "esconder_olhos",
    name: "Esconder dos Olhos",
    element: "conhecimento",
    circle: 2,
    execution: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "cena",
    description: "O alvo fica invisível aos olhos comuns. Seres com Terceiro Olho podem vê-lo. O alvo perde a invisibilidade se atacar ou realizar ação chamativa.",
    upgrade: "Discente (+3 PE): o alvo pode atacar sem perder a invisibilidade por 1 rodada/cena. Requer 3º círculo.",
    trueForm: "Verdadeiro (+6 PE): o alvo permanece invisível mesmo ao atacar durante toda a cena. Requer 4º círculo.",
  },
  {
    id: "invadir_mente",
    name: "Invadir Mente",
    element: "conhecimento",
    circle: 2,
    execution: "padrão",
    range: "curto",
    target: "1 pessoa",
    duration: "instantânea",
    resistance: "Vontade parcial",
    description: "Escolha: (a) Rajada mental — 5d6 dano mental (Vontade reduz à metade); ou (b) Ligação telepática — comunique-se telepaticamente com o alvo enquanto ambos estiverem em alcance médio (Vontade anula).",
    upgrade: "Discente: rajada mental 10d6; ou ligação pode ser sustentada por 1 hora. Requer 3º círculo.",
    trueForm: "Verdadeiro (+10 PE): rajada mental 15d6 em área esfera 6m. Requer 4º círculo e afinidade.",
  },
  {
    id: "localizacao",
    name: "Localização",
    element: "conhecimento",
    circle: 2,
    execution: "padrão",
    range: "pessoal",
    target: "você",
    duration: "cena",
    description: "Você determina a direção e distância aproximada de um objeto ou ser que conheça, no mesmo plano que você. Não funciona se o alvo estiver com proteção paranormal.",
    upgrade: "Discente (+3 PE): também sabe o estado geral do alvo (ferido, com medo, morto). Requer 3º círculo.",
  },

  // ENERGIA
  {
    id: "chamas_caos",
    name: "Chamas do Caos",
    element: "energia",
    circle: 2,
    execution: "padrão",
    range: "curto",
    target: "veja texto",
    duration: "cena",
    description: "Manipula calor e fogo. Escolha: Chamejar (arma +1d6 fogo), Esquentar (objeto 1d6/rodada fogo), Extinguir (chama tamanho G ou menor → nuvem fumaça 3m camuflagem), Modelar (mova chama 9m/turno; atravessa ser = 3d6 fogo).",
    upgrade: "Discente (+3 PE): sustentada; projete labareda 4d6 dano Energia (Reflexos reduz). Requer 3º círculo.",
    trueForm: "Verdadeiro (+7 PE): como discente, dano 8d6. Requer 3º círculo.",
  },
  {
    id: "contencao_fantasmagorica",
    name: "Contenção Fantasmagórica",
    element: "energia",
    circle: 2,
    execution: "padrão",
    range: "médio",
    target: "1 ser",
    duration: "cena",
    resistance: "Reflexos anula",
    description: "Três laços de Energia prendem o alvo (agarrado). O alvo pode gastar ação padrão para tentar Atletismo (DT ritual) e destruir laços. Cada laço tem Defesa 10, 10 PV, RD 5, imunidade a Energia.",
    upgrade: "Discente (+3 PE): 6 laços, pode distribuir entre alvos. Requer 3º círculo.",
    trueForm: "Verdadeiro (+5 PE): cada laço destruído libera 2d6+2 dano de Energia no alvo. Requer 3º círculo e afinidade.",
  },
  {
    id: "dissonancia_acustica",
    name: "Dissonância Acústica",
    element: "energia",
    circle: 2,
    execution: "padrão",
    range: "médio",
    area: "cubo 6m",
    duration: "cena",
    description: "Uma área de silêncio caótico. Nenhum som pode entrar ou sair da área. Seres dentro ficam surdos e não podem conjurar rituais que exijam palavras.",
    upgrade: "Discente (+3 PE): área esfera 9m de raio. Requer 3º círculo.",
  },
  {
    id: "sopro_caos",
    name: "Sopro do Caos",
    element: "energia",
    circle: 2,
    execution: "padrão",
    range: "médio",
    target: "veja texto",
    duration: "cena",
    description: "Move o ar de formas impossíveis. Escolha: empurrar ser (Atletismo DT ritual ou recua até 9m e cai), criar barreira de vento (RD 10 contra projéteis), ou sustentar objeto em levitação.",
    upgrade: "Discente (+3 PE): pode afetar múltiplos alvos ou aumentar força do vento. Requer 3º círculo.",
  },
  {
    id: "tela_ruido",
    name: "Tela de Ruído",
    element: "energia",
    circle: 2,
    execution: "reação",
    range: "pessoal",
    target: "você",
    duration: "instantânea",
    description: "Cria película protetora de Energia que absorve dano. Você recebe 3d6+3 pontos de redução de dano contra o próximo ataque que receber nesta rodada.",
    upgrade: "Discente (+3 PE): absorção 6d6+6. Requer 3º círculo.",
    trueForm: "Verdadeiro (+7 PE): alcance curto, protege um aliado. Requer 4º círculo.",
  },

  // MORTE
  {
    id: "desacelerar_impacto",
    name: "Desacelerar Impacto",
    element: "morte",
    circle: 2,
    execution: "reação",
    range: "toque",
    target: "1 ser",
    duration: "instantânea",
    description: "Você manipula o tempo ao redor do alvo, amortecendo impactos. Elimina dano de queda e reduz à metade o dano de projéteis nesta rodada.",
    upgrade: "Discente (+3 PE): também reduz à metade dano de explosões. Requer 3º círculo.",
  },
  {
    id: "eco_espiral",
    name: "Eco Espiral",
    element: "morte",
    circle: 2,
    execution: "padrão",
    range: "curto",
    target: "1 ser",
    duration: "cena",
    description: "Espiralado no tempo, o alvo revive o dano sofrido. No início de cada turno do alvo, ele sofre metade do dano total sofrido na rodada anterior (arredondado para baixo, mínimo 1).",
    upgrade: "Discente (+4 PE): o alvo sofre o dano completo, não metade. Requer 3º círculo.",
  },
  {
    id: "paradoxo",
    name: "Paradoxo",
    element: "morte",
    circle: 2,
    execution: "padrão",
    range: "médio",
    area: "esfera 6m de raio",
    duration: "cena",
    description: "Área de tempo paradoxal. Seres na área ficam confusos (–5 em testes) e envelhecem precocemente (–1 PV por rodada, Fortitude DT ritual anula).",
    upgrade: "Discente (+4 PE): dano aumenta para –2 PV por rodada. Requer 3º círculo.",
  },
  {
    id: "miasma_entropico",
    name: "Miasma Entrópico",
    element: "morte",
    circle: 2,
    execution: "padrão",
    range: "médio",
    area: "nuvem esfera 6m de raio",
    duration: "cena",
    resistance: "Fortitude anula",
    description: "Nuvem tóxica envolve a área. Seres dentro ficam enjoados (–5 em testes) e devem fazer Fortitude DT ritual ou ficam sufocados.",
    upgrade: "Discente (+4 PE): seres que saírem da nuvem levam o efeito por 2 rodadas. Requer 3º círculo.",
  },
  {
    id: "velocidade_mortal",
    name: "Velocidade Mortal",
    element: "morte",
    circle: 2,
    execution: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "cena",
    description: "Você acelera o alvo no tempo, dobrando seu deslocamento e concedendo uma ação de movimento adicional por rodada.",
    upgrade: "Discente (+4 PE): o alvo também ganha +5 em Defesa e testes de resistência. Requer 3º círculo.",
    trueForm: "Verdadeiro (+7 PE): o alvo ganha ação padrão adicional por rodada. Requer 4º círculo e afinidade.",
  },

  // SANGUE
  {
    id: "aprimorar_fisico",
    name: "Aprimorar Físico",
    element: "sangue",
    circle: 2,
    execution: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "cena",
    description: "Músculos tonificados e ligamentos reforçados. O alvo recebe +1 em Agilidade ou Força (à escolha dele).",
    upgrade: "Discente (+3 PE): bônus +2. Requer 3º círculo.",
    trueForm: "Verdadeiro (+7 PE): bônus +3. Requer 4º círculo e afinidade.",
  },
  {
    id: "descarnar",
    name: "Descarnar",
    element: "sangue",
    circle: 2,
    execution: "padrão",
    range: "curto",
    target: "1 ser",
    duration: "cena",
    resistance: "Fortitude anula",
    description: "A pele do alvo é dilacerada, abrindo cortes profundos. O alvo sofre 3d6 dano de Sangue por rodada e fica vulnerável a dano enquanto o efeito durar.",
    upgrade: "Discente (+4 PE): dano 6d6 por rodada. Requer 3º círculo.",
  },
  {
    id: "flagelo_sangue",
    name: "Flagelo de Sangue",
    element: "sangue",
    circle: 2,
    execution: "padrão",
    range: "curto",
    target: "1 pessoa",
    duration: "instantânea",
    resistance: "Vontade anula",
    description: "Você manipula os impulsos do alvo. Ele deve obedecer uma ordem de uma frase completa (não suicida). Se passar no teste, a ordem não tem efeito.",
    upgrade: "Discente (+4 PE): o efeito dura até o início do próximo turno do alvo. Requer 3º círculo.",
  },
  {
    id: "hemofagia",
    name: "Hemofagia",
    element: "sangue",
    circle: 2,
    execution: "padrão",
    range: "toque",
    target: "1 ser vivo",
    duration: "instantânea",
    resistance: "Fortitude parcial",
    description: "Absorve o sangue do alvo: 3d8 dano de Sangue e você recupera metade do dano causado em PV. Se o alvo passar, sofre apenas metade do dano e você não recupera PV.",
    upgrade: "Discente (+4 PE): dano 6d8. Requer 3º círculo.",
    trueForm: "Verdadeiro (+7 PE): dano 10d8, área esfera 3m. Requer 4º círculo e afinidade.",
  },
  {
    id: "transfusao_vital",
    name: "Transfusão Vital",
    element: "sangue",
    circle: 2,
    execution: "padrão",
    range: "curto",
    target: "aliados à escolha",
    duration: "instantânea",
    description: "Você transfere 3d6 PV de si mesmo para aliados à sua escolha em alcance curto (distribua como quiser). Você perde os PV; eles os ganham (não pode curar acima do máximo).",
    upgrade: "Discente (+3 PE): você não perde PV e aliados ganham 3d6+3 PV cada. Requer 3º círculo.",
  },

  // MEDO
  {
    id: "protecao_rituais",
    name: "Proteção contra Rituais",
    element: "medo",
    circle: 2,
    execution: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "cena",
    description: "O alvo recebe resistência paranormal +10 (bônus em testes de resistência contra efeitos e criaturas paranormais) e resistência a dano paranormal 5.",
    upgrade: "Discente (+3 PE): bônus +15 e RD paranormal 10. Requer 3º círculo.",
  },
  {
    id: "rejeitar_nevoa",
    name: "Rejeitar Névoa",
    element: "medo",
    circle: 2,
    execution: "padrão",
    range: "pessoal",
    target: "você",
    duration: "cena",
    description: "Você sintoniza sua mente com o Medo, tornando-a resistente. Receba +10 em testes de resistência contra rituais e +5 em Vontade contra efeitos de medo.",
    upgrade: "Discente (+3 PE): alcance curto, até 3 aliados. Requer 3º círculo.",
  },

  // ════════════════════════════════════════════════════════════════════════════
  // 3º CÍRCULO
  // ════════════════════════════════════════════════════════════════════════════

  // CONHECIMENTO
  {
    id: "alterar_memoria",
    name: "Alterar Memória",
    element: "conhecimento",
    circle: 3,
    execution: "padrão",
    range: "toque",
    target: "1 pessoa",
    duration: "instantânea",
    resistance: "Vontade anula",
    description: "Invade a mente e altera/apaga memórias de até 1 hora atrás. Pode mudar detalhes de eventos recentes. O alvo recupera memórias após 1d4 dias.",
    upgrade: "Discente (+4 PE): memórias de até 24 horas. Requer 4º círculo.",
    trueForm: "Verdadeiro (+9 PE): memórias de até uma semana. Requer 4º círculo e afinidade.",
  },
  {
    id: "contato_paranormal",
    name: "Contato Paranormal",
    element: "conhecimento",
    circle: 3,
    execution: "completa",
    range: "pessoal",
    target: "você",
    duration: "1 dia",
    description: "Barganha com a entidade de Conhecimento por ajuda. Receba 6d6 que pode adicionar a testes de perícia. Cada vez que rolar 6 nesses dados, perde 2 de Sanidade.",
    upgrade: "Discente (+4 PE): dados d8; rolar 8 = –3 SAN. Requer 4º círculo.",
    trueForm: "Verdadeiro (+9 PE): dados d12; rolar 12 = –5 SAN. Requer 4º círculo e afinidade.",
  },
  {
    id: "mergulho_mental",
    name: "Mergulho Mental",
    element: "conhecimento",
    circle: 3,
    execution: "padrão",
    range: "toque",
    target: "1 pessoa",
    duration: "cena",
    resistance: "Vontade anula",
    description: "Infiltra-se na mente do alvo para vasculhar pensamentos. Você pode fazer até 3 perguntas que o alvo responde mentalmente e com verdade (que ele saiba).",
    upgrade: "Discente (+4 PE): sem limite de perguntas durante a duração. Requer 4º círculo.",
  },
  {
    id: "videncia",
    name: "Vidência",
    element: "conhecimento",
    circle: 3,
    execution: "padrão",
    range: "ilimitado",
    target: "1 ser ou local conhecido",
    duration: "sustentada",
    description: "Você pode observar e ouvir ao redor de um ser ou local que conheça, como se estivesse presente. Pode mover sua perspectiva até 9m por ação de movimento.",
    upgrade: "Discente (+5 PE): pode interagir com objetos (tocar coisas, acionar interruptores) através da vidência. Requer 4º círculo.",
  },

  // ENERGIA
  {
    id: "convocacao_instantanea",
    name: "Convocação Instantânea",
    element: "energia",
    circle: 3,
    execution: "padrão",
    range: "ilimitado",
    target: "1 objeto marcado",
    duration: "instantânea",
    description: "Teletransporta um objeto marcado (com ação de interlúdio) para suas mãos. O objeto pode estar em qualquer lugar no mundo.",
    upgrade: "Discente (+4 PE): até 3 objetos marcados simultaneamente. Requer 4º círculo.",
  },
  {
    id: "salto_fantasma",
    name: "Salto Fantasma",
    element: "energia",
    circle: 3,
    execution: "padrão",
    range: "médio",
    target: "você e até 5 aliados voluntários",
    duration: "instantânea",
    description: "Teletransporta você e aliados voluntários adjacentes para um ponto visível em alcance médio. Todos chegam adjacentes entre si.",
    upgrade: "Discente (+4 PE): alcance longo, até 10 aliados. Requer 4º círculo.",
    trueForm: "Verdadeiro (+9 PE): alcance extremo. Requer 4º círculo e afinidade.",
  },
  {
    id: "transfigurar_agua",
    name: "Transfigurar Água",
    element: "energia",
    circle: 3,
    execution: "padrão",
    range: "médio",
    area: "cubo 9m",
    duration: "cena",
    description: "Água e gelo na área se comportam de forma caótica. Você pode: solidificar água em plataformas de gelo, criar ondas que derrubam seres (Atletismo DT ritual), ou transformar gelo em vapor.",
    upgrade: "Discente (+5 PE): pode controlar os movimentos da água como ação livre por rodada. Requer 4º círculo.",
  },
  {
    id: "transfigurar_terra",
    name: "Transfigurar Terra",
    element: "energia",
    circle: 3,
    execution: "padrão",
    range: "médio",
    area: "cubo 9m",
    duration: "cena",
    description: "Rochas, lama e areia na área se comportam de forma caótica. Você pode criar terreno difícil, paredes de pedra, ou fazer a terra sumir sob os pés de seres (Reflexos DT ritual ou ficam enterrados).",
    upgrade: "Discente (+5 PE): pode controlar a terra como ação livre por rodada. Requer 4º círculo.",
  },

  // MORTE
  {
    id: "ancora_temporal",
    name: "Âncora Temporal",
    element: "morte",
    circle: 3,
    execution: "padrão",
    range: "curto",
    target: "1 ser",
    duration: "cena",
    resistance: "Vontade parcial",
    description: "Aura espiralada surge sobre o alvo. No início de cada turno, ele faz Vontade DT ritual ou não pode se deslocar naquele turno. O efeito termina se passar em dois testes seguidos.",
    upgrade: "Discente (+4 PE): o alvo também perde ações de movimento se falhar. Requer 4º círculo.",
    trueForm: "Verdadeiro (+4 PE): alvo = seres à escolha. Requer 4º círculo.",
  },
  {
    id: "poeira_podridao",
    name: "Poeira da Podridão",
    element: "morte",
    circle: 3,
    execution: "padrão",
    range: "médio",
    area: "nuvem esfera 9m de raio",
    duration: "cena",
    resistance: "Fortitude parcial",
    description: "Nuvem de poeira escura apodrece tudo que toca. Seres na área sofrem 4d6 dano de Morte por rodada (Fortitude reduz à metade). Objetos orgânicos na área se decompõem.",
    upgrade: "Discente (+5 PE): dano 8d6. Requer 4º círculo.",
  },
  {
    id: "tentaculos_lodo",
    name: "Tentáculos de Lodo",
    element: "morte",
    circle: 3,
    execution: "padrão",
    range: "médio",
    area: "esfera 9m de raio",
    duration: "cena",
    description: "Tentáculos de matéria orgânica putrefata surgem do chão. Seres na área devem fazer Atletismo (DT ritual) ou ficam agarrados. No início de cada turno, sofrem 2d6 dano de Morte.",
    upgrade: "Discente (+5 PE): tentáculos também atacam seres que entrarem na área. Requer 4º círculo.",
  },
  {
    id: "zerar_entropia",
    name: "Zerar Entropia",
    element: "morte",
    circle: 3,
    execution: "padrão",
    range: "curto",
    target: "1 ser",
    duration: "cena",
    resistance: "Vontade parcial",
    description: "O alvo fica lento (velocidade reduzida à metade, –5 em testes de Reflexos e Iniciativa). Se falhar por 5 ou mais, fica paralisado por 1 rodada.",
    upgrade: "Discente (+5 PE): o alvo fica paralisado imediatamente se falhar, desacelera se passar. Requer 4º círculo.",
  },

  // SANGUE
  {
    id: "ferver_sangue",
    name: "Ferver Sangue",
    element: "sangue",
    circle: 3,
    execution: "padrão",
    range: "curto",
    target: "1 ser vivo",
    duration: "cena",
    resistance: "Fortitude parcial",
    description: "Faz o sangue do alvo entrar em ebulição. O alvo sofre 4d6 dano de Sangue e fica fraco (–5 em testes de ataque e Força/Agilidade). Se passar, apenas sofre o dano.",
    upgrade: "Discente (+5 PE): dano 8d6 e fraqueza severa (–10). Requer 4º círculo.",
  },
  {
    id: "forma_monstruosa",
    name: "Forma Monstruosa",
    element: "sangue",
    circle: 3,
    execution: "padrão",
    range: "pessoal",
    target: "você",
    duration: "cena",
    description: "Você assume aparência e forma de uma criatura monstruosa, aumentando para Enorme. Recebe +4 em Força e Vigor, RD 5 e seus ataques desarmados causam 2d10 dano de impacto.",
    upgrade: "Discente (+5 PE): tamanho Colossal, +6 FOR/VIG, RD 10, 3d10 dano. Requer 4º círculo.",
  },
  {
    id: "purgatorio",
    name: "Purgatório",
    element: "sangue",
    circle: 3,
    execution: "padrão",
    range: "médio",
    area: "esfera 9m de raio",
    duration: "cena",
    description: "Área encharcada de sangue. Seres na área ficam vulneráveis a dano (–5 em Defesa). Ao tentar sair, devem fazer Fortitude DT ritual ou sofrem 3d8 dano de Sangue.",
    upgrade: "Discente (+5 PE): dano de saída 6d8. Requer 4º círculo.",
  },
  {
    id: "vomitar_pestes",
    name: "Vomitar Pestes",
    element: "sangue",
    circle: 3,
    execution: "padrão",
    range: "curto",
    target: "veja texto",
    duration: "cena",
    description: "Você vomita um enxame de pequenas criaturas de Sangue que você controla. O enxame tem Defesa 12, 30 PV e causa 3d6 dano de Sangue por rodada a seres no espaço que ocupa.",
    upgrade: "Discente (+5 PE): dois enxames. Requer 4º círculo.",
  },

  // MEDO (3º círculo)
  {
    id: "dissipar_ritual",
    name: "Dissipar Ritual",
    element: "medo",
    circle: 3,
    execution: "padrão",
    range: "médio",
    target: "1 ser ou objeto, ou esfera 3m de raio",
    duration: "instantânea",
    description: "Você dissipa rituais ativos, como se a duração deles tivesse acabado (efeitos instantâneos não podem ser dissipados). Faça um teste de Ocultismo; anula quaisquer rituais ativos no alvo ou na área com DT igual ou menor que o resultado. Pode ser conjurado em um item amaldiçoado para torná-lo mundano por um dia (o portador pode resistir com Vontade).",
  },

  // ════════════════════════════════════════════════════════════════════════════
  // 4º CÍRCULO
  // ════════════════════════════════════════════════════════════════════════════

  // CONHECIMENTO
  {
    id: "controle_mental",
    name: "Controle Mental",
    element: "conhecimento",
    circle: 4,
    execution: "padrão",
    range: "médio",
    target: "1 pessoa ou animal",
    duration: "sustentada",
    resistance: "Vontade parcial",
    description: "Domina a mente do alvo, que obedece todos os comandos exceto ordens suicidas. Ao final de cada turno, o alvo faz Vontade para se livrar. Se passar, fica pasmo por 1 rodada (apenas uma vez por cena).",
    upgrade: "Discente (+5 PE): até 5 alvos.",
    trueForm: "Verdadeiro (+10 PE): até 10 alvos. Requer afinidade.",
  },
  {
    id: "inexistir",
    name: "Inexistir",
    element: "conhecimento",
    circle: 4,
    execution: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "instantânea",
    resistance: "Vontade anula",
    description: "Você toca o alvo e o apaga completamente da existência, eliminando todo rastro. Apenas magia de 4º círculo pode desfazer o efeito.",
  },
  {
    id: "possessao",
    name: "Possessão",
    element: "conhecimento",
    circle: 4,
    execution: "padrão",
    range: "curto",
    target: "1 ser",
    duration: "sustentada",
    resistance: "Vontade anula",
    description: "Sua consciência entra no corpo do alvo. Você controla o alvo completamente, enquanto seu corpo fica indefeso. O alvo pode fazer testes de Vontade por turno para expulsar você.",
  },

  // ENERGIA
  {
    id: "alterar_destino",
    name: "Alterar Destino",
    element: "energia",
    circle: 4,
    execution: "reação",
    range: "pessoal",
    target: "você",
    duration: "instantânea",
    description: "Vislumbre o futuro próximo. Você recebe +15 em um teste de resistência ou na Defesa contra um ataque.",
    upgrade: "Verdadeiro (+5 PE): alcance curto, afeta um aliado.",
  },
  {
    id: "deflagracao_energia",
    name: "Deflagração de Energia",
    element: "energia",
    circle: 4,
    execution: "padrão",
    range: "médio",
    area: "esfera 12m de raio",
    duration: "instantânea",
    resistance: "Reflexos reduz à metade",
    description: "Explosão de energia bruta causa 12d6 dano de Energia. Itens amaldiçoados na área são destruídos automaticamente.",
    upgrade: "Discente (+6 PE): dano 20d6 e alcance extremo.",
  },
  {
    id: "teletransporte",
    name: "Teletransporte",
    element: "energia",
    circle: 4,
    execution: "padrão",
    range: "ilimitado",
    target: "você e até 5 aliados voluntários",
    duration: "instantânea",
    description: "Teletransporta você e aliados para qualquer local que você tenha visitado antes. Se o destino estiver bloqueado, o ritual falha e os PE são perdidos.",
    upgrade: "Discente (+7 PE): pode levar até 20 pessoas.",
  },

  // MORTE
  {
    id: "convocar_algoz",
    name: "Convocar o Algoz",
    element: "morte",
    circle: 4,
    execution: "padrão",
    range: "médio",
    target: "1 ser",
    duration: "cena",
    description: "Conjura ser cadavérico que persegue e tenta matar o alvo designado. O algoz tem Defesa 15, 50 PV, RD 10 e ataca com garras (3d10 dano de Morte + morrendo). Ignora toda proteção e imunidade do alvo.",
  },
  {
    id: "distorcao_temporal",
    name: "Distorção Temporal",
    element: "morte",
    circle: 4,
    execution: "padrão",
    range: "pessoal",
    target: "você",
    duration: "1 rodada",
    description: "Você age livremente enquanto o tempo para para todos ao redor. Durante essa rodada, você pode se mover e agir, mas não pode atacar ou lançar rituais ofensivos. Ao fim, o tempo retoma.",
    upgrade: "Discente (+7 PE): duração de 2 rodadas. Você pode atacar durante a distorção.",
  },
  {
    id: "fim_inevitavel",
    name: "Fim Inevitável",
    element: "morte",
    circle: 4,
    execution: "padrão",
    range: "médio",
    area: "esfera 12m de raio",
    duration: "cena",
    resistance: "Atletismo parcial",
    description: "Uma ruptura no espaço suga tudo ao redor. Todos na área são puxados 9m em direção ao centro a cada rodada (Atletismo DT ritual anula). No centro: 8d10 dano de Morte por rodada.",
  },

  // SANGUE
  {
    id: "capturar_coracao",
    name: "Capturar o Coração",
    element: "sangue",
    circle: 4,
    execution: "padrão",
    range: "curto",
    target: "1 pessoa",
    duration: "cena",
    resistance: "Vontade parcial",
    description: "Desperta paixão obsessiva no alvo por você. No início de cada turno, faz Vontade ou age para ajudá-lo. O efeito termina se passar dois testes seguidos.",
  },
  {
    id: "involucro_carne",
    name: "Invólucro de Carne",
    element: "sangue",
    circle: 4,
    execution: "10 minutos",
    range: "toque",
    target: "1 ser",
    duration: "1 dia",
    description: "Cria clone de carne e sangue com as mesmas estatísticas do alvo. O clone obedece o conjurador e age de forma autônoma. Possui metade dos PV do original.",
  },
  {
    id: "vinculo_sangue",
    name: "Vínculo de Sangue",
    element: "sangue",
    circle: 4,
    execution: "padrão",
    range: "curto",
    target: "1 pessoa",
    duration: "cena",
    resistance: "Vontade anula",
    description: "O alvo sofre todo dano e efeitos negativos que você sofrer durante a duração, no lugar de você. Você não sofre o dano; ele sim.",
  },

  // MEDO
  {
    id: "canalizar_medo",
    name: "Canalizar o Medo",
    element: "medo",
    circle: 4,
    execution: "padrão",
    range: "toque",
    target: "1 pessoa",
    duration: "permanente até ser descarregada",
    description: "Transfere parte do seu poder para outra pessoa. Escolha um ritual de até 3º círculo que conheça; o alvo pode conjurá-lo uma vez sem custo em PE. Seus PE máximos diminuem em valor igual ao custo do ritual transferido até ele ser conjurado.",
  },
  {
    id: "conhecendo_medo",
    name: "Conhecendo o Medo",
    element: "medo",
    circle: 4,
    execution: "padrão",
    range: "toque",
    target: "1 pessoa",
    duration: "instantânea",
    resistance: "Vontade parcial",
    description: "Manifesta medo absoluto na mente do alvo. Se falhar: Sanidade vai a 0 e fica enlouquecendo. Se passar: 10d6 dano mental e apavorado por 1 rodada. Pessoa que fica insana transforma-se em criatura paranormal.",
  },
  {
    id: "lamina_medo",
    name: "Lâmina do Medo",
    element: "medo",
    circle: 4,
    execution: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "instantânea",
    resistance: "Vontade parcial",
    description: "Golpeia o alvo com lâmina de medo puro. Causa dano igual à Sanidade máxima menos a Sanidade atual do conjurador. Se o alvo falhar, também fica apavorado por 1 cena.",
  },
  {
    id: "medo_tangivel",
    name: "Medo Tangível",
    element: "medo",
    circle: 4,
    execution: "padrão",
    range: "pessoal",
    target: "você",
    duration: "cena",
    description: "Você recebe imunidade a dano físico, imunidade a condições de medo, RD 20 contra todos os tipos de dano, e seu tamanho aumenta para Enorme. Você se torna manifestação do Medo.",
  },
  {
    id: "presenca_medo",
    name: "Presença do Medo",
    element: "medo",
    circle: 4,
    execution: "padrão",
    range: "pessoal",
    target: "você",
    duration: "cena",
    description: "Você assume forma impossível dentro da Realidade. Torna-se incorpóreo (imune a dano físico), pode atravessar objetos sólidos, e causa 3d6 dano de Medo em seres adjacentes no início de cada turno deles.",
  },
];

export const RITUAL_BY_ID: Record<string, Ritual> = Object.fromEntries(
  RITUALS.map((r) => [r.id, r]),
);

export const RITUALS_BY_ELEMENT: Record<Element, Ritual[]> = {
  conhecimento: RITUALS.filter((r) => r.element === "conhecimento"),
  energia: RITUALS.filter((r) => r.element === "energia"),
  morte: RITUALS.filter((r) => r.element === "morte"),
  sangue: RITUALS.filter((r) => r.element === "sangue"),
  medo: RITUALS.filter((r) => r.element === "medo"),
};

export const RITUALS_BY_CIRCLE: Record<RitualCircle, Ritual[]> = {
  1: RITUALS.filter((r) => r.circle === 1),
  2: RITUALS.filter((r) => r.circle === 2),
  3: RITUALS.filter((r) => r.circle === 3),
  4: RITUALS.filter((r) => r.circle === 4),
};

// Círculo máximo acessível para um dado NEX (Ocultista)
export function maxRitualCircle(nex: number): RitualCircle | null {
  if (nex >= 85) return 4;
  if (nex >= 55) return 3;
  if (nex >= 25) return 2;
  if (nex >= 5) return 1;
  return null;
}

// Custo total (base + upgrade) de um ritual
export function ritualCost(circle: RitualCircle): number {
  return RITUAL_COST[circle];
}

export const ELEMENT_LABEL_PT: Record<Element, string> = {
  conhecimento: "Conhecimento",
  energia: "Energia",
  morte: "Morte",
  sangue: "Sangue",
  medo: "Medo",
};

export const ELEMENT_COLOR_UI: Record<Element, string> = {
  conhecimento: "#d4af37",
  energia: "#b96bd6",
  morte: "#6b7280",
  sangue: "#a01818",
  medo: "#9aa0a6",
};
