export interface Background {
  id: string;
  name: string;
  icon: string;
  description: string;
  flavor: string;
  skills: string[];
  toolProficiencies: string[];
  languages: number; // number of free language choices
  feature: string;
  featureDesc: string;
  startingEquipment: string[];
  personalityTraits: string[];
  ideals: string[];
  bonds: string[];
  flaws: string[];
}

export const BACKGROUNDS: Background[] = [
  {
    id: "acolito",
    name: "Acólito",
    icon: "⛪",
    description: "Você viveu a serviço de um templo de algum deus, realizando rituais e ofertando sacrifícios.",
    flavor: "Você age como um intermediário entre o reino divino e o reino dos mortais.",
    skills: ["Intuição", "Religião"],
    toolProficiencies: [],
    languages: 2,
    feature: "Abrigo dos Fiéis",
    featureDesc: "Você e seus companheiros podem receber cura e caridade de um templo de sua fé. Aqueles que compartilham de sua religião custeiam um estilo de vida modesto para você.",
    startingEquipment: [
      "Um símbolo sagrado (presente ao ser sagrado)",
      "Um livro de orações ou 5 palitos de incenso",
      "Vestimentas",
      "Roupas comuns",
      "Bolsa com 15 po",
    ],
    personalityTraits: [
      "Eu idolatro um herói particular da minha fé.",
      "Eu consigo encontrar empatia mesmo entre os inimigos mais violentos.",
      "Eu vejo presságios em cada evento e ação.",
      "Nada pode abalar minha atitude otimista.",
      "Eu cito textos sagrados em quase qualquer situação.",
      "Eu sou tolerante a qualquer outra fé.",
      "Eu aprecio comida requintada e a elite do meu templo.",
      "Eu possuo pouca prática em lidar com as pessoas do mundo.",
    ],
    ideals: [
      "Tradição. As tradições ancestrais de adoração devem ser preservadas. (Leal)",
      "Caridade. Eu sempre tento ajudar aqueles em necessidade. (Bom)",
      "Mudança. Devemos ajudar as mudanças que os deuses trabalham para o mundo. (Caótico)",
      "Poder. Espero chegar ao topo na hierarquia da minha religião. (Leal)",
      "Fé. Acredito que minha divindade guia minhas ações. (Leal)",
      "Aspiração. Busco ser digno da graça do meu deus. (Qualquer)",
    ],
    bonds: [
      "Morreria para recuperar uma relíquia ancestral da minha fé.",
      "Ainda terei minha vingança contra o templo corrupto que me acusou de heresia.",
      "Devo minha vida ao sacerdote que me acolheu quando meus pais morreram.",
      "Tudo o que faço, faço pelo povo.",
      "Farei qualquer coisa para proteger o templo que sirvo.",
      "Busco guardar um texto sagrado que meus inimigos tentam destruir.",
    ],
    flaws: [
      "Eu julgo os outros severamente.",
      "Deposito muita confiança naqueles que detêm poder no templo.",
      "Minha devoção me cega perante aqueles que professam minha fé.",
      "Meu pensamento é inflexível.",
      "Eu suspeito de estranhos e sempre espero o pior deles.",
      "Depois de escolher um objetivo, fico obcecado em cumpri-lo.",
    ],
  },
  {
    id: "artesao-de-guilda",
    name: "Artesão de Guilda",
    icon: "🔨",
    description: "Você é membro de uma guilda de artesãos, perito em um campo específico.",
    flavor: "Você é uma parte bem estabelecida do mundo mercantil, livre das restrições de uma ordem social feudal.",
    skills: ["Intuição", "Persuasão"],
    toolProficiencies: ["Ferramentas de artesão (à sua escolha)"],
    languages: 1,
    feature: "Associados da Guilda",
    featureDesc: "Seus camaradas da guilda provêem hospedagem e comida se necessário. Você pode ter acesso a figuras políticas através da guilda.",
    startingEquipment: [
      "Ferramentas do seu ofício",
      "Carta de apresentação da guilda",
      "Roupas de viajante",
      "Bolsa com 15 po",
    ],
    personalityTraits: [
      "Acredito que tudo que valha a pena fazer merece ser feito direito.",
      "Sou um esnobe que olha de cima a baixo quem não aprecia artes requintadas.",
      "Sempre quero aprender como as coisas funcionam.",
      "Sou cheio de aforismos espirituosos e tenho um provérbio para cada ocasião.",
      "Sou grosso com pessoas sem comprometimento com o trabalho honesto.",
      "Gosto de falar longamente sobre minha profissão.",
      "Não gasto meu dinheiro facilmente e barganho incansavelmente.",
      "Sou bem conhecido pelo meu trabalho e quero que todos o apreciem.",
    ],
    ideals: [
      "Comunidade. É dever de todo cidadão fortalecer os elos da comunidade. (Leal)",
      "Generosidade. Meus talentos devem beneficiar o mundo. (Bom)",
      "Liberdade. Todos deveriam ser livres para perseguir seus meios de vida. (Caótico)",
      "Ganância. Estou aqui apenas pelo dinheiro. (Mau)",
      "Povo. Sou comprometido com as pessoas com quem me importo. (Neutro)",
      "Aspiração. Trabalho duro para ser o melhor no meu ofício. (Qualquer)",
    ],
    bonds: [
      "A oficina onde aprendi meu negócio é o local mais importante para mim.",
      "Criei um trabalho incrível para alguém indigno; ainda busco o merecedor.",
      "Tenho uma grande dívida para com minha guilda.",
      "Busco riqueza para conseguir o amor de alguém.",
      "Um dia voltarei e provarei que sou o maior artesão da guilda.",
      "Vou me vingar das forças que destruíram meu negócio.",
    ],
    flaws: [
      "Farei de tudo para pôr minhas mãos em algo raro ou inestimável.",
      "Rapidamente presumo que alguém está tentando me trapacear.",
      "Ninguém saberá que certa vez roubei dinheiro da guilda.",
      "Nunca estou satisfeito com o que tenho; sempre quero mais.",
      "Mataria para adquirir um título de nobreza.",
      "Sou terrivelmente invejoso de qualquer um que ofusque meu ofício.",
    ],
  },
  {
    id: "artista",
    name: "Artista",
    icon: "🎭",
    description: "Você cresce em frente a uma audiência. Sabe como fasciná-los, entretê-los e inspirá-los.",
    flavor: "Suas poesias podem avivar o coração daqueles que te ouvem, despertando tristeza ou alegria, risadas ou ira.",
    skills: ["Acrobacia", "Atuação"],
    toolProficiencies: ["Kit de disfarce", "Instrumento musical (à sua escolha)"],
    languages: 0,
    feature: "Pela Demanda Popular",
    featureDesc: "Você sempre encontra um lugar para atuar, recebendo alojamento e comida modesta em troca de atuação noturna. Sua atuação o torna uma figura local reconhecida.",
    startingEquipment: [
      "Um instrumento musical (à sua escolha)",
      "Favor de um admirador (carta de amor, mecha de cabelo ou bugiganga)",
      "Fantasia",
      "Bolsa com 15 po",
    ],
    personalityTraits: [
      "Conheço uma história relevante de praticamente todas as situações.",
      "Sempre que chego em um lugar novo, coleto rumores e espalho fofocas.",
      "Sou um romântico incorrigível, sempre em busca do 'alguém especial'.",
      "Ninguém fica com raiva de mim por muito tempo; acabo com qualquer tensão.",
      "Amo um bom insulto, até os direcionados a mim.",
      "Fico sentido se não for o centro das atenções.",
      "Não me contentarei com nada menos que a perfeição.",
      "Mudo de ânimo tão rápido quanto mudo de nota em uma canção.",
    ],
    ideals: [
      "Beleza. Quando atuo, torno o mundo um lugar melhor. (Bom)",
      "Tradição. As histórias e canções do passado nunca devem ser esquecidas. (Leal)",
      "Criatividade. O mundo precisa de novas ideias e ações ousadas. (Caótico)",
      "Ganância. Estou aqui apenas pelo dinheiro e pela fama. (Mau)",
      "Povo. Gosto de ver sorrisos nos rostos das pessoas quando atuo. (Neutro)",
      "Honestidade. A arte deve refletir a alma. (Qualquer)",
    ],
    bonds: [
      "Meu instrumento é meu bem mais valioso.",
      "Alguém roubou meu instrumento e um dia vou recuperá-lo.",
      "Quero ser famoso, custe o que custar.",
      "Idolatro um herói dos contos antigos.",
      "Farei tudo para provar que sou superior ao meu rival.",
      "Faria qualquer coisa pelos membros da minha antiga trupe.",
    ],
    flaws: [
      "Farei de tudo para ganhar fama e renome.",
      "Viro um idiota quando vejo um rosto bonito.",
      "Um escândalo me impede de voltar para casa.",
      "Satirizei um nobre que ainda quer minha cabeça.",
      "Tenho problemas em esconder meus verdadeiros sentimentos.",
      "Meus amigos não me consideram confiável.",
    ],
  },
  {
    id: "charlatao",
    name: "Charlatão",
    icon: "🃏",
    description: "Você sempre teve jeito com as pessoas. Sabe o que as deixa extasiadas e pode lê-las como livros.",
    flavor: "Você sabe o que as pessoas querem e as entrega — ou pelo menos promete que vai entregar.",
    skills: ["Enganação", "Prestidigitação"],
    toolProficiencies: ["Kit de disfarce", "Kit de falsificação"],
    languages: 0,
    feature: "Identidade Falsa",
    featureDesc: "Você criou uma segunda identidade com documentos, conhecidos e disfarces. Pode forjar documentos, incluindo papeis oficiais e cartas pessoais.",
    startingEquipment: [
      "Roupas finas",
      "Kit de disfarce",
      "Ferramentas para o golpe predileto (10 po)",
      "Bolsa com 15 po",
    ],
    personalityTraits: [
      "Me apaixono e desapaixono facilmente.",
      "Tenho uma piada para cada ocasião, especialmente inapropriadas.",
      "Bajulação é meu truque predileto.",
      "Sou um jogador nato que não resiste a se arriscar.",
      "Minto sobre quase tudo, mesmo sem razão.",
      "Sarcasmo e insultos são minhas armas prediletas.",
      "Tenho vários símbolos sagrados e invoco o mais útil.",
      "Furto qualquer coisa que possa ter valor.",
    ],
    ideals: [
      "Independência. Sou um espírito livre. (Caótico)",
      "Justiça. Nunca roubo de quem não pode perder. (Leal)",
      "Caridade. Distribuo o que adquiro com quem precisa. (Bom)",
      "Criatividade. Nunca faço a mesma trapaça duas vezes. (Caótico)",
      "Amizade. Bens materiais vêm e vão; laços de amizade duram. (Bom)",
      "Aspiração. Estou determinado a fazer algo por mim mesmo. (Qualquer)",
    ],
    bonds: [
      "Extorqui a pessoa errada e devo evitá-la para sempre.",
      "Devo tudo ao meu mentor terrível.",
      "Tenho um filho que não me conhece; torno o mundo melhor para ele.",
      "Vim de família nobre e reivindicarei minhas terras.",
      "Uma pessoa poderosa matou alguém que amei.",
      "Arruinei a vida de alguém que não merecia; busco reparar.",
    ],
    flaws: [
      "Não resisto a um rostinho bonito.",
      "Gasto meus lucros com luxúrias mais rápido do que os ganho.",
      "Estou convencido que ninguém pode me enganar.",
      "Sou ganancioso demais; não resisto a se arriscar por dinheiro.",
      "Não resisto a enganar pessoas mais poderosas que eu.",
      "Vou correr e salvar minha própria pele se as coisas engrossarem.",
    ],
  },
  {
    id: "criminoso",
    name: "Criminoso",
    icon: "🗡️",
    description: "Você é um criminoso experiente que passou tempo entre outros criminosos, mantendo contatos com o submundo.",
    flavor: "Você sobreviveu desprezando a lei e os regulamentos da sociedade.",
    skills: ["Enganação", "Furtividade"],
    toolProficiencies: ["Ferramentas de ladrão", "Kit de jogo (à sua escolha)"],
    languages: 0,
    feature: "Contato Criminal",
    featureDesc: "Você possui contatos de confiança em uma rede criminosa. Sabe como se comunicar com mensageiros locais, mestres de caravana corruptos e marinheiros escusos.",
    startingEquipment: [
      "Pé de cabra",
      "Roupas comuns com capuz",
      "Ferramentas de ladrão",
      "Bolsa com 15 po",
    ],
    personalityTraits: [
      "Sempre tenho um plano para quando as coisas dão errado.",
      "Estou sempre calmo, não importa a situação.",
      "Ao chegar em um novo local, decoro a localização de coisas valiosas.",
      "Prefiro fazer um novo amigo a um novo inimigo.",
      "Sou incrivelmente receoso em confiar.",
      "Não presto atenção aos riscos envolvidos em uma situação.",
      "A melhor maneira de me levar a fazer algo é dizendo que não posso.",
      "Explodo ao menor insulto.",
    ],
    ideals: [
      "Honra. Não roubo de irmãos de profissão. (Leal)",
      "Liberdade. Correntes foram feitas para ser partidas. (Caótico)",
      "Caridade. Roubo dos ricos para dar aos que precisam. (Bom)",
      "Ganância. Farei qualquer coisa para me tornar rico. (Mau)",
      "Povo. Sou leal aos meus amigos, não a qualquer ideal. (Neutro)",
      "Redenção. Há uma centelha de bondade em todo mundo. (Bom)",
    ],
    bonds: [
      "Estou tentando quitar uma dívida com um benfeitor generoso.",
      "Meus ganhos, honestos ou não, sustentam minha família.",
      "Algo importante foi roubado de mim e vou recuperar.",
      "Tornarei-me o maior ladrão que já existiu.",
      "Sou culpado por um terrível crime; espero me redimir.",
      "Alguém que amei morreu por um erro meu. Nunca mais.",
    ],
    flaws: [
      "Quando vejo algo valioso, só consigo pensar em roubá-lo.",
      "Confrontado entre dinheiro e amigo, escolho o dinheiro.",
      "Se há um plano, vou esquecê-lo ou ignorá-lo.",
      "Tenho um 'tique' que revela quando estou mentindo.",
      "Viro as costas e corro quando as coisas começam a ficar ruins.",
      "Um inocente foi preso por um crime que cometi. Por mim, tudo bem.",
    ],
  },
  {
    id: "eremita",
    name: "Eremita",
    icon: "🏔️",
    description: "Você viveu em reclusão por um período importante da vida, encontrando quietude e solidão.",
    flavor: "No tempo longe do clamor da sociedade, você encontrou algumas das respostas que procurava.",
    skills: ["Medicina", "Religião"],
    toolProficiencies: ["Kit de herbalismo"],
    languages: 1,
    feature: "Descoberta",
    featureDesc: "Sua reclusão lhe deu acesso a descobertas únicas — uma grande verdade sobre o cosmos, um local nunca visto, ou informação que poderia reescrever a história.",
    startingEquipment: [
      "Estojo para pergaminhos cheio de notas",
      "Cobertor de inverno",
      "Roupas comuns",
      "Kit de herbalismo",
      "Bolsa com 5 po",
    ],
    personalityTraits: [
      "Fiquei tanto tempo isolado que raramente falo.",
      "Sou absurdamente sereno, mesmo face ao desespero.",
      "O líder da minha comunidade tem algo sábio para cada tópico.",
      "Sinto empatia tremenda por todos que sofrem.",
      "Estou alheio a etiqueta e expectativas sociais.",
      "Relaciono tudo que acontece comigo a um grande plano cósmico.",
      "Muitas vezes me perco em pensamentos e contemplação.",
      "Estou trabalhando em uma grande teoria filosófica.",
    ],
    ideals: [
      "Bem Maior. Meus dons devem ser partilhados com todos. (Bom)",
      "Lógica. Emoções não podem obscurecer meu pensamento lógico. (Leal)",
      "Pensamento Livre. Questionamentos e curiosidade são pilares do progresso. (Caótico)",
      "Poder. Isolamento é caminho para poderes místicos. (Mau)",
      "Viva e Deixe Viver. Intrometer-se nos assuntos alheios traz problemas. (Neutro)",
      "Autoconhecimento. Se você se conhece, não há mais nada para saber. (Qualquer)",
    ],
    bonds: [
      "Nada é mais importante que os outros membros do meu eremitério.",
      "Entrei em reclusão para esconder-me de quem ainda me caça.",
      "Ainda busco o esclarecimento que perseguia durante meu isolamento.",
      "Entrei em reclusão porque amei alguém que não podia ter.",
      "Se minha descoberta vier à tona, poderá trazer destruição.",
      "Meu isolamento me deu discernimento sobre um grande mal que só eu posso destruir.",
    ],
    flaws: [
      "Agora que voltei ao mundo, desfruto de seus prazeres demais.",
      "Escondo pensamentos sanguinários que meu isolamento não apagou.",
      "Sou dogmático em meus pensamentos e filosofia.",
      "Deixo meu desejo de vencer discussões ofuscar amizades.",
      "Arrisco-me muito para descobrir conhecimento perdido.",
      "Gosto de guardar segredos e não os partilho.",
    ],
  },
  {
    id: "forasteiro",
    name: "Forasteiro",
    icon: "🌲",
    description: "Você cresceu em área selvagem, longe da civilização. O isolamento está no seu sangue.",
    flavor: "Você testemunhou a migração de manadas maiores que florestas e sobreviveu a climas extremos.",
    skills: ["Atletismo", "Sobrevivência"],
    toolProficiencies: ["Instrumento musical (à sua escolha)"],
    languages: 1,
    feature: "Andarilho",
    featureDesc: "Você tem memória excelente para mapas e geografia. Pode encontrar comida e água fresca para até cinco pessoas por dia em terra fértil.",
    startingEquipment: [
      "Um cajado",
      "Uma armadilha de caça",
      "Uma faca",
      "Cópia de um mapa da sua terra natal",
      "Roupas de viajante",
      "Bolsa com 10 po",
    ],
    personalityTraits: [
      "Fui guiado por uma sede de viagens que me levou a abandonar meu lar.",
      "Cuido dos meus amigos como filhotes recém-nascidos.",
      "Certa vez corri quarenta quilômetros sem parar para alertar meu clã.",
      "Tenho uma lição para cada situação, aprendida na natureza.",
      "Não vejo lugar para o povo rico e educado.",
      "Estou sempre pegando coisas distraidamente e às vezes quebrando-as.",
      "Sinto-me mais confortável entre animais que entre pessoas.",
      "Fui, de fato, criado por lobos.",
    ],
    ideals: [
      "Mudança. A vida está em constante mudança; devemos mudar com ela. (Caótico)",
      "Bem Maior. É responsabilidade de todos trazer felicidade para a tribo. (Bom)",
      "Honra. Se me desonrar, desonrarei todo meu clã. (Leal)",
      "Força. O mais forte deve governar. (Mau)",
      "Natureza. O mundo natural é mais importante que a civilização. (Neutro)",
      "Glória. Devo adquirir glória em batalha para mim e meu clã. (Qualquer)",
    ],
    bonds: [
      "Minha família, clã ou tribo é a coisa mais importante.",
      "Uma ofensa à natureza intocada do meu lar é uma ofensa a mim.",
      "Trarei fúria terrível aos malfeitores que destruíram minha terra natal.",
      "Sou o último da minha tribo; devo garantir que seus nomes sejam lembrados.",
      "Sofro de visões terríveis de um desastre vindouro.",
      "É meu dever prover filhos para sustentar minha tribo.",
    ],
    flaws: [
      "Sou muito apaixonado por cerveja, vinho e outras bebidas.",
      "Não existe lugar para precaução em uma vida vivida ao máximo.",
      "Lembro de cada insulto que sofri e nutro ressentimento silencioso.",
      "Tenho dificuldade em confiar em membros de outras raças ou tribos.",
      "A violência é minha resposta para quase todos os obstáculos.",
      "Não espere que eu salve quem não consegue se virar sozinho.",
    ],
  },
  {
    id: "heroi-do-povo",
    name: "Herói do Povo",
    icon: "🛡️",
    description: "Você veio de parcela humilde da sociedade, mas está destinado a muito mais.",
    flavor: "O povo de sua vila já o reconhece como campeão, e seu destino o conduz a batalhas contra tiranos.",
    skills: ["Adestrar Animais", "Sobrevivência"],
    toolProficiencies: ["Ferramentas de artesão (à sua escolha)", "Veículos (terrestres)"],
    languages: 0,
    feature: "Hospitalidade Rústica",
    featureDesc: "É fácil se misturar ao povo comum. Você pode encontrar lugar entre os camponeses para se esconder, descansar ou se recuperar, a menos que isso ofereça risco direto a eles.",
    startingEquipment: [
      "Ferramentas de artesão (à sua escolha)",
      "Uma pá",
      "Um pote de ferro",
      "Roupas comuns",
      "Bolsa com 10 po",
    ],
    personalityTraits: [
      "Julgo as pessoas por suas ações, não por suas palavras.",
      "Se alguém está em apuros, estou sempre pronto para ajudar.",
      "Quando fixo minha mente em algo, sigo esse caminho.",
      "Tenho um forte senso de justiça.",
      "Confio em minhas habilidades e farei o necessário para que outros também confiem.",
      "Pensar é para os outros; prefiro agir.",
      "Abuso de palavras longas tentando soar inteligente.",
      "Me entedio fácil; para onde devo ir para encontrar meu destino?",
    ],
    ideals: [
      "Respeito. As pessoas merecem ser tratadas com dignidade. (Bom)",
      "Justiça. Ninguém deve estar acima da lei. (Leal)",
      "Liberdade. Não pode haver tiranos oprimindo o povo. (Caótico)",
      "Força. Se ficar forte, posso pegar tudo que desejo. (Mau)",
      "Sinceridade. Não há nada de bom em fingir ser algo que não sou. (Neutro)",
      "Destino. Nada pode me manter longe do meu chamado. (Qualquer)",
    ],
    bonds: [
      "Tenho família, embora não saiba onde estão; espero encontrá-los.",
      "Trabalho a terra, amo a terra e vou defendê-la.",
      "Um nobre orgulhoso me deu uma surra; vou me vingar.",
      "Minhas ferramentas são símbolo da minha vida passada.",
      "Devo proteger aqueles que não podem se defender.",
      "Gostaria que meu amor viesse comigo para seguir meu destino.",
    ],
    flaws: [
      "O tirano que comanda minha terra não vai parar até ver meu cadáver.",
      "Estou convencido do significado do meu destino e cego aos riscos.",
      "Pessoas que me conhecem desde criança sabem de um segredo vergonhoso meu.",
      "Tenho fraqueza pelos vícios da cidade, especialmente bebedeira.",
      "Secretamente, acredito que as coisas estariam melhores sob um tirano.",
      "Tenho dificuldades em confiar em meus aliados.",
    ],
  },
  {
    id: "marinheiro",
    name: "Marinheiro",
    icon: "⚓",
    description: "Você navegou por mares por anos, enfrentando tormentas, monstros e piratas.",
    flavor: "Seu primeiro amor é a distante linha do horizonte, mas chegou a hora de pôr suas mãos em algo novo.",
    skills: ["Atletismo", "Percepção"],
    toolProficiencies: ["Ferramentas de navegador", "Veículo (aquático)"],
    languages: 0,
    feature: "Passagem de Navio",
    featureDesc: "Você pode conseguir passagem gratuita para você e seus companheiros em um navio com o qual tenha boas relações. Em troca, espera-se que ajudem a tripulação.",
    startingEquipment: [
      "Uma linha de seda com anzol",
      "Um totem de boa sorte",
      "Roupas comuns",
      "Bolsa com 10 po",
    ],
    personalityTraits: [
      "Meus amigos sabem que podem contar comigo pro que der e vier.",
      "Trabalho duro para poder me divertir muito quando o trabalho está pronto.",
      "Gosto de navegar para novos portos e fazer amizades.",
      "Modifico alguns fatos para o bem de uma boa história.",
      "Para mim, uma briga de taverna é ótima forma de conhecer uma nova cidade.",
      "Nunca deixo passar uma aposta amigável.",
      "Meu vocabulário é tão sujo quanto o covil de um otyugh.",
      "Gosto de trabalhos bem feitos, especialmente se posso convencer alguém a fazê-los.",
    ],
    ideals: [
      "Respeito. O que mantém um navio unido é o respeito mútuo. (Bom)",
      "Justiça. Todos fazemos o trabalho; todos partilhamos os espólios. (Leal)",
      "Liberdade. O mar é liberdade — ir aonde quiser. (Caótico)",
      "Domínio. Sou um predador e os outros navios são minhas presas. (Mau)",
      "Povo. Sou apegado a meus companheiros de tripulação. (Neutro)",
      "Aspiração. Algum dia serei dono do meu próprio navio. (Qualquer)",
    ],
    bonds: [
      "Sou leal ao meu capitão, primeiramente.",
      "O navio é o mais importante; tripulantes vêm e vão.",
      "Sempre me lembrarei do meu primeiro navio.",
      "Em uma cidade portuária, tenho uma amante que quase me roubou do mar.",
      "Fui enganado na divisão dos espólios e quero o que me é devido.",
      "Cruéis piratas mataram meu capitão; a vingança será minha.",
    ],
    flaws: [
      "Sigo ordens, mesmo que ache que estão erradas.",
      "Direi qualquer coisa para evitar trabalho extra.",
      "Certa vez alguém duvidou da minha coragem; nunca recuo.",
      "Quando começo a beber, é difícil parar.",
      "Não resisto a uma sacolinha de moedas dando sopa.",
      "Meu orgulho provavelmente levará a minha destruição.",
    ],
  },
  {
    id: "nobre",
    name: "Nobre",
    icon: "👑",
    description: "Você entende de riqueza, poder e privilégios. Carrega um título de nobreza.",
    flavor: "Sua família possui terras, coleta impostos e exerce influência política significativa.",
    skills: ["História", "Persuasão"],
    toolProficiencies: ["Kit de jogo (à sua escolha)"],
    languages: 1,
    feature: "Posição Privilegiada",
    featureDesc: "Graças à sua origem nobre, as pessoas tendem a pensar o melhor de você. Você é bem-vindo na alta sociedade e pode conseguir audiência com nobres locais.",
    startingEquipment: [
      "Roupas finas",
      "Anel de sinete",
      "Histórico familiar",
      "Bolsa com 25 po",
    ],
    personalityTraits: [
      "Minha bajulação faz com que todos se sintam a pessoa mais importante do mundo.",
      "As pessoas comuns me amam por minha bondade e generosidade.",
      "Ninguém pode duvidar que estou acima das massas plebeias.",
      "Tenho grande cuidado de estar sempre no meu melhor.",
      "Não gosto de sujar minhas mãos.",
      "Apesar da minha origem nobre, não estou acima dos outros.",
      "Meu apoio, uma vez perdido, não volta.",
      "Se você me ferir, esmagarei você, arruinarei seu nome e salarei seus campos.",
    ],
    ideals: [
      "Respeito. O respeito é devido por minha posição, mas todos merecem dignidade. (Bom)",
      "Responsabilidade. É meu dever respeitar aqueles acima de mim. (Leal)",
      "Independência. Devo provar que posso me cuidar sem minha família. (Caótico)",
      "Poder. Se alcançar mais poder, ninguém me dirá o que fazer. (Mau)",
      "Família. O sangue corre mais grosso que a água. (Qualquer)",
      "Obrigação Nobre. É meu dever proteger as pessoas abaixo de mim. (Bom)",
    ],
    bonds: [
      "Enfrentarei qualquer desafio para ganhar a aprovação da minha família.",
      "A aliança da minha casa com outra família deve ser mantida a todo custo.",
      "Nada é mais importante que os outros membros da minha família.",
      "Sou apaixonado pela herdeira de uma família que a minha despreza.",
      "Minha lealdade ao meu soberano é inabalável.",
      "As pessoas comuns devem me ver como um herói do povo.",
    ],
    flaws: [
      "Secretamente acredito que todos estão abaixo de mim.",
      "Escondo um segredo escandaloso que poderia arruinar minha família.",
      "Ouço insultos em cada palavra dirigida a mim e me irrito rápido.",
      "Tenho um desejo insaciável por prazeres carnais.",
      "O mundo gira ao meu redor.",
      "Pelas minhas palavras e ações, frequentemente envergonho minha família.",
    ],
  },
  {
    id: "orfao",
    name: "Órfão",
    icon: "🌆",
    description: "Você cresceu nas ruas, sozinho e pobre. Aprendeu a se virar sozinho através de astúcia e agilidade.",
    flavor: "Você lutou ferozmente por comida e se manteve atento a outras almas desesperadas que pudessem te roubar.",
    skills: ["Furtividade", "Prestidigitação"],
    toolProficiencies: ["Kit de disfarce", "Ferramentas de ladrão"],
    languages: 0,
    feature: "Segredos da Cidade",
    featureDesc: "Você conhece os padrões e o fluxo das cidades. Você e companheiros podem viajar entre dois locais na cidade com o dobro da velocidade normal.",
    startingEquipment: [
      "Uma pequena faca",
      "Mapa da cidade onde cresceu",
      "Um rato de estimação",
      "Lembrança dos seus pais",
      "Roupas comuns",
      "Bolsa com 10 po",
    ],
    personalityTraits: [
      "Escondo pedaços de comida e bugigangas em meus bolsos.",
      "Pergunto um monte de coisas.",
      "Gosto de me espremer em locais pequenos onde ninguém possa me alcançar.",
      "Durmo encostado em um muro, abraçado com todas minhas posses.",
      "Como feito um porco e tenho maus modos.",
      "Acho que todos os gentis têm segundas intenções.",
      "Não gosto de tomar banho.",
      "Digo na cara o que as outras pessoas insinuam ou escondem.",
    ],
    ideals: [
      "Respeito. Todas as pessoas, ricas ou pobres, merecem respeito. (Bom)",
      "Comunidade. Temos que tomar conta uns dos outros. (Leal)",
      "Mudança. Os baixos se erguerão e os altos irão tombar. (Caótico)",
      "Retribuição. Os ricos precisam ver como é a vida nas sarjetas. (Mau)",
      "Povo. Ajudo as pessoas que me ajudam. (Neutro)",
      "Aspiração. Vou provar que sou merecedor de uma vida melhor. (Qualquer)",
    ],
    bonds: [
      "Minha cidade ou vila é meu lar e vou lutar para defendê-la.",
      "Patrocino um orfanato para que outros não passem pelo que passei.",
      "Devo minha sobrevivência a outros órfãos que me ensinaram a vida.",
      "Tenho uma dívida impagável com alguém que teve pena de mim.",
      "Saí da pobreza roubando alguém importante; sou procurado por isso.",
      "Ninguém deveria suportar as dificuldades pelas quais passei.",
    ],
    flaws: [
      "Se estiver em desvantagem, fugirei de uma briga.",
      "Ouro parece muito dinheiro; faria praticamente qualquer coisa por mais.",
      "Nunca confiarei plenamente em ninguém além de mim mesmo.",
      "Prefiro matar alguém enquanto dorme a uma luta justa.",
      "Não é roubo se eu preciso mais que outra pessoa.",
      "Pessoas que não conseguem se virar sozinhas têm o que merecem.",
    ],
  },
  {
    id: "sabio",
    name: "Sábio",
    icon: "📚",
    description: "Você ficou anos aprendendo sobre o conhecimento do multiverso, estudando manuscritos e ouvindo especialistas.",
    flavor: "Seus esforços fizeram de você um mestre no seu campo de estudo.",
    skills: ["Arcanismo", "História"],
    toolProficiencies: [],
    languages: 2,
    feature: "Pesquisador",
    featureDesc: "Ao tentar obter um fragmento de conhecimento, você sabe onde e com quem pode obtê-lo — bibliotecas, arquivos, universidades ou outros sábios.",
    startingEquipment: [
      "Uma garrafa de tinta negra",
      "Uma caneta tinteiro",
      "Uma faca pequena",
      "Cartas de um colega falecido",
      "Roupas comuns",
      "Bolsa com 10 po",
    ],
    personalityTraits: [
      "Uso palavras polissilábicas para endossar minha impressão de erudição.",
      "Li todos os livros das grandes bibliotecas — ou gosto de dizer que li.",
      "Costumo ajudar os outros que não são tão inteligentes e explico pacientemente.",
      "Nada para mim é melhor que um bom mistério.",
      "Voluntariamente escuto cada lado antes de tomar uma decisão.",
      "Falo lentamente ao conversar com idiotas.",
      "Sou horrível em situações sociais.",
      "Estou convencido de que todos tentam roubar meus segredos.",
    ],
    ideals: [
      "Conhecimento. O caminho para o poder é através do conhecimento. (Neutro)",
      "Beleza. O que é belo nos mostra o que é verdadeiro. (Bom)",
      "Lógica. Emoções não devem nublar o pensamento lógico. (Leal)",
      "Sem Limites. Nada pode apaziguar a possibilidade infinita da existência. (Caótico)",
      "Poder. Conhecimento é o caminho para a dominação. (Mau)",
      "Auto Aperfeiçoamento. O objetivo de estudar é melhorar a si mesmo. (Qualquer)",
    ],
    bonds: [
      "É meu dever proteger meus estudantes.",
      "Guardo um texto ancestral com terríveis segredos.",
      "Trabalho para preservar uma biblioteca ou monastério.",
      "O trabalho da minha vida é uma série de tomos sobre um campo específico.",
      "Busco a resposta para uma questão que persigo a vida toda.",
      "Vendi minha alma por conhecimento; espero realizações para ganhá-la de volta.",
    ],
    flaws: [
      "Me distraio facilmente com a promessa de informação.",
      "Muitas pessoas correm de um corruptor; eu paro e tomo notas.",
      "Desvendar um mistério ancestral pode valer o preço de uma civilização.",
      "Prefiro soluções óbvias a complicadas.",
      "Falo sem antes pensar, invariavelmente insultando outros.",
      "Não consigo guardar um segredo para salvar minha vida.",
    ],
  },
  {
    id: "soldado",
    name: "Soldado",
    icon: "⚔️",
    description: "A guerra esteve na sua vida desde que você se recorda. Treinado desde jovem no uso de armas e armaduras.",
    flavor: "Você pode ter feito parte de uma armada nacional, companhia de mercenários ou milícia local.",
    skills: ["Atletismo", "Intimidação"],
    toolProficiencies: ["Kit de jogo (à sua escolha)", "Veículo (terrestre)"],
    languages: 0,
    feature: "Patente Militar",
    featureDesc: "Soldados leais à sua antiga organização reconhecem sua autoridade. Você pode requisitar equipamentos simples e ter acesso a acampamentos militares aliados.",
    startingEquipment: [
      "Insígnia de patente",
      "Troféu de um inimigo abatido",
      "Conjunto de dados com ossos",
      "Roupas comuns",
      "Bolsa com 10 po",
    ],
    personalityTraits: [
      "Sou sempre polido e respeitoso.",
      "Sou assombrado pelas memórias da guerra.",
      "Perdi muitos amigos e sou muito devagar para fazer novos.",
      "Tenho muitas histórias de inspiração da minha experiência militar.",
      "Não consigo encarar um cão infernal sem vacilar.",
      "Gosto de ser forte e de quebrar coisas.",
      "Tenho um senso de humor grosseiro.",
      "Enfrento os problemas de frente; uma solução direta é o melhor caminho.",
    ],
    ideals: [
      "Bem Maior. Nosso destino é dar nossas vidas em defesa de terceiros. (Bom)",
      "Responsabilidade. Faço o que tenho que fazer e obedeço apenas a autoridade. (Leal)",
      "Independência. Quando pessoas seguem ordens cegas, apoiam a tirania. (Caótico)",
      "Força. A vida é como uma guerra; o mais forte vence. (Mau)",
      "Viva e Deixa Viver. Ideais não valem a pena se você matar por eles. (Neutro)",
      "Aspiração. Minha cidade, nação ou povo são tudo que importa. (Qualquer)",
    ],
    bonds: [
      "Ainda daria minha vida pelas pessoas com quem servi.",
      "Alguém salvou minha vida no campo de batalha; nunca deixo amigos para trás.",
      "Minha honra é minha vida.",
      "Nunca esquecerei a derrota que minha companhia sofreu.",
      "Aqueles que lutam ao meu lado são por quem vale a pena morrer.",
      "Luto por aqueles que não podem lutar por si mesmos.",
    ],
    flaws: [
      "O inimigo monstruoso que enfrentei ainda me deixa tremendo de medo.",
      "Tenho pouco respeito por quem não se prova bom combatente.",
      "Cometi um terrível erro em batalha que custou muitas vidas.",
      "Meu ódio por meus inimigos é cego e irracional.",
      "Obedeço a lei, mesmo se ela trouxer angústia.",
      "Prefiro comer minha armadura a admitir que estou errado.",
    ],
  },
];
