export interface Subclass {
  id: string;
  name: string;
  description: string;
  features: string[];
}

export interface ClassFeature {
  level: number;
  name: string;
  description: string;
}

export interface DndClass {
  id: string;
  name: string;
  icon: string;
  description: string;
  flavor: string;
  hitDie: number;
  primaryAbilities: string[];
  savingThrows: string[];
  armorProficiencies: string[];
  weaponProficiencies: string[];
  toolProficiencies: string[];
  skillChoices: string[];
  skillCount: number;
  startingEquipment: string[];
  startingGold: string;
  keyFeatures: string[];
  subclasses: Subclass[];
  spellcasting: boolean;
  spellcastingAbility: string | null;
}

export const CLASSES: DndClass[] = [
  {
    id: "barbaro",
    name: "Bárbaro",
    icon: "🪓",
    description: "Um feroz guerreiro de origem primitiva que pode entrar em fúria durante uma batalha.",
    flavor: "Definidos pela fúria: desenfreada, inextinguível e irracional. Mais que uma mera emoção, sua raiva é a ferocidade de um predador acuado.",
    hitDie: 12,
    primaryAbilities: ["Força"],
    savingThrows: ["Força", "Constituição"],
    armorProficiencies: ["Armaduras leves", "Armaduras médias", "Escudos"],
    weaponProficiencies: ["Armas simples", "Armas marciais"],
    toolProficiencies: [],
    skillChoices: ["Adestrar Animais", "Atletismo", "Intimidação", "Natureza", "Percepção", "Sobrevivência"],
    skillCount: 2,
    startingEquipment: [
      "(a) um machado grande ou (b) qualquer arma marcial corpo-a-corpo",
      "(a) dois machados de mão ou (b) qualquer arma simples",
      "Um pacote de aventureiro e quatro azagaias",
    ],
    startingGold: "2d4 × 10 po",
    keyFeatures: [
      "Fúria — Ação bônus para entrar em fúria; vantagem em testes de Força, bônus de dano e resistência a dano físico",
      "Defesa sem Armadura — CA = 10 + mod. Destreza + mod. Constituição sem armadura",
      "Ataque Descuidado (2°) — Vantagem nos ataques com custo de vulnerabilidade à ataques",
      "Sentido de Perigo (2°) — Vantagem em testes de resistência de Destreza visíveis",
      "Caminho Primitivo (3°) — Escolha de subclasse",
      "Ataque Extra (5°) — Ataque duas vezes por ação de Ataque",
      "Movimento Rápido (5°) — +3m de deslocamento sem armadura pesada",
      "Instinto Selvagem (7°) — Vantagem em iniciativa",
      "Crítico Brutal (9°) — Dado extra em acertos críticos",
      "Fúria Implacável (11°) — Pode ficar com 1 PV ao cair a 0 em fúria",
      "Fúria Persistente (15°) — Fúria só termina se inconsciente ou voluntariamente",
      "Força Indomável (18°) — Pode usar valor de Força no lugar da rolagem",
      "Campeão Primitivo (20°) — Força e Constituição +4, máximo 24",
    ],
    subclasses: [
      {
        id: "caminho-furioso",
        name: "Caminho do Furioso",
        description: "A fúria é um meio para um fim – a violência. Você vibra no caos da batalha.",
        features: [
          "Frenesi (3°) — Ataque bônus extra durante a fúria (sofre exaustão ao fim)",
          "Fúria Inconsciente (6°) — Não pode ser enfeitiçado ou amedrontado em fúria",
          "Presença Intimidante (10°) — Ação para amedrontar criatura a 9m",
          "Retaliação (14°) — Reação para atacar quem te feriu a 1,5m",
        ],
      },
      {
        id: "caminho-totemico",
        name: "Caminho do Guerreiro Totêmico",
        description: "Jornada espiritual aceitando um espírito animal como guia. Seu totem preenche você com força sobrenatural.",
        features: [
          "Conselheiro Espiritual (3°) — Ritual de sentido bestial e falar com animais",
          "Totem Espiritual (3°) — Escolha de totem: Águia, Lobo ou Urso",
          "Aspecto da Besta (6°) — Benefício místico do totem",
          "Andarilho Espiritual (10°) — Ritual de comunhão com a natureza",
          "Sintonia Totêmica (14°) — Benefício mágico adicional do totem",
        ],
      },
    ],
    spellcasting: false,
    spellcastingAbility: null,
  },

  {
    id: "bardo",
    name: "Bardo",
    icon: "🎵",
    description: "Um místico inspirador que possui poderes que ecoam a música da criação.",
    flavor: "Bardos tecem sua magia através de palavras e música para inspirar aliados, desmoralizar oponentes, manipular mentes, criar ilusões e curar ferimentos.",
    hitDie: 8,
    primaryAbilities: ["Carisma"],
    savingThrows: ["Destreza", "Carisma"],
    armorProficiencies: ["Armaduras leves"],
    weaponProficiencies: ["Armas simples", "Bestas de mão", "Espadas longas", "Rapieiras", "Espadas curtas"],
    toolProficiencies: ["Três instrumentos musicais (à sua escolha)"],
    skillChoices: [
      "Acrobacia", "Adestrar Animais", "Arcanismo", "Atletismo", "Atuação",
      "Enganação", "Furtividade", "História", "Intimidação", "Intuição",
      "Investigação", "Medicina", "Natureza", "Percepção", "Persuasão",
      "Prestidigitação", "Religião", "Sobrevivência",
    ],
    skillCount: 3,
    startingEquipment: [
      "(a) uma rapieira, (b) uma espada longa ou (c) qualquer arma simples",
      "(a) um pacote de diplomata ou (b) um pacote de artista",
      "(a) um alaúde ou (b) qualquer outro instrumento musical",
      "Armadura de couro e uma adaga",
    ],
    startingGold: "5d4 × 10 po",
    keyFeatures: [
      "Conjuração — Magias de Bardo com habilidade Carisma",
      "Inspiração de Bardo (1°) — Concede dado de inspiração (d6→d12) a aliado",
      "Versatilidade (2°) — Adiciona metade do bônus de proficiência a qualquer teste",
      "Canção do Descanso (2°) — Aliados recuperam PV extra em descanso curto",
      "Colégio de Bardo (3°) — Escolha de subclasse",
      "Aptidão (3°) — Dobra bônus de proficiência em duas perícias",
      "Fonte de Inspiração (5°) — Recupera Inspiração em descanso curto",
      "Canção de Proteção (6°) — Vantagem vs enfeitiçado/amedrontado em área",
      "Segredos Mágicos (10°) — Aprende magias de qualquer classe",
      "Inspiração Superior (20°) — Recupera uso de Inspiração ao rolar iniciativa",
    ],
    subclasses: [
      {
        id: "colegio-conhecimento",
        name: "Colégio do Conhecimento",
        description: "Coletam conhecimento de todas as fontes possíveis, questionando tudo que a audiência crê ser verdade.",
        features: [
          "Proficiência Adicional (3°) — Três perícias adicionais à escolha",
          "Palavras de Interrupção (3°) — Reação para subtrair dado de Inspiração de rolagem inimiga",
          "Segredos Mágicos Adicionais (6°) — Duas magias de qualquer classe",
          "Perícia Inigualável (14°) — Gasta Inspiração para adicionar dado a teste de habilidade próprio",
        ],
      },
      {
        id: "colegio-bravura",
        name: "Colégio da Bravura",
        description: "Escaldos que mantêm viva a memória dos grandes heróis do passado, inspirando novos heróis.",
        features: [
          "Proficiência Adicional (3°) — Armaduras médias, escudos e armas marciais",
          "Inspiração em Combate (3°) — Dado de Inspiração pode ser usado em dano ou CA",
          "Ataque Extra (6°) — Ataca duas vezes por ação",
          "Magia de Batalha (14°) — Ao conjurar, pode atacar com arma como ação bônus",
        ],
      },
    ],
    spellcasting: true,
    spellcastingAbility: "Carisma",
  },

  {
    id: "bruxo",
    name: "Bruxo",
    icon: "🕯️",
    description: "Um portador de magia derivada de barganha com uma entidade planar.",
    flavor: "Desbravadores do conhecimento oculto que fizeram pactos com seres misteriosos. Extraem poder de nobres fadas, demônios, diabos e entidades alienígenas.",
    hitDie: 8,
    primaryAbilities: ["Carisma"],
    savingThrows: ["Sabedoria", "Carisma"],
    armorProficiencies: ["Armaduras leves"],
    weaponProficiencies: ["Armas simples"],
    toolProficiencies: [],
    skillChoices: ["Arcanismo", "Enganação", "História", "Intimidação", "Investigação", "Natureza", "Religião"],
    skillCount: 2,
    startingEquipment: [
      "(a) uma besta leve e 20 virotes ou (b) qualquer arma simples",
      "(a) uma bolsa de componentes ou (b) um foco arcano",
      "(a) um pacote de estudioso ou (b) um pacote de explorador",
      "Armadura de couro, qualquer arma simples e duas adagas",
    ],
    startingGold: "4d4 × 10 po",
    keyFeatures: [
      "Patrono Transcendental (1°) — Escolha do patrono que concede magias expandidas",
      "Magia de Pacto — Espaços únicos recuperados em descanso curto; todos do mesmo nível",
      "Invocações Místicas (2°) — Poderes permanentes de conhecimento proibido",
      "Dádiva do Pacto (3°) — Pacto da Corrente (familiar), Lâmina (arma) ou Tomo (grimório)",
      "Arcana Mística (11°) — Magia de 6°/7°/8°/9° nível sem espaço de magia",
      "Mestre Místico (20°) — Recupera todos os espaços de magia rogando ao patrono",
    ],
    subclasses: [
      {
        id: "arquifada",
        name: "A Arquifada",
        description: "Patrono feérico lendário cujas motivações são inescrutáveis. Inclui o Príncipe do Frio, Titania, Oberon.",
        features: [
          "Presença Feérica (1°) — Ação para enfeitiçar/amedrontar em cubo de 3m",
          "Névoa de Fuga (6°) — Reação para ficar invisível e teletransportar 18m ao sofrer dano",
          "Defesa Sedutora (10°) — Imune a ser enfeitiçado; pode reverter encantamento",
          "Delírio Sombrio (14°) — Imerge criatura num reino ilusório por 1 minuto",
        ],
      },
      {
        id: "corruptor",
        name: "O Corruptor",
        description: "Pacto com ser dos planos inferiores cujo objetivo é o mal. Inclui Demogorgon, Orcus, Asmodeus.",
        features: [
          "Bênção do Obscuro (1°) — Ganha PV temporários ao reduzir inimigo a 0",
          "Sorte do Próprio Obscuro (6°) — Adiciona 1d10 a teste de habilidade ou resistência",
          "Resistência Demoníaca (10°) — Resistência a um tipo de dano por descanso",
          "Lançar no Inferno (14°) — Transporta criatura para plano inferior por um turno",
        ],
      },
      {
        id: "grande-antigo",
        name: "O Grande Antigo",
        description: "Entidade de natureza profundamente alheia à realidade. Inclui Grande Cthulhu, Tharizdun.",
        features: [
          "Despertar a Mente (1°) — Comunicação telepática com criaturas a 9m",
          "Proteção Entrópica (6°) — Reação para impor desvantagem em ataque contra você",
          "Escudo de Pensamentos (10°) — Resistência a dano psíquico; mente ilegível",
          "Criar Lacaio (14°) — Infecta mente de humanoide incapacitado com magia",
        ],
      },
    ],
    spellcasting: true,
    spellcastingAbility: "Carisma",
  },

  {
    id: "clerigo",
    name: "Clérigo",
    icon: "✨",
    description: "Um campeão sacerdotal que empunha magia divina a serviço de um poder maior.",
    flavor: "Intermediários entre o mundo mortal e os deuses. Combinam o poder mágico de curar e inspirar aliados com magias que ferem e debilitam inimigos.",
    hitDie: 8,
    primaryAbilities: ["Sabedoria"],
    savingThrows: ["Sabedoria", "Carisma"],
    armorProficiencies: ["Armaduras leves", "Armaduras médias", "Escudos"],
    weaponProficiencies: ["Todas as armas simples"],
    toolProficiencies: [],
    skillChoices: ["História", "Intuição", "Medicina", "Persuasão", "Religião"],
    skillCount: 2,
    startingEquipment: [
      "(a) uma maça ou (b) um martelo de guerra (se proficiente)",
      "(a) brunea, (b) armadura de couro ou (c) cota de malha (se proficiente)",
      "(a) uma besta leve e 20 virotes ou (b) qualquer arma simples",
      "(a) um pacote de sacerdote ou (b) um pacote de aventureiro",
      "Um escudo e um símbolo sagrado",
    ],
    startingGold: "5d4 × 10 po",
    keyFeatures: [
      "Conjuração — Prepara magias; habilidade Sabedoria",
      "Domínio Divino (1°) — Escolha de subclasse com magias de domínio sempre preparadas",
      "Canalizar Divindade (2°) — Energia divina para efeitos mágicos; inicia com Expulsar Mortos-Vivos",
      "Destruir Mortos-Vivos (5°) — Destrói mortos-vivos de ND baixo ao expulsar",
      "Intervenção Divina (10°) — Roga ao deus por ajuda com rolagem percentual",
    ],
    subclasses: [
      {
        id: "dominio-conhecimento",
        name: "Domínio do Conhecimento",
        description: "Deuses que valorizam estudo e compreensão acima de tudo. Inclui Oghma, Thoth.",
        features: [
          "Bênçãos do Conhecimento (1°) — Dois idiomas e duas perícias com bônus dobrado",
          "Conhecimento das Eras (2°) — CD: proficiência em perícia ou ferramenta por 10 min",
          "Ler Pensamentos (6°) — CD: lê mente e pode conjurar sugestão sem espaço",
          "Conjuração Poderosa (8°) — Adiciona mod. Sabedoria ao dano de truques",
          "Visões do Passado (17°) — Meditação para ver eventos passados de objeto ou local",
        ],
      },
      {
        id: "dominio-enganacao",
        name: "Domínio da Enganação",
        description: "Deuses causadores de travessuras. Inclui Tymora, Loki, Garl Glittergold.",
        features: [
          "Bênção do Trapaceiro (1°) — Toca aliado para vantagem em Furtividade por 1h",
          "Invocar Duplicidade (2°) — CD: cria ilusão perfeita de si mesmo por 1 min",
          "Manto de Sombras (6°) — CD: torna-se invisível até próximo turno",
          "Golpe Divino (8°) — +1d8 de veneno em ataque com arma por turno",
          "Duplicidade Aprimorada (17°) — Cria até quatro duplicatas",
        ],
      },
      {
        id: "dominio-guerra",
        name: "Domínio da Guerra",
        description: "Deuses que zelam pelos guerreiros. Inclui Torm, Tempus, Ares, Gruumsh.",
        features: [
          "Proficiência Adicional (1°) — Armas marciais e armaduras pesadas",
          "Sacerdote da Guerra (1°) — Ataque extra como ação bônus (limitado por Sabedoria)",
          "Ataque Dirigido (2°) — CD: +10 em jogada de ataque",
          "Bênção do Deus da Guerra (6°) — Reação para dar +10 em ataque de aliado",
          "Golpe Divino (8°) — +1d8 do tipo da arma por turno",
          "Avatar da Batalha (17°) — Resistência a dano físico não-mágico",
        ],
      },
      {
        id: "dominio-luz",
        name: "Domínio da Luz",
        description: "Deuses da renovação e verdade. Inclui Lathander, Apolo, Helm.",
        features: [
          "Truque Adicional (1°) — Aprende o truque luz",
          "Labareda Protetora (1°) — Reação para impor desvantagem em ataque contra você",
          "Radiação do Amanhecer (2°) — CD: explosão de luz solar que destrói escuridão mágica",
          "Labareda Aprimorada (6°) — Labareda protege aliados também",
          "Conjuração Poderosa (8°) — Adiciona mod. Sabedoria ao dano de truques",
          "Coroa de Luz (17°) — Aura de luz solar com desvantagem inimiga vs magias de fogo/radiante",
        ],
      },
      {
        id: "dominio-natureza",
        name: "Domínio da Natureza",
        description: "Deuses da natureza selvagem. Inclui Silvanus, Obad-Hai, Pan.",
        features: [
          "Acólito da Natureza (1°) — Um truque de druida e proficiência em perícia de natureza",
          "Proficiência Adicional (1°) — Armaduras pesadas",
          "Enfeitiçar Animais e Plantas (2°) — CD: enfeitiça bestas e plantas próximas",
          "Amortecer Elementos (6°) — Reação para conceder resistência elemental a criatura próxima",
          "Golpe Divino (8°) — +1d8 de frio/fogo/elétrico por turno",
          "Senhor da Natureza (17°) — Comanda animais/plantas enfeitiçados com ação bônus",
        ],
      },
      {
        id: "dominio-tempestade",
        name: "Domínio da Tempestade",
        description: "Deuses de tempestades e mares. Inclui Talos, Zeus, Thor, Umberlee.",
        features: [
          "Proficiência Adicional (1°) — Armas marciais e armaduras pesadas",
          "Ira da Tormenta (1°) — Reação para infligir 2d8 de dano elétrico/trovão ao atacante",
          "Ira Destruidora (2°) — CD: causa dano máximo em rolagem de dano elétrico/trovão",
          "Golpe de Relâmpago (6°) — Empurra 3m criaturas atingidas com dano elétrico",
          "Golpe Divino (8°) — +1d8 de trovão por turno",
          "Filho da Tormenta (17°) — Deslocamento de voo igual ao de caminhada",
        ],
      },
      {
        id: "dominio-vida",
        name: "Domínio da Vida",
        description: "Deuses da vitalidade e cura. Inclui Chauntea, Lathander, Pelor, Mishakal.",
        features: [
          "Proficiência Adicional (1°) — Armaduras pesadas",
          "Discípulo da Vida (1°) — Magias de cura recuperam 2 + nível da magia extras",
          "Preservar a Vida (2°) — CD: distribui PVs de cura entre aliados próximos",
          "Curandeiro Abençoado (6°) — Ao curar aliado, você também se cura",
          "Golpe Divino (8°) — +1d8 de radiante por turno",
          "Cura Suprema (17°) — Usa resultado máximo em dados de cura",
        ],
      },
    ],
    spellcasting: true,
    spellcastingAbility: "Sabedoria",
  },

  {
    id: "druida",
    name: "Druida",
    icon: "🌿",
    description: "Um sacerdote da Crença Antiga, detentor dos poderes da natureza e capaz de adotar formas animais.",
    flavor: "Encarnações da resistência, astúcia e fúria da natureza. Não se consideram donos, mas extensões da vontade indomável da natureza.",
    hitDie: 8,
    primaryAbilities: ["Sabedoria"],
    savingThrows: ["Inteligência", "Sabedoria"],
    armorProficiencies: ["Armaduras leves", "Armaduras médias", "Escudos (não-metálicos)"],
    weaponProficiencies: ["Clavas", "Adagas", "Dardos", "Azagaias", "Maças", "Bordões", "Cimitarras", "Foices", "Fundas", "Lanças"],
    toolProficiencies: ["Kit de herbalismo"],
    skillChoices: ["Arcanismo", "Adestrar Animais", "Intuição", "Medicina", "Natureza", "Percepção", "Religião", "Sobrevivência"],
    skillCount: 2,
    startingEquipment: [
      "(a) um escudo de madeira ou (b) qualquer arma simples",
      "(a) uma cimitarra ou (b) qualquer arma corpo-a-corpo simples",
      "(a) um pacote de estudioso ou (b) um pacote de explorador",
      "Armadura de couro, um pacote de aventureiro e um foco druídico",
    ],
    startingGold: "2d4 × 10 po",
    keyFeatures: [
      "Druídico — Conhece o idioma secreto dos druidas",
      "Conjuração — Prepara magias; habilidade Sabedoria",
      "Forma Selvagem (2°) — Transforma-se em besta vista antes; 2 usos por descanso",
      "Círculo Druídico (2°) — Escolha de subclasse",
      "Corpo Atemporal (18°) — Envelhece 10x mais devagar; não precisa de comida/água",
      "Magias da Besta (18°) — Conjura magias em forma de besta",
      "Arquidruida (20°) — Forma Selvagem ilimitada",
    ],
    subclasses: [
      {
        id: "circulo-terra",
        name: "Círculo da Terra",
        description: "Místicos e sábios que salvaguardam conhecimento e ritos antigos através da tradição oral.",
        features: [
          "Truque Adicional (2°) — Um truque de druida extra",
          "Recuperação Natural (2°) — Recupera espaços de magia em descanso curto",
          "Magias de Círculo (3°+) — Magias bônus baseadas no terreno escolhido (ártico, costa, floresta etc.)",
          "Caminho da Floresta (6°) — Ignora terreno difícil não-mágico; passa por plantas sem dano",
          "Proteção Natural (10°) — Imune a ser enfeitiçado/amedrontado por elementais/fadas; imune a veneno e doenças",
          "Santuário Natural (14°) — Bestas/plantas devem superar resistência de Sabedoria para atacar você",
        ],
      },
      {
        id: "circulo-lua",
        name: "Círculo da Lua",
        description: "Ferrenhos guardiões da natureza que se reúnem em noites de lua cheia. Mestres da Forma Selvagem.",
        features: [
          "Forma Selvagem de Combate (2°) — Forma Selvagem como ação bônus; gasta espaço para curar",
          "Formas de Círculo (2°) — Transforma em bestas de ND 1 (cresce com nível)",
          "Ataque Primordial (6°) — Ataques em forma de besta contam como mágicos",
          "Forma Selvagem de Elemental (10°) — Gasta 2 usos para virar elemental",
          "Mil Formas (14°) — Conjura alterar-se à vontade",
        ],
      },
    ],
    spellcasting: true,
    spellcastingAbility: "Sabedoria",
  },

  {
    id: "feiticeiro",
    name: "Feiticeiro",
    icon: "🔮",
    description: "Um conjurador que possui magia latente advinda de um dom ou linhagem.",
    flavor: "Carregam magia inata que ninguém escolhe: os poderes escolhem o feiticeiro. Não usam grimórios nem patronos — exploram sua própria magia.",
    hitDie: 6,
    primaryAbilities: ["Carisma"],
    savingThrows: ["Constituição", "Carisma"],
    armorProficiencies: [],
    weaponProficiencies: ["Adagas", "Dardos", "Fundas", "Bordões", "Bestas leves"],
    toolProficiencies: [],
    skillChoices: ["Arcanismo", "Enganação", "Intuição", "Intimidação", "Persuasão", "Religião"],
    skillCount: 2,
    startingEquipment: [
      "(a) uma besta leve e 20 virotes ou (b) qualquer arma simples",
      "(a) uma bolsa de componentes ou (b) um foco arcano",
      "(a) um pacote de explorador ou (b) um pacote de aventureiro",
    ],
    startingGold: "3d4 × 10 po",
    keyFeatures: [
      "Conjuração — Magias conhecidas; habilidade Carisma",
      "Origem de Feitiçaria (1°) — Escolha de subclasse",
      "Fonte de Magia (2°) — Pontos de Feitiçaria para criar espaços ou ganhar pontos",
      "Conjuração Flexível (2°) — Converte espaços em pontos e vice-versa",
      "Metamágica (3°) — Distorce magias: Acelerada, Aumentada, Cuidadosa, Distante, Duplicada, Estendida, Potencializada, Sutil",
      "Restauração Mística (20°) — Recupera 4 pontos de feitiçaria em descanso curto",
    ],
    subclasses: [
      {
        id: "linhagem-draconica",
        name: "Linhagem Dracônica",
        description: "Magia inata de linhagem de dragão. Escolha um ancestral dracônico (Azul, Branco, Bronze, etc.) que define tipo de dano.",
        features: [
          "Ancestral Dracônico (1°) — Língua Dracônica; bônus dobrado em Carisma com dragões",
          "Resiliência Dracônica (1°) — +1 PV por nível; CA 13 + Destreza sem armadura",
          "Afinidade Elemental (6°) — Adiciona mod. Carisma ao dano do tipo do ancestral",
          "Asas de Dragão (14°) — Ação bônus para invocar asas e ganhar voo",
          "Presença Dracônica (18°) — 5 pontos para aura de admiração/medo de 18m",
        ],
      },
      {
        id: "magia-selvagem",
        name: "Magia Selvagem",
        description: "Magia caótica das forças brutas da criação. Pode liberar surtos imprevisíveis de efeitos mágicos.",
        features: [
          "Surto de Magia Selvagem (1°) — Após conjurar, pode rolar na tabela de 100 efeitos aleatórios",
          "Marés de Caos (1°) — Uma vez por descanso longo, vantagem em rolagem",
          "Dobrar a Sorte (6°) — Reação: gasta 2 pontos para rolar 1d4 como bônus/penalidade em rolagem alheia",
          "Caos Controlado (14°) — Rola dois vezes na tabela de Surto e escolhe",
          "Bombardeio de Magia (18°) — Quando rola dano máximo num dado, rola de novo e soma",
        ],
      },
    ],
    spellcasting: true,
    spellcastingAbility: "Carisma",
  },

  {
    id: "guerreiro",
    name: "Guerreiro",
    icon: "⚔️",
    description: "Um mestre do combate, perito em uma vasta gama de armas e armaduras.",
    flavor: "Cavaleiros, lordes conquistadores, campeões reais, mercenários — todos compartilham maestria sem precedentes com armas e armaduras.",
    hitDie: 10,
    primaryAbilities: ["Força", "Destreza"],
    savingThrows: ["Força", "Constituição"],
    armorProficiencies: ["Todas as armaduras", "Escudos"],
    weaponProficiencies: ["Armas simples", "Armas marciais"],
    toolProficiencies: [],
    skillChoices: ["Acrobacia", "Adestrar Animais", "Atletismo", "História", "Intuição", "Intimidação", "Percepção", "Sobrevivência"],
    skillCount: 2,
    startingEquipment: [
      "(a) cota de malha ou (b) gibão de peles, arco longo e 20 flechas",
      "(a) uma arma marcial e um escudo ou (b) duas armas marciais",
      "(a) uma besta leve e 20 virotes ou (b) dois machados de arremesso",
      "(a) um pacote de aventureiro ou (b) um pacote de explorador",
    ],
    startingGold: "5d4 × 10 po",
    keyFeatures: [
      "Estilo de Luta (1°) — Especialize em: Arquearia, Combate com Armas Grandes, Combate com Duas Armas, Defesa, Duelismo ou Proteção",
      "Retomar o Fôlego (1°) — Ação bônus para recuperar 1d10 + nível de PV",
      "Surto de Ação (2°) — Ação adicional uma vez por descanso",
      "Arquétipo Marcial (3°) — Escolha de subclasse",
      "Ataque Extra (5°) — 2 ataques; sobe para 3 no 11° e 4 no 20°",
      "Indomável (9°) — Refaz teste de resistência que falhou; até 3 usos no 17°",
    ],
    subclasses: [
      {
        id: "campeao",
        name: "Campeão",
        description: "Foco no desenvolvimento da pura força física e perfeição mortal.",
        features: [
          "Crítico Aprimorado (3°) — Crítico em 19-20",
          "Atletismo Extraordinário (7°) — Adiciona metade do bônus de proficiência a testes de Força/Des/Con",
          "Estilo de Luta Adicional (10°) — Escolhe um segundo estilo de luta",
          "Crítico Superior (15°) — Crítico em 18-20",
          "Sobrevivente (18°) — Recupera 5 + mod. Con PV no início do turno se abaixo de metade",
        ],
      },
      {
        id: "cavaleiro-arcano",
        name: "Cavaleiro Arcano",
        description: "Combina maestria marcial com estudo cuidadoso de magia (abjuração e evocação de mago).",
        features: [
          "Conjuração (3°) — Magias de mago com Inteligência; foco em abjuração e evocação",
          "Vínculo com Arma (3°) — Ritual para vincular arma (não pode ser desarmado; pode invocar)",
          "Magia de Guerra (7°) — Ao usar truque, pode atacar com arma como ação bônus",
          "Golpe Místico (10°) — Após acertar, criatura tem desvantagem na próxima resistência sua",
          "Investida Arcana (15°) — Teletransporta 9m ao usar Surto de Ação",
          "Magia de Guerra Aprimorada (18°) — Ao conjurar magia, pode atacar como ação bônus",
        ],
      },
      {
        id: "mestre-batalha",
        name: "Mestre de Batalha",
        description: "Emprega técnicas marciais geração após geração. O combate é um campo acadêmico.",
        features: [
          "Superioridade em Combate (3°) — 4 dados de superioridade (d8) e 3 manobras",
          "Estudioso da Guerra (3°) — Proficiência com ferramenta de artesão",
          "Conheça seu Inimigo (7°) — Após 1 min. observando, aprende comparativos de habilidade",
          "Superioridade Aprimorada (10°) — Dados viram d10; d12 no 18°",
          "Implacável (15°) — Ao rolar iniciativa sem dados, recupera um",
          "Manobras disponíveis — Aparar, Ataque Ameaçador, Ataque de Encontrão, Ataque de Finta, Ataque de Manobra, Ataque de Precisão, Derrubar, Golpe Distrativo, Golpe do Comandante, Contra-Atacar e mais",
        ],
      },
    ],
    spellcasting: false,
    spellcastingAbility: null,
  },

  {
    id: "ladino",
    name: "Ladino",
    icon: "🗡️",
    description: "Um trapaceiro que utiliza de furtividade e astúcia para sobrepujar os obstáculos e inimigos.",
    flavor: "Contam com perícia, furtividade e as vulnerabilidades dos inimigos. Priorizam o ataque preciso no lugar certo em vez de força bruta.",
    hitDie: 8,
    primaryAbilities: ["Destreza"],
    savingThrows: ["Destreza", "Inteligência"],
    armorProficiencies: ["Armaduras leves"],
    weaponProficiencies: ["Armas simples", "Bestas de mão", "Espadas longas", "Rapieiras", "Espadas curtas"],
    toolProficiencies: ["Ferramentas de ladrão"],
    skillChoices: ["Acrobacia", "Atletismo", "Atuação", "Enganação", "Furtividade", "Intimidação", "Intuição", "Investigação", "Percepção", "Persuasão", "Prestidigitação"],
    skillCount: 4,
    startingEquipment: [
      "(a) uma rapieira ou (b) uma espada longa",
      "(a) um arco curto e 20 flechas ou (b) uma espada curta",
      "(a) um pacote de assaltante, (b) um pacote de aventureiro ou (c) um pacote de explorador",
      "Armadura de couro, duas adagas e ferramentas de ladrão",
    ],
    startingGold: "4d4 × 10 po",
    keyFeatures: [
      "Especialização (1°) — Dobra bônus de proficiência em duas perícias; +2 no 6°",
      "Ataque Furtivo (1°) — 1d6 extra (cresce até 10d6 no 20°) com vantagem ou aliado próximo",
      "Gíria de Ladrão (1°) — Idioma secreto dos ladrões",
      "Ação Ardilosa (2°) — Ação bônus para Disparada, Desengajar ou Esconder",
      "Arquétipo de Ladino (3°) — Escolha de subclasse",
      "Esquiva Sobrenatural (5°) — Reação para reduzir dano à metade",
      "Evasão (7°) — Sem dano em resistência de Destreza bem-sucedida",
      "Talento Confiável (11°) — Resultado 9 ou menos no d20 = 10 em testes com proficiência",
      "Sentido Cego (14°) — Detecta criaturas escondidas/invisíveis a 3m se puder ouvir",
      "Mente Escorregadia (15°) — Proficiência em resistência de Sabedoria",
      "Elusivo (18°) — Nenhum ataque tem vantagem contra você",
      "Golpe de Sorte (20°) — Transforma falha em acerto ou trata d20 como 20",
    ],
    subclasses: [
      {
        id: "assassino",
        name: "Assassino",
        description: "Focado na arte da morte. Usa subterfúgio, veneno e disfarces para eliminar oponentes.",
        features: [
          "Proficiência Adicional (3°) — Kit de disfarce e kit de venenos",
          "Assassinar (3°) — Vantagem contra criaturas que ainda não agiram; crítico em surpresa",
          "Especialização em Infiltração (9°) — Cria identidades falsas infalíveis",
          "Impostor (13°) — Imita fala, escrita e comportamento de pessoa após 3h de estudo",
          "Golpe Letal (17°) — Criatura surpresa deve resistir ou sofrer dano duplicado",
        ],
      },
      {
        id: "ladrao",
        name: "Ladrão",
        description: "Arte do furto. Habilidades para desbravar ruínas antigas e usar itens mágicos.",
        features: [
          "Mãos Rápidas (3°) — Ação bônus para Prestidigitação, ferramentas de ladrão ou Usar Objeto",
          "Andarilho de Telhados (3°) — Escalar sem custo extra; salto maior",
          "Furtividade Suprema (9°) — Vantagem em Furtividade ao se mover até metade do deslocamento",
          "Usar Instrumento Mágico (13°) — Ignora requisitos de classes/raças em itens mágicos",
          "Reflexos de Ladrão (17°) — Dois turnos no primeiro turno de combate",
        ],
      },
      {
        id: "trapaceiro-arcano",
        name: "Trapaceiro Arcano",
        description: "Combina furtividade com truques de encantamento e ilusão de mago.",
        features: [
          "Conjuração (3°) — Magias de mago com Inteligência; foco em encantamento/ilusão",
          "Mãos Mágicas Malabaristas (3°) — Mãos mágicas invisíveis para tarefas extras",
          "Emboscada Mágica (9°) — Escondido ao conjurar: criatura tem desvantagem na resistência",
          "Trapaceiro Versátil (13°) — Ação bônus para vantagem em ataque via mãos mágicas",
          "Ladrão de Magia (17°) — Reação para roubar magia que foi conjurada contra você",
        ],
      },
    ],
    spellcasting: false,
    spellcastingAbility: null,
  },

  {
    id: "mago",
    name: "Mago",
    icon: "📚",
    description: "Um usuário de magia escolado, capaz de manipular as estruturas da realidade.",
    flavor: "Usuários de magia soberanos que conjuram magias explosivas de fogo, relâmpagos, ilusões, controle de mentes e transformações da realidade.",
    hitDie: 6,
    primaryAbilities: ["Inteligência"],
    savingThrows: ["Inteligência", "Sabedoria"],
    armorProficiencies: [],
    weaponProficiencies: ["Adagas", "Dardos", "Fundas", "Bordões", "Bestas leves"],
    toolProficiencies: [],
    skillChoices: ["Arcanismo", "História", "Intuição", "Investigação", "Medicina", "Religião"],
    skillCount: 2,
    startingEquipment: [
      "(a) um bordão ou (b) uma adaga",
      "(a) uma bolsa de componentes ou (b) um foco arcano",
      "(a) um pacote de estudioso ou (b) um pacote de explorador",
      "Um grimório (com 6 magias de 1° nível)",
    ],
    startingGold: "4d4 × 10 po",
    keyFeatures: [
      "Conjuração — Prepara magias do grimório; habilidade Inteligência",
      "Grimório (1°) — Livro de magias com 6 de 1° nível; +2 por nível",
      "Recuperação Arcana (1°) — Uma vez por dia, recupera espaços em descanso curto",
      "Tradição Arcana (2°) — Escolha de subclasse (escola de magia)",
      "Dominar Magia (18°) — Conjura magia de 1° e 2° escolhidas à vontade",
      "Assinatura Mágica (20°) — Duas magias de 3° nível sempre preparadas e 1x/dia sem espaço",
    ],
    subclasses: [
      {
        id: "escola-abjuracao",
        name: "Escola de Abjuração",
        description: "Especialistas em magias que bloqueiam, expulsam ou protegem. Chamados de abjuradores.",
        features: [
          "Abjuração Instruída (2°) — Metade do custo para copiar magias de abjuração",
          "Proteção Arcana (2°) — Cria proteção mágica que absorve dano (2 × nível + Int)",
          "Proteção Projetada (6°) — Proteção pode absorver dano de aliados próximos",
          "Abjuração Aprimorada (10°) — Adiciona bônus de proficiência a testes de habilidade de abjuração",
          "Resistência à Magia (14°) — Vantagem vs magias e resistência a dano mágico",
        ],
      },
      {
        id: "escola-adivinhacao",
        name: "Escola de Adivinhação",
        description: "Separam os véus do espaço, tempo e consciência para ver claramente.",
        features: [
          "Adivinhação Instruída (2°) — Metade do custo para copiar magias de adivinhação",
          "Prodígio (2°) — Rola 2d20 em descanso longo para substituir rolagens futuras",
          "Especialista em Adivinhação (6°) — Ao conjurar adivinhação de 2°+, recupera espaço menor",
          "O Terceiro Olho (10°) — Ação para Visão no Escuro, Visão Etérea, Compreensão Maior ou Ver Invisibilidade",
          "Prodígio Maior (14°) — Rola três dados para o Prodígio",
        ],
      },
      {
        id: "escola-conjuracao",
        name: "Escola de Conjuração",
        description: "Produzem objetos e criaturas do nada. Teletransportação e viagens entre planos.",
        features: [
          "Conjuração Instruída (2°) — Metade do custo para copiar magias de conjuração",
          "Conjuração Menor (2°) — Ação para criar objeto inanimado pequeno",
          "Transposição Benigna (6°) — Teletransporta 9m ou troca com criatura voluntária",
          "Conjuração Focada (10°) — Concentração em magia de conjuração não é interrompida por dano",
          "Invocações Resistentes (14°) — Criaturas invocadas ganham 30 PV temporários",
        ],
      },
      {
        id: "escola-encantamento",
        name: "Escola de Encantamento",
        description: "Entram magicamente na mente e seduzem pessoas e monstros.",
        features: [
          "Encantamento Instruído (2°) — Metade do custo para copiar magias de encantamento",
          "Olhar Hipnotizante (2°) — Ação para paralisar criatura a 1,5m (resistência de Sabedoria)",
          "Encanto Instintivo (6°) — Reação para desviar ataque para outro alvo",
          "Dividir Encantamento (10°) — Magia de encantamento de alvo único afeta segundo alvo",
          "Alterar Memórias (14°) — Criatura enfeitiçada esquece parte do período",
        ],
      },
      {
        id: "escola-evocacao",
        name: "Escola de Evocação",
        description: "Criam poderosos efeitos elementais: fogo, gelo, trovão, relâmpago, ácido.",
        features: [
          "Evocação Instruída (2°) — Metade do custo para copiar magias de evocação",
          "Esculpir Magias (2°) — Protege criaturas escolhidas das próprias magias de área",
          "Truque Potente (6°) — Criaturas que passam em resistência de truque sofrem metade do dano",
          "Evocação Potencializada (10°) — Adiciona mod. Inteligência ao dano de evocações de mago",
          "Sobrecarga (14°) — Magia de 5° ou menor causa dano máximo (com custo em descanso longo)",
        ],
      },
      {
        id: "escola-ilusao",
        name: "Escola de Ilusão",
        description: "Ofuscam sentidos, confundem mentes e enganam até os mais sábios.",
        features: [
          "Ilusão Instruída (2°) — Metade do custo para copiar magias de ilusão",
          "Ilusão Menor Aprimorada (2°) — Ilusão menor cria som E imagem simultaneamente",
          "Ilusões Moldáveis (6°) — Muda ilusão duradoura com ação",
          "Eu Ilusório (10°) — Reação para interpor duplicata e anular ataque",
          "Realidade Ilusória (14°) — Torna objeto inanimado de ilusão real por 1 minuto",
        ],
      },
      {
        id: "escola-necromancia",
        name: "Escola de Necromancia",
        description: "Exploram as forças cósmicas da vida, morte e morte-vida.",
        features: [
          "Necromancia Instruída (2°) — Metade do custo para copiar magias de necromancia",
          "Colheita Sinistra (2°) — Recupera PV ao matar criaturas com magias",
          "Escravos Mortos-Vivos (6°) — Animar mortos cria dois mortos-vivos; eles ficam mais fortes",
          "Acostumado à Morte-Vida (10°) — Resistência a dano necrótico; máximo de PV não reduz",
          "Comandar Mortos-Vivos (14°) — Ação para tentar controlar morto-vivo de outro conjurador",
        ],
      },
      {
        id: "escola-transmutacao",
        name: "Escola de Transmutação",
        description: "Modificam energia e matéria. O mundo é eminentemente mutável.",
        features: [
          "Transmutação Instruída (2°) — Metade do custo para copiar magias de transmutação",
          "Alquimia Menor (2°) — Altera temporariamente material (madeira, pedra, ferro etc.)",
          "Pedra de Transmutador (6°) — Cria pedra com benefício à escolha para quem a carrega",
          "Metamorfo (10°) — Conjura metamorfose em si mesmo sem espaço 1x por descanso",
          "Mestre Transmutador (14°) — Consome pedra para efeito: transformação, panaceia, reviver ou restaurar juventude",
        ],
      },
    ],
    spellcasting: true,
    spellcastingAbility: "Inteligência",
  },

  {
    id: "monge",
    name: "Monge",
    icon: "👊",
    description: "Um mestre das artes marciais, utilizando o poder corporal para atingir a perfeição física e espiritual.",
    flavor: "Atrelam o chi para criar efeitos mágicos e exceder a capacidade física. Canalizam velocidade e força incríveis em ataques desarmados.",
    hitDie: 8,
    primaryAbilities: ["Destreza", "Sabedoria"],
    savingThrows: ["Força", "Destreza"],
    armorProficiencies: [],
    weaponProficiencies: ["Armas simples", "Espadas curtas"],
    toolProficiencies: ["Um tipo de ferramenta de artesão ou instrumento musical"],
    skillChoices: ["Acrobacia", "Atletismo", "Furtividade", "História", "Intuição", "Religião"],
    skillCount: 2,
    startingEquipment: [
      "(a) uma espada curta ou (b) qualquer arma simples",
      "(a) um pacote de explorador ou (b) um pacote de aventureiro",
      "10 dardos",
    ],
    startingGold: "5d4 po",
    keyFeatures: [
      "Defesa sem Armadura (1°) — CA = 10 + Des + Sab sem armadura",
      "Artes Marciais (1°) — Usa Destreza em ataques; dano 1d4→1d10 por nível",
      "Chi (2°) — Pontos de chi para Rajada de Golpes, Defesa Paciente, Passo do Vento",
      "Movimento sem Armadura (2°) — +3m a +9m de deslocamento ao longo dos níveis",
      "Tradição Monástica (3°) — Escolha de subclasse",
      "Defletir Projéteis (3°) — Reação para reduzir dano de projétil; pode arremessar de volta",
      "Ataque Extra (5°) — Ataque duas vezes por ação",
      "Ataque Atordoante (5°) — Gasta 1 chi: alvo resiste Constituição ou fica atordoado",
      "Golpes de Chi (6°) — Ataques desarmados contam como mágicos",
      "Evasão (7°) — Sem dano em resistência de Destreza bem-sucedida",
      "Pureza Corporal (10°) — Imune a doenças e venenos",
      "Alma de Diamante (14°) — Proficiência em todas as resistências",
      "Corpo Atemporal (15°) — Não envelhece nem magicamente; não precisa de comida/água",
      "Auto Aperfeiçoamento (20°) — Ao rolar iniciativa sem chi, recupera 4 pontos",
    ],
    subclasses: [
      {
        id: "caminho-mao-aberta",
        name: "Caminho da Mão Aberta",
        description: "Mestres supremos das artes marciais. Manipulam o chi do inimigo para derrubar, empurrar ou paralisar.",
        features: [
          "Técnica da Mão Aberta (3°) — Ataques de Rajada de Golpes podem derrubar, empurrar ou negar reações",
          "Integridade Corporal (6°) — Ação para se curar (3 × nível de monge PV)",
          "Tranquilidade (11°) — Aura de santuário ao fim de descanso longo",
          "Palma Vibrante (17°) — Ataques criam vibrações letais que podem matar ou causar 10d10 necrótico",
        ],
      },
      {
        id: "caminho-sombra",
        name: "Caminho da Sombra",
        description: "Valoriza furtividade e subterfúgio. Ninjas e dançarinos das sombras que servem como espiões.",
        features: [
          "Artes Sombrias (3°) — Gasta chi para escuridão, visão no escuro, passos sem pegadas ou silêncio",
          "Passo das Sombras (6°) — Ação bônus para teletransportar entre sombras até 18m",
          "Manto de Sombras (11°) — Ação para ficar invisível em penumbra/escuridão",
          "Oportunista (17°) — Reação para atacar criatura a 1,5m que foi atingida por aliado",
        ],
      },
      {
        id: "caminho-quatro-elementos",
        name: "Caminho dos Quatro Elementos",
        description: "Domina os elementos: água, ar, fogo e terra através de disciplinas mágicas de chi.",
        features: [
          "Discípulo dos Elementos (3°) — Aprende disciplinas elementais (Chicote de Água, Mãos Flamejantes, etc.)",
          "Disciplinas adicionais no 6°, 11° e 17° nível",
          "Exemplos: Golpe de Varredura Cauterizante, Punho dos Quatro Trovões, Serragem do Vento do Norte, Chamas da Fênix, Defesa Eterna da Montanha",
        ],
      },
    ],
    spellcasting: false,
    spellcastingAbility: null,
  },

  {
    id: "paladino",
    name: "Paladino",
    icon: "🛡️",
    description: "Um guerreiro divino vinculado a um juramento sagrado.",
    flavor: "Unidos pelos juramentos de se imporem contra as forças do mal. O poder vem tanto do comprometimento com a justiça quanto de um deus.",
    hitDie: 10,
    primaryAbilities: ["Força", "Carisma"],
    savingThrows: ["Sabedoria", "Carisma"],
    armorProficiencies: ["Todas as armaduras", "Escudos"],
    weaponProficiencies: ["Armas simples", "Armas marciais"],
    toolProficiencies: [],
    skillChoices: ["Atletismo", "Intuição", "Intimidação", "Medicina", "Persuasão", "Religião"],
    skillCount: 2,
    startingEquipment: [
      "(a) uma arma marcial e um escudo ou (b) duas armas marciais",
      "(a) cinco azagaias ou (b) qualquer arma simples corpo-a-corpo",
      "(a) um pacote de sacerdote ou (b) um pacote de aventureiro",
      "Cota de malha e um símbolo sagrado",
    ],
    startingGold: "5d4 × 10 po",
    keyFeatures: [
      "Sentido Divino (1°) — Detecta celestiais, corruptores, mortos-vivos e locais sagrados/profanos a 18m",
      "Cura pelas Mãos (1°) — Reserva de cura de 5 × nível; cura doenças e venenos",
      "Estilo de Luta (2°) — Combate com Armas Grandes, Defesa, Duelismo ou Proteção",
      "Conjuração (2°) — Prepara magias; habilidade Carisma",
      "Destruição Divina (2°) — Gasta espaço de magia para +2d8 dano radiante por ataque (cresce até 5d8)",
      "Saúde Divina (3°) — Imune a doenças",
      "Juramento Sagrado (3°) — Escolha de subclasse com Canalizar Divindade",
      "Ataque Extra (5°) — Ataque duas vezes por ação",
      "Aura de Proteção (6°) — Aliados a 3m (→9m no 18°) ganham mod. Carisma em resistências",
      "Aura da Coragem (10°) — Aliados a 3m (→9m no 18°) não podem ser amedrontados",
      "Destruição Divina Aprimorada (11°) — Todos ataques corpo-a-corpo causam +1d8 radiante",
      "Toque Purificador (14°) — Ação para terminar magia em si ou aliado voluntário",
    ],
    subclasses: [
      {
        id: "juramento-devocao",
        name: "Juramento de Devoção",
        description: "Vinculado aos mais sublimes ideais de justiça, virtude e ordem. O cavaleiro na armadura brilhante.",
        features: [
          "Arma Sagrada (3°/CD) — Imbuí arma com energia positiva: +Carisma em ataques e luz",
          "Expulsar o Profano (3°/CD) — Expulsa corruptores e mortos-vivos que falhem em Sabedoria",
          "Aura de Devoção (7°) — Aliados próximos não podem ser enfeitiçados",
          "Pureza de Espírito (15°) — Sempre sob proteção contra o bem e mal",
          "Halo Sagrado (20°) — Aura de luz solar: inimigos sofrem 10 radiante; vantagem vs corruptores",
        ],
      },
      {
        id: "juramento-anciaos",
        name: "Juramento dos Anciões",
        description: "Vincula-se ao lado da luz por amor às coisas belas. Cavaleiros feéricos, verdejantes.",
        features: [
          "Fúria da Natureza (3°/CD) — Vinhas espectrais impedem criatura (resistência de Força/Destreza)",
          "Expulsar os Infiéis (3°/CD) — Expulsa fadas e corruptores",
          "Aura de Vigilância (7°) — Aliados têm resistência a dano mágico",
          "Sentinela Imortal (15°) — 1x por descanso: cai para 1 PV em vez de 0; não envelhece",
          "Campeão dos Anciões (20°) — Transformação: recupera PV, conjura como bônus, inimigos têm desvantagem",
        ],
      },
      {
        id: "juramento-vinganca",
        name: "Juramento de Vingança",
        description: "Comprometimento solene para punir os que cometeram grandes pecados. Vingadores e cavaleiros negros.",
        features: [
          "Abjurar Inimigo (3°/CD) — Amedrontado com deslocamento 0 em falha (desvantagem para corruptores/mortos)",
          "Voto de Inimizade (3°/CD) — Ação bônus para vantagem em ataques contra criatura a 3m",
          "Vingador Implacável (7°) — Após ataque de oportunidade, move metade do deslocamento",
          "Alma de Vingança (15°) — Reação para atacar criatura que ataca durante Voto de Inimizade",
          "Anjo Vingador (20°) — 1 hora: voo 18m e aura de medo de 9m",
        ],
      },
    ],
    spellcasting: true,
    spellcastingAbility: "Carisma",
  },

  {
    id: "patrulheiro",
    name: "Patrulheiro",
    icon: "🏹",
    description: "Um guerreiro que utiliza de poderio marcial e magia natural para combater ameaças nos limites da civilização.",
    flavor: "Longe das cidades e vilas, entre as árvores de florestas sem trilhas, os patrulheiros mantêm sua vigília interminável contra monstros e hordas.",
    hitDie: 10,
    primaryAbilities: ["Destreza", "Sabedoria"],
    savingThrows: ["Força", "Destreza"],
    armorProficiencies: ["Armaduras leves", "Armaduras médias", "Escudos"],
    weaponProficiencies: ["Armas simples", "Armas marciais"],
    toolProficiencies: [],
    skillChoices: ["Adestrar Animais", "Atletismo", "Furtividade", "Intuição", "Investigação", "Natureza", "Percepção", "Sobrevivência"],
    skillCount: 3,
    startingEquipment: [
      "(a) brunea ou (b) armadura de couro",
      "(a) duas espadas curtas ou (b) duas armas simples corpo-a-corpo",
      "(a) um pacote de explorador ou (b) um pacote de aventureiro",
      "Um arco longo e uma aljava com 20 flechas",
    ],
    startingGold: "5d4 × 10 po",
    keyFeatures: [
      "Inimigo Favorito (1°) — +2 dano e vantagem em rastrear/lembrar inimigo escolhido",
      "Explorador Natural (1°) — Ignora terreno difícil; vantagem em iniciativa; grupo não se perde",
      "Estilo de Luta (2°) — Arquearia, Combate com Duas Armas, Defesa ou Duelismo",
      "Conjuração (2°) — Magias conhecidas; habilidade Sabedoria",
      "Conclave de Patrulheiro (3°) — Escolha de subclasse",
      "Consciência Primitiva (3°) — Comunica-se com bestas; detecta inimigos favoritos a 8 km",
      "Inimigo Favorito Maior (6°) — Segundo inimigo favorito; bônus de dano sobe para +4",
      "Pés Rápidos (8°) — Disparada como ação bônus",
      "Mimetismo (10°) — Quando imóvel, -10 em testes de percepção de inimigos",
      "Desaparecer (14°) — Esconder como ação bônus; não pode ser rastreado não-magicamente",
      "Sentidos Selvagens (18°) — Ataca sem desvantagem criaturas invisíveis; detecta invisíveis a 9m",
      "Matador de Inimigos (20°) — 1x por turno adiciona mod. Sabedoria a ataque ou dano",
    ],
    subclasses: [
      {
        id: "conclave-besta",
        name: "Conclave da Besta",
        description: "Desenvolve um vínculo poderoso com um companheiro animal através de magia.",
        features: [
          "Companheiro Animal (3°) — Invoca besta companheira com vínculo especial de 8h (50 po)",
          "Vínculo com o Companheiro (3°) — Companheiro usa seu bônus de proficiência; obedece comandos",
          "Ataque Coordenado (5°) — Companheiro usa reação para atacar quando você usa ação de Ataque",
          "Defesa da Besta (7°) — Companheiro tem vantagem em todas as resistências enquanto te vê",
          "Tempestade de Garras e Presas (11°) — Companheiro ataca todas as criaturas a 1,5m",
          "Defesa da Besta Superior (15°) — Companheiro pode reduzir dano à metade com reação",
        ],
      },
      {
        id: "conclave-cacador",
        name: "Conclave do Caçador",
        description: "Técnicas especializadas contra as mais terríveis ameaças: ogros, hordas, gigantes, dragões.",
        features: [
          "Presa do Caçador (3°) — Escolha: Assassino de Colossos, Matador de Gigantes ou Destruidor de Hordas",
          "Ataque Extra (5°) — Ataque duas vezes por ação",
          "Táticas Defensivas (7°) — Escolha: Escapar da Horda, Defesa Contra Múltiplos Ataques ou Vontade de Aço",
          "Ataque Múltiplo (11°) — Saraivada (à distância) ou Ataque Giratório (corpo-a-corpo)",
          "Defesa de Caçador Superior (15°) — Evasão, Manter-se Contra a Maré ou Esquiva Sobrenatural",
        ],
      },
      {
        id: "conclave-rastreador-subterraneo",
        name: "Conclave do Rastreador Subterrâneo",
        description: "Especialistas em descobrir e derrotar ameaças ocultas abaixo da terra.",
        features: [
          "Batedor do Subterrâneo (3°) — No 1° turno: +3m e ataque adicional; evita vantagem de visão no escuro",
          "Magia do Rastreador Subterrâneo (3°) — Visão no escuro 27m e magias bônus por nível",
          "Ataque Extra (5°) — Ataque duas vezes por ação",
          "Mente de Aço (7°) — Proficiência em resistência de Sabedoria",
          "Rajada do Rastreador (11°) — Ao errar ataque, pode realizar outro",
          "Esquiva do Rastreador (15°) — Reação para impor desvantagem em ataque contra você",
        ],
      },
    ],
    spellcasting: true,
    spellcastingAbility: "Sabedoria",
  },
];

export const CLASS_LABELS: Record<string, string> = {
  barbaro:    "Bárbaro",
  bardo:      "Bardo",
  bruxo:      "Bruxo",
  clerigo:    "Clérigo",
  druida:     "Druida",
  feiticeiro: "Feiticeiro",
  guerreiro:  "Guerreiro",
  ladino:     "Ladino",
  mago:       "Mago",
  monge:      "Monge",
  paladino:   "Paladino",
  patrulheiro: "Patrulheiro",
};

export function getHitDieLabel(die: number): string {
  return `d${die}`;
}
