import type { StarWarsCreature } from "./types";

export const CIVIS: StarWarsCreature[] = [
  // ─── 1. Criminosos ────────────────────────────────────────────────────
  {
    id: "civil-criminoso-rua",
    book: "civis",
    name: "Criminoso de Rua",
    category: "Civil",
    faction: "Independente",
    level: 5,
    threat: "Fraco",
    role: "Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Variável (baixos-fundos urbanos)",
    environment: "Cidades",
    intelligence: "Média",
    disposition: "Oportunista",
    pv: 20,
    pe: 8,
    defense: 17,
    initiative: 4,
    speed: "9m",
    attrs: { agi: 3, int: 0, forc: 2, vig: 1, pre: 0, sen: 0 },
    skills: "Furtividade (Treinado), Intimidação (Iniciante)",
    attacks: [
      { name: "Pistola Improvisada", range: "12m", hit: "AGI+8", damage: "2d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "—" },
      { name: "Faca", range: "Corpo a corpo", hit: "AGI+8", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "—" },
    ],
    powers: [],
    passives: [
      { name: "Conhece os Becos", effect: "vantagem em Furtividade dentro do próprio território urbano." },
    ],
    ai: "Ataca em grupo (2–4), prefere emboscada e roubo rápido a combate prolongado. Foge se a vítima resistir com força desproporcional — não vale o risco.",
    loot: "Créditos roubados, pistola improvisada, itens de vítimas anteriores (ganchos de história).",
    lore: "A base da criminalidade urbana comum — desesperados, oportunistas ou simplesmente sem outra opção nos níveis mais baixos das megacidades da galáxia.",
  },
  {
    id: "civil-mercenario",
    book: "civis",
    name: "Mercenário",
    category: "Civil",
    faction: "Independente/Companhia contratada",
    level: 12,
    threat: "Médio",
    role: "Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Variável",
    environment: "Qualquer (zona de conflito paga)",
    intelligence: "Alta",
    disposition: "Calculista",
    pv: 52,
    pe: 20,
    defense: 19,
    initiative: 6,
    speed: "9m",
    attrs: { agi: 4, int: 2, forc: 3, vig: 4, pre: 1, sen: 0 },
    skills: "Armas de Energia (Treinado), Atletismo (Treinado), Percepção (Treinado)",
    attacks: [
      { name: "Rifle Blaster de Combate", range: "30m", hit: "AGI+14", damage: "2d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "—" },
      { name: "Granada de Fragmentação", range: "15m (área 4m)", hit: "AGI+14", damage: "2d6", damageType: "Explosivo", cost: "2 PE", cooldown: "3 rodadas", effect: "—" },
    ],
    powers: [],
    passives: [
      { name: "Profissional Pago", effect: "nunca luta além do que o contrato cobre; se o pagamento for ameaçado ou o risco superar muito o valor, negocia recuo ou troca de lado." },
    ],
    ai: "Combate competente e frio — sem heroísmo nem crueldade gratuita, só eficiência. Avalia risco/recompensa constantemente; se o empregador não pagar ou a missão virar suicida, o contrato \"acaba\" ali.",
    loot: "Rifle de combate, armadura leve, contrato de trabalho (gancho de história — quem contratou?).",
    lore: "Soldado de aluguel que vende habilidade de combate a quem pagar mais — sem lealdade fixa a facção alguma, o que os torna tanto úteis quanto imprevisíveis como aliados temporários dos PJs.",
  },
  {
    id: "civil-pirata-espacial",
    book: "civis",
    name: "Pirata Espacial",
    category: "Civil",
    faction: "Bando Independente",
    level: 10,
    threat: "Médio",
    role: "Dano/Artilheiro",
    size: "Médio",
    type: "Humanoide",
    planet: "Bases ocultas em campos de asteroides",
    environment: "Espaço/naves",
    intelligence: "Média",
    disposition: "Oportunista",
    pv: 46,
    pe: 18,
    defense: 19,
    initiative: 5,
    speed: "9m",
    attrs: { agi: 4, int: 1, forc: 3, vig: 3, pre: 1, sen: 0 },
    skills: "Pilotagem Espacial (Treinado), Armas de Energia (Treinado), Intimidação (Treinado)",
    attacks: [
      { name: "Blaster de Abordagem", range: "20m", hit: "AGI+14", damage: "2d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "—" },
      { name: "Machado de Abordagem", range: "Corpo a corpo", hit: "FOR+13", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "—" },
    ],
    powers: [],
    passives: [
      { name: "Bando Barulhento", effect: "em grupo, ganha +3 em Intimidação coletiva (tenta render a vítima sem lutar antes de escalar)." },
    ],
    ai: "Prefere intimidar e roubar sem combate real — mas escala pra violência rápido se resistido. Foca carga valiosa (não necessariamente matar a tripulação), e recua se a resistência for mais forte do que o esperado.",
    loot: "Blaster de abordagem, machado, mapa de rotas de contrabando (gancho de campanha).",
    lore: "Assaltantes de naves de carga e passageiros, operando de bases escondidas em campos de asteroides ou luas remotas — o terror clássico das rotas comerciais menos protegidas.",
  },
  {
    id: "civil-contrabandista",
    book: "civis",
    name: "Contrabandista",
    category: "Civil",
    faction: "Independente",
    level: 9,
    threat: "Fraco",
    role: "Furtivo/Suporte",
    size: "Médio",
    type: "Humanoide",
    planet: "Variável (itinerante)",
    environment: "Naves/portos espaciais",
    intelligence: "Alta",
    disposition: "Oportunista",
    pv: 36,
    pe: 24,
    defense: 19,
    initiative: 6,
    speed: "9m",
    attrs: { agi: 4, int: 2, forc: 1, vig: 2, pre: 2, sen: 0 },
    skills: "Pilotagem Espacial (Expert), Enganação (Treinado), Furtividade (Treinado)",
    attacks: [
      { name: "Blaster Pessoal", range: "15m", hit: "AGI+14", damage: "2d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "—" },
    ],
    powers: [],
    passives: [
      { name: "Sempre Tem Um Plano B", effect: "uma vez por cena, pode reverter automaticamente uma complicação menor de fuga/perseguição (encontra uma rota alternativa, engana um sensor, etc.) sem precisar de teste." },
    ],
    ai: "Evita combate ativamente — prioriza fuga, negociação ou suborno. Se realmente encurralado, atira pra ferir e correr, não pra vencer um confronto direto.",
    loot: "Carga de contrabando (item de valor/gancho), nave própria (se aplicável à cena), contatos no submundo.",
    lore: "Transportadores de carga (nem sempre legal) que vivem na linha tênue entre comerciante honesto e criminoso, dependendo de quem pergunta e de qual regime está no poder naquele setor.",
  },
  {
    id: "civil-cacador-recompensas",
    book: "civis",
    name: "Caçador de Recompensas (Civil)",
    category: "Civil",
    faction: "Independente/Guilda",
    level: 15,
    threat: "Médio",
    role: "Furtivo/Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Variável (itinerante)",
    environment: "Qualquer",
    intelligence: "Alta",
    disposition: "Calculista",
    pv: 68,
    pe: 30,
    defense: 22,
    initiative: 8,
    speed: "9m",
    attrs: { agi: 5, int: 3, forc: 3, vig: 4, pre: 1, sen: 0 },
    skills: "Investigação (Expert), Armas de Energia (Treinado), Furtividade (Treinado), Intimidação (Treinado)",
    attacks: [
      { name: "Blaster de Precisão", range: "30m", hit: "AGI+17", damage: "3d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "—" },
      { name: "Algemas de Choque", range: "Corpo a corpo", hit: "AGI+17", damage: "1d6", damageType: "Energia", cost: "2 PE", cooldown: "2 rodadas", effect: "Não busca dano — imobiliza um alvo já Derrubado/Agarrado pra captura viva." },
    ],
    powers: [],
    passives: [
      { name: "Sabe o Valor da Presa", effect: "vantagem em Investigação pra localizar um alvo específico com recompensa ativa." },
    ],
    ai: "Diferente do mandaloriano especializado (ver Livro 5), o caçador civil é mais improvisado — usa qualquer vantagem disponível (terreno, disfarce, suborno de informantes) em vez de arsenal padronizado. Prioriza captura viva quando o contrato paga mais por isso.",
    loot: "Blaster de precisão, algemas de choque, contrato de recompensa.",
    lore: "Sem clã, sem beskar, sem tradição — apenas habilidade pessoal e fome de créditos. Alguns dos caçadores mais perigosos da galáxia nunca usaram uma armadura mandaloriana na vida.",
  },
  {
    id: "civil-mafioso",
    book: "civis",
    name: "Mafioso (Hutt/Sindicato)",
    category: "Civil",
    faction: "Sindicato do Crime Organizado",
    level: 18,
    threat: "Forte",
    role: "Comandante/Controle",
    size: "Médio",
    type: "Humanoide",
    planet: "Nar Shaddaa/Tatooine e centros de crime organizado",
    environment: "Palácios/covis",
    intelligence: "Alta",
    disposition: "Calculista",
    pv: 96,
    pe: 44,
    defense: 23,
    initiative: 6,
    speed: "9m (Hutts: 3m, sem pernas — compensado por guarda-costas sempre presente)",
    attrs: { agi: 2, int: 4, forc: 3, vig: 5, pre: 7, sen: 0 },
    skills: "Intimidação (Veterano), Persuasão (Expert), Enganação (Expert), Liderança (Treinado)",
    attacks: [
      { name: "Blaster Escondido (ou Ataque de Cauda, se Hutt)", range: "15m ou corpo a corpo", hit: "AGI+9 / FOR+21", damage: "4d6", damageType: "Energia/Físico", cost: "—", cooldown: "—", effect: "Raramente luta pessoalmente — normalmente é protegido por 2+ guarda-costas (use Mercenário ou Guerreiro Mandaloriano)." },
    ],
    powers: [
      { name: "Rede de Contatos", text: "descrição: convoca ajuda através de informantes e subordinados — regra: uma vez por cena, pode \"chamar\" 1d4 Criminosos de Rua ou 1 Mercenário pra reforçar a defesa, chegando em 1d3 rodadas — recarga: 1x por cena — duração: até os reforços chegarem — interações: não funciona fora do próprio território." },
    ],
    passives: [
      { name: "Imunidade Comprada", effect: "protegido por suborno e influência; autoridades locais raramente agem contra ele sem provas irrefutáveis (proteção narrativa, não mecânica)." },
    ],
    ai: "Praticamente nunca luta pessoalmente — negocia, ameaça, suborna ou manda outros lutarem por ele. Se realmente encurralado sem guarda-costas, tenta comprar a própria saída antes de qualquer coisa.",
    loot: "Créditos (muitos), registros de dívidas/chantagem (ganchos de campanha extensos), itens de luxo.",
    lore: "Figura de poder do submundo criminoso — pode ser um Hutt tradicional, um chefe humano de sindicato, ou qualquer espécie com ambição e recursos suficientes. Raramente é a ameaça de combate; é a ameaça de consequência.",
  },

  // ─── 2. Profissionais ─────────────────────────────────────────────────
  {
    id: "civil-cientista",
    book: "civis",
    name: "Cientista",
    category: "Civil",
    faction: "Independente/Corporativo",
    level: 8,
    threat: "Fraco",
    role: "Suporte",
    size: "Médio",
    type: "Humanoide",
    planet: "Variável (laboratórios, universidades)",
    environment: "Instalações de pesquisa",
    intelligence: "Sobre-humana",
    disposition: "Calculista",
    pv: 28,
    pe: 30,
    defense: 18,
    initiative: 3,
    speed: "9m",
    attrs: { agi: 0, int: 6, forc: -1, vig: 1, pre: 1, sen: 0 },
    skills: "Ciências (Mestre), Medicina (Treinado), Computação (Treinado)",
    attacks: [
      { name: "Pistola de Laboratório (defesa)", range: "10m", hit: "AGI+6", damage: "1d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "Praticamente nunca usada com intenção — cientistas evitam combate." },
    ],
    powers: [
      { name: "Solução Improvisada", text: "descrição: usa conhecimento científico pra resolver um problema técnico em tempo real — regra: teste de Ciências pra criar um item/efeito temporário útil à cena (antídoto, gambiarra tecnológica, análise crítica) — recarga: narrativa, a critério do Mestre — duração: variável — interações: ferramenta narrativa mais que ofensiva." },
    ],
    passives: [
      { name: "Mente Analítica", effect: "vantagem em qualquer teste de Investigação ou Ciências envolvendo um problema já observado por pelo menos 1 rodada." },
    ],
    ai: "Não luta — foge, se esconde, ou tenta negociar com base em valor de seu conhecimento. Um ótimo PNJ de resgate ou de recrutamento (a informação/tecnologia que carrega vale muito mais viva que morta).",
    loot: "Dados de pesquisa, protótipos, equipamento de laboratório.",
    lore: "Pesquisadores dedicados ao avanço do conhecimento galáctico — de universidades respeitadas a laboratórios secretos financiados por interesses nem sempre éticos.",
  },
  {
    id: "civil-medico",
    book: "civis",
    name: "Médico",
    category: "Civil",
    faction: "Independente/Corporativo",
    level: 10,
    threat: "Fraco",
    role: "Suporte",
    size: "Médio",
    type: "Humanoide",
    planet: "Variável",
    environment: "Clínicas/naves-hospital/campo de batalha",
    intelligence: "Alta",
    disposition: "Protetora",
    pv: 38,
    pe: 34,
    defense: 18,
    initiative: 4,
    speed: "9m",
    attrs: { agi: 1, int: 4, forc: 0, vig: 2, pre: 3, sen: 0 },
    skills: "Medicina (Mestre), Ciências (Treinado), Diplomacia (Iniciante)",
    attacks: [
      { name: "Bisturi/Ferramenta Médica", range: "Corpo a corpo", hit: "AGI+7", damage: "1d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Só em auto-defesa desesperada." },
    ],
    powers: [
      { name: "Cirurgia de Emergência", text: "descrição: estabiliza ou trata ferimentos graves com equipamento adequado — regra: restaura 5d6 PV a um alvo, mas exige 2 rodadas sem interrupção e equipamento médico decente — recarga: 3 rodadas — duração: instantâneo — interações: sem equipamento adequado, a cura cai pela metade (2d6)." },
    ],
    passives: [
      { name: "Juramento Médico", effect: "recusa-se a matar deliberadamente, mesmo sob ameaça; vantagem em testes de resistência contra coerção quando a exigência é causar dano letal." },
    ],
    ai: "Não luta — prioriza tratar feridos mesmo em zona de perigo ativo, um comportamento que pode colocá-lo em risco real. Excelente aliado recorrente em campanhas com muito combate.",
    loot: "Kit médico avançado, estoque de bacta, registros de pacientes (ganchos de história).",
    lore: "De médicos de campo de batalha a especialistas particulares de elite, unidos pelo compromisso de preservar a vida — um dos poucos papéis respeitados por praticamente todas as facções da galáxia, mesmo as mais hostis entre si.",
  },
  {
    id: "civil-diplomata",
    book: "civis",
    name: "Diplomata",
    category: "Civil",
    faction: "Governamental/Independente",
    level: 10,
    threat: "Fraco",
    role: "Suporte",
    size: "Médio",
    type: "Humanoide",
    planet: "Variável (Coruscant, Chandrila e centros políticos)",
    environment: "Salões de negociação",
    intelligence: "Alta",
    disposition: "Calculista",
    pv: 32,
    pe: 24,
    defense: 18,
    initiative: 4,
    speed: "9m",
    attrs: { agi: 1, int: 3, forc: -1, vig: 1, pre: 6, sen: 0 },
    skills: "Diplomacia (Mestre), Persuasão (Expert), Conhecimento Galáctico (Treinado), Enganação (Treinado)",
    attacks: [
      { name: "Blaster Compacto Oculto", range: "10m", hit: "AGI+7", damage: "1d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "Diplomatas raramente admitem carregar armas." },
    ],
    powers: [
      { name: "Palavra Convincente", text: "descrição: negocia com autoridade quase persuasiva demais — regra: teste de Diplomacia ou Persuasão pra evitar um combate iminente completamente (não funciona contra alvos Fanáticos ou já em Fúria/Fase 2) — recarga: 1x por cena — duração: até a situação mudar — interações: falha crítica pode piorar a situação social." },
    ],
    passives: [
      { name: "Imunidade Protocolar", effect: "em contextos oficiais/formais, tem proteção diplomática nominal (nem sempre respeitada, mas geralmente sim — ferramenta narrativa)." },
    ],
    ai: "Evita combate a todo custo — sua \"arma\" é a palavra. Se a violência começar, prioriza sair da cena com segurança (própria e de quem protege) e negociar um cessar-fogo assim que possível.",
    loot: "Documentos oficiais, credenciais diplomáticas, contatos políticos (gancho de campanha valioso).",
    lore: "Representante formal de governos, organizações ou facções em negociações — figuras que, bem ou mal usadas, podem evitar (ou provocar) guerras inteiras com as palavras certas (ou erradas).",
  },
  {
    id: "civil-mecanico",
    book: "civis",
    name: "Mecânico",
    category: "Civil",
    faction: "Independente",
    level: 7,
    threat: "Fraco",
    role: "Suporte",
    size: "Médio",
    type: "Humanoide",
    planet: "Variável (oficinas, portos espaciais)",
    environment: "Hangares/oficinas",
    intelligence: "Alta",
    disposition: "Leal (a quem paga bem/trata bem)",
    pv: 30,
    pe: 18,
    defense: 17,
    initiative: 3,
    speed: "9m",
    attrs: { agi: 2, int: 4, forc: 1, vig: 2, pre: 0, sen: 0 },
    skills: "Mecânica (Mestre), Computação (Treinado), Pilotagem Espacial (Iniciante)",
    attacks: [
      { name: "Chave de Fenda Hidráulica", range: "Corpo a corpo", hit: "FOR+8", damage: "1d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Improvisado, só em emergência." },
    ],
    powers: [
      { name: "Conserto de Emergência", text: "descrição: repara uma nave/droide/equipamento em campo — regra: teste de Mecânica pra restaurar função crítica de um sistema danificado (motor, escudo, arma) — recarga: narrativa — duração: variável — interações: um dos NPCs de suporte mais valiosos pra qualquer grupo com nave própria." },
    ],
    passives: [
      { name: "Sente a Máquina", effect: "diagnostica qualquer problema mecânico só por som/vibração, sem precisar de teste formal pra identificar (só pra consertar)." },
    ],
    ai: "Não luta — foge ou se esconde perto de equipamento valioso que pode tentar proteger/sabotar contra invasores. Excelente PNJ recorrente de tripulação.",
    loot: "Ferramentas, peças sobressalentes, um droide de manutenção próprio (companheiro recorrente).",
    lore: "A pessoa que mantém a galáxia literalmente funcionando — de mecânicos de podracer a técnicos de estaleiro, respeitados (e cobiçados) por qualquer um que dependa de uma nave funcionando.",
  },

  // ─── 3. Exploradores e Trabalhadores ──────────────────────────────────
  {
    id: "civil-explorador",
    book: "civis",
    name: "Explorador",
    category: "Civil",
    faction: "Independente/Guilda de Exploradores",
    level: 11,
    threat: "Médio",
    role: "Suporte/Furtivo",
    size: "Médio",
    type: "Humanoide",
    planet: "Variável (fronteiras desconhecidas)",
    environment: "Qualquer terreno inexplorado",
    intelligence: "Alta",
    disposition: "Oportunista",
    pv: 46,
    pe: 26,
    defense: 20,
    initiative: 7,
    speed: "9m",
    attrs: { agi: 4, int: 3, forc: 2, vig: 4, pre: 1, sen: 1 },
    skills: "Sobrevivência (Expert), Astrogação (Treinado), Percepção (Treinado), Pilotagem Espacial (Treinado)",
    attacks: [
      { name: "Rifle de Caça", range: "25m", hit: "AGI+14", damage: "3d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "—" },
    ],
    powers: [],
    passives: [
      { name: "Nunca Se Perde", effect: "imune à condição narrativa \"perdido\"; sempre encontra o caminho de volta a um ponto já visitado." },
    ],
    ai: "Prefere evitar confronto em território desconhecido (risco desnecessário), mas é autossuficiente e competente se precisar lutar por sobrevivência. Prioriza retirada estratégica sobre heroísmo.",
    loot: "Equipamento de sobrevivência de ponta, mapas de regiões pouco conhecidas (ganchos de campanha valiosos), amostras/registros de descobertas.",
    lore: "Desbravadores das Regiões Desconhecidas e outras fronteiras, motivados por curiosidade, lucro (direitos de descoberta) ou fuga de um passado que preferem deixar pra trás.",
  },
  {
    id: "civil-colonizador",
    book: "civis",
    name: "Colonizador",
    category: "Civil",
    faction: "Comunidade de Assentamento",
    level: 4,
    threat: "Fraco",
    role: "Suporte",
    size: "Médio",
    type: "Humanoide",
    planet: "Variável (mundos de fronteira)",
    environment: "Assentamentos novos",
    intelligence: "Média",
    disposition: "Protetora (da comunidade)",
    pv: 18,
    pe: 10,
    defense: 16,
    initiative: 2,
    speed: "9m",
    attrs: { agi: 1, int: 1, forc: 2, vig: 2, pre: 1, sen: 0 },
    skills: "Sobrevivência (Treinado), Mecânica (Iniciante)",
    attacks: [
      { name: "Rifle de Fazenda", range: "15m", hit: "AGI+6", damage: "1d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "Arma de defesa de propriedade, não de combate profissional." },
    ],
    powers: [],
    passives: [
      { name: "Comunidade Unida", effect: "em grupo defendendo o próprio assentamento, ganha +3 em Defesa por moral coletiva." },
    ],
    ai: "Só luta em defesa direta do lar/comunidade — sem treino formal, mas motivado ao extremo quando a família/assentamento está em risco real.",
    loot: "Suprimentos agrícolas, ferramentas, água/recursos básicos (valiosos em mundos áridos).",
    lore: "Pioneiros estabelecendo vida em mundos de fronteira — a espinha dorsal silenciosa da expansão galáctica, raramente heroica em combate, mas essencial à sobrevivência de qualquer nova colônia.",
  },
  {
    id: "civil-minerador",
    book: "civis",
    name: "Minerador",
    category: "Civil",
    faction: "Corporativo/Independente",
    level: 6,
    threat: "Fraco",
    role: "Suporte/Tanque (equipamento pesado)",
    size: "Médio",
    type: "Humanoide",
    planet: "Variável (Geonosis, cinturões de asteroides, luas)",
    environment: "Minas/instalações industriais",
    intelligence: "Média",
    disposition: "Oportunista",
    pv: 30,
    pe: 12,
    defense: 17,
    initiative: 2,
    speed: "9m",
    attrs: { agi: 1, int: 1, forc: 3, vig: 4, pre: 0, sen: 0 },
    skills: "Mecânica (Treinado), Sobrevivência (Iniciante), Atletismo (Treinado)",
    attacks: [
      { name: "Perfuratriz de Mão", range: "Corpo a corpo", hit: "FOR+9", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Ferramenta de trabalho, eficaz em emergência." },
      { name: "Carga de Demolição Controlada", range: "10m (área 3m)", hit: "INT+7", damage: "2d6", damageType: "Explosivo", cost: "2 PE", cooldown: "3 rodadas", effect: "Uso profissional em rocha — dano dobrado contra estruturas/paredes." },
    ],
    powers: [],
    passives: [
      { name: "Resistente ao Trabalho Pesado", effect: "imune a fadiga por esforço físico prolongado; +2 em Atletismo em ambientes de baixa gravidade ou pressão adversa." },
    ],
    ai: "Luta com ferramentas de trabalho quando necessário — desajeitado em combate formal, mas perigoso em espaços apertados (minas, túneis) que conhece bem.",
    loot: "Minérios brutos, ferramentas de mineração, cargas de demolição.",
    lore: "Trabalhadores de indústrias extrativistas por toda a galáxia — de operações corporativas legítimas a minas ilegais em mundos disputados, sempre sob risco constante de desabamento, gás tóxico ou exploração corporativa.",
  },
  {
    id: "civil-cacador-batedor",
    book: "civis",
    name: "Caçador (Batedor/Rastreador)",
    category: "Civil",
    faction: "Independente",
    level: 9,
    threat: "Médio",
    role: "Furtivo/Artilheiro à Distância",
    size: "Médio",
    type: "Humanoide",
    planet: "Variável",
    environment: "Selvas/desertos/qualquer bioma de caça",
    intelligence: "Alta",
    disposition: "Territorial",
    pv: 38,
    pe: 20,
    defense: 19,
    initiative: 7,
    speed: "9m",
    attrs: { agi: 5, int: 1, forc: 2, vig: 3, pre: 0, sen: 1 },
    skills: "Sobrevivência (Veterano), Pontaria (Expert), Percepção (Treinado), Furtividade (Treinado)",
    attacks: [
      { name: "Rifle de Caça de Longo Alcance", range: "40m", hit: "AGI+20", damage: "2d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "Contra alvo Surpreendido, +2d6." },
      { name: "Armadilha de Caça", range: "Área (pré-armada)", hit: "AGI+20", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "1 uso", effect: "Precisa ser preparada antes; acerto automático se o alvo não notar (Percepção DT 19)." },
    ],
    powers: [],
    passives: [
      { name: "Leitor de Rastros", effect: "vantagem automática em qualquer teste de Sobrevivência pra rastrear uma criatura ou pessoa específica já observada uma vez." },
    ],
    ai: "Paciente e metódico — prefere observar o alvo por várias rodadas antes de agir, usando Furtividade e armadilhas pra reduzir risco pessoal ao mínimo. Evita combate direto/justo sempre que uma emboscada é possível.",
    loot: "Rifle de caça, peles/troféus de caça anteriores, mapa de rotas de migração de fauna local.",
    lore: "Caçadores profissionais que vivem da carne, pele ou partes de criaturas selvagens — desde fornecedores legítimos de mercados exóticos até caçadores furtivos de espécies protegidas, dependendo da ética (ou falta dela) de cada um.",
  },
];
