import type { StarWarsCreature } from "./types";

export const CRIATURAS: StarWarsCreature[] = [
  {
    id: "criaturas-nexu",
    book: "criaturas",
    name: "Nexu",
    epithet: "Fera das Cavernas",
    category: "Criatura",
    faction: "Selvagem",
    level: 4,
    threat: "Fraco",
    role: "Dano",
    size: "Médio",
    type: "Fauna",
    planet: "Cato Neimoidia",
    environment: "Cavernas/florestas",
    intelligence: "Animal",
    disposition: "Agressiva",
    pv: 12,
    pe: 4,
    defense: 17,
    initiative: 5,
    speed: "12m (salto 6m)",
    attrs: { agi: 4, int: -1, forc: 2, vig: 1, pre: 0, sen: 1 },
    skills: "Acrobacia (Treinado), Percepção (Expert), Furtividade (Treinado)",
    attacks: [
      { name: "Garras Duplas", range: "Corpo a corpo", hit: "AGI+10", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Dois cortes simultâneos, um por garra dianteira." },
      { name: "Bote Predatório", range: "Corpo a corpo (salto até 6m)", hit: "AGI+10", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "1 rodada", effect: "Se acertar, alvo é derrubado (Prone)." },
    ],
    powers: [],
    passives: [
      { name: "Farejador de Sangue", effect: "vantagem (rola +1d20 extra e mantém melhor) contra alvos com PV abaixo de 50%." },
    ],
    ai: "Ataca o alvo ferido mais próximo primeiro (ver Farejador de Sangue). Prefere Bote Predatório no primeiro ataque contra alvos parados. Foge se ficar sozinho abaixo de 25% PV — nunca luta até a morte.",
    loot: "Presas de nexu (material de artesanato, 2d10 cr), pelagem (couro resistente).",
    lore: "Caçador solitário e territorial, o nexu marca cavernas com arranhões profundos e caça por emboscada. Domesticado por alguns caçadores de recompensas como animal de guarda — mas nunca totalmente confiável.",
  },
  {
    id: "criaturas-acklay",
    book: "criaturas",
    name: "Acklay",
    epithet: "Terror das Arenas",
    category: "Criatura",
    faction: "Selvagem",
    level: 10,
    threat: "Forte",
    role: "Tanque/Dano",
    size: "Grande",
    type: "Fauna",
    planet: "Vendaxa (comum em arenas de toda a galáxia)",
    environment: "Pântanos",
    intelligence: "Instintiva",
    disposition: "Agressiva",
    pv: 66,
    pe: 24,
    defense: 19,
    initiative: 6,
    speed: "12m",
    attrs: { agi: 5, int: 0, forc: 6, vig: 5, pre: -1, sen: 1 },
    skills: "Atletismo (Expert), Percepção (Treinado), Intimidação (Treinado)",
    attacks: [
      { name: "Garra Perfurante (×4 pernas)", range: "Corpo a corpo 3m", hit: "FOR+15", damage: "3d6", damageType: "Perfurante", cost: "—", cooldown: "—", effect: "Pode atacar até 2 alvos diferentes na mesma rodada (2 ações)." },
      { name: "Bico Trituador", range: "Corpo a corpo", hit: "FOR+15", damage: "3d6", damageType: "Físico", cost: "—", cooldown: "1 rodada", effect: "Se acertar um alvo Agarrado, dano dobrado." },
      { name: "Investida", range: "Corpo a corpo (movimento em linha reta)", hit: "FOR+15", damage: "3d6", damageType: "Físico", cost: "2 PE", cooldown: "2 rodadas", effect: "Empurra o alvo 3m e o derruba." },
    ],
    powers: [],
    passives: [
      { name: "Casco Ósseo", effect: "reduz todo dano físico recebido em 3 (mínimo 1)." },
    ],
    ai: "Foca o alvo que causou mais dano na última rodada. Usa Investida para separar o grupo antes de focar um isolado. Não recua nunca — instinto de arena não reconhece derrota.",
    loot: "Casco de acklay (peças de armadura crua), garras (armas improvisadas 2d6).",
    lore: "Usado há séculos como besta de arena por sua ferocidade indiscriminada. Na natureza, caça em pântanos rasos, imobilizando presas grandes com as garras antes do golpe fatal do bico.",
  },
  {
    id: "criaturas-rancor-jovem",
    book: "criaturas",
    name: "Rancor Jovem",
    category: "Criatura",
    faction: "Selvagem",
    level: 15,
    threat: "Forte",
    role: "Tanque",
    size: "Grande",
    type: "Fauna",
    planet: "Dathomir",
    environment: "Cavernas/selva",
    intelligence: "Baixa",
    disposition: "Territorial",
    pv: 108,
    pe: 34,
    defense: 21,
    initiative: 4,
    speed: "9m",
    attrs: { agi: 3, int: 0, forc: 7, vig: 6, pre: 0, sen: 1 },
    skills: "Atletismo (Expert), Intimidação (Veterano)",
    attacks: [
      { name: "Punho Esmagador", range: "Corpo a corpo", hit: "FOR+20", damage: "4d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "—" },
      { name: "Agarrar e Morder", range: "Corpo a corpo", hit: "FOR+20", damage: "4d6", damageType: "Perfurante", cost: "—", cooldown: "1 rodada", effect: "Alvo fica Agarrado; enquanto agarrado, sofre 2d6 automático no início de cada turno do rancor." },
      { name: "Arremesso", range: "Corpo a corpo (só contra alvo Agarrado)", hit: "FOR+20", damage: "4d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Arremessa o alvo até 9m; quem colide com algo/alguém sofre +2d6." },
    ],
    powers: [],
    passives: [
      { name: "Fúria Territorial", effect: "abaixo de 50% PV, ganha +1 ação por rodada (não acumula com Segunda Fase de Chefe, mas um Rancor Adulto estatuído como Chefe usaria a mesma regra)." },
    ],
    ai: "Agarra o alvo mais próximo primeiro, depois usa Arremesso contra o alvo que parecer mais frágil (menor PV aparente). Protege a própria caverna/ninho — não persegue para fora do território.",
    loot: "Dentes de rancor (2d20 cr no mercado negro), couro grosso (armadura pesada improvisada).",
    lore: "Criaturas de Dathomir criadas há gerações pelas Irmãs da Noite como guardiãs e montarias de guerra. Um espécime adulto (estatuir como Ameaça Planetária, nível 45+) é lendário o suficiente pra ter nome próprio em algumas tribos.",
  },
  {
    id: "criaturas-bantha",
    book: "criaturas",
    name: "Bantha",
    category: "Criatura",
    faction: "Selvagem/Domesticado",
    level: 2,
    threat: "Fraco",
    role: "Tanque (montaria)",
    size: "Grande",
    type: "Fauna",
    planet: "Tatooine",
    environment: "Deserto",
    intelligence: "Animal",
    disposition: "Protetora (com a manada)",
    pv: 20,
    pe: 6,
    defense: 15,
    initiative: 1,
    speed: "9m",
    attrs: { agi: 0, int: -1, forc: 3, vig: 4, pre: 0, sen: 2 },
    skills: "Sobrevivência (Treinado), Percepção (Treinado)",
    attacks: [
      { name: "Chifrada", range: "Corpo a corpo", hit: "FOR+10", damage: "1d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Só ataca se provocado ou pra proteger a manada." },
    ],
    powers: [],
    passives: [
      { name: "Pele Grossa", effect: "imune a dano de calor/sol extremo." },
      { name: "Instinto de Manada", effect: "nunca ataca sozinho por vontade própria." },
    ],
    ai: "Não inicia combate. Se atacado, chifra o agressor mais próximo e tenta fugir assim que possível. Extremamente dócil quando domesticado — Tusken Raiders e fazendeiros moisture usam como montaria.",
    loot: "Pelo (tecido resistente ao calor), leite de bantha (item de sobrevivência no deserto).",
    lore: "Espinha dorsal da economia nômade de Tatooine. Manadas selvagens migram seguindo rotas de água subterrânea; perder o rastro de uma manada pode significar perder a única fonte de líquido num raio de dias.",
  },
  {
    id: "criaturas-ronto",
    book: "criaturas",
    name: "Ronto",
    category: "Criatura",
    faction: "Domesticado",
    level: 5,
    threat: "Fraco",
    role: "Tanque (montaria de carga)",
    size: "Enorme",
    type: "Fauna",
    planet: "Tatooine",
    environment: "Deserto",
    intelligence: "Animal",
    disposition: "Dócil/Territorial",
    pv: 42,
    pe: 10,
    defense: 17,
    initiative: 2,
    speed: "9m",
    attrs: { agi: -1, int: -1, forc: 5, vig: 5, pre: -1, sen: 0 },
    skills: "Sobrevivência (Treinado)",
    attacks: [
      { name: "Pisão", range: "Corpo a corpo (área 2m)", hit: "FOR+15", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "1 rodada", effect: "Atinge todos na área; alvos derrubados." },
    ],
    powers: [],
    passives: [
      { name: "Carga Pesada", effect: "pode carregar até 10x seu próprio peso sem penalidade de deslocamento." },
    ],
    ai: "Só ataca se encurralado ou se seu condutor for atacado diretamente. Pisão é usado pra abrir espaço quando cercado, nunca como abertura de combate.",
    loot: "Nenhum de combate — vale como montaria capturável (500+ cr vivo).",
    lore: "Mais lento e resistente que o bantha, usado pelos Jawas pra transportar sandcrawlers desmontados e cargas industriais pelo deserto profundo.",
  },
  {
    id: "criaturas-falumpaset",
    book: "criaturas",
    name: "Falumpaset",
    category: "Criatura",
    faction: "Selvagem",
    level: 3,
    threat: "Fraco",
    role: "Enxame (manada)",
    size: "Médio",
    type: "Fauna",
    planet: "Naboo",
    environment: "Pradarias",
    intelligence: "Animal",
    disposition: "Selvagem",
    pv: 16,
    pe: 6,
    defense: 16,
    initiative: 4,
    speed: "12m",
    attrs: { agi: 3, int: -1, forc: 1, vig: 2, pre: 0, sen: 1 },
    skills: "Percepção (Treinado), Sobrevivência (Iniciante)",
    attacks: [
      { name: "Coice", range: "Corpo a corpo", hit: "AGI+10", damage: "1d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Só usado em fuga/pânico." },
    ],
    powers: [],
    passives: [
      { name: "Estouro de Manada", effect: "quando um falumpaset é ferido, todos os outros num raio de 15m ganham +2 de deslocamento na fuga." },
    ],
    ai: "Foge ao primeiro sinal de perigo. Nunca engaja voluntariamente — se um combate acontece perto de uma manada, o Mestre deve tratá-la como obstáculo de terreno (estouro pode derrubar PJs no caminho), não como inimiga.",
    loot: "Nenhum relevante em combate.",
    lore: "Base da pecuária nabooiana, criados em grandes fazendas nas planícies. Selvagens migram em manadas de centenas, um espetáculo natural que atrai turistas.",
  },
  {
    id: "criaturas-opee-sea-killer",
    book: "criaturas",
    name: "Opee Sea Killer",
    category: "Criatura",
    faction: "Selvagem",
    level: 12,
    threat: "Forte",
    role: "Furtivo/Assassino",
    size: "Grande",
    type: "Fauna",
    planet: "Naboo",
    environment: "Oceano profundo (núcleo do planeta)",
    intelligence: "Animal",
    disposition: "Agressiva",
    pv: 72,
    pe: 26,
    defense: 19,
    initiative: 7,
    speed: "15m (nado)",
    attrs: { agi: 6, int: -1, forc: 4, vig: 3, pre: -1, sen: 2 },
    skills: "Furtividade (Expert), Percepção (Veterano)",
    attacks: [
      { name: "Tentáculo Preênsil (×2)", range: "Corpo a corpo 6m", hit: "AGI+15", damage: "3d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Acerto agarra o alvo e o puxa 3m em direção à boca." },
      { name: "Bote Fulminante", range: "Corpo a corpo", hit: "AGI+15", damage: "3d6", damageType: "Perfurante", cost: "2 PE", cooldown: "2 rodadas", effect: "Se o alvo estiver Agarrado, dano dobrado e some para as profundezas." },
    ],
    powers: [],
    passives: [
      { name: "Emboscada Abissal", effect: "invisível pra Percepção até atacar pela primeira vez (exceto por Sensitividade da Força)." },
    ],
    ai: "Espreita nas sombras da água até um alvo isolado se afastar do grupo — nunca ataca alvos em grupo compacto. Depois do primeiro Bote Fulminante bem-sucedido, mergulha com a presa em vez de continuar o combate.",
    loot: "Bico córneo (material raro de ferramentas), tentáculos (componente alquímico).",
    lore: "Predador de tocaia do ecossistema aquático subterrâneo de Naboo — mas está longe do topo da cadeia alimentar local (veja Colo Claw Fish).",
  },
  {
    id: "criaturas-colo-claw-fish",
    book: "criaturas",
    name: "Colo Claw Fish",
    category: "Criatura",
    faction: "Selvagem",
    level: 20,
    threat: "Elite",
    role: "Dano",
    size: "Enorme",
    type: "Fauna",
    planet: "Naboo",
    environment: "Oceano profundo",
    intelligence: "Animal",
    disposition: "Agressiva",
    pv: 200,
    pe: 46,
    defense: 23,
    initiative: 6,
    speed: "18m (nado)",
    attrs: { agi: 5, int: -1, forc: 7, vig: 5, pre: 0, sen: 1 },
    skills: "Percepção (Veterano), Atletismo (Expert)",
    attacks: [
      { name: "Mordida Massiva", range: "Corpo a corpo", hit: "FOR+18", damage: "5d6", damageType: "Perfurante", cost: "—", cooldown: "—", effect: "Contra alvos Grande ou menor, chance de engolir (veja Passiva)." },
      { name: "Golpe de Cauda", range: "Corpo a corpo 4m (área)", hit: "FOR+18", damage: "5d6", damageType: "Físico", cost: "3 PE", cooldown: "2 rodadas", effect: "Atinge todos numa linha de 4m; derruba/afasta alvos." },
    ],
    powers: [],
    passives: [
      { name: "Engolidor", effect: "se Mordida Massiva acertar um alvo já Agarrado, o alvo é engolido inteiro (dano automático de 3d6 por rodada até escapar com teste de Atletismo DT 23)." },
    ],
    ai: "Persegue o maior alvo visível (avalia \"maior\" por Tamanho, não por PV). Ignora alvos pequenos a menos que ataquem primeiro. Uma vez engolindo um alvo, ignora o resto do grupo até o alvo escapar ou morrer.",
    loot: "Garras dianteiras (matéria-prima de lâminas), escamas (couro de armadura resistente a água).",
    lore: "Segundo maior predador conhecido do ecossistema do núcleo de Naboo — e ele mesmo é presa ocasional do Sando Aqua Monster (veja Criaturas Lendárias).",
  },
  {
    id: "criaturas-convor",
    book: "criaturas",
    name: "Convor",
    category: "Criatura",
    faction: "Selvagem",
    level: 1,
    threat: "Muito Fraco",
    role: "Suporte (narrativo)",
    size: "Minúsculo",
    type: "Fauna",
    planet: "Ahch-To e florestas úmidas em geral",
    environment: "Florestas",
    intelligence: "Animal",
    disposition: "Territorial",
    pv: 4,
    pe: 2,
    defense: 15,
    initiative: 6,
    speed: "3m (voo 15m)",
    attrs: { agi: 4, int: -1, forc: -2, vig: -1, pre: 0, sen: 3 },
    skills: "Percepção (Expert), Furtividade (Treinado)",
    attacks: [
      { name: "Bicada", range: "Corpo a corpo", hit: "AGI+10", damage: "1d6", damageType: "Perfurante", cost: "—", cooldown: "—", effect: "Só em auto-defesa." },
    ],
    powers: [],
    passives: [
      { name: "Sensível ao Redemoinho", effect: "convors são levemente sensíveis à Força e reagem (agitação, fuga, silêncio súbito) perto de eventos ligados à Força antes deles acontecerem. Ferramenta de presságio pro Mestre, não de combate." },
    ],
    ai: "Foge de qualquer confronto. Só é relevante como sinal ambiental.",
    loot: "Nenhum.",
    lore: "Ave pequena e curiosa que aninha em templos e ruínas antigas. Tradições locais dizem que convors \"sabem\" quando algo importante está pra acontecer.",
  },
  {
    id: "criaturas-aiwha",
    book: "criaturas",
    name: "Aiwha",
    category: "Criatura",
    faction: "Domesticado/Selvagem",
    level: 8,
    threat: "Médio",
    role: "Suporte (montaria)",
    size: "Grande",
    type: "Fauna",
    planet: "Kamino",
    environment: "Céu aberto sobre oceano",
    intelligence: "Baixa",
    disposition: "Dócil",
    pv: 48,
    pe: 20,
    defense: 17,
    initiative: 3,
    speed: "6m (voo 21m)",
    attrs: { agi: 2, int: 0, forc: 3, vig: 3, pre: -1, sen: 2 },
    skills: "Sobrevivência (Treinado), Percepção (Treinado)",
    attacks: [
      { name: "Baque de Nadadeira", range: "Corpo a corpo", hit: "FOR+13", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Só em auto-defesa ou defesa do condutor." },
    ],
    powers: [],
    passives: [
      { name: "Voo Sustentado", effect: "pode carregar até 3 passageiros médios sem penalidade." },
    ],
    ai: "Evita combate; se atacado enquanto carrega passageiros, prioriza fugir voando alto antes de revidar.",
    loot: "Nenhum de combate — captura viva vale como montaria treinável.",
    lore: "Usada pelos Kaminoanos como transporte oficial sobre os oceanos tempestuosos do planeta. Voo suave e silencioso a torna ideal pra reconhecimento aéreo discreto.",
  },
  {
    id: "criaturas-falcao-de-vento-de-utapau",
    book: "criaturas",
    name: "Falcão-de-Vento de Utapau",
    category: "Criatura",
    faction: "Selvagem",
    level: 14,
    threat: "Forte",
    role: "Furtivo/Assassino",
    size: "Grande",
    type: "Fauna",
    planet: "Utapau",
    environment: "Poços de sinkhole",
    intelligence: "Animal",
    disposition: "Territorial",
    pv: 84,
    pe: 30,
    defense: 21,
    initiative: 9,
    speed: "6m (voo 24m em mergulho)",
    attrs: { agi: 8, int: -1, forc: 4, vig: 2, pre: 0, sen: 2 },
    skills: "Percepção (Veterano), Furtividade (Expert)",
    attacks: [
      { name: "Garras em Mergulho", range: "Corpo a corpo (requer mergulho de 10m+)", hit: "AGI+18", damage: "4d6", damageType: "Perfurante", cost: "—", cooldown: "2 rodadas", effect: "Se o alvo estiver no chão, arremessa-o 6m ao subir de novo." },
      { name: "Rasante", range: "Corpo a corpo", hit: "AGI+18", damage: "4d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Ataque leve durante voo raso, sem precisar de recarga." },
    ],
    powers: [],
    passives: [
      { name: "Vento dos Poços", effect: "correntes térmicas dos sinkholes de Utapau dão +5 em testes de Pilotagem Atmosférica/deslocamento aéreo dentro do território." },
    ],
    ai: "Observa do alto antes de agir (usa 1 rodada de Percepção). Ataca com Garras em Mergulho o alvo mais isolado da beira do poço — nunca mergulha sobre um grupo compacto. Retorna à altitude depois de cada ataque.",
    loot: "Penas (materiais aerodinâmicos), garras (componente de armas de caça).",
    lore: "Caça pequenos mamíferos e, ocasionalmente, dactillions perdidos nas profundezas dos sinkholes de Utapau. Utapaus locais consideram avistar um casal acasalando em voo um sinal de boa sorte.",
  },
  {
    id: "criaturas-mynock",
    book: "criaturas",
    name: "Mynock",
    category: "Criatura",
    faction: "Selvagem",
    level: 3,
    threat: "Fraco",
    role: "Enxame",
    size: "Pequeno",
    type: "Fauna",
    planet: "Asteroides e cascos de naves em geral",
    environment: "Vácuo/espaço",
    intelligence: "Animal",
    disposition: "Oportunista",
    pv: 10,
    pe: 4,
    defense: 16,
    initiative: 3,
    speed: "9m (voo espacial)",
    attrs: { agi: 2, int: -2, forc: 0, vig: 1, pre: -1, sen: 0 },
    skills: "Sobrevivência Espacial (Treinado)",
    attacks: [
      { name: "Mordida Sugadora", range: "Corpo a corpo", hit: "AGI+8", damage: "1d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "Se acertar, gruda no alvo/nave e drena PE (1 PE do alvo por rodada) até ser removido." },
    ],
    powers: [],
    passives: [
      { name: "Vive no Vácuo", effect: "imune a dano de vácuo/asfixia." },
      { name: "Drenador de Energia", effect: "pode se prender ao casco de uma nave e drenar sistemas elétricos, causando falhas aleatórias em vez de dano direto." },
    ],
    ai: "Vem em enxames de 3–10. Prioriza se prender ao alvo mais próximo e alimentar; não \"luta\" no sentido tático — só precisa ser destacado ou morto individualmente (poucos PV cada).",
    loot: "Nenhum de valor — asco geral.",
    lore: "Praga de campos de asteroides e cascos de naves abandonadas. Contrabandistas odeiam mynocks quase tanto quanto odeiam a Patrulha Imperial — um enxame pode inutilizar os sistemas de uma nave em minutos.",
  },
  {
    id: "criaturas-verme-da-ferrugem",
    book: "criaturas",
    name: "Verme-da-Ferrugem",
    category: "Criatura",
    faction: "Selvagem",
    level: 6,
    threat: "Médio",
    role: "Controle",
    size: "Pequeno",
    type: "Fauna",
    planet: "Comum em depósitos de sucata (Ord Mantell, Geonosis)",
    environment: "Sucata/industrial",
    intelligence: "Animal",
    disposition: "Oportunista",
    pv: 30,
    pe: 12,
    defense: 17,
    initiative: 2,
    speed: "4,5m",
    attrs: { agi: 1, int: -1, forc: 1, vig: 3, pre: -1, sen: 0 },
    skills: "Sobrevivência (Treinado)",
    attacks: [
      { name: "Secreção Corrosiva", range: "Corpo a corpo", hit: "VIG+11", damage: "2d6", damageType: "Corrosivo", cost: "—", cooldown: "—", effect: "Contra armaduras/droides: dano extra de 1d6 no início do próximo turno do alvo (corrosão continua)." },
    ],
    powers: [],
    passives: [
      { name: "Devorador de Metal", effect: "pode consumir durasteel como alimento; equipamentos metálicos deixados perto de um ninho são destruídos em horas." },
    ],
    ai: "Foge de combate direto contra alvos vivos — foca exclusivamente em droides e equipamentos metálicos largados. Se encurralado, usa Secreção Corrosiva uma vez e tenta escapar por uma fresta.",
    loot: "Secreção (usável como solvente/arma improvisada, corrosivo).",
    lore: "Pequena praga que se banqueteia em sucata metálica — motivo pelo qual sucateiros de Ord Mantell mantêm cães-de-guarda geneticamente adaptados só pra caçá-los.",
  },
  {
    id: "criaturas-larva-sarlacc",
    book: "criaturas",
    name: "Larva Sarlacc",
    category: "Criatura",
    faction: "Selvagem",
    level: 25,
    threat: "Forte",
    role: "Controle",
    size: "Médio",
    type: "Fauna",
    planet: "Tatooine (e outros desertos áridos)",
    environment: "Poços de areia",
    intelligence: "Instintiva",
    disposition: "Territorial",
    pv: 175,
    pe: 54,
    defense: 26,
    initiative: 2,
    speed: "3m (a maior parte enterrada)",
    attrs: { agi: 2, int: 0, forc: 6, vig: 7, pre: 1, sen: 0 },
    skills: "Furtividade (Veterano — enterrada), Intimidação (Treinado)",
    attacks: [
      { name: "Tentáculo Preênsil (×8)", range: "Corpo a corpo 6m", hit: "FOR+21", damage: "7d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Acerto agarra o alvo e o puxa em direção à boca central." },
      { name: "Sugadouro de Areia", range: "Área 4m ao redor da boca", hit: "FOR+21", damage: "—", damageType: "Controle", cost: "4 PE", cooldown: "3 rodadas", effect: "Todos na área fazem teste de Atletismo DT 26 ou são puxados 2m em direção ao centro." },
    ],
    powers: [],
    passives: [
      { name: "Digestão Lenta", effect: "um alvo engolido não morre de imediato; sofre 2d6 por rodada e pode ser resgatado." },
      { name: "Emboscada de Areia", effect: "invisível até atacar pela primeira vez enquanto enterrada." },
    ],
    ai: "Não se move do poço. Usa Sugadouro de Areia repetidamente pra arrastar vítimas pra perto, depois foca Tentáculo Preênsil no alvo mais próximo do centro. Nunca sai do buraco — um grupo pode simplesmente se afastar da borda pra encerrar o combate.",
    loot: "Ácido digestivo (componente alquímico raro), fragmentos de vítimas antigas (ganchos de aventura).",
    lore: "Forma juvenil de um Sarlacc adulto (veja Criaturas Lendárias) — ainda não desenvolveu a boca central com múltiplas fileiras de dentes, mas já é mortal o suficiente pra qualquer caravana desavisada.",
  },
  {
    id: "criaturas-ysalamiri",
    book: "criaturas",
    name: "Ysalamiri",
    category: "Criatura",
    faction: "Selvagem",
    level: 2,
    threat: "Muito Fraco",
    role: "Suporte (anti-Força)",
    size: "Pequeno",
    type: "Criatura da Força",
    planet: "Myrkr",
    environment: "Florestas de árvores vwoshyr",
    intelligence: "Animal",
    disposition: "Territorial",
    pv: 8,
    pe: 4,
    defense: 15,
    initiative: 1,
    speed: "3m (não sai de galhos)",
    attrs: { agi: 0, int: -1, forc: -1, vig: 1, pre: 0, sen: 4 },
    skills: "Percepção (Treinado)",
    attacks: [
      { name: "Mordida", range: "Corpo a corpo", hit: "AGI+5", damage: "1d4", damageType: "Físico", cost: "—", cooldown: "—", effect: "Só em auto-defesa, praticamente irrelevante em combate." },
    ],
    powers: [],
    passives: [
      { name: "Bolha Anti-Força", effect: "enquanto vivo (e enquanto permanece parado num galho), cria uma bolha de 6m de raio onde nenhum poder da Força funciona — nem Poderes Gerais, nem habilidades de classe ligadas à Força, nem a regra especial de dano de Sabre de Luz (que passa a usar dano normal do tipo de arma). Afeta aliados e inimigos igualmente. Se removido do galho/carregado, a bolha viaja com ele." },
    ],
    ai: "Não luta — é uma ferramenta narrativa e tática. Caçadores de Jedi, a Ordem Imperial e certos sindicatos criminosos carregam ysalamiri em gaiolas portáteis especificamente pra neutralizar oponentes sensíveis à Força. Um Mestre pode usar um ysalamiri pra criar uma cena de combate \"sem poderes\" contra um Sith ou Jedi de outra forma esmagador.",
    loot: "Vivo, vale uma fortuna no mercado negro anti-Jedi (milhares de créditos).",
    lore: "Espécie descoberta nas florestas de Myrkr, onde a densidade de árvores vwoshyr já naturalmente enfraquece a Força — os ysalamiri evoluíram pra empurrar esse efeito ainda mais longe, criando bolhas de silêncio total. Tornaram-se lendários entre caçadores de recompensas especializados em alvos sensíveis à Força.",
  },
  {
    id: "criaturas-forca-cao",
    book: "criaturas",
    name: "Força-Cão",
    category: "Criatura",
    faction: "Selvagem",
    level: 9,
    threat: "Médio",
    role: "Furtivo/Controle",
    size: "Médio",
    type: "Criatura da Força",
    planet: "Nexos de Força em geral (Dagobah, Ilum, Jedha)",
    environment: "Florestas/cavernas próximas a nexos",
    intelligence: "Baixa",
    disposition: "Territorial",
    pv: 46,
    pe: 40,
    defense: 19,
    initiative: 6,
    speed: "12m",
    attrs: { agi: 4, int: -1, forc: 2, vig: 2, pre: 0, sen: 6 },
    skills: "Percepção (Mestre), Furtividade (Expert), Domínio da Força (Treinado)",
    attacks: [
      { name: "Mordida Espectral", range: "Corpo a corpo", hit: "AGI+14", damage: "3d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "—" },
      { name: "Empurrão da Força", range: "9m", hit: "SEN+16", damage: "3d6", damageType: "Força", cost: "2 PE", cooldown: "2 rodadas", effect: "Empurra o alvo 4m e o derruba, sem precisar tocar." },
    ],
    powers: [
      { name: "Sentir Intenção", text: "descrição: percebe emoções hostis num raio de 30m, mesmo através de paredes — regra: nunca é surpreendido em combate — recarga: passiva — duração: contínua — interações: ignora Furtividade de qualquer criatura com intenção de atacá-lo." },
    ],
    passives: [
      { name: "Casca Etérea", effect: "meio-transparente; 25% de chance de qualquer ataque físico simplesmente atravessá-lo sem efeito (não se aplica a ataques ligados à Força)." },
    ],
    ai: "Observa de longe usando Sentir Intenção antes de se aproximar. Ataca primeiro quem demonstrou intenção hostil mais forte (ex.: quem sacou uma arma). Prefere Empurrão da Força pra separar o grupo antes de engajar em corpo a corpo com o mais fraco.",
    loot: "Pelagem etérea (componente alquímico Sith/Jedi raro), nada de valor comercial comum.",
    lore: "Criatura naturalmente ligada a nexos de Força, cuja existência parece meio no plano físico e meio em outro lugar. Jedi antigos acreditavam que força-cães eram guardiões deixados por espíritos ancestrais pra proteger locais sagrados.",
  },
  {
    id: "criaturas-terentatek",
    book: "criaturas",
    name: "Terentatek",
    category: "Criatura",
    faction: "Selvagem/Corrompida",
    level: 30,
    threat: "Chefe",
    role: "Tanque/Caçador de Jedi",
    size: "Grande",
    type: "Criatura da Força",
    planet: "Originado em Korriban, hoje disperso",
    environment: "Cavernas escuras",
    intelligence: "Baixa",
    disposition: "Fanática (odeia usuários do Lado da Luz)",
    pv: 385,
    pe: 108,
    defense: 27,
    initiative: 5,
    speed: "12m",
    attrs: { agi: 5, int: -1, forc: 11, vig: 10, pre: 1, sen: 5 },
    skills: "Intimidação (Veterano), Atletismo (Expert), Percepção (Expert)",
    attacks: [
      { name: "Garras Envenenadas (×2)", range: "Corpo a corpo", hit: "FOR+24", damage: "8d6", damageType: "Perfurante/Veneno", cost: "—", cooldown: "—", effect: "Alvo sofre 2d6 de veneno no início dos próximos 2 turnos." },
      { name: "Fome de Força", range: "9m", hit: "SEN+20", damage: "8d6", damageType: "Força", cost: "4 PE", cooldown: "3 rodadas", effect: "Alvo sensível à Força perde 1d4 PE junto com o dano; terentatek recupera metade do PE drenado." },
    ],
    powers: [],
    passives: [
      { name: "Predador de Jedi", effect: "vantagem em Acerto contra qualquer criatura com PE atual acima de 0 ligada à Força." },
      { name: "Regeneração de Sangue Escuro", effect: "recupera 10 PV no início de cada turno enquanto houver ao menos um usuário do Lado da Luz visível." },
    ],
    ai: "Ignora completamente combatentes não sensíveis à Força a menos que sejam a única ameaça restante — foca obsessivamente qualquer Jedi, Consular ou usuário do Lado da Luz na cena, usando Fome de Força assim que possível. Não foge nunca.",
    loot: "Sangue (componente de alquimia Sith de altíssimo valor), presas (usadas em rituais sombrios).",
    lore: "Diz a lenda que os primeiros terentateks foram criaturas comuns corrompidas por rituais Sith em Korriban há milênios, criadas especificamente pra caçar Jedi. A espécie se perpetuou, espalhando-se por mundos escuros da galáxia — um pesadelo recorrente pra qualquer Ordem Jedi que tente reconstruir sua presença.",
  },
  {
    id: "criaturas-krayt-dragon-anciao",
    book: "criaturas",
    name: "Krayt Dragon Ancião",
    category: "Criatura",
    faction: "Selvagem",
    level: 55,
    threat: "Chefe Lendário",
    role: "Tanque/Dano",
    size: "Colossal",
    type: "Besta Lendária",
    planet: "Tatooine",
    environment: "Deserto profundo/cavernas",
    intelligence: "Baixa",
    disposition: "Territorial",
    pv: 1235,
    pe: 216,
    defense: 32,
    initiative: 7,
    speed: "15m",
    attrs: { agi: 8, int: 0, forc: 18, vig: 16, pre: 2, sen: 3 },
    skills: "Intimidação (Mestre), Percepção (Veterano), Atletismo (Mestre)",
    attacks: [
      { name: "Mordida Devastadora", range: "Corpo a corpo", hit: "FOR+30", damage: "12d6", damageType: "Perfurante", cost: "—", cooldown: "—", effect: "Contra alvo Médio ou menor, chance de engolir inteiro." },
      { name: "Coice de Cauda", range: "Corpo a corpo 6m (área, linha)", hit: "FOR+30", damage: "12d6", damageType: "Físico", cost: "—", cooldown: "2 rodadas", effect: "Atinge todos numa linha de 6m; derruba e empurra 4m." },
      { name: "Rugido Sísmico", range: "Área 15m", hit: "VIG+28", damage: "8d6", damageType: "Físico", cost: "5 PE", cooldown: "3 rodadas", effect: "Todos na área fazem teste de Atletismo DT 30 ou ficam Atordoados 1 rodada." },
    ],
    powers: [
      { name: "Fúria do Deserto (Fase 2)", text: "descrição: abaixo de 50% PV, o dragão entra em frenesi — regra: todos os ataques ganham +2d6 de dano e a recarga de Rugido Sísmico cai pra 1 rodada — recarga: uma vez por combate, ao cruzar 50% PV — duração: resto do combate — interações: substitui a Segunda Fase padrão de Chefe." },
    ],
    passives: [
      { name: "Escamas de Pérola", effect: "reduz todo dano físico recebido em 10 (mínimo 1)." },
      { name: "Sentido Sísmico", effect: "percebe qualquer criatura Grande+ num raio de 60m através do solo, ignorando Furtividade baseada em visão/som." },
    ],
    ai: "Emerge da areia com Coice de Cauda contra o grupo mais próximo, depois foca o alvo que causou mais dano. Usa Rugido Sísmico quando 3+ combatentes estão agrupados. Territorial ao extremo — não persegue além de ~200m do seu covil, e recua pra lá (não foge da galáxia, só do combate) se ficar isolado sem cobertura.",
    loot: "Pérola de Krayt (item lendário — cura ou amplifica poderes da Força, raríssimo), escamas (armadura de altíssimo nível), esqueleto (usado por Tusken Raiders como símbolo de status/arma cerimonial).",
    lore: "O maior predador nativo de Tatooine, capaz de viver séculos. Tusken Raiders reverenciam krayt dragons e usam suas costelas como sabres cerimoniais. Matar um krayt dragon ancião é, por si só, lenda o suficiente pra abrir qualquer porta em Mos Eisley.",
  },
  {
    id: "criaturas-sarlacc-adulto",
    book: "criaturas",
    name: "Sarlacc Adulto",
    category: "Criatura",
    faction: "Selvagem",
    level: 45,
    threat: "Chefe Lendário",
    role: "Controle/Tanque",
    size: "Colossal",
    type: "Besta Lendária",
    planet: "Tatooine, Dathomir e outros ermos áridos",
    environment: "Poço fixo",
    intelligence: "Instintiva",
    disposition: "Territorial (imóvel)",
    pv: 980,
    pe: 180,
    defense: 30,
    initiative: 1,
    speed: "0m (fixo no poço)",
    attrs: { agi: 1, int: 1, forc: 14, vig: 18, pre: 3, sen: 2 },
    skills: "Intimidação (Veterano)",
    attacks: [
      { name: "Tentáculos em Enxame (até 6 alvos)", range: "12m ao redor do poço", hit: "FOR+28", damage: "10d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Cada acerto agarra um alvo diferente e o arrasta 3m pra dentro do poço." },
      { name: "Areia Movediça", range: "Área 12m ao redor", hit: "VIG+30", damage: "—", damageType: "Controle", cost: "5 PE", cooldown: "passiva/constante", effect: "Toda criatura na área tem deslocamento reduzido à metade, exceto o próprio sarlacc." },
    ],
    powers: [],
    passives: [
      { name: "Digestão Milenar", effect: "um alvo engolido não morre rapidamente; a \"morte\" é lenta (1d6 dano real por dia, narrativamente) — resgate é possível por dias após ser engolido, criando ganchos de aventura." },
      { name: "Imóvel mas Eterno", effect: "regenera 5% do PV máximo por rodada enquanto houver qualquer criatura viva agarrada." },
    ],
    ai: "Não se move nunca. Usa Tentáculos em Enxame repetidamente contra qualquer criatura dentro de 12m, priorizando quem está mais perto da borda (mais fácil de puxar pra dentro). Nunca \"persegue\" — a estratégia do grupo correta é simplesmente manter distância de 15m+.",
    loot: "Sangue de sarlacc (componente alquímico extremamente raro, usado em rituais de longevidade), vítimas antigas parcialmente digeridas (ganchos de história, itens perdidos).",
    lore: "Criatura praticamente eterna, cresce por séculos no mesmo poço. O Império usou o Grande Poço de Carkoon como forma de execução — mas poucos sabem que o sarlacc é, na verdade, minimamente senciente e guarda memórias fragmentadas de tudo que já engoliu.",
  },
  {
    id: "criaturas-exogorth-anciao",
    book: "criaturas",
    name: "Exogorth Ancião",
    epithet: "Verme Espacial",
    category: "Criatura",
    faction: "Selvagem",
    level: 70,
    threat: "Ameaça Planetária",
    role: "Tanque/Controle",
    size: "Colossal",
    type: "Besta Lendária",
    planet: "Campos de asteroides",
    environment: "Vácuo espacial",
    intelligence: "Instintiva",
    disposition: "Territorial",
    pv: 4200,
    pe: 340,
    defense: 34,
    initiative: 2,
    speed: "6m (quase imóvel, ancorado ao asteroide hospedeiro)",
    attrs: { agi: 2, int: 0, forc: 22, vig: 24, pre: 3, sen: 4 },
    skills: "Percepção (Mestre), Sobrevivência Espacial (Mestre)",
    attacks: [
      { name: "Mordida do Abismo (só contra naves)", range: "Corpo a corpo (até nave Grande)", hit: "FOR+35", damage: "15d6", damageType: "Físico", cost: "—", cooldown: "2 rodadas", effect: "Contra uma nave, chance de \"engolir\" — nave fica presa dentro do exogorth até escapar por propulsão em DT 34." },
      { name: "Acidez Estomacal", range: "Área 20m dentro do exogorth", hit: "VIG+37", damage: "8d6", damageType: "Corrosivo", cost: "—", cooldown: "passiva/constante", effect: "Todo alvo (nave ou pessoa) dentro do exogorth sofre isso a cada rodada." },
    ],
    powers: [],
    passives: [
      { name: "Ecossistema Próprio", effect: "o interior do exogorth abriga mynocks e outras criaturas menores (use estatísticas de Mynock, seção 5)." },
      { name: "Escala Planetária", effect: "imune a qualquer dano de armas pessoais; só armamento de nave (ou poderes da Força em escala Ameaça Planetária+) causa dano de verdade." },
    ],
    ai: "Não \"luta\" no sentido convencional — é um obstáculo ambiental. Se uma nave pousa nele (confundindo-o com um asteroide comum) ou entra na boca por engano, o exogorth reage tentando fechar a boca e digerir. A única \"estratégia\" de combate é escapar antes da digestão completar (vários turnos de margem, propositalmente, pra permitir fuga tensa).",
    loot: "Nenhum de combate direto — mas o interior de um exogorth morto/abandonado é um local de exploração (recursos, destroços de naves anteriores, mynocks vivos).",
    lore: "Um dos poucos seres vivos capazes de sobreviver no vácuo em escala colossal, se alimentando de minerais de asteroides e da energia de naves que passam perto demais. Lendas de contrabandistas contam histórias (quase sempre exageradas) de fugas por dentro da garganta de um exogorth.",
  },
  {
    id: "criaturas-bando-de-guerra-trandoshano",
    book: "criaturas",
    name: "Bando de Guerra Trandoshano",
    category: "Espécie",
    faction: "Independente/Mercenária",
    level: 10,
    threat: "Médio",
    role: "Dano/Furtivo",
    size: "Médio",
    type: "Humanoide",
    planet: "Trandosha",
    environment: "Selva/qualquer local de caça",
    intelligence: "Alta",
    disposition: "Agressiva",
    pv: 58,
    pe: 22,
    defense: 19,
    initiative: 5,
    speed: "9m",
    attrs: { agi: 3, int: 1, forc: 4, vig: 3, pre: 0, sen: 0 },
    skills: "Pontaria (Expert), Sobrevivência (Veterano), Percepção (Expert), Intimidação (Treinado)",
    attacks: [
      { name: "Rifle de Caça", range: "30m", hit: "AGI+18", damage: "3d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "—" },
      { name: "Garras (regeneração natural)", range: "Corpo a corpo", hit: "FOR+19", damage: "3d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Trandoshanos regeneram membros perdidos — narrativamente, \"matar\" um em combate corpo a corpo costuma exigir dano concentrado." },
    ],
    powers: [],
    passives: [
      { name: "Regeneração Reptiliana", effect: "recupera 1d6 PV por rodada fora de combate direto; membros decepados regeneram em semanas." },
    ],
    ai: "Caça em bandos de 3–5, flanqueando e usando Furtividade pra emboscar. Prioriza o alvo mais \"prestigioso\" (armadura melhor, arma rara) como troféu. Se um membro do bando é abatido de forma humilhante, o resto pode recuar pra \"regenerar honra\" em vez de continuar.",
    loot: "Rifles de caça, troféus de caça anteriores (ganchos de história), créditos de recompensa.",
    lore: "Caçadores natos que veneram a caça como rito espiritual — abater uma presa poderosa (incluindo Wookiees, historicamente) é motivo de status social em Trandosha. Frequentemente contratados como batedores ou caçadores de recompensa.",
  },
  {
    id: "criaturas-colonia-geonosiana-em-guerra",
    book: "criaturas",
    name: "Colônia Geonosiana em Guerra",
    category: "Espécie",
    faction: "Facção Separatista/Independente",
    level: 8,
    threat: "Médio",
    role: "Enxame/Artilheiro",
    size: "Médio",
    type: "Humanoide",
    planet: "Geonosis",
    environment: "Colmeias subterrâneas",
    intelligence: "Alta",
    disposition: "Leal (à Rainha da colmeia)",
    pv: 34,
    pe: 16,
    defense: 18,
    initiative: 6,
    speed: "9m (voo curto 6m)",
    attrs: { agi: 4, int: 1, forc: 2, vig: 1, pre: 0, sen: 0 },
    skills: "Mecânica (Treinado), Pontaria (Treinado), Percepção (Treinado)",
    attacks: [
      { name: "Pistola de Som", range: "20m", hit: "AGI+14", damage: "2d6", damageType: "Sônico", cost: "—", cooldown: "—", effect: "Ignora metade da Defesa de alvos sem proteção auditiva." },
      { name: "Ferrão", range: "Corpo a corpo", hit: "FOR+12", damage: "2d6", damageType: "Perfurante/Veneno", cost: "—", cooldown: "—", effect: "Alvo sofre 1d6 de veneno no próximo turno." },
    ],
    powers: [],
    passives: [
      { name: "Mente de Colmeia", effect: "todos os geonosianos num raio de 100m sabem instantaneamente a localização de qualquer inimigo avistado por qualquer um deles." },
    ],
    ai: "Ataca coordenado em grupo, sempre cercando alvos isolados usando a Mente de Colmeia. Nunca recua individualmente — a colônia sacrifica indivíduos sem hesitar pra proteger a Rainha ou a linha de produção industrial.",
    loot: "Pistolas de som, componentes de fábrica de droides, cristais geodos (valor comercial).",
    lore: "Sociedade industrial-inseto organizada em torno de uma Rainha reprodutora. Fábricas geonosianas produziram boa parte do exército droide separatista — atacar uma colônia em guerra é, essencialmente, atacar uma linha de montagem militar viva.",
  },
  {
    id: "criaturas-bando-jawa",
    book: "criaturas",
    name: "Bando Jawa",
    category: "Espécie",
    faction: "Independente",
    level: 2,
    threat: "Muito Fraco",
    role: "Suporte (narrativo/comércio)",
    size: "Pequeno",
    type: "Humanoide",
    planet: "Tatooine",
    environment: "Deserto",
    intelligence: "Alta",
    disposition: "Oportunista",
    pv: 8,
    pe: 8,
    defense: 15,
    initiative: 3,
    speed: "7,5m",
    attrs: { agi: 2, int: 3, forc: -1, vig: 0, pre: 1, sen: 0 },
    skills: "Mecânica (Veterano), Persuasão (Treinado), Furtividade (Treinado), Enganação (Treinado)",
    attacks: [
      { name: "Bastão Elétrico", range: "Corpo a corpo", hit: "AGI+7", damage: "1d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "Alvo faz teste de VIG DT 15 ou fica Atordoado 1 rodada." },
    ],
    powers: [],
    passives: [
      { name: "Negociante Nato", effect: "vantagem em qualquer teste de Persuasão ou Enganação envolvendo compra/venda de equipamento e sucata." },
    ],
    ai: "Jawas não buscam combate — preferem fugir, negociar ou (se necessário) atordoar e roubar. Um bando encurralado luta em grupo com bastões elétricos, priorizando atordoar pra criar chance de fuga com o \"butim\".",
    loot: "Droides usados (funcionais ou não), peças de sucata, informação sobre a região.",
    lore: "Comerciantes nômades que vasculham o deserto de Tatooine em Sandcrawlers, coletando e revendendo droides e tecnologia abandonada. Vistos com desconfiança por colonos, mas raramente hostis sem motivo — negócio é sempre a prioridade.",
  },
  {
    id: "criaturas-tribo-ewok",
    book: "criaturas",
    name: "Tribo Ewok",
    category: "Espécie",
    faction: "Independente",
    level: 4,
    threat: "Fraco",
    role: "Furtivo/Enxame",
    size: "Pequeno",
    type: "Humanoide",
    planet: "Endor",
    environment: "Floresta densa",
    intelligence: "Alta",
    disposition: "Protetora (do território tribal)",
    pv: 18,
    pe: 12,
    defense: 16,
    initiative: 5,
    speed: "9m",
    attrs: { agi: 3, int: 1, forc: 1, vig: 1, pre: 1, sen: 2 },
    skills: "Furtividade (Expert), Sobrevivência (Veterano), Percepção (Treinado)",
    attacks: [
      { name: "Lança/Funda", range: "15m ou corpo a corpo", hit: "AGI+13", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "—" },
      { name: "Armadilha de Floresta", range: "Área (pré-armada)", hit: "AGI+13", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "1 uso", effect: "Precisa ser preparada antes do combate (rede, tronco, poço); acerto automático se o alvo não notar (teste de Percepção DT 16 pra evitar)." },
    ],
    powers: [],
    passives: [
      { name: "Conhece Cada Galho", effect: "vantagem em Furtividade e Acrobacia dentro da floresta de Endor." },
    ],
    ai: "Nunca engaja em campo aberto ou combate direto contra tecnologia superior — usa armadilhas, emboscadas e retirada tática. Uma tribo em guerra pode neutralizar até forças tecnologicamente muito superiores através de número e conhecimento do terreno (histórico contra o Império).",
    loot: "Armas primitivas, materiais de floresta, informação valiosa sobre o território.",
    lore: "Sociedade tribal profundamente conectada à floresta de Endor, organizada em clãs com xamãs espirituais. Aparentemente ingênuos a estranhos, mas capazes de ferocidade tática surpreendente quando o território é ameaçado.",
  },
  {
    id: "criaturas-circulo-ithoriano-de-herbologistas",
    book: "criaturas",
    name: "Círculo Ithoriano de Herbologistas",
    category: "Espécie",
    faction: "Independente/Científica",
    level: 6,
    threat: "Fraco",
    role: "Suporte",
    size: "Médio",
    type: "Humanoide",
    planet: "Ithor",
    environment: "Florestas-jardim",
    intelligence: "Alta",
    disposition: "Protetora (da natureza)",
    pv: 24,
    pe: 26,
    defense: 17,
    initiative: 2,
    speed: "9m",
    attrs: { agi: 0, int: 3, forc: 0, vig: 1, pre: 2, sen: 1 },
    skills: "Ciências (Veterano), Medicina (Expert), Diplomacia (Treinado), Sobrevivência (Treinado)",
    attacks: [
      { name: "Bordão Ritual", range: "Corpo a corpo", hit: "FOR+10", damage: "1d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Só em auto-defesa." },
      { name: "Esporo Sedativo", range: "6m", hit: "INT+13", damage: "—", damageType: "Controle", cost: "3 PE", cooldown: "2 rodadas", effect: "Alvo faz teste de VIG DT 17 ou fica Lento por 2 rodadas." },
    ],
    powers: [
      { name: "Cura de Ervas", text: "descrição: prepara um remédio à base de flora local — regra: restaura 3d6 PV a um alvo — recarga: 3 rodadas — duração: instantâneo — interações: exige acesso a flora viva (não funciona em ambiente estéril como nave/estação)." },
    ],
    passives: [
      { name: "Pacifista Convicto", effect: "nunca inicia combate; prefere negociar, fugir ou neutralizar não-letalmente." },
    ],
    ai: "Evita confronto ativamente. Se atacado, usa Esporo Sedativo pra neutralizar o agressor mais perigoso e foge com o grupo em vez de revidar com força letal. Excelente aliado de suporte se recrutado como PNJ amigável.",
    loot: "Ervas medicinais raras, sementes de flora exótica, conhecimento científico (ganchos de missão).",
    lore: "Ithorianos tratam toda a superfície do próprio planeta como templo vivo — cidades flutuam em \"hastes\" pra nunca tocar o solo. Círculos de herbologistas viajam a outros mundos estudando flora, sempre com reverência quase religiosa pela vida vegetal.",
  },
];
