import type { StarWarsCreature } from "./types";

export const FAUNA_PLANETAS: StarWarsCreature[] = [
  // ===== Tatooine =====
  {
    id: "fauna-tatooine-womp-rat",
    book: "fauna",
    name: "Womp Rat",
    category: "Criatura",
    faction: "Selvagem",
    level: 2,
    threat: "Muito Fraco",
    role: "Enxame",
    size: "Pequeno",
    type: "Fauna",
    planet: "Tatooine",
    environment: "Canyons rochosos",
    intelligence: "Animal",
    disposition: "Territorial",
    pv: 8,
    pe: 2,
    defense: 15,
    initiative: 3,
    speed: "9m",
    attrs: { agi: 3, int: -2, forc: 0, vig: 0, pre: -1, sen: 0 },
    skills: "Percepção (Iniciante)",
    attacks: [
      { name: "Mordida", range: "Corpo a corpo", hit: "AGI+8", damage: "1d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "—" },
    ],
    powers: [],
    passives: [
      { name: "Vive em Buracos", effect: "some em tocas se ficar abaixo de 50% PV, encerrando o combate sem \"matar\" a criatura narrativamente." },
    ],
    ai: "Vem em enxames de 4–8, ataca em número e foge em pânico ao primeiro abatido. Famoso alvo de prática de mira de moisture farmers entediados.",
    loot: "Nada de valor — só notoriedade (\"nem dois metros\" de distância no canyon).",
    lore: "Roedor comum de canyon, praga persistente pra fazendeiros de umidade — mas inofensivo em pequeno número.",
  },
  {
    id: "fauna-tatooine-dewback",
    book: "fauna",
    name: "Dewback",
    category: "Criatura",
    faction: "Domesticado",
    level: 6,
    threat: "Fraco",
    role: "Tanque (montaria)",
    size: "Grande",
    type: "Fauna",
    planet: "Tatooine",
    environment: "Deserto",
    intelligence: "Animal",
    disposition: "Dócil",
    pv: 34,
    pe: 10,
    defense: 17,
    initiative: 2,
    speed: "9m",
    attrs: { agi: 0, int: -1, forc: 4, vig: 4, pre: -1, sen: 0 },
    skills: "Sobrevivência (Treinado)",
    attacks: [
      { name: "Mordida", range: "Corpo a corpo", hit: "FOR+14", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Só em auto-defesa ou defesa do condutor." },
    ],
    powers: [],
    passives: [
      { name: "Pele Escamosa", effect: "reduz dano de calor/sol em metade. Nunca desidrata (armazena água por semanas)." },
    ],
    ai: "Não inicia combate — usado como montaria de patrulha por guarnições de Tatooine (inclusive tropas imperiais). Se atacado, defende o condutor com mordidas lentas mas pesadas.",
    loot: "Sela e equipamento de montaria, couro escamoso.",
    lore: "Réptil grande e resistente, principal montaria de patrulha imperial e local em Tatooine — mais lento que um ronto, mas muito mais dócil de treinar.",
  },

  // ===== Naboo =====
  {
    id: "fauna-naboo-fambaa",
    book: "fauna",
    name: "Fambaa",
    category: "Criatura",
    faction: "Domesticado (Gungan)",
    level: 8,
    threat: "Fraco",
    role: "Tanque (suporte de escudo)",
    size: "Enorme",
    type: "Fauna",
    planet: "Naboo",
    environment: "Pântanos/planícies",
    intelligence: "Animal",
    disposition: "Dócil",
    pv: 54,
    pe: 16,
    defense: 18,
    initiative: 1,
    speed: "9m",
    attrs: { agi: -1, int: 0, forc: 4, vig: 6, pre: -1, sen: 0 },
    skills: "Sobrevivência (Treinado)",
    attacks: [
      { name: "Pisão", range: "Corpo a corpo", hit: "FOR+16", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Só em auto-defesa; fambaas são criados pra carregar, não brigar." },
    ],
    powers: [],
    passives: [
      { name: "Carrega o Gerador de Escudo", effect: "quando equipado (uso Gungan tradicional), projeta uma bolha de escudo de 12m de raio que bloqueia disparos de energia (não física) pra todos dentro, exceto disparos do próprio fambaa/aliados saindo." },
    ],
    ai: "Anda em linha à frente de formações Gungan, sustentando o escudo enquanto tropas atrás disparam. Não ataca proativamente — é uma peça de suporte de exército viva, não um combatente.",
    loot: "Gerador de escudo (se equipado — item tático valioso), couro grosso.",
    lore: "Besta de carga gigante usada pelo Grande Exército Gungan como plataforma móvel de escudo defletor — uma das razões pelas quais os Gungans conseguiram enfrentar o Exército Droide Separatista em campo aberto.",
  },
  {
    id: "fauna-naboo-kaadu",
    book: "fauna",
    name: "Kaadu",
    category: "Criatura",
    faction: "Domesticado (Gungan)",
    level: 3,
    threat: "Muito Fraco",
    role: "Suporte (montaria)",
    size: "Médio",
    type: "Fauna",
    planet: "Naboo",
    environment: "Pântanos/planícies",
    intelligence: "Animal",
    disposition: "Dócil",
    pv: 14,
    pe: 6,
    defense: 16,
    initiative: 4,
    speed: "12m (salto 4m)",
    attrs: { agi: 3, int: -1, forc: 1, vig: 1, pre: -1, sen: 0 },
    skills: "Percepção (Treinado)",
    attacks: [
      { name: "Coice", range: "Corpo a corpo", hit: "AGI+8", damage: "1d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Só em fuga/pânico." },
    ],
    powers: [],
    passives: [
      { name: "Saltador Ágil", effect: "ignora terreno pantanoso/lamacento sem penalidade de deslocamento." },
    ],
    ai: "Não luta — foge em ziguezague saltado, difícil de acertar em movimento (Mestre pode dar +3 de Defesa a um kaadu em fuga ativa).",
    loot: "Nenhum relevante.",
    lore: "Montaria bípede ágil dos Gungans, usada tanto em batalha (cavalaria leve) quanto no dia a dia dos pântanos de Naboo.",
  },

  // ===== Coruscant =====
  {
    id: "fauna-coruscant-enxame-de-ratos-de-nivel-inferior",
    book: "fauna",
    name: "Enxame de Ratos de Nível Inferior",
    category: "Criatura",
    faction: "Selvagem",
    level: 2,
    threat: "Fraco",
    role: "Enxame",
    size: "Pequeno",
    type: "Fauna",
    planet: "Coruscant",
    environment: "Níveis inferiores/esgotos",
    intelligence: "Animal",
    disposition: "Oportunista",
    pv: 12,
    pe: 4,
    defense: 16,
    initiative: 4,
    speed: "9m",
    attrs: { agi: 3, int: -1, forc: 0, vig: 0, pre: -1, sen: 0 },
    skills: "Furtividade (Treinado)",
    attacks: [
      { name: "Mordidas em Enxame", range: "Corpo a corpo (área 2m)", hit: "AGI+8", damage: "1d6", damageType: "Físico/Doença", cost: "—", cooldown: "—", effect: "Alvo mordido tem 10% de chance (a critério do Mestre) de contrair uma doença menor dos níveis inferiores." },
    ],
    powers: [],
    passives: [
      { name: "Mutação Urbana", effect: "resistente à maioria dos venenos/toxinas industriais dos níveis inferiores." },
    ],
    ai: "Ataca em massa qualquer coisa que pareça comida ou ameace o ninho — foge em debandada se dano suficiente for causado de uma vez (área).",
    loot: "Nada de valor.",
    lore: "Geração após geração de roedores adaptados aos níveis mais baixos e esquecidos de Coruscant, onde a luz do sol nunca chega e a lei raramente também.",
  },
  {
    id: "fauna-coruscant-falcao-de-predio",
    book: "fauna",
    name: "Falcão de Prédio",
    category: "Criatura",
    faction: "Selvagem",
    level: 4,
    threat: "Fraco",
    role: "Furtivo",
    size: "Pequeno",
    type: "Fauna",
    planet: "Coruscant",
    environment: "Topos de arranha-céus",
    intelligence: "Animal",
    disposition: "Territorial",
    pv: 16,
    pe: 8,
    defense: 17,
    initiative: 6,
    speed: "6m (voo 18m)",
    attrs: { agi: 5, int: -1, forc: 0, vig: 0, pre: 0, sen: 1 },
    skills: "Percepção (Expert), Furtividade (Treinado)",
    attacks: [
      { name: "Garras em Mergulho", range: "Corpo a corpo (requer voo)", hit: "AGI+15", damage: "2d6", damageType: "Perfurante", cost: "—", cooldown: "—", effect: "Contra itens pequenos soltos (não presos), pode roubar em vez de ferir." },
    ],
    powers: [],
    passives: [
      { name: "Adaptado ao Tráfego Aéreo", effect: "imune a colisão acidental com veículos; navega o tráfego de speeders com precisão sobrenatural." },
    ],
    ai: "Ataca por cima, mira itens brilhantes/comida antes de pessoas — mais oportunista que agressivo. Território são os últimos andares de um arranha-céu específico.",
    loot: "Nada relevante, salvo o próprio item que roubou de outra vítima antes (gancho cômico).",
    lore: "Ave de rapina adaptada ao ambiente vertical extremo de Coruscant, caçando entre torres onde nenhum predador terrestre jamais poderia alcançar.",
  },

  // ===== Kashyyyk =====
  {
    id: "fauna-kashyyyk-katarn",
    book: "fauna",
    name: "Katarn",
    category: "Criatura",
    faction: "Selvagem",
    level: 7,
    threat: "Médio",
    role: "Dano",
    size: "Médio",
    type: "Fauna",
    planet: "Kashyyyk",
    environment: "Floresta rasteira/raízes",
    intelligence: "Animal",
    disposition: "Agressiva",
    pv: 32,
    pe: 12,
    defense: 18,
    initiative: 5,
    speed: "12m",
    attrs: { agi: 4, int: -1, forc: 3, vig: 2, pre: 0, sen: 0 },
    skills: "Percepção (Treinado), Furtividade (Treinado)",
    attacks: [
      { name: "Chifrada Dupla", range: "Corpo a corpo", hit: "FOR+12", damage: "2d6", damageType: "Perfurante", cost: "—", cooldown: "—", effect: "—" },
      { name: "Investida", range: "Corpo a corpo (linha reta 6m)", hit: "FOR+12", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "2 rodadas", effect: "Derruba o alvo se acertar." },
    ],
    powers: [],
    passives: [
      { name: "Casco Frontal", effect: "reduz dano recebido de ataques vindos de frente em 3." },
    ],
    ai: "Emboscador de raízes baixas — ataca de surpresa com Investida, depois luta com agressividade sustentada. Alguns wookiees domesticam katarns filhotes como animais de guarda.",
    loot: "Chifres (material de artesanato wookiee), couro grosso.",
    lore: "Predador quadrúpede das raízes de Kashyyyk, respeitado pelos Wookiees como teste de coragem tradicional para jovens caçadores.",
  },
  {
    id: "fauna-kashyyyk-gorryn-aranha-de-copa",
    book: "fauna",
    name: "Gorryn",
    epithet: "Aranha de Copa",
    category: "Criatura",
    faction: "Selvagem",
    level: 14,
    threat: "Forte",
    role: "Furtivo/Controle",
    size: "Grande",
    type: "Fauna",
    planet: "Kashyyyk",
    environment: "Copas altas das wroshyr",
    intelligence: "Animal",
    disposition: "Territorial",
    pv: 84,
    pe: 30,
    defense: 21,
    initiative: 8,
    speed: "9m (teia 12m)",
    attrs: { agi: 7, int: -1, forc: 4, vig: 3, pre: 0, sen: 1 },
    skills: "Furtividade (Expert), Percepção (Veterano)",
    attacks: [
      { name: "Presas Venenosas", range: "Corpo a corpo", hit: "AGI+18", damage: "4d6", damageType: "Perfurante/Veneno", cost: "—", cooldown: "—", effect: "Alvo sofre 1d6 de veneno contínuo nas próximas 2 rodadas." },
      { name: "Rede de Teia", range: "9m (área 3m)", hit: "AGI+18", damage: "—", damageType: "Controle", cost: "2 PE", cooldown: "2 rodadas", effect: "Alvo faz teste de FOR DT 21 ou fica Preso (deslocamento 0 até se libertar)." },
    ],
    powers: [],
    passives: [
      { name: "Mestra do Alto", effect: "invisível pra Percepção enquanto imóvel na copa das árvores." },
    ],
    ai: "Ataca de emboscada da copa, imobilizando com Rede de Teia antes de descer pra o golpe venenoso. Nunca desce ao solo voluntariamente — luta sempre nas alturas ou foge subindo.",
    loot: "Glândulas de veneno (componente alquímico), fios de teia (material têxtil resistente).",
    lore: "Predador temido nas copas mais altas das árvores wroshyr, onde poucos Wookiees se aventuram sem preparo — território quase exclusivamente dela.",
  },

  // ===== Hoth =====
  {
    id: "fauna-hoth-wampa",
    book: "fauna",
    name: "Wampa",
    category: "Criatura",
    faction: "Selvagem",
    level: 16,
    threat: "Forte",
    role: "Tanque/Dano",
    size: "Grande",
    type: "Fauna",
    planet: "Hoth",
    environment: "Cavernas de gelo",
    intelligence: "Baixa",
    disposition: "Territorial",
    pv: 94,
    pe: 32,
    defense: 22,
    initiative: 5,
    speed: "9m",
    attrs: { agi: 3, int: -1, forc: 8, vig: 6, pre: 0, sen: 0 },
    skills: "Intimidação (Treinado), Percepção (Treinado)",
    attacks: [
      { name: "Garras Congeladas", range: "Corpo a corpo", hit: "FOR+22", damage: "4d6", damageType: "Perfurante", cost: "—", cooldown: "—", effect: "—" },
      { name: "Arremesso", range: "Corpo a corpo (só contra alvo Agarrado)", hit: "FOR+22", damage: "4d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Arremessa o alvo até 6m contra uma parede de gelo." },
    ],
    powers: [],
    passives: [
      { name: "Pelagem Branca", effect: "imune a dano de frio/congelamento. Vantagem em Furtividade contra Percepção em nevascas/tempestades." },
    ],
    ai: "Caça sozinho, arrastando presas vivas de volta à caverna pra \"estocar\" — comportamento clássico que dá aos PJs uma janela de resgate se agirem rápido após um sequestro. Extremamente territorial dentro da própria toca.",
    loot: "Pelagem branca (isolante térmico de alto valor), garras (material de arma).",
    lore: "Predador ápice do gelado Hoth, temido tanto por sua força quanto pelo hábito perturbador de manter presas vivas penduradas em suas cavernas.",
  },
  {
    id: "fauna-hoth-tauntaun",
    book: "fauna",
    name: "Tauntaun",
    category: "Criatura",
    faction: "Domesticável",
    level: 4,
    threat: "Fraco",
    role: "Suporte (montaria)",
    size: "Grande",
    type: "Fauna",
    planet: "Hoth",
    environment: "Planícies geladas",
    intelligence: "Animal",
    disposition: "Dócil (domesticado) / Territorial (selvagem)",
    pv: 20,
    pe: 10,
    defense: 17,
    initiative: 5,
    speed: "12m",
    attrs: { agi: 3, int: -1, forc: 2, vig: 3, pre: -1, sen: 0 },
    skills: "Sobrevivência (Treinado)",
    attacks: [
      { name: "Chifrada", range: "Corpo a corpo", hit: "FOR+9", damage: "1d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Só em auto-defesa." },
    ],
    powers: [],
    passives: [
      { name: "Termorregulação Interna", effect: "sobrevive ao frio extremo de Hoth, mas morre em poucas horas se exposto a calor moderado por tempo prolongado (referência ao famoso truque de sobrevivência de emergência)." },
    ],
    ai: "Foge de predadores (especialmente wampas — reação de pânico instantânea e reconhecível ao cheiro). Domesticado, é montaria confiável mas nervosa.",
    loot: "Pelagem, carne (alimento de sobrevivência).",
    lore: "Réptil-mamífero adaptado ao frio extremo de Hoth, usado pela Aliança Rebelde como patrulha de reconhecimento durante a ocupação da Base Eco.",
  },

  // ===== Mustafar =====
  {
    id: "fauna-mustafar-verme-de-lava",
    book: "fauna",
    name: "Verme de Lava",
    category: "Criatura",
    faction: "Selvagem",
    level: 10,
    threat: "Médio",
    role: "Controle",
    size: "Médio",
    type: "Fauna",
    planet: "Mustafar",
    environment: "Rios de lava",
    intelligence: "Animal",
    disposition: "Territorial",
    pv: 50,
    pe: 18,
    defense: 19,
    initiative: 2,
    speed: "6m (nado em lava 9m)",
    attrs: { agi: 1, int: -1, forc: 3, vig: 5, pre: 0, sen: 0 },
    skills: "Sobrevivência (Treinado)",
    attacks: [
      { name: "Investida de Magma", range: "Corpo a corpo", hit: "FOR+13", damage: "3d6", damageType: "Fogo", cost: "—", cooldown: "—", effect: "Alvo pega fogo (1d6/rodada por 2 rodadas se não apagar)." },
    ],
    powers: [],
    passives: [
      { name: "Nativo do Fogo", effect: "imune a dano de fogo/calor e a lava. Pode submergir completamente na lava por tempo indefinido." },
    ],
    ai: "Emboscador que espreita sob a superfície de rios de lava, atacando quem se aproxima demais da margem. Nunca sai da lava — manter distância da beira encerra o combate.",
    loot: "Escamas resistentes a calor (material industrial valioso).",
    lore: "Uma das poucas formas de vida macroscópicas capazes de sobreviver dentro da lava líquida de Mustafar, adaptação extrema mesmo pelos padrões de um mundo vulcânico inteiro.",
  },
  {
    id: "fauna-mustafar-predador-de-cinzas",
    book: "fauna",
    name: "Predador de Cinzas",
    category: "Criatura",
    faction: "Selvagem",
    level: 13,
    threat: "Médio",
    role: "Furtivo/Dano",
    size: "Médio",
    type: "Fauna",
    planet: "Mustafar",
    environment: "Planícies de cinzas vulcânicas",
    intelligence: "Animal",
    disposition: "Agressiva",
    pv: 64,
    pe: 24,
    defense: 21,
    initiative: 7,
    speed: "9m",
    attrs: { agi: 5, int: 0, forc: 4, vig: 4, pre: 0, sen: 0 },
    skills: "Furtividade (Expert — camuflagem em cinzas), Percepção (Treinado)",
    attacks: [
      { name: "Garras Cortantes", range: "Corpo a corpo", hit: "AGI+18", damage: "4d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "—" },
    ],
    powers: [],
    passives: [
      { name: "Camuflagem de Cinzas", effect: "invisível pra Percepção enquanto parado em terreno de cinzas vulcânicas." },
    ],
    ai: "Se enterra parcialmente em cinzas e espera, atacando de emboscada quando a presa passa perto. Extremamente resistente ao calor ambiente, mas não imune como o Verme de Lava — evita contato direto com lava líquida.",
    loot: "Pelagem resistente ao calor, garras.",
    lore: "Predador terrestre adaptado à paisagem hostil de cinzas e rocha vulcânica fora dos rios de lava propriamente ditos — o topo da cadeia alimentar em terra firme mustafariana.",
  },

  // ===== Kamino =====
  {
    id: "fauna-kamino-enguia-tempestade",
    book: "fauna",
    name: "Enguia-Tempestade",
    category: "Criatura",
    faction: "Selvagem",
    level: 9,
    threat: "Médio",
    role: "Controle",
    size: "Médio",
    type: "Fauna",
    planet: "Kamino",
    environment: "Oceano aberto/tempestades",
    intelligence: "Animal",
    disposition: "Agressiva",
    pv: 42,
    pe: 22,
    defense: 19,
    initiative: 6,
    speed: "15m (nado)",
    attrs: { agi: 4, int: -1, forc: 2, vig: 3, pre: 0, sen: 1 },
    skills: "Percepção (Treinado)",
    attacks: [
      { name: "Choque Elétrico", range: "Corpo a corpo", hit: "AGI+14", damage: "3d6", damageType: "Elétrico", cost: "—", cooldown: "—", effect: "Alvo faz teste de VIG DT 19 ou fica Atordoado 1 rodada." },
    ],
    powers: [],
    passives: [
      { name: "Sensível a Tempestades", effect: "fica mais agressiva e numerosa durante as tempestades constantes de Kamino; +2 em Iniciativa durante clima severo." },
    ],
    ai: "Caça em cardumes durante tempestades, usando choques coordenados pra atordoar presas maiores antes de atacar em grupo. Kaminoanos evitam operações de superfície durante \"temporada de enguias\".",
    loot: "Órgãos elétricos (componente tecnológico/alquímico).",
    lore: "Predador elétrico do oceano infinito de Kamino, cuja atividade aumenta dramaticamente durante as tempestades incessantes do planeta — um perigo constante pra qualquer instalação flutuante isolada.",
  },
  {
    id: "fauna-kamino-predador-das-profundezas",
    book: "fauna",
    name: "Predador das Profundezas de Kamino",
    category: "Criatura",
    faction: "Selvagem",
    level: 18,
    threat: "Forte",
    role: "Tanque/Dano",
    size: "Enorme",
    type: "Fauna",
    planet: "Kamino",
    environment: "Oceano profundo",
    intelligence: "Animal",
    disposition: "Territorial",
    pv: 108,
    pe: 40,
    defense: 23,
    initiative: 6,
    speed: "15m (nado)",
    attrs: { agi: 4, int: -1, forc: 7, vig: 6, pre: 0, sen: 0 },
    skills: "Percepção (Veterano)",
    attacks: [
      { name: "Mordida Massiva", range: "Corpo a corpo", hit: "FOR+21", damage: "5d6", damageType: "Perfurante", cost: "—", cooldown: "—", effect: "—" },
      { name: "Golpe de Cauda", range: "Corpo a corpo 4m", hit: "FOR+21", damage: "5d6", damageType: "Físico", cost: "—", cooldown: "2 rodadas", effect: "Empurra e derruba." },
    ],
    powers: [],
    passives: [
      { name: "Pressão das Profundezas", effect: "imune a dano por pressão; nunca precisa subir à superfície." },
    ],
    ai: "Raramente visto — habita as profundezas abaixo de qualquer instalação Kaminoana. Ataca embarcações/estruturas subaquáticas que invadem seu território profundo, ignorando alvos na superfície.",
    loot: "Nenhum de combate comum — carcaça (se recuperada) vale fortuna científica.",
    lore: "Pouco estudado mesmo pelos Kaminoanos, que preferem simplesmente evitar as profundezas onde essa espécie vive — um lembrete de que nem toda a vida do oceano de Kamino foi catalogada.",
  },

  // ===== Endor =====
  {
    id: "fauna-endor-gorax",
    book: "fauna",
    name: "Gorax",
    category: "Criatura",
    faction: "Selvagem",
    level: 20,
    threat: "Forte",
    role: "Tanque",
    size: "Enorme",
    type: "Fauna",
    planet: "Endor",
    environment: "Floresta profunda",
    intelligence: "Baixa",
    disposition: "Territorial",
    pv: 200,
    pe: 48,
    defense: 23,
    initiative: 4,
    speed: "9m",
    attrs: { agi: 1, int: -2, forc: 9, vig: 7, pre: -1, sen: 0 },
    skills: "Intimidação (Treinado)",
    attacks: [
      { name: "Punho Esmagador", range: "Corpo a corpo", hit: "FOR+19", damage: "5d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "—" },
      { name: "Arrancar Árvore", range: "Corpo a corpo (arma improvisada)", hit: "FOR+19", damage: "5d6", damageType: "Físico", cost: "—", cooldown: "2 rodadas", effect: "Área 3m; derruba todos que falharem em VIG DT 23." },
    ],
    powers: [],
    passives: [
      { name: "Colosso da Floresta", effect: "reduz todo dano físico recebido em 5." },
    ],
    ai: "Lento e burro, mas devastador — Ewoks tradicionalmente evitam o território dele completamente em vez de confrontá-lo. Ataca qualquer coisa que o irrite persistentemente, sem estratégia real.",
    loot: "Nenhum de valor comercial — pele grossa como troféu de caça extremamente arriscado.",
    lore: "Gigante lento e solitário das profundezas da floresta de Endor, temido até pelos Ewoks como uma força da natureza a ser evitada, não enfrentada.",
  },
  {
    id: "fauna-endor-yuzzum",
    book: "fauna",
    name: "Yuzzum",
    category: "Criatura",
    faction: "Selvagem",
    level: 8,
    threat: "Médio",
    role: "Dano",
    size: "Grande",
    type: "Fauna",
    planet: "Endor",
    environment: "Floresta",
    intelligence: "Baixa",
    disposition: "Agressiva",
    pv: 40,
    pe: 16,
    defense: 18,
    initiative: 4,
    speed: "9m",
    attrs: { agi: 2, int: -1, forc: 5, vig: 3, pre: 0, sen: 0 },
    skills: "Atletismo (Treinado)",
    attacks: [
      { name: "Golpe de Braço Longo", range: "Corpo a corpo (2m)", hit: "FOR+13", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "—" },
    ],
    powers: [],
    passives: [
      { name: "Braços Longos", effect: "alcance de ataque corpo a corpo estendido em 2m além do normal." },
    ],
    ai: "Territorial e mal-humorado — ataca qualquer intruso no próprio pedaço de floresta sem aviso. Rivaliza com tribos Ewok por território há gerações.",
    loot: "Pelagem, presas.",
    lore: "Humanoide primitivo e desajeitado da floresta de Endor, historicamente em conflito territorial com as tribos Ewok mais organizadas.",
  },

  // ===== Felucia =====
  {
    id: "fauna-felucia-enxame-de-esporos-carnivoros",
    book: "fauna",
    name: "Enxame de Esporos Carnívoros",
    category: "Criatura",
    faction: "Selvagem",
    level: 6,
    threat: "Médio",
    role: "Enxame/Controle",
    size: "Pequeno",
    type: "Vegetal/Fungo",
    planet: "Felucia",
    environment: "Selva fúngica",
    intelligence: "Instintiva",
    disposition: "Agressiva",
    pv: 28,
    pe: 16,
    defense: 17,
    initiative: 2,
    speed: "3m (flutua no ar)",
    attrs: { agi: 1, int: -2, forc: 0, vig: 2, pre: 0, sen: 0 },
    skills: "Sobrevivência (Iniciante)",
    attacks: [
      { name: "Nuvem de Esporos", range: "Área 6m", hit: "VIG+11", damage: "2d6", damageType: "Veneno", cost: "2 PE", cooldown: "2 rodadas", effect: "Todos na área testam VIG DT 17 ou ficam Envenenados (1d6/rodada por 2 rodadas)." },
    ],
    powers: [],
    passives: [
      { name: "Fotossíntese", effect: "regenera 2 PV por rodada enquanto exposto à luz solar direta de Felucia." },
    ],
    ai: "Deriva lentamente em direção a qualquer fonte de calor/movimento (presas em potencial), soltando esporos continuamente. Sem inteligência real — puro instinto de predação vegetal.",
    loot: "Esporos (componente alquímico/venenoso, valioso pra alquimistas).",
    lore: "Colônia fúngica semi-móvel da selva psicodélica de Felucia, parte do ecossistema hostil e exuberante que torna o planeta tão perigoso quanto belo.",
  },
  {
    id: "fauna-felucia-predador-fungo",
    book: "fauna",
    name: "Predador-Fungo de Felucia",
    category: "Criatura",
    faction: "Selvagem",
    level: 15,
    threat: "Forte",
    role: "Dano",
    size: "Grande",
    type: "Fauna",
    planet: "Felucia",
    environment: "Selva fúngica",
    intelligence: "Animal",
    disposition: "Agressiva",
    pv: 88,
    pe: 30,
    defense: 21,
    initiative: 7,
    speed: "12m",
    attrs: { agi: 5, int: -1, forc: 6, vig: 4, pre: 0, sen: 1 },
    skills: "Percepção (Treinado), Furtividade (Treinado — camuflagem entre fungos)",
    attacks: [
      { name: "Mandíbulas Fúngicas", range: "Corpo a corpo", hit: "FOR+17", damage: "4d6", damageType: "Perfurante", cost: "—", cooldown: "—", effect: "—" },
      { name: "Investida Camuflada", range: "Corpo a corpo", hit: "AGI+17", damage: "4d6", damageType: "Físico", cost: "—", cooldown: "2 rodadas", effect: "Se atacando de camuflagem, acerto automático." },
    ],
    powers: [],
    passives: [
      { name: "Simbiose Fúngica", effect: "pele coberta de esporos torna a criatura quase indistinguível da flora ao redor quando parada." },
    ],
    ai: "Espreita entre a flora bioluminescente, confiando na camuflagem pra garantir o primeiro golpe decisivo. Depois do ataque de surpresa, luta com agressividade direta.",
    loot: "Pele fúngica (material de camuflagem, item raro), garras.",
    lore: "Predador ápice adaptado tão profundamente ao ecossistema fúngico de Felucia que praticamente se tornou parte dele — clones e soldados que serviram na Batalha de Felucia relatam encontros aterrorizantes com a espécie.",
  },

  // ===== Geonosis =====
  {
    id: "fauna-geonosis-verme-de-areia-geonosiano",
    book: "fauna",
    name: "Verme de Areia Geonosiano",
    category: "Criatura",
    faction: "Selvagem",
    level: 11,
    threat: "Médio",
    role: "Controle",
    size: "Grande",
    type: "Fauna",
    planet: "Geonosis",
    environment: "Deserto avermelhado",
    intelligence: "Animal",
    disposition: "Territorial",
    pv: 56,
    pe: 22,
    defense: 19,
    initiative: 3,
    speed: "6m (a maior parte enterrado)",
    attrs: { agi: 2, int: -1, forc: 5, vig: 5, pre: 0, sen: 0 },
    skills: "Furtividade (Expert — enterrado)",
    attacks: [
      { name: "Emboscada Subterrânea", range: "Corpo a corpo", hit: "FOR+15", damage: "3d6", damageType: "Perfurante", cost: "—", cooldown: "1 rodada", effect: "Ataque de surpresa — se acertar na primeira investida do combate, dano dobrado." },
    ],
    powers: [],
    passives: [
      { name: "Sentido Sísmico", effect: "percebe qualquer criatura Média+ num raio de 20m através do solo." },
    ],
    ai: "Espera enterrado até sentir passos próximos, então emerge pra um único golpe devastador antes de recuar de volta à areia. Não persegue fora do próprio território de caça.",
    loot: "Carapaça (material industrial), veneno residual (componente).",
    lore: "Predador oportunista das areias vermelhas de Geonosis, cuja presença é um dos motivos pelos quais mesmo os geonosianos evitam viajar a pé por longas distâncias na superfície.",
  },
  {
    id: "fauna-geonosis-orray",
    book: "fauna",
    name: "Orray",
    category: "Criatura",
    faction: "Domesticável",
    level: 3,
    threat: "Fraco",
    role: "Suporte (montaria)",
    size: "Médio",
    type: "Fauna",
    planet: "Geonosis",
    environment: "Deserto/arenas",
    intelligence: "Animal",
    disposition: "Territorial (selvagem) / Dócil (domesticado)",
    pv: 16,
    pe: 8,
    defense: 16,
    initiative: 5,
    speed: "15m",
    attrs: { agi: 4, int: -1, forc: 1, vig: 1, pre: -1, sen: 0 },
    skills: "Percepção (Treinado)",
    attacks: [
      { name: "Chifrada", range: "Corpo a corpo", hit: "AGI+9", damage: "1d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "—" },
    ],
    powers: [],
    passives: [
      { name: "Corredor Veloz", effect: "ignora terreno arenoso difícil sem penalidade." },
    ],
    ai: "Selvagem, evita confronto e foge em disparada. Domesticado, é usado (historicamente) como montaria de arena — inclusive nas execuções da Arena de Petranaki.",
    loot: "Nenhum relevante.",
    lore: "Réptil-ave veloz nativo de Geonosis, famoso pela cena de execução na Arena de Petranaki onde criaturas como o acklay, o reek e o nexu foram usadas contra prisioneiros montados em orrays.",
  },

  // ===== Mandalore =====
  {
    id: "fauna-mandalore-strill",
    book: "fauna",
    name: "Strill",
    category: "Criatura",
    faction: "Domesticável",
    level: 5,
    threat: "Fraco",
    role: "Furtivo (companheiro de caça)",
    size: "Médio",
    type: "Fauna",
    planet: "Mandalore",
    environment: "Planícies pós-guerra",
    intelligence: "Animal",
    disposition: "Leal (quando domesticado)",
    pv: 22,
    pe: 14,
    defense: 17,
    initiative: 6,
    speed: "12m (voo curto/planeio 9m)",
    attrs: { agi: 5, int: 0, forc: 2, vig: 2, pre: 0, sen: 0 },
    skills: "Percepção (Expert), Furtividade (Treinado)",
    attacks: [
      { name: "Mordida", range: "Corpo a corpo", hit: "AGI+10", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "—" },
    ],
    powers: [],
    passives: [
      { name: "Farejador Nato", effect: "vantagem automática em rastrear qualquer alvo cujo cheiro já tenha sido apresentado a ele." },
    ],
    ai: "Como companheiro, ataca quem seu dono/treinador mandaloriano apontar, priorizando flanquear. Selvagem, caça em pequenos bandos usando emboscada aérea curta.",
    loot: "Nenhum relevante — vale mais vivo como companheiro treinável.",
    lore: "Criatura reptil-alada usada por caçadores mandalorianos como companheira de rastreamento — leal ao extremo uma vez que o vínculo de confiança é estabelecido.",
  },
  {
    id: "fauna-mandalore-fera-das-planicies",
    book: "fauna",
    name: "Fera das Planícies Mandalorianas",
    category: "Criatura",
    faction: "Selvagem",
    level: 14,
    threat: "Forte",
    role: "Dano",
    size: "Grande",
    type: "Fauna",
    planet: "Mandalore",
    environment: "Planícies pós-guerra/crateras",
    intelligence: "Animal",
    disposition: "Agressiva",
    pv: 84,
    pe: 28,
    defense: 21,
    initiative: 6,
    speed: "15m",
    attrs: { agi: 5, int: -1, forc: 7, vig: 5, pre: 0, sen: 0 },
    skills: "Percepção (Treinado), Atletismo (Treinado)",
    attacks: [
      { name: "Garras de Corrida", range: "Corpo a corpo", hit: "FOR+16", damage: "4d6", damageType: "Perfurante", cost: "—", cooldown: "—", effect: "Se moveu 6m+ antes de atacar, +1d6." },
    ],
    powers: [],
    passives: [
      { name: "Endurecida pela Guerra", effect: "evoluiu em crateras de bombardeio e ruínas de guerra; imune a dano de escombros/explosão residual do ambiente." },
    ],
    ai: "Caça em corridas rápidas através das planícies abertas, usando velocidade pra alcançar presas antes que possam reagir. Mandalorianos jovens frequentemente caçam essa espécie como rito de passagem.",
    loot: "Garras (material de arma tradicional), pelagem resistente.",
    lore: "Predador que prosperou nas paisagens marcadas pela guerra de Mandalore — um símbolo, para alguns clãs, de resiliência: a vida que insiste mesmo depois da devastação.",
  },

  // ===== Ilum =====
  {
    id: "fauna-ilum-guardiao-de-gelo",
    book: "fauna",
    name: "Guardião de Gelo",
    category: "Criatura",
    faction: "Selvagem",
    level: 17,
    threat: "Forte",
    role: "Tanque",
    size: "Grande",
    type: "Criatura da Força",
    planet: "Ilum",
    environment: "Cavernas de cristal kyber",
    intelligence: "Instintiva",
    disposition: "Territorial",
    pv: 102,
    pe: 60,
    defense: 23,
    initiative: 5,
    speed: "9m",
    attrs: { agi: 3, int: -1, forc: 6, vig: 8, pre: 0, sen: 5 },
    skills: "Percepção (Veterano), Domínio da Força (Treinado)",
    attacks: [
      { name: "Punho de Cristal", range: "Corpo a corpo", hit: "FOR+21", damage: "5d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Se o alvo estiver carregando cristal kyber não sintonizado, +2d6." },
      { name: "Ressonância Kyber", range: "Área 9m", hit: "SEN+22", damage: "5d6", damageType: "Força", cost: "4 PE", cooldown: "3 rodadas", effect: "Todos na área testam VIG DT 23 ou ficam Atordoados 1 rodada (som ressoante que perturba o equilíbrio)." },
    ],
    powers: [],
    passives: [
      { name: "Ligado aos Cristais", effect: "imune a dano de frio. Sente qualquer cristal kyber sendo removido de Ilum num raio de 1km." },
    ],
    ai: "Protege as cavernas de kyber com ferocidade — considera qualquer coleta de cristal sem \"permissão\" (ritual sentido pela Força, não verbal) uma invasão. Jedi historicamente aprendem a negociar essa permissão via meditação antes de coletar seu cristal.",
    loot: "Fragmentos de cristal (nunca o cristal de coleta ritual em si — isso é sempre uma escolha pessoal do personagem, não saque de combate).",
    lore: "Guardião natural das cavernas sagradas de Ilum, parte do motivo pelo qual a coleta de cristal kyber sempre foi tratada como provação espiritual, não simples mineração.",
  },
  {
    id: "fauna-ilum-morcego-das-cavernas",
    book: "fauna",
    name: "Morcego das Cavernas de Ilum",
    category: "Criatura",
    faction: "Selvagem",
    level: 4,
    threat: "Fraco",
    role: "Enxame",
    size: "Pequeno",
    type: "Fauna",
    planet: "Ilum",
    environment: "Cavernas de gelo",
    intelligence: "Animal",
    disposition: "Territorial",
    pv: 18,
    pe: 8,
    defense: 17,
    initiative: 6,
    speed: "3m (voo 15m)",
    attrs: { agi: 5, int: -1, forc: 0, vig: 1, pre: 0, sen: 1 },
    skills: "Percepção (Treinado — ecolocalização)",
    attacks: [
      { name: "Mordida", range: "Corpo a corpo", hit: "AGI+10", damage: "1d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "—" },
    ],
    powers: [],
    passives: [
      { name: "Ecolocalização", effect: "imune a Furtividade baseada em ocultação visual dentro de cavernas (mas não a silêncio total)." },
    ],
    ai: "Vem em bandos de 6+, reage a qualquer luz/som repentino defendendo o ninho. Foge se dano suficiente for causado.",
    loot: "Nada relevante.",
    lore: "Espécie adaptada à escuridão total das cavernas mais profundas de Ilum, navegando por ecolocalização onde nem a luz de um lanterna alcança.",
  },

  // ===== Dathomir =====
  {
    id: "fauna-dathomir-fera-das-sombras",
    book: "fauna",
    name: "Fera das Sombras de Dathomir",
    category: "Criatura",
    faction: "Selvagem/Corrompida",
    level: 13,
    threat: "Médio",
    role: "Furtivo/Dano",
    size: "Médio",
    type: "Criatura da Força",
    planet: "Dathomir",
    environment: "Florestas sombrias",
    intelligence: "Animal",
    disposition: "Agressiva",
    pv: 62,
    pe: 34,
    defense: 21,
    initiative: 8,
    speed: "12m",
    attrs: { agi: 6, int: -1, forc: 4, vig: 3, pre: 0, sen: 4 },
    skills: "Furtividade (Expert), Percepção (Treinado)",
    attacks: [
      { name: "Garras Sombrias", range: "Corpo a corpo", hit: "AGI+17", damage: "4d6", damageType: "Físico/Força", cost: "—", cooldown: "—", effect: "Meio-etérea — 20% de chance de ataques físicos comuns a atravessarem sem efeito." },
    ],
    powers: [],
    passives: [
      { name: "Toque da Magia Negra", effect: "a presença constante de magia de Dathomir tornou essa espécie levemente sensível à Força; imune a Furtividade de criaturas não-sensíveis." },
    ],
    ai: "Caça nas sombras profundas da floresta, evitando clareiras iluminadas. Bruxas de Dathomir ocasionalmente domesticam espécimes jovens como guardiãs de vilas.",
    loot: "Pelagem sombria (componente alquímico de baixo-médio valor), garras.",
    lore: "Espécie nativa de Dathomir, moldada geração após geração pela magia ambiental onipresente do planeta — nem totalmente natural, nem totalmente sobrenatural.",
  },
  {
    id: "fauna-dathomir-serpente-vortice",
    book: "fauna",
    name: "Serpente Vórtice",
    category: "Criatura",
    faction: "Selvagem",
    level: 7,
    threat: "Médio",
    role: "Controle",
    size: "Médio",
    type: "Fauna",
    planet: "Dathomir",
    environment: "Pântanos/florestas",
    intelligence: "Animal",
    disposition: "Territorial",
    pv: 34,
    pe: 16,
    defense: 18,
    initiative: 5,
    speed: "9m (nado 12m)",
    attrs: { agi: 4, int: -1, forc: 3, vig: 3, pre: 0, sen: 1 },
    skills: "Furtividade (Treinado)",
    attacks: [
      { name: "Constrição", range: "Corpo a corpo", hit: "FOR+13", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Alvo fica Agarrado; sofre 1d6 automático por rodada até escapar (Atletismo DT 18)." },
    ],
    powers: [],
    passives: [
      { name: "Escamas Escorregadias", effect: "vantagem em testes de resistência pra escapar de ser agarrado por outra criatura." },
    ],
    ai: "Espreita em água parada ou lama, atacando por baixo. Prioriza constringir e drenar antes de se preocupar com outros alvos na cena.",
    loot: "Pele (couro de alta qualidade), veneno leve (componente).",
    lore: "Serpente aquática dos pântanos de Dathomir, respeitada pelas Bruxas como símbolo de paciência predatória em rituais tradicionais.",
  },

  // ===== Corellia =====
  {
    id: "fauna-corellia-cao-de-guarda",
    book: "fauna",
    name: "Cão de Guarda Corelliano",
    category: "Criatura",
    faction: "Domesticado",
    level: 3,
    threat: "Fraco",
    role: "Tanque (guarda)",
    size: "Médio",
    type: "Fauna",
    planet: "Corellia",
    environment: "Urbano/industrial",
    intelligence: "Animal",
    disposition: "Leal (ao dono)",
    pv: 16,
    pe: 8,
    defense: 16,
    initiative: 4,
    speed: "9m",
    attrs: { agi: 3, int: -1, forc: 2, vig: 2, pre: 0, sen: 0 },
    skills: "Percepção (Treinado), Intimidação (Iniciante)",
    attacks: [
      { name: "Mordida", range: "Corpo a corpo", hit: "AGI+8", damage: "1d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "—" },
    ],
    powers: [],
    passives: [
      { name: "Treinado pra Alarme", effect: "nunca é surpreendido; alerta automaticamente aliados próximos ao detectar uma ameaça." },
    ],
    ai: "Defende propriedade/dono com lealdade feroz, latindo/alertando antes de atacar. Bom NPC recorrente pra guardar oficinas e estaleiros.",
    loot: "Nenhum relevante.",
    lore: "Raça canina comum criada em Corellia pra guardar estaleiros e propriedades industriais — inteligente o bastante pra reconhecer padrões de intrusão, não só estranhos.",
  },
  {
    id: "fauna-corellia-predador-dos-estaleiros",
    book: "fauna",
    name: "Predador dos Estaleiros",
    category: "Criatura",
    faction: "Selvagem (adaptada ao urbano)",
    level: 8,
    threat: "Médio",
    role: "Furtivo",
    size: "Médio",
    type: "Fauna",
    planet: "Corellia",
    environment: "Sucata industrial",
    intelligence: "Animal",
    disposition: "Oportunista",
    pv: 38,
    pe: 18,
    defense: 18,
    initiative: 6,
    speed: "9m",
    attrs: { agi: 5, int: 0, forc: 3, vig: 2, pre: 0, sen: 0 },
    skills: "Furtividade (Expert), Percepção (Treinado)",
    attacks: [
      { name: "Bote de Sucata", range: "Corpo a corpo", hit: "AGI+15", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Contra alvo Surpreendido, +2d6." },
    ],
    powers: [],
    passives: [
      { name: "Adaptado ao Metal", effect: "imune a cortes por metal/sucata afiada; ignora dificuldade de terreno em pilhas de sucata." },
    ],
    ai: "Ataca de emboscada em pátios de sucata abandonados, prefere alvos solitários. Fugitivo — nunca briga em desvantagem numérica clara.",
    loot: "Pelagem oleosa (impermeável), nada mais de valor.",
    lore: "Espécie que se adaptou aos vastos pátios de sucata e estaleiros abandonados de Corellia, prosperando exatamente onde a indústria descarta o que não quer mais.",
  },

  // ===== Alderaan =====
  {
    id: "fauna-alderaan-veado-de-cristal",
    book: "fauna",
    name: "Veado-de-Cristal Alderaaniano",
    category: "Criatura",
    faction: "Selvagem",
    level: 2,
    threat: "Muito Fraco",
    role: "Suporte (fauna decorativa/caça leve)",
    size: "Médio",
    type: "Fauna",
    planet: "Alderaan (histórico — anterior à destruição do planeta)",
    environment: "Montanhas nevadas",
    intelligence: "Animal",
    disposition: "Dócil",
    pv: 10,
    pe: 4,
    defense: 15,
    initiative: 3,
    speed: "12m",
    attrs: { agi: 3, int: -1, forc: 0, vig: 0, pre: 1, sen: 0 },
    skills: "Percepção (Treinado)",
    attacks: [
      { name: "Chifrada", range: "Corpo a corpo", hit: "FOR+5", damage: "1d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Só em auto-defesa." },
    ],
    powers: [],
    passives: [
      { name: "Chifres Cristalinos", effect: "refletem luz de forma característica; caça-lo por esporte era tradicionalmente malvista na cultura pacifista alderaaniana." },
    ],
    ai: "Foge de qualquer confronto — nunca ataca primeiro.",
    loot: "Chifres cristalinos (item decorativo/artesanal de valor sentimental, especialmente após a destruição de Alderaan).",
    lore: "Símbolo da beleza natural preservada de Alderaan antes de sua destruição pela Estrela da Morte — hoje, uma lembrança de um mundo que não existe mais, relevante em campanhas ambientadas antes desse evento ou como flashback/memória.",
  },
  {
    id: "fauna-alderaan-ave-canora",
    book: "fauna",
    name: "Ave-Canora das Montanhas",
    category: "Criatura",
    faction: "Selvagem",
    level: 1,
    threat: "Muito Fraco",
    role: "Suporte (ambientação)",
    size: "Minúsculo",
    type: "Fauna",
    planet: "Alderaan",
    environment: "Montanhas/vales",
    intelligence: "Animal",
    disposition: "Dócil",
    pv: 4,
    pe: 2,
    defense: 15,
    initiative: 5,
    speed: "3m (voo 12m)",
    attrs: { agi: 4, int: -2, forc: -2, vig: -1, pre: 1, sen: 0 },
    skills: "Percepção (Treinado)",
    attacks: [
      { name: "Bicada", range: "Corpo a corpo", hit: "AGI+9", damage: "1d4", damageType: "Físico", cost: "—", cooldown: "—", effect: "Puramente defensivo." },
    ],
    powers: [],
    passives: [
      { name: "Canto Icônico", effect: "seu canto é reconhecível em toda a cultura alderaaniana (usado em música e poesia tradicionais)." },
    ],
    ai: "Não luta — puro elemento de ambientação/nostalgia.",
    loot: "Nenhum.",
    lore: "Pequena ave cujo canto matinal é tão associado à identidade cultural de Alderaan que sobrevive em gravações e composições musicais muito depois da destruição do planeta.",
  },

  // ===== Korriban =====
  {
    id: "fauna-korriban-cao-de-tumba",
    book: "fauna",
    name: "Cão de Tumba",
    category: "Criatura",
    faction: "Selvagem/Corrompida",
    level: 15,
    threat: "Forte",
    role: "Tanque/Dano",
    size: "Médio",
    type: "Criatura da Força",
    planet: "Korriban/Moraband",
    environment: "Tumbas Sith/cemitérios",
    intelligence: "Baixa",
    disposition: "Fanática (protege tumbas)",
    pv: 90,
    pe: 36,
    defense: 21,
    initiative: 6,
    speed: "12m",
    attrs: { agi: 4, int: -1, forc: 6, vig: 6, pre: 0, sen: 3 },
    skills: "Intimidação (Treinado), Percepção (Treinado)",
    attacks: [
      { name: "Mordida Corrosiva", range: "Corpo a corpo", hit: "FOR+16", damage: "4d6", damageType: "Perfurante/Sombrio", cost: "—", cooldown: "—", effect: "Alvo sofre 1d6 adicional de dano sombrio na rodada seguinte." },
    ],
    powers: [],
    passives: [
      { name: "Guardião Ritual", effect: "imune a Amedrontar. Regenera 5 PV por rodada enquanto dentro de uma tumba Sith consagrada." },
    ],
    ai: "Ataca sem hesitação qualquer intruso que perturbe uma tumba ou local sagrado Sith — instinto quase ritualístico, não puramente animal. Não persegue além dos limites do território funerário.",
    loot: "Presas (componente alquímico Sith), pelagem corrompida.",
    lore: "Predador cuja linhagem foi exposta por gerações a rituais sombrios em Korriban, resultando numa espécie que age quase como guardiã instintiva das tumbas Sith mais antigas.",
  },
  {
    id: "fauna-korriban-espectro-de-areia",
    book: "fauna",
    name: "Espectro de Areia",
    category: "Criatura",
    faction: "Sobrenatural",
    level: 22,
    threat: "Forte",
    role: "Controle/Dano",
    size: "Médio",
    type: "Criatura da Força",
    planet: "Korriban/Moraband",
    environment: "Deserto de tumbas",
    intelligence: "Média",
    disposition: "Fanática",
    pv: 130,
    pe: 68,
    defense: 26,
    initiative: 9,
    speed: "9m (flutua sobre a areia)",
    attrs: { agi: 5, int: 1, forc: 3, vig: 4, pre: 2, sen: 8 },
    skills: "Domínio da Força (Veterano), Intimidação (Expert)",
    attacks: [
      { name: "Toque Gelado", range: "Corpo a corpo", hit: "SEN+18", damage: "5d6", damageType: "Força/Sombrio", cost: "—", cooldown: "—", effect: "Alvo faz teste de PRE DT 26 ou fica Amedrontado 1 rodada." },
      { name: "Sussurro dos Mortos", range: "Área 9m", hit: "SEN+18", damage: "—", damageType: "Força/Controle", cost: "3 PE", cooldown: "2 rodadas", effect: "Impõe visões perturbadoras; alvos na área sofrem −5 em todos os testes até o fim do próximo turno deles." },
    ],
    powers: [],
    passives: [
      { name: "Semi-Incorpóreo", effect: "30% de chance de ataques físicos comuns passarem através dele sem efeito. Imune a dano físico/perfurante convencional (só dano de energia, Força ou explosivo funciona normalmente)." },
    ],
    ai: "Emerge da areia perto de tumbas perturbadas, tentando afastar (não necessariamente matar) intrusos com medo e desorientação antes de escalar pra dano direto. Retorna à areia e \"morre\" temporariamente se reduzido a 0 PV, reformando-se em 1d4 dias se a tumba permanecer intacta.",
    loot: "Nenhum de combate — associado a artefatos antigos na tumba que guarda (gancho de exploração).",
    lore: "Manifestação semi-fantasmagórica de energia residual do Lado Sombrio acumulada por milênios em Korriban — não é claro (nem mesmo para os próprios Sith) se são espíritos reais ou simplesmente eco de tanta morte e ódio concentrados num só lugar.",
  },

  // ===== Malachor =====
  {
    id: "fauna-malachor-aberracao-de-malachor",
    book: "fauna",
    name: "Aberração de Malachor",
    category: "Criatura",
    faction: "Corrompida",
    level: 28,
    threat: "Elite",
    role: "Dano/Tanque",
    size: "Grande",
    type: "Criatura da Força",
    planet: "Malachor",
    environment: "Campo de batalha petrificado",
    intelligence: "Baixa",
    disposition: "Fanática",
    pv: 240,
    pe: 76,
    defense: 27,
    initiative: 8,
    speed: "9m",
    attrs: { agi: 5, int: -1, forc: 9, vig: 8, pre: 0, sen: 6 },
    skills: "Intimidação (Veterano), Atletismo (Expert)",
    attacks: [
      { name: "Golpe Mutante", range: "Corpo a corpo", hit: "FOR+24", damage: "7d6", damageType: "Físico/Sombrio", cost: "—", cooldown: "—", effect: "—" },
      { name: "Explosão Residual", range: "Área 6m", hit: "SEN+21", damage: "7d6", damageType: "Força/Sombrio", cost: "4 PE", cooldown: "3 rodadas", effect: "Ecoa a energia da antiga catástrofe do planeta; todos na área testam VIG DT 27 ou ficam Derrubados." },
    ],
    powers: [],
    passives: [
      { name: "Mutação pela Catástrofe", effect: "reduz todo dano recebido em 6. Imune a venenos e doenças (biologia já irreversivelmente alterada)." },
    ],
    ai: "Ataca com fúria quase sem padrão reconhecível — resquício de trauma da devastadora explosão de massa que atingiu o planeta há gerações. Não distingue aliado de inimigo com clareza; até outros Sith evitam a área onde essas criaturas vagam.",
    loot: "Tecido mutado (componente alquímico instável, perigoso de manusear), fragmentos de armadura antiga fundida à própria pele da criatura.",
    lore: "Fauna sobrevivente (ou o que restou dela) do cataclismo que devastou Malachor — mutação extrema, alimentada por resíduos de uma arma de escala planetária e séculos de energia sombria acumulada no solo.",
  },
  {
    id: "fauna-malachor-sombra-errante",
    book: "fauna",
    name: "Sombra Errante",
    category: "Criatura",
    faction: "Sobrenatural",
    level: 20,
    threat: "Forte",
    role: "Controle",
    size: "Médio",
    type: "Criatura da Força",
    planet: "Malachor",
    environment: "Ruínas de guerra",
    intelligence: "Média",
    disposition: "Territorial",
    pv: 118,
    pe: 70,
    defense: 23,
    initiative: 7,
    speed: "9m (flutua)",
    attrs: { agi: 4, int: 0, forc: 2, vig: 3, pre: 1, sen: 9 },
    skills: "Domínio da Força (Expert), Furtividade (Expert)",
    attacks: [
      { name: "Dreno de Vontade", range: "9m", hit: "SEN+23", damage: "5d6", damageType: "Força", cost: "3 PE", cooldown: "2 rodadas", effect: "Alvo perde 1d4 PE além do dano; a Sombra recupera metade do PE drenado." },
    ],
    powers: [],
    passives: [
      { name: "Eco de Guerra", effect: "invisível a Percepção convencional (só sensitivos à Força ou tecnologia especial a detectam). Imune a dano físico comum." },
    ],
    ai: "Vaga pelas ruínas sem destino claro, atraída por concentrações de emoção forte (medo, raiva, desespero) que consegue sentir à distância — ataca quem gera esse \"ruído\" emocional mais intensamente, não necessariamente a ameaça tática mais óbvia.",
    loot: "Nenhum de combate — puramente uma entidade residual.",
    lore: "Fragmento de consciência ou emoção que nunca \"partiu\" depois da catástrofe de Malachor — nem viva nem exatamente morta, apenas presa, repetindo ecos de uma dor antiga que talvez nunca termine completamente.",
  },
];
