// Star Wars: Além da Fronteira — Bestiário Oficial de Mestre, Livro 2: Jedi
// Transcrito de StarWars-Teste/11-bestiario-jedi.md

import type { StarWarsCreature, CreatureModule } from "./types";

export const JEDI: StarWarsCreature[] = [
  {
    id: "jedi-youngling",
    book: "jedi",
    name: "Youngling",
    category: "Usuário da Força",
    faction: "Ordem Jedi",
    level: 1,
    threat: "Muito Fraco",
    role: "Suporte/Fuga",
    size: "Pequeno/Médio" as StarWarsCreature["size"],
    type: "Sensitivo",
    planet: "Coruscant (Templo Jedi)",
    environment: "Templo/academia",
    intelligence: "Alta",
    disposition: "Leal",
    pv: 6,
    pe: 8,
    defense: 15,
    initiative: 3,
    speed: "9m",
    attrs: { agi: 1, int: 1, forc: -1, vig: 0, pre: 0, sen: 2 },
    skills: "Domínio da Força (Iniciante), Percepção (Iniciante), Acrobacia (Iniciante)",
    attacks: [
      { name: "Bordão de Treino", range: "Corpo a corpo", hit: "AGI+6", damage: "1d4", damageType: "Físico (não-letal)", cost: "—", cooldown: "—", effect: "Sabre de treino a laser — dano reduzido de propósito, nunca mata." },
    ],
    powers: [
      { name: "Empurrãozinho", text: "descrição: leve rajada telecinética — regra: 1d4 de dano ou empurra o alvo 1,5m — recarga: 3 rodadas — duração: instantâneo — interações: quase sempre usado pra brincar ou desarmar, não pra ferir." },
    ],
    passives: [
      { name: "Potencial Não Lapidado", effect: "recebe vantagem em qualquer teste de Domínio da Força feito com supervisão de um Mestre presente." },
    ],
    ai: "Younglings nunca deveriam estar em combate real — se isso acontecer, o comportamento correto é fuga imediata e pedir ajuda. Se forçado a lutar, usa Empurrãozinho pra criar distância e foge.",
    loot: "Cristal kyber não lapidado (item de progressão narrativa, não de venda).",
    lore: "Crianças sensíveis à Força trazidas ao Templo Jedi cedo, treinadas em clãs até serem escolhidas como Padawan por um Mestre. Um clã de younglings numa cena de perigo é um gancho emocional poderoso, não um combate justo.",
  },
  {
    id: "jedi-padawan",
    book: "jedi",
    name: "Padawan",
    category: "Usuário da Força",
    faction: "Ordem Jedi",
    level: 8,
    threat: "Fraco",
    role: "Dano/Suporte",
    size: "Médio",
    type: "Sensitivo",
    planet: "Variável (aprendiz itinerante)",
    environment: "Qualquer",
    intelligence: "Alta",
    disposition: "Leal",
    pv: 30,
    pe: 22,
    defense: 17,
    initiative: 5,
    speed: "9m",
    attrs: { agi: 3, int: 1, forc: 0, vig: 1, pre: 1, sen: 4 },
    skills: "Sabres de Luz (Treinado), Domínio da Força (Treinado), Percepção (Treinado), Acrobacia (Iniciante)",
    attacks: [
      { name: "Forma I — Corte Inicial", range: "Corpo a corpo", hit: "Sabre de Luz", damage: "6d6×atributo+perícia", damageType: "Energia", cost: "—", cooldown: "—", effect: "Golpe básico e disciplinado — o primeiro que todo Jedi aprende." },
      { name: "Empurrão da Força", range: "6m", hit: "SEN+9", damage: "2d6", damageType: "Força", cost: "2 PE", cooldown: "2 rodadas", effect: "Empurra o alvo 3m; pode derrubar se o alvo estiver desequilibrado." },
    ],
    powers: [
      { name: "Salto Aumentado", text: "descrição: usa a Força pra saltar muito além do normal — regra: pode saltar até 6m de altura/distância sem teste — recarga: passiva — duração: contínua — interações: combina com Acrobacia pra manobras aéreas em combate." },
    ],
    passives: [
      { name: "Vínculo com o Mestre", effect: "se estiver na mesma cena que seu Mestre Jedi (uma patente Cavaleiro+ estatuída à parte), ganha +5 em Defesa." },
    ],
    ai: "Luta de forma disciplinada e um pouco hesitante — prioriza defesa e proteção de civis/aliados sobre dano puro. Recua se seu Mestre ordenar recuo, mesmo em desvantagem pessoal.",
    loot: "Sabre de luz de treino/aprendiz (uma lâmina, cor variável), componentes de kyber.",
    lore: "Aprendizes formalmente designados a um Mestre Jedi, viajando a campo pela primeira vez em missões reais. A relação Mestre-Padawan é o núcleo emocional da tradição Jedi — perder um Padawan em campo marca um Mestre pelo resto da vida.",
  },
  {
    id: "jedi-cavaleiro",
    book: "jedi",
    name: "Cavaleiro Jedi",
    category: "Usuário da Força",
    faction: "Ordem Jedi",
    level: 18,
    threat: "Médio",
    role: "Dano",
    size: "Médio",
    type: "Sensitivo",
    planet: "Variável",
    environment: "Qualquer",
    intelligence: "Alta",
    disposition: "Leal",
    pv: 68,
    pe: 42,
    defense: 23,
    initiative: 7,
    speed: "9m",
    attrs: { agi: 5, int: 1, forc: 0, vig: 2, pre: 2, sen: 6 },
    skills: "Sabres de Luz (Expert), Domínio da Força (Expert), Percepção (Treinado), Acrobacia (Treinado), Diplomacia (Iniciante)",
    attacks: [
      { name: "Forma III — Contra-Ataque (Soresu)", range: "Corpo a corpo", hit: "Sabre de Luz", damage: "6d6×atributo+perícia", damageType: "Energia", cost: "—", cooldown: "—", effect: "Enquanto usa esta forma, ganha +3 de Defesa até o início do próximo turno." },
      { name: "Puxão da Força", range: "9m", hit: "SEN+16", damage: "3d6", damageType: "Força", cost: "2 PE", cooldown: "2 rodadas", effect: "Puxa o alvo até 6m em direção ao Cavaleiro; pode desarmar em vez de causar dano." },
    ],
    powers: [
      { name: "Reflexo de Sabre", text: "descrição: intercepta um tiro de blaster em pleno voo — regra: uma vez por rodada, pode anular um ataque à distância contra si ou um aliado adjacente com um teste de Sabres de Luz DT 23 — recarga: 1 rodada — duração: instantâneo — interações: não funciona contra ataques em área." },
    ],
    passives: [
      { name: "Independência Plena", effect: "já não sofre nenhuma penalidade por lutar sem supervisão; ganha +5 em Iniciativa quando é o único Jedi na cena." },
    ],
    ai: "Combatente completo e confiante — avalia a cena antes de agir (1 rodada de leitura tática se possível), depois foca a ameaça mais perigosa ao grupo que protege, não necessariamente a mais fácil. Usa Puxão da Força pra desarmar antes de ferir quando a situação permite misericórdia.",
    loot: "Sabre de luz de Cavaleiro (lâmina própria construída), holocron pessoal (se aplicável à história).",
    lore: "Um Jedi plenamente reconhecido, livre pra aceitar seu próprio Padawan e agir com autonomia total em missões da Ordem. A maioria dos Jedi que a galáxia encontra em campo está nesta patente.",
  },
  {
    id: "jedi-veterano",
    book: "jedi",
    name: "Jedi Veterano",
    category: "Usuário da Força",
    faction: "Ordem Jedi",
    level: 28,
    threat: "Forte",
    role: "Dano/Tanque",
    size: "Médio",
    type: "Sensitivo",
    planet: "Variável",
    environment: "Qualquer",
    intelligence: "Alta",
    disposition: "Leal",
    pv: 147,
    pe: 68,
    defense: 26,
    initiative: 9,
    speed: "9m",
    attrs: { agi: 7, int: 2, forc: 1, vig: 3, pre: 3, sen: 8 },
    skills: "Sabres de Luz (Veterano), Domínio da Força (Veterano), Percepção (Expert), Liderança (Treinado)",
    attacks: [
      { name: "Forma V — Golpe Retaliatório (Djem So)", range: "Corpo a corpo", hit: "Sabre de Luz", damage: "6d6×atributo+perícia", damageType: "Energia", cost: "—", cooldown: "—", effect: "Se sofreu dano no turno anterior, este golpe recebe +2d6." },
      { name: "Barreira da Força", range: "9m (self ou aliado)", hit: "—", damage: "—", damageType: "Força", cost: "3 PE", cooldown: "3 rodadas", effect: "Cria um escudo que absorve os próximos 4d6 de dano recebido pelo alvo." },
    ],
    powers: [
      { name: "Precognição de Combate", text: "descrição: enxerga fragmentos de futuro próximo em combate — regra: uma vez por rodada, pode rolar novamente um teste de Defesa (mantém o melhor resultado) — recarga: passiva, 1x/rodada — duração: contínua — interações: não empilha com Reflexo de Sabre no mesmo ataque." },
    ],
    passives: [
      { name: "Veterano de Guerra", effect: "imune à condição Atordoado. Aliados a até 9m ganham +2 em Iniciativa (presença tranquilizadora em combate)." },
    ],
    ai: "Luta com paciência e leitura tática de longo prazo — deixa o oponente gastar recursos primeiro, contando com Precognição pra sobreviver aberturas. Protege ativamente aliados feridos usando Barreira da Força antes de focar dano próprio.",
    loot: "Sabre de luz veterano (possivelmente dupla lâmina ou variante), registros de campanhas passadas.",
    lore: "Jedi que atravessaram guerras, conflitos prolongados ou décadas de missões de campo. Muitos se tornam instrutores informais mesmo sem assento no Conselho — respeitados por experiência, não só por poder.",
  },
  {
    id: "jedi-mestre",
    book: "jedi",
    name: "Mestre Jedi",
    category: "Usuário da Força",
    faction: "Ordem Jedi",
    level: 42,
    threat: "Elite",
    role: "Dano/Controle",
    size: "Médio",
    type: "Sensitivo",
    planet: "Variável (frequentemente Coruscant)",
    environment: "Qualquer",
    intelligence: "Alta",
    disposition: "Leal",
    pv: 260,
    pe: 100,
    defense: 30,
    initiative: 11,
    speed: "9m",
    attrs: { agi: 9, int: 3, forc: 2, vig: 4, pre: 4, sen: 11 },
    skills: "Sabres de Luz (Mestre), Domínio da Força (Mestre), Percepção (Veterano), Liderança (Expert), Diplomacia (Treinado)",
    attacks: [
      { name: "Forma IV — Dança das Lâminas (Ataru)", range: "Corpo a corpo (pode atingir até 2 alvos adjacentes)", hit: "Sabre de Luz", damage: "6d6×atributo+perícia", damageType: "Energia", cost: "—", cooldown: "—", effect: "Movimento acrobático contínuo; ignora terreno difícil ao se mover entre alvos." },
      { name: "Onda de Força", range: "Área 9m à frente", hit: "SEN+23", damage: "5d6", damageType: "Força", cost: "4 PE", cooldown: "3 rodadas", effect: "Todos na área fazem teste de VIG DT 30 ou são derrubados e empurrados 4m." },
    ],
    powers: [
      { name: "Cura Profunda", text: "descrição: canaliza a Força pra fechar ferimentos graves — regra: restaura 6d6 PV a si ou a um aliado tocado — recarga: 4 rodadas — duração: instantâneo — interações: não pode ser usado no mesmo turno que um ataque." },
    ],
    passives: [
      { name: "Mestre Reconhecido", effect: "pode ter até 1 Padawan sob supervisão direta (estatuído à parte); enquanto o Padawan está na cena, ambos ganham +3 em todos os testes." },
    ],
    ai: "Comanda a cena com autoridade tática — usa Onda de Força pra controlar posicionamento do grupo inimigo antes de engajar. Prioriza neutralizar ameaças a civis antes de perseguir o alvo principal. Prefere resolver o conflito com o menor dano possível, mesmo tendo poder de sobra pra escalar.",
    loot: "Sabre de luz de Mestre, holocron de conhecimento avançado, cristal kyber sintonizado.",
    lore: "Um Jedi plenamente amadurecido, com assento potencial no Alto Conselho. Mestres Jedi lideram equipes, treinam gerações de Cavaleiros e frequentemente atuam como representantes diplomáticos da Ordem perante governos.",
  },
  {
    id: "jedi-mestre-conselho",
    book: "jedi",
    name: "Mestre do Conselho",
    category: "Usuário da Força",
    faction: "Ordem Jedi",
    level: 58,
    threat: "Chefe",
    role: "Dano/Controle",
    size: "Médio",
    type: "Sensitivo",
    planet: "Coruscant (Alto Conselho)",
    environment: "Templo Jedi",
    intelligence: "Sobre-humana",
    disposition: "Leal",
    // PV original: "616 (Segunda Fase abaixo de 50%: +1 ação e destrava Tempestade Serena)"
    pv: 616,
    pe: 144,
    defense: 32,
    initiative: 13,
    speed: "9m",
    attrs: { agi: 12, int: 4, forc: 3, vig: 6, pre: 6, sen: 15 },
    skills: "Sabres de Luz (Mestre), Domínio da Força (Mestre), Percepção (Mestre), Liderança (Mestre), Diplomacia (Veterano)",
    attacks: [
      { name: "Forma VII — Vórtice (Juyo controlado)", range: "Corpo a corpo (até 3 alvos)", hit: "Sabre de Luz", damage: "6d6×atributo+perícia", damageType: "Energia", cost: "—", cooldown: "—", effect: "Cada alvo adicional além do primeiro sofre metade do dano." },
      { name: "Tempestade da Força", range: "Área 12m", hit: "SEN+27", damage: "8d6", damageType: "Força", cost: "5 PE", cooldown: "3 rodadas", effect: "Todos na área fazem teste de VIG DT 32; falha = derrubado e Atordoado 1 rodada." },
    ],
    powers: [
      { name: "Tempestade Serena (Fase 2)", text: "descrição: destravada abaixo de 50% PV — regra: todos os poderes deste statblock custam metade do PE pelo resto do combate — recarga: 1x por combate — duração: resto do combate — interações: substitui a regeneração padrão de Chefe." },
    ],
    passives: [
      { name: "Voz do Conselho", effect: "em cenas sociais/políticas, sua palavra carrega peso institucional automático (vantagem em Diplomacia/Liderança envolvendo a Ordem Jedi ou a República)." },
    ],
    ai: "Extremamente calculista — nunca entra em combate sem antes tentar negociação ou desescalada, mas quando o combate é inevitável, age com eficiência letal e mínima hesitação. Protege o Templo, a República e Jedi mais jovens acima de qualquer outro objetivo tático.",
    loot: "Sabre de luz de assento do Conselho, holocron do Conselho (informação estratégica de altíssimo valor), registros confidenciais da Ordem.",
    lore: "Um dos doze assentos do Alto Conselho Jedi, responsáveis por guiar a Ordem inteira. Décadas — às vezes séculos — de experiência (especialmente em espécies de vida longa) tornam cada Mestre do Conselho uma autoridade viva em táticas, filosofia e política da Força.",
  },
  {
    id: "jedi-mestre-lendario",
    book: "jedi",
    name: "Mestre Lendário",
    category: "Usuário da Força",
    faction: "Ordem Jedi",
    level: 78,
    threat: "Chefe Lendário",
    role: "Dano/Controle",
    size: "Médio",
    type: "Sensitivo",
    planet: "Variável (frequentemente recluso)",
    environment: "Qualquer",
    intelligence: "Sobre-humana",
    disposition: "Leal",
    pv: 1190,
    pe: 210,
    defense: 34,
    initiative: 16,
    speed: "9m",
    attrs: { agi: 16, int: 5, forc: 4, vig: 8, pre: 8, sen: 20 },
    skills: "Sabres de Luz (Mestre), Domínio da Força (Mestre), Percepção (Mestre), Conhecimento da Força (Mestre)",
    attacks: [
      { name: "Golpe Final de Vaapad", range: "Corpo a corpo", hit: "Sabre de Luz", damage: "6d6×atributo+perícia", damageType: "Energia", cost: "—", cooldown: "—", effect: "Uma vez por combate, este golpe pode ser declarado \"decisivo\": se acertar, causa dano máximo automático em vez de rolar." },
      { name: "Tempestade Absoluta", range: "Área 20m", hit: "SEN+38", damage: "15d6", damageType: "Força", cost: "7 PE", cooldown: "4 rodadas", effect: "Todos na área (aliados podem optar por não ser afetados) fazem teste de VIG DT 34; falha = Derrubado, Atordoado 1 rodada e empurrado 6m." },
    ],
    powers: [
      { name: "Domínio Total da Força (Fase 2)", text: "descrição: destravado abaixo de 50% PV — regra: ignora custo de PE de todos os poderes pelo resto do combate — recarga: 1x por combate — duração: resto do combate — interações: se combinado com Golpe Final de Vaapad, o golpe decisivo fica disponível novamente." },
    ],
    passives: [
      { name: "Presença Inegável", effect: "qualquer criatura de nível inferior ao Mestre Lendário sofre −5 em testes de Intimidação contra ele e não pode ficar Amedrontada por ele (já superou esse medo há muito tempo, ou é imune por natureza)." },
    ],
    ai: "Luta apenas quando não há alternativa — um Mestre Lendário nesse nível resolve a maioria dos conflitos antes que cheguem a combate. Quando luta, é cirúrgico: neutraliza a maior ameaça em 1–2 trocas e imediatamente desescala, buscando capturar ou dissuadir em vez de matar sempre que possível.",
    loot: "Sabre de luz lendário (frequentemente com história própria conhecida na galáxia), holocron de sabedoria ancestral, cristal kyber único.",
    lore: "Uma lenda viva mesmo dentro da Ordem — nomes que aparecem em lições de história do Templo. Poucos alcançam este nível; a maioria dos que alcançam se afasta da vida pública, servindo como conselheiros ocultos ou eremitas guardando conhecimento longe de olhos perigosos.",
  },
  {
    id: "jedi-grao-mestre",
    book: "jedi",
    name: "Grão-Mestre",
    category: "Usuário da Força",
    faction: "Ordem Jedi",
    level: 96,
    // Ameaça original: "Chefe Lendário (capstone — o teto mecânico do sistema para um único Jedi)"
    threat: "Chefe Lendário (capstone — o teto mecânico do sistema para um único Jedi)" as StarWarsCreature["threat"],
    role: "Dano/Controle/Suporte",
    size: "Pequeno/Médio (varia por espécie)" as StarWarsCreature["size"],
    type: "Sensitivo",
    planet: "Coruscant (Templo Jedi)",
    environment: "Templo/qualquer",
    intelligence: "Sobre-humana",
    disposition: "Leal",
    pv: 1850,
    pe: 300,
    defense: 36,
    initiative: 20,
    speed: "9m (ou menos, com Deslocamento reduzido compensado por Salto Aumentado em qualquer alcance)",
    attrs: { agi: 18, int: 7, forc: 5, vig: 10, pre: 10, sen: 24 },
    skills: "Sabres de Luz (Mestre), Domínio da Força (Mestre), Conhecimento da Força (Mestre), Percepção (Mestre), Liderança (Mestre), Diplomacia (Mestre)",
    attacks: [
      { name: "Golpe da Unidade", range: "Corpo a corpo", hit: "Sabre de Luz", damage: "6d6×atributo+perícia", damageType: "Energia", cost: "—", cooldown: "—", effect: "Raramente usado — o Grão-Mestre prefere resolver conflitos sem violência." },
      { name: "Vontade da Força", range: "30m (ou toda a cena)", hit: "SEN+44", damage: "—", damageType: "Força", cost: "6 PE", cooldown: "3 rodadas", effect: "Efeito narrativo poderoso à escolha do Mestre: acalmar uma multidão inteira, revelar uma mentira, ou impor uma sugestão forte (nunca controle mental absoluto)." },
    ],
    powers: [
      { name: "Unidade com a Força (assinatura)", text: "descrição: o Grão-Mestre está tão em sintonia com a Força viva que parece antecipar tudo — regra: uma vez por combate, pode anular completamente um ataque ou efeito de qualquer origem (incluindo Ameaça Planetária/Galáctica), sem teste — recarga: 1x por cena — duração: instantâneo — interações: não pode ser usado duas vezes na mesma cena, nem por ninguém além do Grão-Mestre." },
    ],
    passives: [
      { name: "Farol da Ordem", effect: "enquanto vivo e livre, todo Jedi na galáxia sente uma calma sutil de fundo (benefício narrativo: +2 em testes de resistência a medo/Lado Sombrio pra qualquer PJ Jedi da campanha). Sua morte é sentida por toda a Ordem simultaneamente." },
    ],
    ai: "Um Grão-Mestre em combate é, quase sempre, o clímax final de uma campanha — seja como aliado supremo ou (raríssimo) como antagonista corrompido. Prioriza sempre minimizar dano colateral e preservar vidas, mesmo à própria custa. Jamais usa Vontade da Força de forma manipuladora — isso é, por definição, incompatível com o papel.",
    loot: "Não se aplica normalmente — este é um NPC de estrutura narrativa, não de saque. Se necessário: sabre de luz do Grão-Mestre (item de importância histórica para toda a galáxia).",
    lore: "O líder eleito ou reconhecido do Alto Conselho Jedi, guardião final da tradição e da Força viva. Existe apenas um por vez na Ordem. Nota de design: mecanicamente é tratado como Chefe Lendário (não Ameaça Planetária) de propósito — mesmo o Jedi mais poderoso da galáxia continua sendo *um combatente*, não um evento de escala mundial; isso preserva a possibilidade (rara, mas real) de um grupo de PJs de altíssimo nível desafiá-lo em ficção.",
  },
];

export const JEDI_SPECIALIZATIONS: CreatureModule[] = [
  { id: "jedi-spec-guardiao", name: "Guardião", text: "+Atletismo (mesmo grau da patente base). Poder extra: **Postura Inabalável** (custo 2 PE, recarga 2 rodadas — +8 Defesa por 2 rodadas). Passiva ajustada: PV máximo +20%." },
  { id: "jedi-spec-consular", name: "Consular", text: "+Conhecimento da Força. Poder extra: **Serenidade Projetada** (custo 3 PE, recarga 3 rodadas — remove uma condição de controle de até 2 aliados num raio de 9m). Passiva ajustada: custo de todos os Poderes reduzido em 1 PE (mínimo 1)." },
  { id: "jedi-spec-sentinela", name: "Sentinela", text: "+Furtividade e +Investigação. Poder extra: **Passo Silencioso** (custo 1 PE, recarga 1 rodada — some da Percepção de todos até seu próximo ataque). Passiva ajustada: primeiro golpe de cada combate causa +2d6 se o alvo não notou sua aproximação." },
  { id: "jedi-spec-curandeiro", name: "Curandeiro", text: "+Medicina. Poder extra (substitui Cura Profunda se a patente já tiver): **Transferência de Vida** (custo 4 PE, recarga 4 rodadas — transfere até 6d6 PV de si pra um aliado, sem restaurar os próprios PV). Passiva ajustada: qualquer cura que este NPC realiza é 50% mais eficaz." },
  { id: "jedi-spec-arqueologo", name: "Arqueólogo Jedi", text: "+Conhecimento Galáctico e +Investigação. Poder extra: **Memória da Força** (sem custo, recarga 1x por cena — identifica automaticamente a origem/história de qualquer artefato tocado). Passiva ajustada: vantagem em qualquer teste envolvendo ruínas, holocrons ou textos antigos." },
  { id: "jedi-spec-mestre-das-bestas", name: "Mestre das Bestas", text: "+Sobrevivência. Poder extra: **Chamado Selvagem** (custo 3 PE, recarga por cena — uma criatura selvagem amistosa do bestiário aparece pra ajudar, escolhida pelo Mestre conforme o bioma). Passiva ajustada: nunca é atacado por criaturas selvagens não-sencientes a menos que ataque primeiro." },
  { id: "jedi-spec-mestre-diplomata", name: "Mestre Diplomata", text: "+Diplomacia e +Persuasão. Poder extra: **Palavra que Acalma** (custo 2 PE, recarga 2 rodadas — impõe DT 23+ em qualquer teste de Intimidação/Enganação feito contra o grupo dele nos próximos 2 turnos). Passiva ajustada: nunca é o alvo inicial de uma emboscada — inimigos preferem negociar primeiro por instinto/reputação." },
  { id: "jedi-spec-mestre-investigador", name: "Mestre Investigador", text: "+Investigação e +Percepção. Poder extra: **Eco do Passado** (sem custo, recarga 1x por cena — vê um flash psíquico de um evento recente ligado à Força ocorrido no local). Passiva ajustada: nunca é enganado por Furtividade de nível igual ou inferior ao seu." },
  { id: "jedi-spec-mestre-da-forca", name: "Mestre da Força", text: "+Domínio da Força (sobe um grau em relação à patente base). Poder extra: **Rajada Bruta** (custo igual ao poder de ataque da patente, recarga igual — mesmo dano do Poder de área principal da patente, mas em alcance dobrado). Passiva ajustada: PE máximo +30%." },
];
