import type { StarWarsCreature, CreatureModule } from "./types";

export const MANDALORIANOS: StarWarsCreature[] = [
  {
    id: "mandaloriano-recruta",
    book: "mandalorianos",
    name: "Recruta",
    category: "Mandaloriano",
    faction: "Clã (variável)",
    level: 3,
    threat: "Fraco",
    role: "Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Mandalore",
    environment: "Qualquer",
    intelligence: "Alta",
    disposition: "Leal (ao clã)",
    pv: 16,
    pe: 8,
    defense: 16,
    initiative: 3,
    speed: "9m",
    attrs: { agi: 2, int: 1, forc: 1, vig: 2, pre: 0, sen: 0 },
    skills: "Armas de Energia (Iniciante), Atletismo (Iniciante)",
    attacks: [
      {
        name: "Blaster Padrão",
        range: "20m",
        hit: "AGI+7",
        damage: "1d6",
        damageType: "Energia",
        cost: "—",
        cooldown: "—",
        effect: "—",
      },
      {
        name: "Vibro-faca",
        range: "Corpo a corpo",
        hit: "AGI+7",
        damage: "1d6",
        damageType: "Físico",
        cost: "—",
        cooldown: "—",
        effect: "—",
      },
    ],
    powers: [],
    passives: [
      {
        name: "Armadura de Treino",
        effect: "reduz dano físico recebido em 1 (armadura ainda não é beskar completo).",
      },
    ],
    ai: "Segue ordens de um Guerreiro ou Comandante presente sem questionar. Sozinho, luta com coragem mas sem refinamento tático — erra posicionamento com frequência.",
    loot: "Blaster padrão, fragmentos de armadura mandaloriana (não-beskar).",
    lore: "Jovem mandaloriano recém-formado no Treinamento da Fundição, ainda ganhando o direito de forjar cada peça da própria armadura através de feitos provados.",
  },
  {
    id: "mandaloriano-guerreiro",
    book: "mandalorianos",
    name: "Guerreiro",
    category: "Mandaloriano",
    faction: "Clã (variável)",
    level: 10,
    threat: "Médio",
    role: "Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Mandalore",
    environment: "Qualquer",
    intelligence: "Alta",
    disposition: "Leal (ao clã)",
    pv: 44,
    pe: 20,
    defense: 19,
    initiative: 6,
    speed: "9m",
    attrs: { agi: 4, int: 2, forc: 3, vig: 4, pre: 1, sen: 0 },
    skills: "Armas de Energia (Treinado), Atletismo (Treinado), Pilotagem Atmosférica (Iniciante)",
    attacks: [
      {
        name: "Rifle Blaster",
        range: "30m",
        hit: "AGI+14",
        damage: "2d6",
        damageType: "Energia",
        cost: "—",
        cooldown: "—",
        effect: "—",
      },
      {
        name: "Lançador de Pulso do Pulso",
        range: "12m (área 3m)",
        hit: "AGI+14",
        damage: "2d6",
        damageType: "Energia",
        cost: "2 PE",
        cooldown: "2 rodadas",
        effect: "Todos na área testam AGI DT 17 ou ficam Derrubados.",
      },
    ],
    powers: [],
    passives: [
      {
        name: "Beskar Completo",
        effect: "reduz todo dano físico e de energia recebido em 3.",
      },
    ],
    ai: "Combatente confiável e disciplinado — mantém formação com outros mandalorianos, prioriza cobertura tática antes de avançar. Usa Lançador de Pulso pra abrir espaço antes de avançar em corpo a corpo.",
    loot: "Rifle blaster, armadura beskar (peças, altíssimo valor), lançador de pulso.",
    lore: 'Um mandaloriano de armadura completa, "Este é o Caminho" plenamente internalizado — guerreiro capaz e leal, espinha dorsal de qualquer força de combate mandaloriana.',
  },
  {
    id: "mandaloriano-veterano",
    book: "mandalorianos",
    name: "Veterano",
    category: "Mandaloriano",
    faction: "Clã (variável)",
    level: 18,
    threat: "Forte",
    role: "Dano/Tanque",
    size: "Médio",
    type: "Humanoide",
    planet: "Mandalore",
    environment: "Qualquer",
    intelligence: "Alta",
    disposition: "Leal (ao clã)",
    pv: 102,
    pe: 40,
    defense: 23,
    initiative: 8,
    speed: "9m (voo com jetpack 15m, 3 rodadas)",
    attrs: { agi: 6, int: 2, forc: 4, vig: 5, pre: 2, sen: 0 },
    skills: "Armas de Energia (Expert), Atletismo (Veterano), Pilotagem Atmosférica (Treinado)",
    attacks: [
      {
        name: "Rifle Blaster Modificado",
        range: "35m",
        hit: "AGI+21",
        damage: "4d6",
        damageType: "Energia",
        cost: "—",
        cooldown: "—",
        effect: "—",
      },
      {
        name: "Lança-Chamas do Pulso",
        range: "6m (cone)",
        hit: "AGI+21",
        damage: "4d6",
        damageType: "Fogo",
        cost: "3 PE",
        cooldown: "2 rodadas",
        effect: "Todos no cone sofrem +1d6 de fogo contínuo na rodada seguinte se não apagarem.",
      },
      {
        name: "Jetpack — Investida Aérea",
        range: "Corpo a corpo (após voo)",
        hit: "FOR+18",
        damage: "4d6",
        damageType: "Físico",
        cost: "2 PE",
        cooldown: "2 rodadas",
        effect: "Requer usar o jetpack no turno anterior; empurra o alvo 3m.",
      },
    ],
    powers: [],
    passives: [
      {
        name: "Combate 3D",
        effect: "o jetpack permite ignorar terreno difícil e atacar de ângulos verticais; +3 em Iniciativa quando entra em combate vindo do ar.",
      },
    ],
    ai: "Usa o espaço vertical agressivamente — abre combate com Investida Aérea contra o alvo mais perigoso, depois usa Lança-Chamas contra grupos agrupados. Recua voando se a situação virar, mas raramente foge de vez — mandalorianos veteranos preferem reagrupar e retornar.",
    loot: "Jetpack funcional, rifle modificado, armadura beskar veterana (frequentemente customizada com cores de clã).",
    lore: "Sobrevivente de múltiplos conflitos reais, um Veterano carrega cicatrizes (literais e na armadura) de cada batalha. Muitos se tornam instrutores informais de Recrutas.",
  },
  {
    id: "mandaloriano-cacador-de-recompensas",
    book: "mandalorianos",
    name: "Caçador de Recompensas",
    category: "Mandaloriano",
    faction: "Independente (guilda)",
    level: 22,
    threat: "Forte",
    role: "Furtivo/Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Variável (itinerante)",
    environment: "Qualquer",
    intelligence: "Alta",
    disposition: "Calculista",
    pv: 118,
    pe: 46,
    defense: 26,
    initiative: 10,
    speed: "9m (voo com jetpack 15m, 3 rodadas)",
    attrs: { agi: 7, int: 3, forc: 4, vig: 5, pre: 1, sen: 0 },
    skills: "Armas de Energia (Veterano), Investigação (Expert), Furtividade (Treinado), Intimidação (Treinado)",
    attacks: [
      {
        name: "Blaster de Precisão",
        range: "40m",
        hit: "AGI+24",
        damage: "5d6",
        damageType: "Energia",
        cost: "—",
        cooldown: "—",
        effect: "Contra alvo Surpreendido, +2d6.",
      },
      {
        name: "Dardo Rastreador",
        range: "15m",
        hit: "AGI+24",
        damage: "1d6",
        damageType: "Físico",
        cost: "2 PE",
        cooldown: "1x por alvo/cena",
        effect: "Não busca dano — gruda um rastreador no alvo, revelando localização por 24h de jogo.",
      },
      {
        name: "Rede Vibro-Eletrificada",
        range: "9m",
        hit: "AGI+24",
        damage: "3d6",
        damageType: "Energia",
        cost: "3 PE",
        cooldown: "3 rodadas",
        effect: "Alvo fica Agarrado e Atordoado se falhar em VIG DT 26 — ideal pra capturas vivas.",
      },
    ],
    powers: [],
    passives: [
      {
        name: "Sempre Recebe o Pagamento",
        effect: "vantagem em Investigação pra localizar qualquer alvo com recompensa ativa. Escudo de energia pessoal (Beskar + tech) absorve os primeiros 2d6 de dano recebido por combate, recarregando entre cenas.",
      },
    ],
    ai: "Extremamente metódico — usa Dardo Rastreador antes de engajar quando possível, prefere resolver o contrato (morto ou vivo, conforme o pedido) com o menor risco pessoal. Não briga por orgulho; se o contrato vira armadilha, aborta sem hesitar.",
    loot: "Blaster de precisão, equipamento de rastreamento, créditos de recompensa (o próprio motivo do encontro).",
    lore: "Mandaloriano que troca lealdade de clã fixa por trabalho contratado através da Guilda de Caçadores de Recompensas — ainda segue o Caminho, mas o aplica de forma mais individualista e pragmática.",
  },
  {
    id: "mandaloriano-comandante",
    book: "mandalorianos",
    name: "Comandante",
    category: "Mandaloriano",
    faction: "Clã (variável)",
    level: 30,
    threat: "Elite",
    role: "Comandante/Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Mandalore",
    environment: "Qualquer",
    intelligence: "Alta",
    disposition: "Leal (ao clã)",
    pv: 180,
    pe: 66,
    defense: 27,
    initiative: 11,
    speed: "9m (voo com jetpack 15m, 4 rodadas)",
    attrs: { agi: 8, int: 4, forc: 6, vig: 7, pre: 5, sen: 0 },
    skills: "Armas de Energia (Veterano), Liderança (Expert), Atletismo (Veterano), Pilotagem Espacial (Treinado)",
    attacks: [
      {
        name: "Rifle Blaster de Comando",
        range: "35m",
        hit: "AGI+28",
        damage: "7d6",
        damageType: "Energia",
        cost: "—",
        cooldown: "—",
        effect: "—",
      },
      {
        name: "Pássaros Sibilantes (mini-mísseis)",
        range: "20m (área 4m)",
        hit: "AGI+28",
        damage: "7d6",
        damageType: "Explosivo",
        cost: "4 PE",
        cooldown: "3 rodadas",
        effect: "Enxame de projéteis guiados; pode dividir entre até 3 alvos diferentes na área.",
      },
    ],
    powers: [
      {
        name: "Comando de Batalha",
        text: "descrição: coordena tropas mandalorianas em tempo real — regra: até 3 aliados mandalorianos na cena ganham +5 em Acerto na próxima rodada — recarga: 2 rodadas — duração: 1 rodada — interações: não afeta a si mesmo.",
      },
    ],
    passives: [
      {
        name: "Beskar de Comando",
        effect: "reduz todo dano recebido em 6. Nunca fica sem ação por condições de controle de nível inferior ao seu (recusa-se a cair).",
      },
    ],
    ai: "Comanda ativamente — usa Comando de Batalha antes de qualquer ataque pessoal, sempre priorizando a coordenação do grupo sobre o dano individual. Se ficar sozinho, ainda luta com eficiência de elite, mas prioriza recuar pra reagrupar com tropas.",
    loot: "Rifle de comando, lançador de Pássaros Sibilantes, armadura beskar de comando (visual distinto, cores de clã proeminentes).",
    lore: "Líder tático de esquadrões mandalorianos em campanha — abaixo apenas do Líder de Clã na cadeia de comando, mas frequentemente quem realmente executa a estratégia em campo.",
  },
  {
    id: "mandaloriano-ferreiro",
    book: "mandalorianos",
    name: "Ferreiro (Armeira do Clã)",
    category: "Mandaloriano",
    faction: "Clã (variável)",
    level: 35,
    threat: "Elite",
    role: "Suporte/Tanque",
    size: "Médio",
    type: "Humanoide",
    planet: "Mandalore (forja do clã)",
    environment: "Forja",
    intelligence: "Sobre-humana",
    disposition: "Leal (guardiã da tradição)",
    pv: 210,
    pe: 88,
    defense: 27,
    initiative: 9,
    speed: "9m",
    attrs: { agi: 6, int: 8, forc: 7, vig: 8, pre: 4, sen: 0 },
    skills: "Mecânica (Mestre), Armas de Energia (Veterano), Ciências (Expert), Atletismo (Treinado)",
    attacks: [
      {
        name: "Martelo de Forja (arma ritual)",
        range: "Corpo a corpo",
        hit: "FOR+27",
        damage: "8d6",
        damageType: "Físico",
        cost: "—",
        cooldown: "—",
        effect: "Forjado em beskar puro — ignora metade de qualquer redução de dano do alvo.",
      },
      {
        name: "Explosivo de Forja",
        range: "12m (área 4m)",
        hit: "INT+29",
        damage: "8d6",
        damageType: "Explosivo",
        cost: "4 PE",
        cooldown: "3 rodadas",
        effect: "Composto químico da própria forja; deixa fogo residual (1d6/rodada por 2 rodadas).",
      },
    ],
    powers: [
      {
        name: "Forjar Sob Pressão",
        text: 'descrição: repara ou aprimora armadura em campo, mesmo em combate — regra: restaura o equivalente a 6d6 de "PV de armadura" a si ou a um aliado adjacente (reduz o próximo dano recebido nesse valor) — recarga: 3 rodadas — duração: até absorver o dano — interações: não empilha com Beskar de Comando de outro NPC.',
      },
    ],
    passives: [
      {
        name: "Guardiã dos Segredos",
        effect: "imune a qualquer tentativa de roubo/cópia de conhecimento de forja (proteção narrativa). Sabe forjar qualquer item de beskar descrito neste livro.",
      },
    ],
    ai: "Prefere não entrar em combate — é a guardiã espiritual e técnica do clã, não a linha de frente. Quando luta (geralmente em defesa da forja ou do clã), é implacável e usa Forjar Sob Pressão pra manter aliados na luta.",
    loot: "Ferramentas de forja (item de progressão narrativa — permite criar armaduras beskar pros PJs), lingotes de beskar bruto.",
    lore: "Guardiã do conhecimento sagrado de forjar beskar e das tradições religiosas mais profundas do Caminho — posição de altíssimo respeito, frequentemente máscara desenhada de forma única e reconhecível.",
  },
  {
    id: "mandaloriano-elite",
    book: "mandalorianos",
    name: "Elite (Comando Especial)",
    category: "Mandaloriano",
    faction: "Clã de elite/Death Watch-equivalente",
    level: 48,
    threat: "Chefe",
    role: "Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Mandalore ou base secreta",
    environment: "Qualquer",
    intelligence: "Alta",
    disposition: "Fanática",
    pv: 686,
    pe: 118,
    defense: 30,
    initiative: 14,
    speed: "9m (voo com jetpack 18m, ilimitado com combustível de campanha)",
    attrs: { agi: 11, int: 5, forc: 9, vig: 11, pre: 6, sen: 0 },
    skills: "Armas de Energia (Mestre), Atletismo (Mestre), Intimidação (Veterano), Pilotagem Atmosférica (Expert)",
    attacks: [
      {
        name: "Duplo Blaster de Punho",
        range: "30m",
        hit: "AGI+36",
        damage: "10d6",
        damageType: "Energia",
        cost: "—",
        cooldown: "—",
        effect: "Dois disparos simultâneos — pode dividir o dano entre 2 alvos.",
      },
      {
        name: "Lança de Beskar",
        range: "Corpo a corpo/12m (arremesso)",
        hit: "FOR+34",
        damage: "10d6",
        damageType: "Perfurante",
        cost: "—",
        cooldown: "1 rodada",
        effect: "Ignora completamente redução de dano por armadura do alvo.",
      },
    ],
    powers: [
      {
        name: "Fúria de Beskar (Fase 2)",
        text: "descrição: destravada abaixo de 50% PV — regra: +2 ações por rodada pelo resto do combate, todos os ataques ganham +3d6 — recarga: 1x por combate — duração: resto do combate — interações: consome combustível de jetpack mais rápido (narrativo).",
      },
    ],
    passives: [
      {
        name: "Armadura de Elite",
        effect: "reduz todo dano recebido em 10. Imune à condição Derrubado (jetpack corrige o equilíbrio automaticamente).",
      },
    ],
    ai: "Combatente de elite treinado pra operações de alto risco — ataca com agressividade calculada, focando sempre o alvo de maior ameaça primeiro. Fúria de Beskar é usada sem hesitação quando percebe que a vitória está em jogo.",
    loot: "Duplo blaster de punho, lança de beskar (item raro de altíssimo valor), armadura de elite completa.",
    lore: "Mandaloriano de operações especiais, treinado além do padrão de Veterano ou Comandante — frequentemente associado a facções mais radicais que acreditam que o Caminho exige conquista ativa, não só defesa.",
  },
  {
    id: "mandaloriano-lendario",
    book: "mandalorianos",
    name: "Lendário (Portador do Título de Mandalore)",
    category: "Mandaloriano",
    faction: "Todo Mandalore (ou pretendente ao título)",
    level: 70,
    threat: "Chefe Lendário",
    role: "Comandante/Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Mandalore",
    environment: "Qualquer",
    intelligence: "Sobre-humana",
    disposition: "Leal (a todo o povo mandaloriano)",
    pv: 1400,
    pe: 160,
    defense: 34,
    initiative: 17,
    speed: "9m (voo ilimitado com jetpack de comando)",
    attrs: { agi: 15, int: 6, forc: 12, vig: 14, pre: 10, sen: 0 },
    skills: "Armas de Energia (Mestre), Liderança (Mestre), Atletismo (Mestre), Intimidação (Mestre)",
    attacks: [
      {
        name: "Darksaber ou Arma Ancestral do Clã",
        range: "Corpo a corpo",
        hit: "FOR+35",
        damage: "15d6",
        damageType: "Energia/Físico",
        cost: "—",
        cooldown: "—",
        effect: "Se empunhar um Darksaber (item único de campanha), este ataque conta como conquista simbólica — vencer o duelo pode transferir a liderança de Mandalore narrativamente.",
      },
      {
        name: "Arsenal Completo",
        range: "30m (escolha um efeito por rodada: Pássaros Sibilantes, lança-chamas, ou disparo de precisão)",
        hit: "AGI+35",
        damage: "15d6",
        damageType: "Variável",
        cost: "5 PE",
        cooldown: "1 rodada",
        effect: "Flexibilidade tática máxima — muda o tipo de ataque a cada rodada conforme a situação.",
      },
    ],
    powers: [
      {
        name: "Une o Povo",
        text: 'descrição: em batalha, todo mandaloriano aliado presente luta como se fosse parte de um só corpo — regra: todos os aliados mandalorianos na cena ganham +1 ação na primeira rodada de qualquer combate que o Lendário participe — recarga: 1x por combate — duração: 1 rodada — interações: um dos raros efeitos de "buff em massa" fora do sistema padrão de Poderes Gerais, justificado pela lenda pessoal do NPC.',
      },
    ],
    passives: [
      {
        name: "Símbolo Vivo",
        effect: "reduz todo dano recebido em 12. Enquanto vivo, unifica (ao menos temporariamente) clãs mandalorianos rivais contra uma ameaça comum — efeito puramente narrativo de campanha.",
      },
    ],
    ai: "Luta como lenda viva — combina toda a versatilidade das patentes anteriores (voo, arsenal completo, comando de tropas) com julgamento tático impecável. Prioriza sempre o bem do povo mandaloriano acima da glória pessoal — aceita ajuda, recua estrategicamente se necessário pra lutar outro dia.",
    loot: 'Arma ancestral do clã ou Darksaber (item de campanha, não "loot" comum), armadura beskar lendária.',
    lore: 'O título de Mandalore (ou equivalente supremo, dependendo da era e facção da campanha) é conquistado por direito de conquista, herança ou consenso de clãs — raramente os três ao mesmo tempo, o que torna a posição perpetuamente contestada. Um verdadeiro capítulo de campanha inteiro pode girar em torno de quem "deveria" portar este título.',
  },
];

export const MANDALORIAN_LOADOUTS: CreatureModule[] = [
  {
    id: "mandaloriano-loadout-franco-atirador",
    name: "Franco-atirador",
    text: "troca ataque de longo alcance por um com alcance dobrado e +5 em Acerto contra alvo Surpreendido, mas sem ataque secundário de área.",
  },
  {
    id: "mandaloriano-loadout-explosivos",
    name: "Explosivos",
    text: "troca ataque secundário por uma carga explosiva de mesma escala de dano, com recarga +1 rodada mas atingindo área maior (+3m de raio).",
  },
  {
    id: "mandaloriano-loadout-escudo-e-lanca",
    name: "Escudo e Lança",
    text: "troca um ataque à distância por +5 de Defesa permanente e um ataque corpo a corpo extra de mesmo dano.",
  },
  {
    id: "mandaloriano-loadout-camuflagem-ativa",
    name: "Camuflagem Ativa",
    text: 'adiciona a Passiva "Invisível até atacar ou até 1 rodada se passar, o que vier primeiro" — em troca, reduz o PV total em 15%.',
  },
  {
    id: "mandaloriano-loadout-suporte-medico-de-campo",
    name: "Suporte Médico de Campo",
    text: 'troca um ataque por um Poder de cura idêntico ao "Forjar Sob Pressão" do Ferreiro, na mesma escala de PE da patente.',
  },
];
