import type { StarWarsCreature } from "./types";

export const MILITARES: StarWarsCreature[] = [
  // ─── 1. República ─────────────────────────────────────────────────────
  {
    id: "militar-soldado-republica",
    book: "militares",
    name: "Soldado da República (Milícia Planetária)",
    category: "Militar",
    faction: "República",
    level: 5,
    threat: "Fraco",
    role: "Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Variável",
    environment: "Guarnições planetárias",
    intelligence: "Média",
    disposition: "Leal",
    pv: 22,
    pe: 8,
    defense: 17,
    initiative: 3,
    speed: "9m",
    attrs: { agi: 2, int: 1, forc: 1, vig: 2, pre: 0, sen: 0 },
    skills: "Armas de Energia (Iniciante), Liderança (Iniciante — só oficiais)",
    attacks: [
      { name: "Blaster de Milícia", range: "25m", hit: "AGI+7", damage: "2d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "—" },
    ],
    powers: [],
    passives: [
      { name: "Reservista", effect: "em número (grupos de 4+), ganha +2 em Acerto por moral coletiva." },
    ],
    ai: "Segue protocolo básico de cobertura, mas hesita sob pressão real — não é tropa profissional. Foge ou se rende se a liderança cair.",
    loot: "Blaster padrão, kit de primeiros socorros básico.",
    lore: "Forças de defesa planetária locais, mobilizadas em crises quando o Grande Exército da República não está disponível — corajosos, mas sem o treino dos clones.",
  },
  {
    id: "militar-clone-trooper",
    book: "militares",
    name: "Clone Trooper (Padrão)",
    category: "Militar",
    faction: "República",
    level: 10,
    threat: "Médio",
    role: "Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Kamino (origem)",
    environment: "Frente de batalha",
    intelligence: "Alta",
    disposition: "Leal",
    pv: 44,
    pe: 16,
    defense: 19,
    initiative: 6,
    speed: "9m",
    attrs: { agi: 3, int: 2, forc: 2, vig: 3, pre: 1, sen: 0 },
    skills: "Armas de Energia (Treinado), Liderança (Iniciante), Pilotagem Atmosférica (Iniciante)",
    attacks: [
      { name: "Rifle DC-15A", range: "35m", hit: "AGI+13", damage: "2d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "—" },
      { name: "Granada Termal", range: "15m (área 4m)", hit: "AGI+13", damage: "2d6", damageType: "Explosivo", cost: "2 PE", cooldown: "3 rodadas", effect: "—" },
    ],
    powers: [],
    passives: [
      { name: "Treinamento Kaminoano", effect: "vantagem em testes de moral (nunca entra em pânico sozinho). Sempre coordena com outros clones automaticamente (sem precisar de teste social)." },
    ],
    ai: "Executa táticas de esquadrão com precisão — cobertura mútua, avanço em bounding overwatch, prioriza alvos marcados por um oficial. Segue Ordem 66 e comandos similares sem hesitação quando ativados (gancho de campanha, não regra mecânica padrão).",
    loot: "Rifle DC-15A, armadura Fase I/II (peças), granadas termais.",
    lore: "Soldado geneticamente idêntico produzido em Kamino a partir do material genético de Jango Fett, treinado desde a \"infância\" acelerada pra guerra. A espinha dorsal do Grande Exército da República.",
  },
  {
    id: "militar-arc-trooper",
    book: "militares",
    name: "ARC Trooper",
    category: "Militar",
    faction: "República",
    level: 18,
    threat: "Forte",
    role: "Dano/Furtivo",
    size: "Médio",
    type: "Humanoide",
    planet: "Kamino (origem, treino avançado)",
    environment: "Operações especiais",
    intelligence: "Alta",
    disposition: "Leal",
    pv: 102,
    pe: 34,
    defense: 23,
    initiative: 9,
    speed: "9m",
    attrs: { agi: 6, int: 3, forc: 4, vig: 5, pre: 2, sen: 0 },
    skills: "Armas de Energia (Veterano), Furtividade (Treinado), Investigação (Treinado), Liderança (Treinado)",
    attacks: [
      { name: "Duplo Blaster WESTAR-M5", range: "30m", hit: "AGI+21", damage: "4d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "Dois disparos por ataque — pode dividir entre 2 alvos." },
      { name: "Carga Direcionada", range: "6m", hit: "AGI+21", damage: "4d6", damageType: "Explosivo", cost: "3 PE", cooldown: "2 rodadas", effect: "Explosivo de demolição — dano triplicado contra estruturas/veículos." },
    ],
    powers: [],
    passives: [
      { name: "Treinamento Avançado", effect: "imune à condição Amedrontado. Ganha +5 em Iniciativa em missões de infiltração/reconhecimento." },
    ],
    ai: "Opera com autonomia muito maior que um clone padrão — toma decisões táticas complexas sem esperar ordens. Prioriza alvos de comando inimigos (oficiais, droides táticos) antes de tropas comuns.",
    loot: "Duplo blaster WESTAR-M5, cargas de demolição, armadura ARC customizada (kama, marcas pessoais).",
    lore: "Clones Avançados de Reconhecimento, treinados além do padrão em Kamino pra operações independentes de alto risco — muitos desenvolvem personalidades e cabelo próprios (fora do padrão), sinal de individualidade cultivada deliberadamente.",
  },
  {
    id: "militar-clone-commando",
    book: "militares",
    name: "Clone Commando",
    category: "Militar",
    faction: "República",
    level: 22,
    threat: "Forte",
    role: "Dano/Furtivo",
    size: "Médio",
    type: "Humanoide",
    planet: "Kamino (treino Comando)",
    environment: "Operações especiais de alto risco",
    intelligence: "Alta",
    disposition: "Leal",
    pv: 126,
    pe: 42,
    defense: 26,
    initiative: 10,
    speed: "9m",
    attrs: { agi: 7, int: 4, forc: 5, vig: 6, pre: 2, sen: 0 },
    skills: "Armas de Energia (Veterano), Furtividade (Expert), Mecânica (Treinado), Sobrevivência (Treinado)",
    attacks: [
      { name: "DC-17m Modular", range: "35m (ou corpo a corpo com bainha de lâmina acoplada)", hit: "AGI+24", damage: "5d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "Modo alternável: sniper (bônus de Acerto +3, sem movimento) ou automático (área 3m, -2 Acerto)." },
      { name: "Explosivos Anti-Blindagem", range: "12m", hit: "AGI+24", damage: "5d6", damageType: "Explosivo", cost: "3 PE", cooldown: "2 rodadas", effect: "Dano dobrado contra Droides ou veículos." },
    ],
    powers: [],
    passives: [
      { name: "Esquadrão de 4", effect: "Clone Commandos operam quase sempre em esquadrões de exatamente 4; enquanto os 4 estiverem vivos e próximos (9m), todos ganham +3 em Defesa por cobertura mútua treinada." },
    ],
    ai: "Extremamente coordenado — cada membro do esquadrão tem um papel fixo (ponto, retaguarda, demolição, médico de campo) e o Mestre deve tratar o grupo de 4 quase como uma única entidade tática em termos de sincronização.",
    loot: "DC-17m modular, explosivos anti-blindagem, equipamento de infiltração.",
    lore: "Elite entre a elite — treinados separadamente dos clones padrão desde o início, em doutrina mais próxima de forças especiais reais que de exército em massa. Esquadrões lendários como o Delta Squad se tornaram lenda mesmo entre outros clones.",
  },
  {
    id: "militar-oficial",
    book: "militares",
    name: "Oficial (Comandante Clone)",
    category: "Militar",
    faction: "República",
    level: 28,
    threat: "Elite",
    role: "Comandante",
    size: "Médio",
    type: "Humanoide",
    planet: "Kamino (origem)",
    environment: "Comando de campo",
    intelligence: "Alta",
    disposition: "Leal",
    pv: 168,
    pe: 60,
    defense: 27,
    initiative: 9,
    speed: "9m",
    attrs: { agi: 6, int: 5, forc: 4, vig: 6, pre: 6, sen: 0 },
    skills: "Liderança (Mestre), Armas de Energia (Veterano), Pilotagem Atmosférica (Treinado), Conhecimento Galáctico (Treinado)",
    attacks: [
      { name: "Blaster de Comando Duplo", range: "30m", hit: "AGI+20", damage: "7d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "—" },
    ],
    powers: [
      { name: "Ordem Tática", text: "descrição: reorganiza o campo de batalha em tempo real — regra: até 4 clones aliados na cena ganham +5 em Acerto ou Defesa (escolha do Oficial) na próxima rodada — recarga: 2 rodadas — duração: 1 rodada — interações: pode ser combinado com Esquadrão de 4 do Clone Commando pra sinergia extrema." },
    ],
    passives: [
      { name: "Comando Reconhecido", effect: "clones aliados nunca fogem enquanto o Oficial estiver vivo e visível." },
    ],
    ai: "Fica atrás da linha de frente coordenando, só entrando em combate direto se a situação exigir ou se um alvo de alto valor aparecer. Usa Ordem Tática constantemente — a força real dele está em multiplicar a eficácia do esquadrão, não no dano pessoal.",
    loot: "Blaster de comando, mapas táticos, holoprojetor de campo.",
    lore: "Clones promovidos (por mérito, não hierarquia genética) a posições de comando — capitães, comandantes e majors que lideram companhias inteiras através de guerras longas.",
  },
  {
    id: "militar-general",
    book: "militares",
    name: "General (Comando Supremo de Campanha)",
    category: "Militar",
    faction: "República",
    level: 40,
    threat: "Elite",
    role: "Comandante/Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Coruscant (comando)",
    environment: "Frente de guerra",
    intelligence: "Sobre-humana",
    disposition: "Leal",
    pv: 260,
    pe: 90,
    defense: 30,
    initiative: 11,
    speed: "9m",
    attrs: { agi: 8, int: 7, forc: 6, vig: 8, pre: 9, sen: 0 },
    skills: "Liderança (Mestre), Conhecimento Galáctico (Mestre), Armas de Energia (Veterano), Diplomacia (Treinado)",
    attacks: [
      { name: "Blaster de Oficial Superior", range: "30m", hit: "AGI+18", damage: "10d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "—" },
    ],
    powers: [
      { name: "Manobra Decisiva", text: "descrição: reposiciona toda uma força em campo — regra: reorganiza até 8 NPCs militares aliados no mapa de batalha instantaneamente (movimento tático livre) — recarga: 1x por combate — duração: instantâneo — interações: pode virar o rumo de um combate de escala de batalha inteira." },
    ],
    passives: [
      { name: "Estrategista de Guerra", effect: "nunca é surpreendido em batalhas planejadas (só em emboscadas genuínas). Toda tropa sob seu comando na campanha ganha bônus narrativo de moral mesmo fora de cena." },
    ],
    ai: "Raramente luta pessoalmente — comanda de um posto avançado ou centro de operações, entrando em combate direto só se a linha de comando for ameaçada diretamente. Quando luta, é competente mas não excepcional em dano pessoal — o valor dele é estratégico, não marcial.",
    loot: "Registros de campanha (ganchos de história), equipamento de comando de altíssima qualidade.",
    lore: "Comando supremo de uma campanha militar inteira — em muitos casos um General Jedi (ver Livro 2 pra versão sensível à Força), mas também oficiais de carreira da própria República que provaram valor ao longo de décadas de serviço.",
  },

  // ─── 2. Separatistas ──────────────────────────────────────────────────
  {
    id: "militar-droide-b1",
    book: "militares",
    name: "Droide de Batalha B1",
    category: "Militar",
    faction: "Confederação de Sistemas Independentes",
    level: 3,
    threat: "Muito Fraco",
    role: "Enxame",
    size: "Médio",
    type: "Droide",
    planet: "Geonosis (fabricação)",
    environment: "Frente de batalha",
    intelligence: "Baixa",
    disposition: "Leal (programação)",
    pv: 10,
    pe: 4,
    defense: 15,
    initiative: 1,
    speed: "9m",
    attrs: { agi: 0, int: 0, forc: 0, vig: 0, pre: -2, sen: 0 },
    skills: "Armas de Energia (Iniciante)",
    attacks: [
      { name: "Rifle E-5", range: "25m", hit: "AGI+5", damage: "1d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "Notoriamente impreciso — o Mestre pode narrar erros cômicos sem penalidade extra." },
    ],
    powers: [],
    passives: [
      { name: "Produção em Massa", effect: "sem PV de reserva; sempre vem em grupos de 6+. Desligado (0 PV) permanentemente — sem chance de \"acordar\" de novo sem reparo ativo." },
    ],
    ai: "Segue ordens de um Droide Tático ou comandante geonosiano sem nenhuma iniciativa própria — se desconectado do comando central, trava ou repete a última ordem indefinidamente (ótimo gancho cômico/tático pros PJs explorarem).",
    loot: "Peças de droide (sucata), rifle E-5.",
    lore: "A força numérica do Exército Droide Separatista — baratos, descartáveis e infinitamente substituíveis. Individualmente patéticos; em milhares, uma ameaça de escala planetária real.",
  },
  {
    id: "militar-droide-b2",
    book: "militares",
    name: "Super Droide de Batalha B2",
    category: "Militar",
    faction: "Confederação de Sistemas Independentes",
    level: 12,
    threat: "Médio",
    role: "Tanque/Dano",
    size: "Grande",
    type: "Droide",
    planet: "Geonosis (fabricação)",
    environment: "Frente de batalha",
    intelligence: "Baixa",
    disposition: "Leal (programação)",
    pv: 60,
    pe: 20,
    defense: 19,
    initiative: 2,
    speed: "9m",
    attrs: { agi: 1, int: 0, forc: 5, vig: 5, pre: -1, sen: 0 },
    skills: "Armas de Energia (Treinado)",
    attacks: [
      { name: "Canhão de Braço Integrado", range: "25m", hit: "AGI+11", damage: "3d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "Não pode ser desarmado — o canhão é parte do próprio braço." },
      { name: "Lançador de Foguetes (variante)", range: "20m (área 4m)", hit: "AGI+11", damage: "3d6", damageType: "Explosivo", cost: "2 PE", cooldown: "3 rodadas", effect: "Substitui o Canhão em algumas unidades — nunca ambos no mesmo droide." },
    ],
    powers: [],
    passives: [
      { name: "Blindagem Pesada", effect: "reduz todo dano recebido em 4." },
    ],
    ai: "Muito mais confiável em combate que o B1 — avança em linha reta sob fogo, prioriza alvos que representam maior ameaça blindada/tática. Não recua nunca por conta própria.",
    loot: "Canhão de braço (recuperável como arma pesada), blindagem (sucata de alto valor).",
    lore: "Versão muito mais robusta e confiável do B1, usada como linha de frente pesada em vez de simples número. A presença de fileiras de B2 costuma sinalizar um ataque separatista sério, não uma escaramuça menor.",
  },
  {
    id: "militar-droideka",
    book: "militares",
    name: "Droideka (Destroyer Droid)",
    category: "Militar",
    faction: "Confederação de Sistemas Independentes",
    level: 20,
    threat: "Forte",
    role: "Artilheiro à Distância/Tanque",
    size: "Médio",
    type: "Droide",
    planet: "Colla IV (fabricação)",
    environment: "Frente de batalha",
    intelligence: "Média",
    disposition: "Leal (programação)",
    pv: 90,
    pe: 30,
    defense: 23,
    initiative: 7,
    speed: "12m (rolando) / 6m (bípede desdobrado)",
    attrs: { agi: 4, int: 2, forc: 2, vig: 4, pre: -1, sen: 0 },
    skills: "Armas de Energia (Expert), Percepção (Treinado)",
    attacks: [
      { name: "Blasters Duplos Automáticos", range: "25m", hit: "AGI+18", damage: "5d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "Dispara duas vezes por ataque — cada disparo rola separadamente." },
    ],
    powers: [],
    passives: [
      { name: "Escudo Deflector Pessoal", effect: "imune a dano de blaster/energia enquanto o escudo estiver ativo (some após sofrer 20+ de dano físico/explosivo acumulado numa única rodada, ou automaticamente ao se desdobrar pra rolar)." },
      { name: "Modo de Transporte", effect: "pode rolar (deslocamento 12m) mas o escudo desativa nesse modo." },
    ],
    ai: "Desdobra o escudo assim que percebe combate (1 rodada de setup) e então mantém posição, disparando continuamente. Rola em modo transporte só pra reposicionar entre coberturas, nunca durante troca de tiros ativa — droidekas confiam total no escudo, raramente recuam.",
    loot: "Blasters duplos (recuperáveis), gerador de escudo (item tecnológico raro e valioso).",
    lore: "Um dos droides de combate mais temidos do arsenal separatista — o escudo deflector torna ataques de blaster convencionais praticamente inúteis, forçando adversários a usar explosivos, ataques físicos diretos ou desligar o escudo por outros meios (EMP, corte de energia).",
  },
  {
    id: "militar-magnaguard",
    book: "militares",
    name: "Magnaguard (IG-100)",
    category: "Militar",
    faction: "Confederação de Sistemas Independentes",
    level: 28,
    threat: "Elite",
    role: "Tanque/Dano",
    size: "Médio",
    type: "Droide",
    planet: "Fabricação Geonosiana/Techno Union",
    environment: "Guarda pessoal de altos comandantes",
    intelligence: "Alta",
    disposition: "Leal (programação de elite)",
    pv: 176,
    pe: 46,
    defense: 27,
    initiative: 10,
    speed: "9m",
    attrs: { agi: 7, int: 4, forc: 6, vig: 6, pre: 0, sen: 0 },
    skills: "Armas de Energia (Veterano), Atletismo (Expert), Percepção (Treinado)",
    attacks: [
      { name: "Bastão Eletrostaff (dupla ponta)", range: "Corpo a corpo (alcance 3m)", hit: "AGI+21", damage: "7d6", damageType: "Físico/Energia", cost: "—", cooldown: "—", effect: "Pode bloquear ataques de sabre de luz — trate como Defesa +5 contra ataques de Sabre de Luz especificamente." },
    ],
    powers: [],
    passives: [
      { name: "Reflexos de Combate Superiores", effect: "resistente a golpes que derrubariam humanoides; imune à condição Derrubado. Feito especificamente pra duelar usuários de sabre de luz." },
    ],
    ai: "Combatente extremamente competente em corpo a corpo, frequentemente em pares ou grupos de 4 protegendo um comandante de alto valor (General Grievous e equivalentes). Foca exclusivamente ameaças diretas ao protegido, ignorando alvos secundários.",
    loot: "Eletrostaff (arma única, alto valor), componentes de droide de combate avançado.",
    lore: "Guarda-costas droide de elite, projetado especificamente pra neutralizar Jedi em combate corpo a corpo — o eletrostaff duplo é uma das poucas armas convencionais capazes de bloquear um sabre de luz de forma confiável.",
  },
  {
    id: "militar-droide-tatico",
    book: "militares",
    name: "Droide Tático (Comandante)",
    category: "Militar",
    faction: "Confederação de Sistemas Independentes",
    level: 22,
    threat: "Forte",
    role: "Comandante",
    size: "Médio",
    type: "Droide",
    planet: "Fabricação Separatista",
    environment: "Centro de comando/campo",
    intelligence: "Sobre-humana",
    disposition: "Leal (programação/lealdade calculada)",
    pv: 100,
    pe: 60,
    defense: 26,
    initiative: 8,
    speed: "6m (flutuante ou repulsor)",
    attrs: { agi: 3, int: 9, forc: 0, vig: 3, pre: 2, sen: 0 },
    skills: "Liderança (Mestre), Conhecimento Galáctico (Expert), Computação (Veterano)",
    attacks: [
      { name: "Pistola de Autodefesa", range: "15m", hit: "AGI+10", damage: "4d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "Fraco em combate direto — não é seu papel." },
    ],
    powers: [
      { name: "Cálculo Estratégico", text: "descrição: processa o campo de batalha inteiro instantaneamente — regra: até 6 droides B1/B2 aliados na cena ganham +5 em Acerto ou Defesa nesta rodada — recarga: 2 rodadas — duração: 1 rodada — interações: só funciona em droides, não em tropas orgânicas aliadas." },
    ],
    passives: [
      { name: "Processamento Superior", effect: "nunca é enganado por táticas repetidas (aprende com cada rodada de combate; a mesma finta não funciona duas vezes)." },
    ],
    ai: "Fica longe da linha de frente, coordenando via Cálculo Estratégico. É covarde por design (autopreservação lógica) — foge/desliga-se de forma segura se a batalha estiver claramente perdida, sem \"orgulho\" que o impeça.",
    loot: "Núcleo de processamento (item tecnológico valioso), dados de estratégia (ganchos de campanha).",
    lore: "Droides com IA muito mais sofisticada que a tropa comum, responsáveis por planejar operações separatistas inteiras — frequentemente desdenhosos com a \"ineficiência orgânica\", mas racionalmente cientes de sua própria vulnerabilidade física.",
  },

  // ─── 3. Império ───────────────────────────────────────────────────────
  {
    id: "militar-stormtrooper",
    book: "militares",
    name: "Stormtrooper",
    category: "Militar",
    faction: "Império Galáctico",
    level: 10,
    threat: "Médio",
    role: "Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Variável (treino em Academias Imperiais)",
    environment: "Qualquer",
    intelligence: "Média",
    disposition: "Leal",
    pv: 44,
    pe: 14,
    defense: 19,
    initiative: 5,
    speed: "9m",
    attrs: { agi: 3, int: 1, forc: 2, vig: 3, pre: 0, sen: 0 },
    skills: "Armas de Energia (Treinado), Liderança (Iniciante)",
    attacks: [
      { name: "Rifle E-11", range: "30m", hit: "AGI+13", damage: "2d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "—" },
    ],
    powers: [],
    passives: [
      { name: "Armadura Padrão Imperial", effect: "reduz dano físico recebido em 2." },
    ],
    ai: "Segue protocolo rígido, mas menos individualmente competente que um clone (recrutamento em massa, treino mais raso). Costuma avançar em formação previsível — grupos organizados de PJs conseguem explorar isso taticamente.",
    loot: "Rifle E-11, armadura stormtrooper (peças).",
    lore: "A força de ocupação padrão do Império Galáctico — número e uniformidade importam mais que excelência individual, uma escolha deliberada da doutrina imperial pós-clones.",
  },
  {
    id: "militar-scout-trooper",
    book: "militares",
    name: "Scout Trooper",
    category: "Militar",
    faction: "Império Galáctico",
    level: 14,
    threat: "Médio",
    role: "Furtivo/Artilheiro à Distância",
    size: "Médio",
    type: "Humanoide",
    planet: "Endor e outros ambientes de reconhecimento",
    environment: "Florestas/terrenos abertos",
    intelligence: "Média",
    disposition: "Leal",
    pv: 62,
    pe: 22,
    defense: 21,
    initiative: 9,
    speed: "9m (speeder bike 90m)",
    attrs: { agi: 6, int: 1, forc: 2, vig: 3, pre: 0, sen: 0 },
    skills: "Pilotagem Atmosférica (Expert), Furtividade (Treinado), Percepção (Treinado), Armas de Energia (Treinado)",
    attacks: [
      { name: "Blaster Leve", range: "25m", hit: "AGI+16", damage: "3d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "—" },
      { name: "Investida de Speeder Bike", range: "Corpo a corpo (requer speeder bike)", hit: "AGI+16", damage: "3d6", damageType: "Físico", cost: "—", cooldown: "2 rodadas", effect: "Alta velocidade — se acertar, alvo é derrubado; se errar, o piloto arrisca perder o controle (a critério do Mestre em terreno difícil)." },
    ],
    powers: [],
    passives: [
      { name: "Armadura Leve", effect: "sem redução de dano, mas +3 de Defesa extra (agilidade sobre proteção)." },
    ],
    ai: "Prioriza mobilidade e reconhecimento sobre combate direto prolongado — ataca de surpresa (Furtividade), reporta posição do inimigo por rádio, e usa velocidade pra hit-and-run em vez de troca de tiros parada.",
    loot: "Blaster leve, speeder bike (se recuperável), equipamento de comunicação.",
    lore: "Tropa de reconhecimento rápido do Império, equipada com armadura leve e speeder bikes velozes — os \"olhos\" avançados de qualquer operação imperial em terreno hostil.",
  },
  {
    id: "militar-death-trooper",
    book: "militares",
    name: "Death Trooper",
    category: "Militar",
    faction: "Império Galáctico (Inteligência Imperial)",
    level: 26,
    threat: "Forte",
    role: "Dano/Furtivo",
    size: "Médio",
    type: "Humanoide",
    planet: "Classificado (treino de elite)",
    environment: "Operações secretas de alto risco",
    intelligence: "Alta",
    disposition: "Fanática",
    pv: 138,
    pe: 44,
    defense: 26,
    initiative: 10,
    speed: "9m",
    attrs: { agi: 7, int: 3, forc: 5, vig: 6, pre: 1, sen: 0 },
    skills: "Armas de Energia (Veterano), Furtividade (Expert), Intimidação (Treinado)",
    attacks: [
      { name: "Rifle E-11D Modificado", range: "35m", hit: "AGI+22", damage: "5d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "Modo automático: pode gastar 1 PE pra atacar 2 vezes na mesma ação." },
      { name: "Faca de Combate Silenciosa", range: "Corpo a corpo", hit: "AGI+22", damage: "5d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Contra alvo Surpreendido, acerto automático." },
    ],
    powers: [],
    passives: [
      { name: "Armadura Negra Selada", effect: "imune a gases/venenos e a dano de vácuo. Reduz dano recebido em 5." },
    ],
    ai: "Opera em silêncio absoluto sempre que possível — elimina sentinelas antes de qualquer alarme, prioriza alvos de alto valor (oficiais, informantes) com execuções rápidas. Só engaja combate aberto como último recurso, quando a missão de infiltração já falhou.",
    loot: "Rifle E-11D modificado, faca de combate, dados classificados (ganchos de campanha).",
    lore: "Unidade de elite ultrassecreta da Inteligência Imperial, associada a missões que oficialmente \"nunca aconteceram\". Sua simples presença numa cena sinaliza que algo grande e perigoso está em jogo.",
  },
  {
    id: "militar-purge-trooper",
    book: "militares",
    name: "Purge Trooper",
    category: "Militar",
    faction: "Império Galáctico (Inquisitorius)",
    level: 32,
    threat: "Elite",
    role: "Caçador de Jedi/Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Classificado",
    environment: "Operações anti-Jedi",
    intelligence: "Alta",
    disposition: "Fanática",
    pv: 196,
    pe: 60,
    defense: 27,
    initiative: 11,
    speed: "9m",
    attrs: { agi: 8, int: 4, forc: 6, vig: 7, pre: 2, sen: 0 },
    skills: "Armas de Energia (Veterano), Investigação (Treinado), Percepção (Expert), Intimidação (Treinado)",
    attacks: [
      { name: "Bastão Eletrificado com Ponta de Lâmina", range: "Corpo a corpo", hit: "AGI+24", damage: "8d6", damageType: "Físico/Energia", cost: "—", cooldown: "—", effect: "Especificamente projetado pra bloquear sabres de luz — Defesa +5 contra ataques de Sabre de Luz." },
      { name: "Rifle Bláster Modificado", range: "30m", hit: "AGI+24", damage: "8d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "Contém munição especial capaz de perfurar deflexão de sabre em alcance curto (≤6m: ignora o bônus de Defesa de Reflexo de Sabre do Livro 2)." },
    ],
    powers: [],
    passives: [
      { name: "Treinado Contra a Ordem", effect: "vantagem em Acerto contra qualquer usuário de sabre de luz. Imune a técnicas de manipulação mental leve (Sussurro Sombrio e similares)." },
    ],
    ai: "Caça em esquadrões especializados, coordenando pra cercar e isolar especificamente Jedi remanescentes ou outros sensíveis à Força — trata alvos não-Force como baixa prioridade a menos que interfiram diretamente na missão.",
    loot: "Bastão eletrificado, rifle modificado, armadura de combate pesada com blindagem anti-energia.",
    lore: "Sucessores táticos dos clones caçadores de Jedi, criados após o Expurgo pra continuar erradicando qualquer remanescente da Ordem que tenha sobrevivido — combatentes profissionais, não fanáticos descontrolados, o que os torna ainda mais perigosos.",
  },
  {
    id: "militar-guarda-imperial",
    book: "militares",
    name: "Guarda Imperial (Guarda Real)",
    category: "Militar",
    faction: "Império Galáctico (Guarda Pessoal do Imperador)",
    level: 45,
    threat: "Chefe",
    role: "Tanque/Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Coruscant (Palácio Imperial)",
    environment: "Presença do Imperador",
    intelligence: "Alta",
    disposition: "Fanática",
    pv: 600,
    pe: 90,
    defense: 30,
    initiative: 12,
    speed: "9m",
    attrs: { agi: 10, int: 4, forc: 9, vig: 9, pre: 3, sen: 0 },
    skills: "Armas de Energia (Mestre — a Lança da Força), Atletismo (Veterano), Intimidação (Veterano)",
    attacks: [
      { name: "Lança da Força (Force Pike)", range: "Corpo a corpo (alcance 3m)", hit: "AGI+30", damage: "10d6", damageType: "Físico/Energia", cost: "—", cooldown: "—", effect: "Pode ser usada como arma de choque (não-letal, VIG DT 30 ou Atordoado) ou letal — escolha do usuário a cada golpe." },
    ],
    powers: [
      { name: "Juramento Final (Fase 2)", text: "descrição: destravado abaixo de 50% PV (PV 600, Segunda Fase concede +1 ação) — regra: pelo resto do combate, todo ataque contra o Guarda Imperial sofre −5 (ele se torna quase impossível de acertar, defendendo o Imperador até o fim) — recarga: 1x por combate — duração: resto do combate — interações: não pode ser dissipado por meios convencionais." },
    ],
    passives: [
      { name: "Escolhido a Dedo", effect: "imune a Intimidação e manipulação social. Reduz todo dano recebido em 8." },
    ],
    ai: "Nunca abandona o posto — mesmo com ordem de recuo, um Guarda Imperial só se move se isso servir diretamente à proteção do Imperador (ou figura equivalente que protege). Luta até a morte sem exceção, sempre posicionado entre a ameaça e quem protege.",
    loot: "Lança da Força (item de altíssimo prestígio), armadura vermelha cerimonial/de combate.",
    lore: "A guarda pessoal mais confiável do Imperador — cada membro é selecionado após anos de avaliação de lealdade absoluta. Vê-los fora do Palácio Imperial normalmente significa que o próprio Imperador (ou um substituto de altíssimo valor) está por perto.",
  },

  // ─── 4. Outras Facções ────────────────────────────────────────────────
  {
    id: "militar-soldado-rebelde",
    book: "militares",
    name: "Soldado da Aliança Rebelde",
    category: "Militar",
    faction: "Aliança Rebelde",
    level: 8,
    threat: "Fraco",
    role: "Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Variável (bases dispersas)",
    environment: "Qualquer",
    intelligence: "Alta",
    disposition: "Leal (à causa)",
    pv: 34,
    pe: 16,
    defense: 18,
    initiative: 5,
    speed: "9m",
    attrs: { agi: 3, int: 2, forc: 1, vig: 2, pre: 2, sen: 0 },
    skills: "Armas de Energia (Treinado), Sobrevivência (Treinado), Mecânica (Iniciante)",
    attacks: [
      { name: "Rifle Blaster A280", range: "30m", hit: "AGI+13", damage: "2d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "—" },
      { name: "Granada Improvisada", range: "12m (área 3m)", hit: "AGI+13", damage: "2d6", damageType: "Explosivo", cost: "2 PE", cooldown: "3 rodadas", effect: "Fabricação de campo — 20% de chance (a critério do Mestre) de não detonar corretamente." },
    ],
    powers: [],
    passives: [
      { name: "Luta pela Causa", effect: "vantagem em testes de moral quando em franca desvantagem numérica (nunca é o primeiro a fugir de uma causa que acredita)." },
    ],
    ai: "Menos disciplinado que tropas imperiais, mas extremamente motivado — usa terreno e improviso em vez de doutrina rígida. Prioriza objetivos da missão (sabotagem, extração) sobre eliminar inimigos quando possível.",
    loot: "Rifle A280, suprimentos de campo, informações de inteligência rebelde (ganchos de campanha).",
    lore: "Voluntários de incontáveis mundos unidos contra o Império — de ex-militares republicanos a civis que pegaram em armas pela primeira vez. Motivação é a maior força da Aliança; recursos, quase sempre a maior fraqueza.",
  },
  {
    id: "militar-trooper-nova-ordem",
    book: "militares",
    name: "Trooper de Nova Ordem",
    category: "Militar",
    faction: "Facção Sucessora Militarista (pós-Império)",
    level: 15,
    threat: "Médio",
    role: "Dano",
    size: "Médio",
    type: "Humanoide",
    planet: "Base secreta nas Regiões Desconhecidas",
    environment: "Qualquer",
    intelligence: "Alta",
    disposition: "Fanática",
    pv: 66,
    pe: 26,
    defense: 21,
    initiative: 7,
    speed: "9m",
    attrs: { agi: 4, int: 2, forc: 3, vig: 4, pre: 1, sen: 0 },
    skills: "Armas de Energia (Expert), Intimidação (Treinado), Liderança (Iniciante)",
    attacks: [
      { name: "Rifle Blaster de Nova Geração", range: "35m", hit: "AGI+16", damage: "3d6", damageType: "Energia", cost: "—", cooldown: "—", effect: "Tecnologia superior ao E-11 padrão — +1 dado extra de dano em relação a um Stormtrooper equivalente." },
    ],
    powers: [],
    passives: [
      { name: "Doutrinação Desde o Nascimento", effect: "imune à condição Amedrontado e a qualquer tentativa de persuasão pra desertar (criados sem outra referência de mundo desde crianças)." },
    ],
    ai: "Mais competente e motivado individualmente que um stormtrooper padrão — treinado desde cedo especificamente para combate, sem o problema de moral baixa por recrutamento forçado. Segue doutrina agressiva de avanço constante.",
    loot: "Rifle de nova geração, equipamento com tecnologia avançada recuperada de fontes imperiais antigas.",
    lore: "Produto de programas de doutrinação militar de facções que herdaram (ideológica ou literalmente) restos do aparato militar imperial nas décadas seguintes à queda do Império — mais fanáticos e, individualmente, mais competentes que a tropa imperial original.",
  },
];
