// Star Wars: Além da Fronteira — Bestiário Oficial de Mestre, Livro 4: Sensitivos da Força (fora de Jedi/Sith)
// Transcrito de StarWars-Teste/13-bestiario-sensitivos.md

import type { StarWarsCreature } from "./types";

export const SENSITIVOS: StarWarsCreature[] = [
  {
    id: "sensitivos-cultista-da-forca",
    book: "sensitivos",
    name: "Cultista da Força",
    category: "Sensitivo",
    faction: "Culto Independente",
    level: 3,
    threat: "Fraco",
    role: "Enxame",
    size: "Médio",
    type: "Sensitivo",
    planet: "Variável",
    environment: "Templos improvisados/subterrâneos",
    intelligence: "Média",
    disposition: "Fanática",
    pv: 14,
    pe: 12,
    defense: 16,
    initiative: 2,
    speed: "9m",
    attrs: { agi: 1, int: 0, forc: 1, vig: 1, pre: 1, sen: 3 },
    skills: "Domínio da Força (Iniciante), Intimidação (Iniciante)",
    attacks: [
      { name: "Adaga Ritual", range: "Corpo a corpo", hit: "AGI+6", damage: "1d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "—" },
      { name: "Fé Cega", range: "6m", hit: "SEN+8", damage: "1d6", damageType: "Força", cost: "1 PE", cooldown: "2 rodadas", effect: "Dano fraco, mas o cultista ignora medo/dor ao usá-lo (nunca hesita)." },
    ],
    powers: [],
    passives: [
      { name: "Devoção Fanática", effect: "imune à condição Amedrontado enquanto ao menos 2 outros cultistas estiverem visíveis." },
    ],
    ai: "Ataca em grupo, sem tática real — confia cegamente na liderança de um sensitivo mais poderoso (frequentemente um Adepto ou pior, um Sith disfarçado usando o culto como fachada). Luta até a morte por convicção genuína, não por ordem.",
    loot: "Textos religiosos (às vezes com pistas reais sobre a Força), itens rituais baratos.",
    lore: "Seguidores de cultos que interpretam a Força de forma distorcida, místico-religiosa, sem qualquer treinamento formal Jedi ou Sith. Alguns cultos são inofensivos; outros escondem verdadeiros perigos por trás da fachada devota.",
  },
  {
    id: "sensitivos-adepto-da-forca",
    book: "sensitivos",
    name: "Adepto da Força",
    category: "Sensitivo",
    faction: "Independente",
    level: 5,
    threat: "Fraco",
    role: "Suporte/Controle",
    size: "Médio",
    type: "Sensitivo",
    planet: "Variável",
    environment: "Qualquer (autodidata itinerante)",
    intelligence: "Alta",
    disposition: "Oportunista",
    pv: 22,
    pe: 20,
    defense: 17,
    initiative: 4,
    speed: "9m",
    attrs: { agi: 2, int: 1, forc: 1, vig: 1, pre: 1, sen: 5 },
    skills: "Domínio da Força (Treinado), Percepção (Treinado), Sobrevivência (Iniciante)",
    attacks: [
      { name: "Cajado Improvisado", range: "Corpo a corpo", hit: "AGI+7", damage: "1d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "—" },
      { name: "Empurrão Instintivo", range: "6m", hit: "SEN+10", damage: "2d6", damageType: "Força", cost: "2 PE", cooldown: "2 rodadas", effect: "Técnica autodidata e imprecisa — metade de chance (a critério do Mestre) de também empurrar o próprio Adepto 1,5m pra trás." },
    ],
    powers: [],
    passives: [
      { name: "Autodidata", effect: "nunca teve professor formal; sofre −2 em qualquer teste de Domínio da Força feito sob supervisão/instrução de outro (não sabe seguir formação estruturada), mas ganha +2 quando age por conta própria." },
    ],
    ai: "Imprevisível — usa a Força de forma criativa e não-convencional (empurra objetos do ambiente, não só inimigos). Prioriza sobrevivência pessoal sobre glória ou ideologia; foge se a situação virar contra ele.",
    loot: "Anotações pessoais sobre a Força (conhecimento fragmentado, às vezes valioso), itens de sobrevivência.",
    lore: "Sensível à Força que nunca foi encontrado (ou escolheu não ser encontrado) por nenhuma Ordem. Aprende sozinho, por instinto e tentativa/erro — poderoso de forma bruta, mas sem refinamento técnico.",
  },
  {
    id: "sensitivos-bruxa-de-dathomir",
    book: "sensitivos",
    name: "Bruxa de Dathomir",
    category: "Sensitivo",
    faction: "Clã de Dathomir",
    level: 12,
    threat: "Médio",
    role: "Controle/Suporte",
    size: "Médio",
    type: "Sensitivo",
    planet: "Dathomir",
    environment: "Florestas sombrias",
    intelligence: "Alta",
    disposition: "Leal (ao clã)",
    pv: 48,
    pe: 46,
    defense: 19,
    initiative: 5,
    speed: "9m",
    attrs: { agi: 3, int: 2, forc: 2, vig: 3, pre: 4, sen: 7 },
    skills: "Domínio da Força (Expert), Medicina (Treinado), Intimidação (Treinado), Persuasão (Iniciante)",
    attacks: [
      { name: "Bastão Ritual", range: "Corpo a corpo", hit: "AGI+13", damage: "2d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "—" },
      { name: "Magia da Bruxa", range: "9m", hit: "SEN+17", damage: "3d6", damageType: "Força/Sombrio", cost: "3 PE", cooldown: "2 rodadas", effect: "Efeito ritualístico: fogo verde característico; alvo faz teste de VIG DT 19 ou fica Amedrontado 1 rodada." },
    ],
    powers: [
      { name: "Ritual de Cura Ancestral", text: "descrição: canaliza a magia coletiva do clã — regra: restaura 4d6 PV a um aliado tocado, mas exige 1 rodada de canalização sem se mover — recarga: 3 rodadas — duração: instantâneo — interações: só funciona plenamente com 2+ Bruxas participando (sozinha, cura metade)." },
    ],
    passives: [
      { name: "Magia do Sangue", effect: "imune a doenças e venenos naturais de Dathomir. Reconhece automaticamente qualquer outro sensitivo à Força que entre no território do clã." },
    ],
    ai: "Luta em conjunto com outras Bruxas do clã, coordenando rituais. Prioriza proteger a Matriarca (se presente) acima de tudo, inclusive da própria vida. Contra forasteiros, prefere intimidar e expulsar a matar — mas escala rápido se o território for realmente ameaçado.",
    loot: "Componentes rituais (ervas de Dathomir, sangue de rancor), bastão pessoal.",
    lore: "Praticante da tradição ancestral e feminina de magia da Força de Dathomir, distinta de Jedi e Sith — uma terceira via que mistura ritual, natureza e vontade coletiva do clã.",
  },
  {
    id: "sensitivos-irma-da-noite",
    book: "sensitivos",
    name: "Irmã da Noite",
    category: "Sensitivo",
    faction: "Clã de Dathomir (Irmãs da Noite)",
    level: 22,
    threat: "Forte",
    role: "Dano/Controle",
    size: "Médio",
    type: "Sensitivo",
    planet: "Dathomir",
    environment: "Florestas sombrias",
    intelligence: "Alta",
    disposition: "Fanática (ao clã)",
    pv: 100,
    pe: 66,
    defense: 26,
    initiative: 8,
    speed: "9m",
    attrs: { agi: 6, int: 2, forc: 4, vig: 4, pre: 5, sen: 10 },
    skills: "Domínio da Força (Veterano), Intimidação (Expert), Sobrevivência (Treinado), Armas de Energia (Treinado)",
    attacks: [
      // Tabela original omite a coluna "Recarga" pra estas duas entradas — cooldown mantido "—".
      { name: "Lança Ritual", range: "Corpo a corpo/15m (arremesso)", hit: "AGI+21", damage: "5d6", damageType: "Perfurante", cost: "—", cooldown: "—", effect: "—" },
      { name: "Magia Sombria em Chamas", range: "Área 6m", hit: "SEN+25", damage: "5d6", damageType: "Força/Fogo", cost: "4 PE", cooldown: "—", effect: "Fogo verde característico das Irmãs da Noite; queima por 1d6 adicional na rodada seguinte." },
    ],
    powers: [
      { name: "Marionete de Sangue", text: "descrição: técnica das Irmãs da Noite pra controlar corpos à distância — regra: teste oposto de Domínio da Força contra um alvo Fraco ou Muito Fraco; sucesso força o alvo a realizar uma ação simples no turno dele — recarga: 1x por combate — duração: 1 turno do alvo — interações: não funciona contra alvos com PE atual acima de 30." },
    ],
    passives: [
      { name: "Guerreira-Feiticeira", effect: "combina combate físico e magia sem penalidade; pode usar um Poder e um Ataque na mesma rodada (a maioria das criaturas escolhe um ou outro)." },
    ],
    ai: "Combatente completa — abre com Magia Sombria em Chamas contra grupos agrupados, depois engaja em combate corpo a corpo com Lança Ritual contra quem sobrar. Usa Marionete de Sangue contra o membro mais fraco do grupo adversário pra criar caos interno.",
    loot: "Lança ritual (arma única, valiosa por manufatura), componentes alquímicos de Dathomir.",
    lore: "A ala militar do clã — guerreiras e feiticeiras treinadas desde jovens em combate e magia simultaneamente, servindo como protetoras e força de ataque do clã sob a Matriarca.",
  },
  {
    id: "sensitivos-matriarca-ancestral",
    book: "sensitivos",
    name: "Matriarca Ancestral (Mãe de Clã)",
    category: "Sensitivo",
    faction: "Clã de Dathomir",
    level: 60,
    threat: "Chefe Lendário",
    role: "Controle/Suporte",
    size: "Médio",
    type: "Sensitivo",
    planet: "Dathomir",
    environment: "Vila ancestral",
    intelligence: "Sobre-humana",
    disposition: "Fanática (protege o clã)",
    pv: 940,
    pe: 220,
    defense: 32,
    initiative: 14,
    speed: "9m",
    attrs: { agi: 10, int: 5, forc: 8, vig: 10, pre: 14, sen: 20 },
    skills: "Domínio da Força (Mestre), Intimidação (Mestre), Liderança (Mestre), Medicina (Veterano)",
    attacks: [
      { name: "Cajado Ancestral", range: "Corpo a corpo", hit: "AGI+30", damage: "12d6", damageType: "Força/Físico", cost: "—", cooldown: "—", effect: "Golpe físico infundido de magia; ignora metade da Defesa por resistência mágica." },
      { name: "Grito da Bruxa", range: "Área 20m", hit: "SEN+34", damage: "8d6", damageType: "Força/Sombrio", cost: "5 PE", cooldown: "3 rodadas", effect: "Todos na área testam PRE DT 32; falha = Amedrontado 2 rodadas (aliados do clã são imunes automaticamente)." },
    ],
    powers: [
      { name: "Chamado das Irmãs (Fase 2)", text: "descrição: destravado abaixo de 50% PV — regra: convoca 1d4 Irmãs da Noite (estatuídas à parte) pra se juntarem ao combate imediatamente — recarga: 1x por combate — duração: até o fim do combate — interações: as convocadas agem no mesmo turno em que aparecem." },
    ],
    passives: [
      { name: "Voz da Tradição", effect: "todo membro do clã na cena (Bruxa ou Irmã da Noite) ganha +5 em Defesa enquanto a Matriarca estiver viva e visível." },
    ],
    ai: "Comanda o clã com autoridade absoluta — raramente entra em combate direto até que a defesa convencional falhe. Quando luta, é devastadora: prioriza proteger o clã acima da própria vida, mas não hesita em usar magia de área mesmo com risco a aliados menores (confia na resiliência deles).",
    loot: "Cajado ancestral (item lendário de clã), grimório de magia de Dathomir (conhecimento raríssimo).",
    lore: "Líder espiritual e política de um clã de Dathomir — figura quase mítica mesmo em vida, guardiã de tradições que remontam a milênios antes da fundação da Ordem Jedi ou Sith. Perder uma Matriarca é catástrofe existencial pro clã inteiro.",
  },
  {
    id: "sensitivos-monge-da-mao-aberta",
    book: "sensitivos",
    name: "Monge da Mão Aberta",
    category: "Sensitivo",
    faction: "Ordem Pacifista",
    level: 10,
    threat: "Médio",
    role: "Suporte/Controle",
    size: "Médio",
    type: "Sensitivo",
    planet: "Variável (comunidades isoladas)",
    environment: "Templos/mosteiros",
    intelligence: "Alta",
    disposition: "Protetora",
    pv: 40,
    pe: 30,
    defense: 19,
    initiative: 5,
    speed: "9m",
    attrs: { agi: 4, int: 2, forc: 2, vig: 3, pre: 3, sen: 6 },
    skills: "Domínio da Força (Treinado), Medicina (Treinado), Acrobacia (Treinado), Percepção (Treinado)",
    attacks: [
      { name: "Golpe de Palma (não-letal)", range: "Corpo a corpo", hit: "AGI+14", damage: "2d6 (não-letal)", damageType: "Físico", cost: "—", cooldown: "—", effect: "Nunca reduz um alvo abaixo de 1 PV." },
      { name: "Equilíbrio Compartilhado", range: "6m", hit: "SEN+16", damage: "—", damageType: "Força/Suporte", cost: "2 PE", cooldown: "2 rodadas", effect: "Remove uma condição negativa de um aliado, ou impõe Lento a um inimigo — nunca ambos na mesma ação." },
    ],
    powers: [],
    passives: [
      { name: "Não-Violência Radical", effect: "se este monge causar dano letal deliberadamente, perde acesso a todos os Poderes desta ficha até o fim da sessão (recupera fé/equilíbrio narrativamente)." },
    ],
    ai: "Evita conflito ativamente — se atacado, neutraliza sem matar (Golpe de Palma) e busca desescalar verbalmente entre ações. Excelente NPC de suporte/mediador em campanhas — raramente um oponente de combate direto.",
    loot: "Vestes tradicionais, textos filosóficos sobre a Força \"que flui através de tudo\".",
    lore: "Praticante de uma filosofia que acredita que a Força pertence a todos os seres vivos, não a uma Ordem — rejeita tanto a estrutura Jedi quanto a agressão Sith. Frequentemente perseguido por ambos os lados por recusar escolher.",
  },
  {
    id: "sensitivos-guardiao-dos-whills",
    book: "sensitivos",
    name: "Guardião dos Whills",
    category: "Sensitivo",
    faction: "Ordem dos Whills",
    level: 16,
    threat: "Forte",
    role: "Tanque/Dano",
    size: "Médio",
    type: "Sensitivo",
    planet: "Jedha",
    environment: "Cidade Sagrada",
    intelligence: "Alta",
    disposition: "Protetora",
    pv: 92,
    pe: 38,
    defense: 22,
    initiative: 7,
    speed: "9m",
    attrs: { agi: 6, int: 2, forc: 4, vig: 5, pre: 3, sen: 6 },
    skills: "Armas de Energia (Veterano — bastão de combate tradicional), Percepção (Mestre — inclui cegos que \"veem\" pela Força), Pontaria (Treinado)",
    attacks: [
      { name: "Bastão de Combate (fé guiada)", range: "Corpo a corpo", hit: "AGI+22", damage: "4d6", damageType: "Físico", cost: "—", cooldown: "—", effect: "Não usa sabre de luz — dano segue a escala normal de nível, não a regra de sabre." },
      { name: "Rajada de Blaster Guiada pela Força", range: "20m", hit: "SEN+22", damage: "4d6", damageType: "Energia", cost: "3 PE", cooldown: "2 rodadas", effect: "Mesmo sem visão, acerta com precisão sobrenatural — ignora penalidades de escuridão/cegueira." },
    ],
    powers: [],
    passives: [
      { name: "\"Eu Sou Um Com a Força\"", effect: "imune a qualquer efeito que dependa de visão (cegueira, escuridão total, camuflagem visual). Percepção nunca é reduzida por falta de luz." },
    ],
    ai: "Sereno e confiante mesmo cercado — combina combate corpo a corpo e à distância fluidamente, guiado pela Força em vez de pelos olhos. Protege peregrinos e o Templo Kyber de Jedha acima de qualquer outra prioridade tática.",
    loot: "Bastão de combate tradicional, blaster modificado, relíquias da Cidade Sagrada.",
    lore: "Monge-guerreiro devoto à Força sem treinamento formal Jedi, protetor histórico dos templos e peregrinos de Jedha. Muitos são fisicamente cegos, mas \"veem\" através da Força com clareza sobrenatural.",
  },
  {
    id: "sensitivos-sabio-de-ordem-antiga",
    book: "sensitivos",
    name: "Sábio de Ordem Antiga",
    category: "Sensitivo",
    faction: "Ordem Mística Antiga (ex.: contemplativos itinerantes)",
    level: 25,
    threat: "Forte",
    role: "Suporte/Controle",
    size: "Médio",
    type: "Sensitivo",
    planet: "Variável (frequentemente isolado nas Regiões Desconhecidas)",
    environment: "Templos remotos/naves-santuário",
    intelligence: "Sobre-humana",
    disposition: "Calculista",
    pv: 118,
    pe: 84,
    defense: 26,
    initiative: 8,
    speed: "9m",
    attrs: { agi: 4, int: 5, forc: 2, vig: 4, pre: 5, sen: 12 },
    skills: "Domínio da Força (Mestre), Conhecimento da Força (Mestre), Astrogação (Treinado), Percepção (Expert)",
    attacks: [
      { name: "Toque de Equilíbrio", range: "Corpo a corpo", hit: "SEN+29", damage: "4d6", damageType: "Força", cost: "—", cooldown: "—", effect: "Dano puramente da Força, sem arma física." },
      { name: "Visão do Caminho", range: "30m ou toda a cena", hit: "SEN+29", damage: "—", damageType: "Força/Controle", cost: "4 PE", cooldown: "3 rodadas", effect: "Revela ao grupo (aliado ou usado contra um inimigo revelando os planos dele) um vislumbre de um futuro próximo provável — informação narrativa poderosa, não dano." },
    ],
    powers: [
      { name: "Contemplação Profunda", text: "descrição: entra em transe pra perceber padrões da Força imperceptíveis a outros — regra: por 1 cena inteira, sabe automaticamente se uma decisão importante do grupo \"ressoa\" bem ou mal na Força (ferramenta de guia narrativo do Mestre, não garantia de sucesso) — recarga: 1x por sessão — duração: 1 cena — interações: nunca revela informação mecânica exata, só impressão qualitativa." },
    ],
    passives: [
      { name: "Além do Binário Luz/Sombra", effect: "não pode ser classificado como Lado da Luz ou Lado Sombrio para efeitos de poderes que dependem dessa distinção (ex.: \"Farejar a Luz\" do Inquisidor Sith simplesmente não o detecta)." },
    ],
    ai: "Extremamente relutante em combate — vê violência como último recurso e sinal de desequilíbrio. Se forçado a lutar, usa Visão do Caminho pra guiar o grupo a uma solução que evite mais mortes, e Toque de Equilíbrio apenas pra neutralizar (nunca matar, quando há escolha).",
    loot: "Textos de sabedoria de ordens perdidas, mapas estelares de regiões desconhecidas, cristais de meditação.",
    lore: "Membro de uma das muitas ordens antigas espalhadas pelas Regiões Desconhecidas — tradições que existiam antes da Ordem Jedi centralizar o estudo da Força em Coruscant, e que sobreviveram justamente por nunca terem entrado no conflito Jedi-Sith.",
  },
];
