import type { StarWarsCreature, CreatureModule } from "./types";

export const SITH: StarWarsCreature[] = [
  {
    id: "sith-iniciado",
    book: "sith",
    name: "Iniciado",
    category: "Usuário da Força",
    faction: "Ordem Sith",
    level: 1,
    threat: "Muito Fraco",
    role: "Dano",
    size: "Médio",
    type: "Sensitivo",
    planet: "Korriban/Moraband (academia)",
    environment: "Academia Sith",
    intelligence: "Alta",
    disposition: "Agressiva",
    pv: 8,
    pe: 6,
    defense: 15,
    initiative: 2,
    speed: "9m",
    attrs: { agi: 1, int: 0, forc: 2, vig: 1, pre: 0, sen: 2 },
    skills: "Intimidação (Iniciante), Domínio da Força (Iniciante)",
    attacks: [
      {
        name: "Golpe Cru",
        range: "Corpo a corpo",
        hit: "FOR+7",
        damage: "1d6",
        damageType: "Físico",
        cost: "—",
        cooldown: "—",
        effect: "Sem técnica formal ainda — força bruta desajeitada.",
      },
    ],
    powers: [
      {
        name: "Faísca do Ódio",
        text: "descrição: primeira manifestação de raiva canalizada — regra: 1d4 de dano de energia, sem precisar de sabre — recarga: 3 rodadas — duração: instantâneo — interações: costuma ferir o próprio Iniciado se usado sem controle (a critério do Mestre, narrativamente).",
      },
    ],
    passives: [
      {
        name: "Ambição Crua",
        effect: "vantagem em testes de resistência contra medo (mas não contra dor — Iniciados sentem tudo).",
      },
    ],
    ai: "Ataca com agressividade descontrolada, sem noção tática real — prioriza o alvo mais próximo, ignora risco pessoal. Academia Sith trata a morte de Iniciados fracos como seleção natural, não tragédia.",
    loot: "Nada de valor — talvez um sabre de treino instável.",
    lore: "Candidatos brutos trazidos às academias Sith (Korriban, Malachor, Ziost) pra competir — literalmente — pela sobrevivência. Muitos morrem antes de sequer serem chamados de Acólito.",
  },
  {
    id: "sith-acolito",
    book: "sith",
    name: "Acólito",
    category: "Usuário da Força",
    faction: "Ordem Sith",
    level: 6,
    threat: "Fraco",
    role: "Dano",
    size: "Médio",
    type: "Sensitivo",
    planet: "Korriban/Moraband",
    environment: "Academia Sith",
    intelligence: "Alta",
    disposition: "Agressiva",
    pv: 24,
    pe: 16,
    defense: 17,
    initiative: 4,
    speed: "9m",
    attrs: { agi: 2, int: 0, forc: 4, vig: 2, pre: 1, sen: 3 },
    skills: "Sabres de Luz (Iniciante), Intimidação (Treinado), Domínio da Força (Treinado)",
    attacks: [
      {
        name: "Forma II — Golpe de Ataque (Makashi básico)",
        range: "Corpo a corpo",
        hit: "Sabre de Luz",
        damage: "6d6×atributo+perícia",
        damageType: "Energia",
        cost: "—",
        cooldown: "—",
        effect: "Estilo agressivo direto, sem floreios defensivos.",
      },
      {
        name: "Choque Menor",
        range: "6m",
        hit: "SEN+8",
        damage: "2d6",
        damageType: "Força/Elétrico",
        cost: "2 PE",
        cooldown: "2 rodadas",
        effect: "Alvo faz teste de VIG DT 17 ou fica Lento 1 rodada.",
      },
    ],
    powers: [
      {
        name: "Fúria Contida",
        text: "descrição: canaliza raiva em foco temporário — regra: próximo ataque ganha +1d6 — recarga: 2 rodadas — duração: 1 ataque — interações: pode ser usado logo antes de Forma II pra maximizar dano de abertura.",
      },
    ],
    passives: [
      {
        name: "Sobrevivente da Academia",
        effect: "já provou seu valor matando ou humilhando rivais; ganha +5 em Intimidação contra outros Sith de patente igual ou inferior.",
      },
    ],
    ai: "Age com confiança calculada — busca dominar psicologicamente antes de atacar (usa Intimidação/postura), depois abre com Fúria Contida + Forma II no alvo que demonstrou mais medo.",
    loot: "Sabre de luz de Acólito (vermelho, cristal sintético), fragmentos de textos Sith proibidos.",
    lore: "Sobreviventes da seleção brutal da Academia, já reconhecidos como dignos de treinamento formal — mas ainda muito abaixo de um Aprendiz com Mestre próprio.",
  },
  {
    id: "sith-aprendiz-sith",
    book: "sith",
    name: "Aprendiz Sith",
    category: "Usuário da Força",
    faction: "Ordem Sith",
    level: 14,
    threat: "Médio",
    role: "Dano",
    size: "Médio",
    type: "Sensitivo",
    planet: "Variável (a serviço de um Lord)",
    environment: "Qualquer",
    intelligence: "Alta",
    disposition: "Agressiva",
    pv: 56,
    pe: 32,
    defense: 21,
    initiative: 6,
    speed: "9m",
    attrs: { agi: 4, int: 1, forc: 6, vig: 3, pre: 2, sen: 5 },
    skills: "Sabres de Luz (Treinado), Domínio da Força (Expert), Intimidação (Treinado), Enganação (Iniciante)",
    attacks: [
      {
        name: "Forma II — Duelista Preciso",
        range: "Corpo a corpo",
        hit: "Sabre de Luz",
        damage: "6d6×atributo+perícia",
        damageType: "Energia",
        cost: "—",
        cooldown: "—",
        effect: "Contra outro usuário de sabre, +2 no teste de Acerto.",
      },
      {
        name: "Relâmpago da Força (menor)",
        range: "9m",
        hit: "SEN+13",
        damage: "3d6",
        damageType: "Força/Elétrico",
        cost: "3 PE",
        cooldown: "2 rodadas",
        effect: "Alvo fica Atordoado 1 rodada em falha crítica de VIG (DT 19).",
      },
    ],
    powers: [
      {
        name: "Sedução Sombria",
        text: "descrição: primeiros passos em manipulação emocional — regra: teste de Enganação DT 19 pra plantar uma dúvida/medo específico num alvo, afetando a próxima decisão dele — recarga: 1x por cena — duração: até o fim da cena — interações: não funciona em alvos com Domínio da Força maior que o do Aprendiz.",
      },
    ],
    passives: [
      {
        name: "Sede de Poder",
        effect: "sempre que reduz um inimigo a 0 PV, recupera 1d6 PE imediatamente.",
      },
    ],
    ai: "Já pensa como um duelista — busca o oponente mais forte da cena como prova de valor perante seu Mestre (ambição pessoal > estratégia de grupo). Usa Relâmpago da Força pra abrir espaço, depois busca duelo direto.",
    loot: "Sabre de luz de Aprendiz, holocron pessoal restrito, correspondência com o Mestre (gancho de história).",
    lore: 'Escolhido pessoalmente por um Lord Sith como aprendiz — a tradição do "Regra de Dois" (ou variantes de Ordem, dependendo da era da campanha) faz do vínculo Mestre-Aprendiz Sith algo tão intenso quanto traiçoeiro.',
  },
  {
    id: "sith-lord-sith",
    book: "sith",
    name: "Lord Sith",
    category: "Usuário da Força",
    faction: "Ordem Sith",
    level: 24,
    threat: "Forte",
    role: "Dano/Controle",
    size: "Médio",
    type: "Sensitivo",
    planet: "Variável",
    environment: "Qualquer",
    intelligence: "Alta",
    disposition: "Agressiva",
    pv: 108,
    pe: 56,
    defense: 26,
    initiative: 8,
    speed: "9m",
    attrs: { agi: 6, int: 2, forc: 8, vig: 4, pre: 4, sen: 8 },
    skills: "Sabres de Luz (Expert), Domínio da Força (Expert), Intimidação (Veterano), Enganação (Treinado)",
    attacks: [
      {
        name: "Forma VI — Ataque Total",
        range: "Corpo a corpo",
        hit: "Sabre de Luz",
        damage: "6d6×atributo+perícia",
        damageType: "Energia",
        cost: "—",
        cooldown: "—",
        effect: "Golpe agressivo sem reserva defensiva — mas ganha +2 no teste de Acerto se for o único atacante engajado.",
      },
      {
        name: "Relâmpago da Força",
        range: "Área 6m (linha)",
        hit: "SEN+22",
        damage: "5d6",
        damageType: "Força/Elétrico",
        cost: "3 PE",
        cooldown: "2 rodadas",
        effect: "Atinge todos na linha; alvos molhados/metálicos sofrem +2d6.",
      },
    ],
    powers: [
      {
        name: "Asfixia da Força",
        text: "descrição: constringe a garganta do alvo remotamente — regra: alvo fica Agarrado (via constrição) e sofre 2d6/rodada até escapar com teste de VIG DT 26; alvo agarrado não pode falar/atacar com voz — recarga: 3 rodadas — duração: até escapar — interações: usável mesmo através de barreiras físicas leves.",
      },
    ],
    passives: [
      {
        name: "Título Conquistado",
        effect: 'o título de "Lord" foi ganho matando o antecessor ou um rival direto; +5 em Defesa quando lutando pra defender seu próprio título/posição.',
      },
    ],
    ai: "Domina a cena pelo medo antes mesmo do primeiro golpe — usa Asfixia da Força como abertura contra o líder aparente do grupo adversário, depois foca dano bruto. Não hesita em sacrificar subordinados pra ganhar vantagem tática.",
    loot: "Sabre de luz de Lord (frequentemente customizado), artefatos sith pessoais, holocron de conhecimento avançado.",
    lore: "Um Sith que conquistou (geralmente à força) o título de Lord — comandante de operações, líder de célula ou governante de um território sob a bandeira do Lado Sombrio.",
  },
  {
    id: "sith-darth",
    book: "sith",
    name: "Darth",
    category: "Usuário da Força",
    faction: "Ordem Sith",
    level: 36,
    threat: "Elite",
    role: "Dano/Controle",
    size: "Médio",
    type: "Sensitivo",
    planet: "Variável (frequentemente sede de poder própria)",
    environment: "Qualquer",
    intelligence: "Alta",
    disposition: "Agressiva",
    pv: 244,
    pe: 90,
    defense: 27,
    initiative: 10,
    speed: "9m",
    attrs: { agi: 8, int: 3, forc: 10, vig: 6, pre: 6, sen: 11 },
    skills: "Sabres de Luz (Veterano), Domínio da Força (Veterano), Intimidação (Mestre), Liderança (Treinado)",
    attacks: [
      {
        name: "Forma VII — Juyo Descontrolado",
        range: "Corpo a corpo (até 2 alvos)",
        hit: "Sabre de Luz",
        damage: "6d6×atributo+perícia",
        damageType: "Energia",
        cost: "—",
        cooldown: "—",
        effect: "Instável e brutal; +1d6 extra, mas o Darth sofre 1d6 de dano próprio se errar o ataque.",
      },
      {
        name: "Tempestade de Relâmpagos",
        range: "Área 12m",
        hit: "SEN+27",
        damage: "7d6",
        damageType: "Força/Elétrico",
        cost: "4 PE",
        cooldown: "3 rodadas",
        effect: "Todos na área, aliados inclusive (a menos que o Darth escolha poupar alguém especificamente).",
      },
    ],
    powers: [
      {
        name: "Domínio pela Dor",
        text: "descrição: impõe sofrimento psíquico à distância — regra: alvo sofre −5 em todos os testes por 2 rodadas (dor debilitante, sem dano direto) — recarga: 3 rodadas — duração: 2 rodadas — interações: pode ser mantido em 1 alvo enquanto ataca outro fisicamente.",
      },
    ],
    passives: [
      {
        name: "Título das Sombras",
        effect: 'o nome "Darth" é reconhecido e temido; qualquer criatura de nível inferior precisa de teste de VIG bem-sucedido (DT igual à Defesa do Darth) só pra atacá-lo primeiro em vez de hesitar.',
      },
    ],
    ai: "Um Darth já não precisa provar nada — luta com eficiência fria e brutal, sem desperdiçar movimento. Usa Domínio pela Dor no combatente mais habilidoso do grupo adversário antes de focar dano, neutralizando a maior ameaça tática primeiro.",
    loot: "Sabre de luz de Darth (item icônico, frequentemente reconhecível), artefatos sombrios raros, holocrons de poder proibido.",
    lore: 'Título reservado a Sith de altíssimo poder e reconhecimento — muitas vezes o braço direito (ou o próprio) de um Império ou Ordem Sith. O nome "Darth" substitui o nome de nascença na maioria dos registros históricos.',
  },
  {
    id: "sith-mestre-sith",
    book: "sith",
    name: "Mestre Sith",
    category: "Usuário da Força",
    faction: "Ordem Sith",
    level: 50,
    threat: "Chefe",
    role: "Dano/Controle",
    size: "Médio",
    type: "Sensitivo",
    planet: "Variável",
    environment: "Qualquer",
    intelligence: "Sobre-humana",
    disposition: "Agressiva",
    pv: 574,
    pe: 132,
    defense: 32,
    initiative: 13,
    speed: "9m",
    attrs: { agi: 11, int: 4, forc: 13, vig: 8, pre: 8, sen: 14 },
    skills: "Sabres de Luz (Mestre), Domínio da Força (Mestre), Intimidação (Mestre), Liderança (Veterano)",
    attacks: [
      {
        name: "Corte da Perdição",
        range: "Corpo a corpo",
        hit: "Sabre de Luz",
        damage: "6d6×atributo+perícia",
        damageType: "Energia",
        cost: "—",
        cooldown: "—",
        effect: "Se o alvo já estiver com uma condição negativa ativa, +3d6.",
      },
      {
        name: "Relâmpago Devastador",
        range: "Área 15m",
        hit: "SEN+32",
        damage: "8d6",
        damageType: "Força/Elétrico",
        cost: "5 PE",
        cooldown: "3 rodadas",
        effect: "DT 32 de VIG; falha = Atordoado 1 rodada e −5 em Defesa por 2 rodadas.",
      },
    ],
    powers: [
      {
        name: "Colapso de Ódio (Fase 2)",
        text: "descrição: destravado abaixo de 50% PV — regra: todos os ataques causam +3d6 pelo resto do combate, mas o Mestre Sith sofre 5% do próprio PV máximo a cada rodada nessa fase (autodestrutivo, mas devastador) — recarga: 1x por combate — duração: resto do combate — interações: pode ser interrompido só por Barreira da Força ou efeito equivalente aplicado nele por um aliado dele mesmo.",
      },
    ],
    passives: [
      {
        name: "Autoridade Sombria",
        effect: "comanda Aprendizes e Acólitos na cena automaticamente; qualquer Sith de patente inferior presente ganha +1 ação extra na primeira rodada por causa da liderança do Mestre.",
      },
    ],
    ai: "Comanda ativamente subordinados presentes (usa Autoridade Sombria pra coordenar), reservando-se pra entrar pessoalmente só contra a maior ameaça da cena. Não teme dano próprio — Colapso de Ódio é usado sem hesitação se achar que vai selar a vitória.",
    loot: "Sabre de luz de Mestre Sith, artefatos de poder significativo, mapas/planos estratégicos (ganchos de campanha).",
    lore: "Um Sith que já formou os próprios Aprendizes e comanda recursos reais — exércitos, frotas ou territórios. Rivaliza em poder com um Mestre Jedi de patente equivalente, mas opera com objetivos muito mais pessoais.",
  },
  {
    id: "sith-membro-do-conselho-negro",
    book: "sith",
    name: "Membro do Conselho Negro",
    category: "Usuário da Força",
    faction: "Ordem Sith",
    level: 65,
    threat: "Chefe Lendário",
    role: "Dano/Controle",
    size: "Médio",
    type: "Sensitivo",
    planet: "Korriban/Moraband ou capital do Império Sith",
    environment: "Salão do Conselho",
    intelligence: "Sobre-humana",
    disposition: "Fanática",
    pv: 1050,
    pe: 168,
    defense: 34,
    initiative: 15,
    speed: "9m",
    attrs: { agi: 13, int: 5, forc: 15, vig: 10, pre: 10, sen: 17 },
    skills: "Sabres de Luz (Mestre), Domínio da Força (Mestre), Intimidação (Mestre), Liderança (Mestre)",
    attacks: [
      {
        name: "Golpe do Conselho",
        range: "Corpo a corpo",
        hit: "Sabre de Luz",
        damage: "6d6×atributo+perícia",
        damageType: "Energia",
        cost: "—",
        cooldown: "—",
        effect: "Uma vez por combate, pode gastar 2 PE pra rolar o dano duas vezes e ficar com o maior resultado.",
      },
      {
        name: "Vórtice de Ódio",
        range: "Área 15m",
        hit: "SEN+37",
        damage: "10d6",
        damageType: "Força/Elétrico",
        cost: "5 PE",
        cooldown: "3 rodadas",
        effect: "Todos na área testam VIG DT 34; falha = Derrubado + Atordoado 1 rodada. Sucesso ainda sofre metade do dano.",
      },
    ],
    powers: [
      {
        name: "Voto Sombrio",
        text: "descrição: invoca o poder coletivo simbólico do Conselho Negro — regra: por 3 rodadas, ganha +5 em todos os testes de Acerto e Defesa — recarga: 1x por combate — duração: 3 rodadas — interações: efeito puramente pessoal, não afeta aliados.",
      },
    ],
    passives: [
      {
        name: "Assento de Poder",
        effect: "imune à condição Amedrontado. Sua simples presença impõe DT 30 de Intimidação passiva sobre qualquer NPC de nível inferior a 30, sem precisar de teste ativo.",
      },
    ],
    ai: "Estrategista de longuíssimo prazo — trata qualquer combate individual como um movimento num jogo maior, nunca o objetivo final. Usa Voto Sombrio no início de um confronto que considera decisivo pra sua agenda; foge (teleporte/nave/fuga planejada) sem hesitação se o combate deixar de servir seus objetivos políticos.",
    loot: "Sabre de luz de altíssimo prestígio, artefatos do Conselho, informações estratégicas de nível imperial.",
    lore: "Um dos poucos assentos do órgão supremo de poder Sith — rivaliza diretamente com o Alto Conselho Jedi em estrutura, mas move-se por ambição individual tanto quanto por ideologia coletiva. Traição interna é constante e esperada.",
  },
  {
    id: "sith-lorde-supremo",
    book: "sith",
    name: "Lorde Supremo",
    category: "Usuário da Força",
    faction: "Ordem Sith",
    level: 82,
    threat: "Chefe Lendário",
    role: "Dano/Controle",
    size: "Médio",
    type: "Sensitivo",
    planet: "Sede do Império/Ordem Sith",
    environment: "Trono",
    intelligence: "Sobre-humana",
    disposition: "Fanática",
    pv: 1720,
    pe: 260,
    defense: 34,
    initiative: 18,
    speed: "9m",
    attrs: { agi: 15, int: 6, forc: 18, vig: 13, pre: 13, sen: 21 },
    skills: "Sabres de Luz (Mestre), Domínio da Força (Mestre), Intimidação (Mestre), Liderança (Mestre), Enganação (Mestre)",
    attacks: [
      {
        name: "Sentença Final",
        range: "Corpo a corpo",
        hit: "Sabre de Luz",
        damage: "6d6×atributo+perícia",
        damageType: "Energia",
        cost: "—",
        cooldown: "—",
        effect: "Se o alvo estiver abaixo de 30% PV, este golpe ignora Defesa.",
      },
      {
        name: "Trono de Relâmpagos",
        range: "Área 20m",
        hit: "SEN+42",
        damage: "12d6",
        damageType: "Força/Elétrico",
        cost: "6 PE",
        cooldown: "4 rodadas",
        effect: "DT 34 de VIG; falha = Derrubado, Atordoado 1 rodada, empurrado 6m.",
      },
    ],
    powers: [
      {
        name: "Domínio Absoluto",
        text: "descrição: comanda a vontade de subordinados a distância — regra: até 3 NPCs Sith de patente inferior na cena agem imediatamente fora da ordem de turno normal, uma vez por combate, no momento que o Lorde Supremo escolher — recarga: 1x por combate — duração: instantâneo — interações: excelente pra sincronizar um ataque devastador em grupo.",
      },
    ],
    passives: [
      {
        name: "O Império é Ele",
        effect: "enquanto vivo, todo NPC Sith/Imperial na campanha ganha +2 em testes de Moral (resistência a fugir/desertar). Sua morte pode fragmentar uma facção inteira (gancho de campanha).",
      },
    ],
    ai: "Raramente entra em combate direto sem vantagem esmagadora já garantida — prefere manobrar political e militarmente até o confronto ser favorável de forma quase injusta. Quando luta, usa Domínio Absoluto pra abrir com um ataque coordenado brutal antes mesmo dos PJs agirem.",
    loot: "Sabre de luz do trono, artefatos de poder supremo, acesso a recursos de escala imperial (frotas, exércitos — gancho de campanha, não item literal).",
    lore: 'O governante supremo de uma Ordem ou Império Sith — o topo absoluto da hierarquia de poder temporal do Lado Sombrio em sua era. Derrubar um Lorde Supremo é, tipicamente, o clímax de uma campanha inteira.',
  },
  {
    id: "sith-lendario",
    book: "sith",
    name: "Sith Lendário",
    category: "Usuário da Força",
    faction: "Ordem Sith",
    level: 98,
    threat: "Chefe Lendário",
    role: "Dano/Controle",
    size: "Médio",
    type: "Sensitivo",
    planet: "Variável (frequentemente lendário/perdido)",
    environment: "Qualquer",
    intelligence: "Sobre-humana",
    disposition: "Fanática",
    pv: 1980,
    pe: 310,
    defense: 36,
    initiative: 21,
    speed: "9m",
    attrs: { agi: 18, int: 7, forc: 22, vig: 15, pre: 15, sen: 24 },
    skills: "Sabres de Luz (Mestre), Domínio da Força (Mestre), Intimidação (Mestre), Conhecimento da Força (Mestre)",
    attacks: [
      {
        name: "Golpe da Eternidade",
        range: "Corpo a corpo",
        hit: "Sabre de Luz",
        damage: "6d6×atributo+perícia",
        damageType: "Energia",
        cost: "—",
        cooldown: "—",
        effect: 'Uma vez por combate, pode ser declarado "imortal": se este golpe reduzir um alvo a 0 PV, o Sith Lendário recupera 20% do próprio PV máximo.',
      },
      {
        name: "Fúria Ancestral",
        range: "Área 25m",
        hit: "SEN+46",
        damage: "18d6",
        damageType: "Força/Elétrico",
        cost: "8 PE",
        cooldown: "4 rodadas",
        effect: "DT 36 de VIG; falha = Derrubado, Atordoado 2 rodadas, empurrado 9m.",
      },
    ],
    powers: [
      {
        name: "Eco de Vidas Passadas",
        text: 'descrição: alguns Sith Lendários preservam consciência além da morte biológica normal (espírito, holocron, possessão) — regra: se "morto" em combate, pode retornar em uma campanha futura por meios narrativos (espectro, ritual, holocron) — recarga: narrativo, não mecânico — duração: permanente até resolução da história — interações: use com moderação — é uma ferramenta de história, não uma forma de tornar o combate sem consequência.',
      },
    ],
    passives: [
      {
        name: "Lenda Viva do Lado Sombrio",
        effect: "imune a todas as condições de controle de criaturas de nível inferior a 80. Regenera 3% do PV máximo por rodada automaticamente, sempre (não só em Fase 2).",
      },
    ],
    ai: 'Combate com um Sith Lendário deveria ser o ápice absoluto de uma campanha — ele luta com séculos (ou mais) de experiência condensada, testando cada fraqueza do grupo adversário sistematicamente antes de escalar pra força total. Não subestima ninguém — já viu Jedi e Sith "impossíveis de vencer" caírem por overconfidence alheia.',
    loot: "Sabre de luz lendário, artefatos de poder inigualável, segredos perdidos do Lado Sombrio (conhecimento, não item físico).",
    lore: "Nomes que ecoam através de milênios — Sith cuja influência moldou impérios inteiros e cujas técnicas ainda são estudadas (com medo reverente) por Sith modernos. Nota de design: mesmo teto mecânico do Grão-Mestre Jedi (Chefe Lendário), por simetria e pelo mesmo motivo — preserva a possibilidade de um grupo de altíssimo nível desafiá-lo em ficção, em vez de torná-lo um evento inevitável e sem escolha real.",
  },
  {
    id: "sith-darth-nihilus",
    book: "sith",
    name: "Darth Nihilus",
    epithet: "O Senhor da Fome",
    category: "Sith Lendário Nomeado",
    faction: "Sith (isolado, sem Ordem formal)",
    level: 95,
    threat: "Ameaça Galáctica",
    role: "Dano/Controle",
    size: "Médio",
    type: "Sensitivo",
    planet: "Nascido em Katarr — mundo inteiro consumido por ele num único ritual",
    environment: "Naves Sith isoladas nas Regiões Desconhecidas",
    intelligence: "Sobre-humana",
    disposition: "Fanática",
    pv: 3600,
    pe: 700,
    defense: 34,
    initiative: 17,
    speed: "9m",
    attrs: { agi: 8, int: 6, forc: 15, vig: 13, pre: 3, sen: 22 },
    skills: "Sabres de Luz (Mestre), Domínio da Força (Mestre), Intimidação (Mestre), Percepção (Veterano)",
    attacks: [
      {
        name: "Lâmina Faminta",
        range: "Corpo a corpo",
        hit: "Sabre de Luz",
        damage: "6d6×atributo+perícia",
        damageType: "Energia/Força",
        cost: "—",
        cooldown: "—",
        effect: "Cada acerto drena 1d6 PE do alvo; Nihilus recupera metade do PE drenado.",
      },
      { name: "Fome Absoluta", range: "Área 15m", hit: "SEN+45", damage: "15d6", damageType: "Força", cost: "6 PE", cooldown: "3 rodadas", effect: "Todo ser vivo/sensível à Força na área sofre dano adicional igual à metade do próprio PE atual perdido no ataque — sensíveis à Força têm desvantagem no teste de resistência." },
      { name: "Vórtice de Vazio", range: "9m", hit: "SEN+45", damage: "15d6", damageType: "Força", cost: "4 PE", cooldown: "2 rodadas", effect: "Puxa o alvo 6m em direção a ele antes do impacto." },
    ],
    powers: [
      {
        name: "A Ferida Viva (Fase 2)",
        text: "descrição: abaixo de 50% PV, sua fome desesperada se intensifica — regra: todos os ataques ganham +3d6 de dano e ele ignora Redução de Dano de qualquer origem — recarga: uma vez por combate, ao cruzar 50% PV — duração: resto do combate — interações: substitui a Segunda Fase padrão de Chefe.",
      },
      {
        name: "Consumir um Mundo",
        text: 'descrição: fora de combate tático, em ritual de dias, pode extinguir toda vida sensível à Força de um planeta inteiro (como fez em Katarr) — regra: gancho de campanha, não uma ação de combate normal — recarga: narrativo — duração: permanente — interações: o Mestre deveria usar isso como ameaça de fundo/motor de enredo, nunca como algo resolvido numa única cena de combate.',
      },
    ],
    passives: [
      { name: "Ferida no Tecido da Força", effect: "invisível pra qualquer sentido da Força (Percepção da Força, premonição) até se revelar; sensíveis à Força só sentem um \"vazio\" perturbador em vez de sua presença." },
      { name: "Fome Insaciável", effect: "recupera PE igual à metade de todo dano que causa." },
    ],
    ai: "Quase não fala. Ataca primeiro quem tiver maior presença na Força (maior SEN/PE atual), ignorando completamente combatentes não sensíveis à Força a menos que atrapalhem o caminho até o verdadeiro alvo. Nunca recua, nunca negocia — a fome não permite.",
    loot: "Máscara ritual (artefato Sith lendário — amplifica absorção de Força de quem a veste, mas maldita), sabre de luz faminto.",
    lore: "Um dos Sith Lordes mais aterrorizantes já registrados — sobrevivente de uma tragédia que o deixou permanentemente faminto por força vital, capaz de extinguir toda vida sensível à Força de um planeta inteiro num só ritual. Raramente enfrentado em combate direto: geralmente é o evento que define uma campanha inteira, não um encontro isolado.",
  },
];

export const SITH_SPECIALIZATIONS: CreatureModule[] = [
  {
    id: "sith-spec-duelista",
    name: "Duelista",
    text: '+Sabres de Luz (sobe um grau). Poder extra: **Prova de Sangue** (sem custo, recarga passiva — em duelo 1-contra-1, ganha +5 em Acerto). Passiva ajustada: nunca sofre penalidade por lutar contra múltiplos estilos de sabre na mesma cena (sempre "leu" o oponente rápido).',
  },
  {
    id: "sith-spec-alquimista-sith",
    name: "Alquimista Sith",
    text: "+Ciências. Poder extra: **Corrupção Alquímica** (custo 3 PE, recarga 3 rodadas — transforma temporariamente uma criatura/planta próxima numa aliada corrompida hostil, usando estatísticas de uma criatura Fraca/Média do bestiário). Passiva ajustada: imune a veneno e doença.",
  },
  {
    id: "sith-spec-assassino",
    name: "Assassino",
    text: "+Furtividade e +Acrobacia. Poder extra: **Golpe das Sombras** (custo 2 PE, recarga 2 rodadas — teleporte curto de até 6m antes de um ataque corpo a corpo, ignorando reações de oportunidade). Passiva ajustada: ataques contra alvos surpreendidos causam +3d6.",
  },
  {
    id: "sith-spec-feiticeiro-sith",
    name: "Feiticeiro Sith",
    text: "+Domínio da Força (sobe um grau). Poder extra: **Maldição Persistente** (custo 4 PE, recarga por cena — impõe uma condição negativa contínua a um alvo que dura até ser removida ativamente, não apenas por tempo). Passiva ajustada: PE máximo +30%.",
  },
  {
    id: "sith-spec-manipulador",
    name: "Manipulador",
    text: "+Enganação e +Persuasão. Poder extra: **Sussurro Sombrio** (custo 2 PE, recarga 2 rodadas — planta uma sugestão específica na mente de um alvo; alvo faz teste de PRE oposto pra resistir). Passiva ajustada: nunca é o primeiro suspeito em uma investigação (vantagem passiva em qualquer teste social de disfarce).",
  },
  {
    id: "sith-spec-general-sith",
    name: "General Sith",
    text: "+Liderança. Poder extra: **Ordem de Ataque** (sem custo, recarga por cena — até 3 NPCs aliados na cena ganham uma ação extra imediata). Passiva ajustada: comanda tropas convencionais (Militares, ver Livro 5) com +2 de bônus de moral pra elas.",
  },
  {
    id: "sith-spec-executor",
    name: "Executor",
    text: "+Intimidação (sobe um grau). Poder extra: **Execução Sumária** (custo igual ao ataque principal da patente — se usado contra um alvo já Derrubado ou Agarrado, dano triplicado). Passiva ajustada: +10 PV máximo por nível de Chefe+ na cena que ele mesmo tenha abatido nesta campanha (acumulativo, rastreie por NPC).",
  },
  {
    id: "sith-spec-inquisidor",
    name: "Inquisidor",
    text: "+Investigação e +Percepção. Poder extra: **Farejar a Luz** (sem custo, recarga passiva — detecta qualquer usuário do Lado da Luz num raio de 500m). Passiva ajustada: vantagem em Acerto contra qualquer alvo Jedi ou Sensitivo do Lado da Luz.",
  },
  {
    id: "sith-spec-cacador-de-jedi",
    name: "Caçador de Jedi",
    text: '+Percepção e +Furtividade. Poder extra: **Neutralizador de Sabre** (custo 3 PE, recarga 3 rodadas — teste oposto de Domínio da Força contra um alvo empunhando sabre de luz; sucesso desarma o alvo à distância). Passiva ajustada: ignora a passiva "Reflexo de Sabre" de qualquer Jedi (ver Livro 2) — anos de treinamento específico contra a Ordem.',
  },
];
