// ─── TORMENTA 20 — Poderes e progressão de classe: Arcanista, Bárbaro, Bardo, Bucaneiro, Caçador ─
// Fonte: Capítulo Um (Tabelas 1-4 a 1-8 + listas "Poder de <Classe>"), pág. 36-51.
import type { Power } from "./types";

export interface ClassLevelRow { level: number; text: string }
export interface ClassFeature { name: string; level: number; description: string }

// ── Arcanista ─────────────────────────────────────────────────────────────────

export const ARCANISTA_LEVELS: ClassLevelRow[] = [
  { level: 1, text: "Caminho do arcanista, magias (1º círculo)" },
  { level: 2, text: "Poder de arcanista" },
  { level: 3, text: "Poder de arcanista" },
  { level: 4, text: "Poder de arcanista" },
  { level: 5, text: "Magias (2º círculo), poder de arcanista" },
  { level: 6, text: "Poder de arcanista" },
  { level: 7, text: "Poder de arcanista" },
  { level: 8, text: "Poder de arcanista" },
  { level: 9, text: "Magias (3º círculo), poder de arcanista" },
  { level: 10, text: "Poder de arcanista" },
  { level: 11, text: "Poder de arcanista" },
  { level: 12, text: "Poder de arcanista" },
  { level: 13, text: "Magias (4º círculo), poder de arcanista" },
  { level: 14, text: "Poder de arcanista" },
  { level: 15, text: "Poder de arcanista" },
  { level: 16, text: "Poder de arcanista" },
  { level: 17, text: "Magias (5º círculo), poder de arcanista" },
  { level: 18, text: "Poder de arcanista" },
  { level: 19, text: "Poder de arcanista" },
  { level: 20, text: "Alta arcana, poder de arcanista" },
];

export const ARCANISTA_FEATURES: ClassFeature[] = [
  {
    name: "Alta Arcana",
    level: 20,
    description: "No 20º nível, seu domínio das artes arcanas é total. O custo em PM de suas magias arcanas é reduzido à metade (após aplicar aprimoramentos e quaisquer outros efeitos que reduzam custo).",
  },
];

export const ARCANISTA_POWERS: Power[] = [
  { id: "arcano-de-batalha", name: "Arcano de Batalha", category: "classe", classId: "arcanista", prerequisite: "—",
    description: "Você soma o bônus de seu atributo-chave nas rolagens de dano para magias e para seu Raio Arcano (caso possua)." },
  { id: "caldeirao-do-bruxo", name: "Caldeirão do Bruxo", category: "classe", classId: "arcanista", prerequisite: "Bruxo, treinado em Ofício (alquimia)",
    description: "Você pode criar poções, como se tivesse o poder geral Preparar Poção. Se tiver ambos, você pode criar poções de 3º círculo." },
  { id: "conhecimento-magico", name: "Conhecimento Mágico", category: "classe", classId: "arcanista", prerequisite: "—",
    description: "Você aprende duas magias de qualquer círculo que possa lançar. Você pode escolher este poder quantas vezes quiser." },
  { id: "contramagica-aprimorada", name: "Contramágica Aprimorada", category: "classe", classId: "arcanista", prerequisite: "Dissipar Magia",
    description: "Uma vez por rodada, você pode fazer uma contramágica como uma reação (veja a página 164)." },
  { id: "envolto-em-misterio", name: "Envolto em Mistério", category: "classe", classId: "arcanista", prerequisite: "—",
    description: "Sua aparência e postura assombrosas o permitem manipular e assustar pessoas ignorantes ou supersticiosas. O mestre define o que exatamente você pode fazer e quem se encaixa nessa descrição. Como regra geral, você recebe +5 em Enganação e Intimidação contra pessoas não treinadas em Conhecimento ou Misticismo." },
  { id: "escriba-arcano", name: "Escriba Arcano", category: "classe", classId: "arcanista", prerequisite: "Mago, treinado em Conhecimento",
    description: "Você pode aprender magias copiando os textos de pergaminhos e grimórios de outros magos. Aprender uma magia dessa forma exige um dia de trabalho e T$ 250 em matérias-primas por PM necessário para lançar a magia. Assim, aprender uma magia de 3º círculo (6 PM) exige 6 dias de trabalho e o gasto de T$ 1.500." },
  { id: "especialista-em-escola", name: "Especialista em Escola", category: "classe", classId: "arcanista", prerequisite: "Bruxo ou Mago",
    description: "Escolha uma escola de magia. A CD para resistir a suas magias dessa escola aumenta em +2." },
  { id: "familiar", name: "Familiar", category: "classe", classId: "arcanista", prerequisite: "—",
    description: "Você possui um animal de estimação mágico — um aliado especial com o qual você pode se comunicar telepaticamente em alcance médio. Ele obedece a suas ordens, mas ainda está limitado ao que uma criatura de sua espécie pode fazer. Se ele morrer, você fica atordoado por uma rodada; pode invocar um novo com um ritual de um dia e T$ 100 em ingredientes. Escolha um: Borboleta (CD de Vontade das suas magias +1), Cobra (CD de Fortitude das suas magias +1), Coruja (pague +1 PM para estender o alcance de toque de uma magia para curto), Corvo (pague 1 PM para rolar dois dados num teste de Misticismo ou Vontade e usar o melhor), Falcão (você nunca fica desprevenido), Gato (visão no escuro e +2 em Furtividade), Lagarto (CD de Reflexos das suas magias +1), Morcego (percepção às cegas em alcance curto), Rato (pode usar seu atributo-chave em Fortitude, no lugar de Constituição), Sapo (soma o bônus de seu atributo-chave ao total de pontos de vida)." },
  { id: "fluxo-de-mana", name: "Fluxo de Mana", category: "classe", classId: "arcanista", prerequisite: "10º nível de arcanista",
    description: "Você pode manter dois efeitos sustentados ativos simultaneamente com apenas uma ação livre, pagando o custo de cada efeito separadamente." },
  { id: "foco-vital", name: "Foco Vital", category: "classe", classId: "arcanista", prerequisite: "Bruxo", magic: true,
    description: "Se você estiver segurando seu foco e sofrer dano que o levaria a 0 PV ou menos, você fica com 1 PV e o foco perde pontos de vida igual ao valor excedente, até ser destruído." },
  { id: "fortalecimento-arcano", name: "Fortalecimento Arcano", category: "classe", classId: "arcanista", prerequisite: "5º nível de arcanista",
    description: "A CD para resistir a suas magias aumenta em +1. Se você puder lançar magias de 4º círculo, em vez disso ela aumenta em +2." },
  { id: "heranca-aprimorada", name: "Herança Aprimorada", category: "classe", classId: "arcanista", prerequisite: "Feiticeiro, 6º nível de arcanista",
    description: "Você recebe a herança aprimorada de sua linhagem sobrenatural (veja Linhagens Sobrenaturais)." },
  { id: "heranca-superior", name: "Herança Superior", category: "classe", classId: "arcanista", prerequisite: "Herança Aprimorada, 11º nível de arcanista",
    description: "Você recebe a herança superior de sua linhagem sobrenatural (veja Linhagens Sobrenaturais)." },
  { id: "magia-pungente", name: "Magia Pungente", category: "classe", classId: "arcanista", prerequisite: "—",
    description: "Quando lança uma magia, você pode pagar 1 PM para aumentar em +2 a CD para resistir a ela." },
  { id: "mestre-em-escola", name: "Mestre em Escola", category: "classe", classId: "arcanista", prerequisite: "Especialista em Escola com a escola escolhida, 8º nível de arcanista",
    description: "Escolha uma escola de magia. O custo para lançar magias dessa escola diminui em –1 PM." },
  { id: "poder-magico", name: "Poder Mágico", category: "classe", classId: "arcanista", prerequisite: "—",
    description: "Você recebe +1 ponto de mana por nível de arcanista. Quando sobe de nível, os PM que recebe por este poder aumentam de acordo (por exemplo, se escolher este poder no 4º nível, recebe 4 PM; ao subir para o 5º nível, recebe +1 PM, e assim por diante). Você pode escolher este poder uma segunda vez, para um total de +2 PM por nível." },
  { id: "raio-arcano", name: "Raio Arcano", category: "classe", classId: "arcanista", prerequisite: "—", magic: true,
    description: "Você pode gastar uma ação padrão para disparar um raio num alvo em alcance curto que causa 1d6 pontos de dano de essência. Esse dano aumenta em +1d6 para cada círculo de magia acima do 1º que você puder lançar. O alvo pode fazer um teste de Reflexos (CD atributo-chave) para reduzir o dano à metade." },
  { id: "raio-elemental", name: "Raio Elemental", category: "classe", classId: "arcanista", prerequisite: "Raio Arcano", magic: true,
    description: "Quando usa Raio Arcano, você pode pagar 1 PM para que ele cause dano de um tipo de energia a sua escolha, entre ácido, eletricidade, fogo, frio ou trevas. Se o alvo falhar no teste de Reflexos, sofre uma condição de acordo com o tipo de energia: Ácido (vulnerável por uma rodada), Eletricidade (ofuscado por uma rodada), Fogo (fica em chamas), Frio (lento por uma rodada), Trevas (não pode ser curado por uma rodada)." },
  { id: "raio-poderoso", name: "Raio Poderoso", category: "classe", classId: "arcanista", prerequisite: "Raio Arcano", magic: true,
    description: "Os dados de dano do seu Raio Arcano aumentam para d8 e o alcance dele aumenta para médio." },
  { id: "tinta-do-mago", name: "Tinta do Mago", category: "classe", classId: "arcanista", prerequisite: "Mago, treinado em Conhecimento",
    description: "Você pode criar pergaminhos, como se tivesse o poder Escrever Pergaminho. Se tiver ambos, seu custo para criar pergaminhos é reduzido à metade." },
];

// ── Bárbaro ───────────────────────────────────────────────────────────────────

export const BARBARO_LEVELS: ClassLevelRow[] = [
  { level: 1, text: "Fúria +2" },
  { level: 2, text: "Poder de bárbaro" },
  { level: 3, text: "Instinto selvagem +1, poder de bárbaro" },
  { level: 4, text: "Poder de bárbaro" },
  { level: 5, text: "Poder de bárbaro, resistência a dano 2" },
  { level: 6, text: "Fúria +3, poder de bárbaro" },
  { level: 7, text: "Poder de bárbaro" },
  { level: 8, text: "Poder de bárbaro, resistência a dano 4" },
  { level: 9, text: "Instinto selvagem +2, poder de bárbaro" },
  { level: 10, text: "Poder de bárbaro" },
  { level: 11, text: "Fúria +4, poder de bárbaro, resistência a dano 6" },
  { level: 12, text: "Poder de bárbaro" },
  { level: 13, text: "Poder de bárbaro" },
  { level: 14, text: "Poder de bárbaro, resistência a dano 8" },
  { level: 15, text: "Instinto selvagem +3, poder de bárbaro" },
  { level: 16, text: "Fúria +5, poder de bárbaro" },
  { level: 17, text: "Poder de bárbaro, resistência a dano 10" },
  { level: 18, text: "Poder de bárbaro" },
  { level: 19, text: "Poder de bárbaro" },
  { level: 20, text: "Fúria titânica, poder de bárbaro" },
];

export const BARBARO_FEATURES: ClassFeature[] = [
  { name: "Instinto Selvagem", level: 3, description: "Você recebe +1 em Percepção e Reflexos. A cada seis níveis, esse bônus aumenta em +1." },
  { name: "Resistência a Dano", level: 5, description: "Graças a seu vigor e força de vontade, você ignora parte de seus ferimentos. Você recebe resistência a dano 2 (todo dano que sofre é reduzido em 2). A cada três níveis, sua RD aumenta em 2, até um máximo de RD 10 no 17º nível." },
  { name: "Fúria Titânica", level: 20, description: "No 20º nível, o bônus que você recebe nos testes de ataque e rolagens de dano quando usa Fúria é dobrado. Por exemplo, se gastar 8 PM, em vez de um bônus de +5, recebe um bônus de +10." },
];

export const BARBARO_POWERS: Power[] = [
  { id: "alma-de-bronze", name: "Alma de Bronze", category: "classe", classId: "barbaro", prerequisite: "—",
    description: "Quando entra em fúria, você recebe uma quantidade de pontos de vida temporários igual a metade do seu nível + mod. Força." },
  { id: "brado-assustador", name: "Brado Assustador", category: "classe", classId: "barbaro", prerequisite: "Treinado em Intimidação",
    description: "Você pode gastar uma ação de movimento e 1 PM para soltar um berro feroz. Todos os inimigos em alcance curto devem fazer um teste de Vontade (CD Car). Um inimigo que falhe fica abalado até o fim da cena. Um inimigo que passe se torna imune a esta habilidade até o fim do dia." },
  { id: "critico-brutal", name: "Crítico Brutal", category: "classe", classId: "barbaro", prerequisite: "6º nível de bárbaro",
    description: "Seu multiplicador de crítico com ataques corpo a corpo aumenta em +1. Por exemplo, se fizer um crítico com um machado de batalha, seu multiplicador será x4, em vez de x3." },
  { id: "destruidor", name: "Destruidor", category: "classe", classId: "barbaro", prerequisite: "For 13",
    description: "Quando causa dano com uma arma corpo a corpo de duas mãos, você pode rolar novamente qualquer resultado 1 ou 2 das rolagens de dano da arma." },
  { id: "espirito-inquebravel", name: "Espírito Inquebrável", category: "classe", classId: "barbaro", prerequisite: "Alma de Bronze",
    description: "Enquanto está em fúria, você não fica inconsciente por estar com 0 ou menos pontos de vida (você ainda morre se chegar em um valor negativo igual à metade de seus PV máximos)." },
  { id: "esquiva-sobrenatural", name: "Esquiva Sobrenatural", category: "classe", classId: "barbaro", prerequisite: "—",
    description: "Seus instintos ficam tão apurados que você consegue reagir ao perigo antes que seus sentidos percebam. Você nunca fica surpreendido." },
  { id: "forca-indomavel", name: "Força Indomável", category: "classe", classId: "barbaro", prerequisite: "—",
    description: "Você pode gastar 1 PM para somar seu nível em um teste de Força ou Atletismo. Você pode usar esta habilidade depois de rolar o dado, mas deve usá-la antes de o mestre dizer se você passou ou não." },
  { id: "frenesi", name: "Frenesi", category: "classe", classId: "barbaro", prerequisite: "—",
    description: "Se estiver em fúria e usar a ação atacar para fazer um ataque corpo a corpo, você pode gastar 2 PM para fazer um ataque adicional." },
  { id: "furia-da-savana", name: "Fúria da Savana", category: "classe", classId: "barbaro", prerequisite: "—",
    description: "Seu deslocamento aumenta em +3m. Quando usa Fúria, você aplica o bônus em ataque e dano também a armas de arremesso." },
  { id: "furia-raivosa", name: "Fúria Raivosa", category: "classe", classId: "barbaro", prerequisite: "—",
    description: "Se sua Fúria for terminar por você não ter atacado nem sido alvo de um efeito hostil, você pode pagar 1 PM para continuar em fúria nesta rodada. Se você atacar ou for atacado na rodada seguinte, sua fúria continua normalmente." },
  { id: "golpe-poderoso", name: "Golpe Poderoso", category: "classe", classId: "barbaro", prerequisite: "—",
    description: "Ao acertar um ataque corpo a corpo, você pode gastar 1 PM para causar um dado de dano extra do mesmo tipo (por exemplo, com um montante, causa +1d6, para um dano total de 3d6; com um machado de guerra, causa +1d12)." },
  { id: "impeto", name: "Ímpeto", category: "classe", classId: "barbaro", prerequisite: "—",
    description: "Você pode gastar 1 PM para aumentar seu deslocamento em +6m por uma rodada." },
  { id: "investida-imprudente", name: "Investida Imprudente", category: "classe", classId: "barbaro", prerequisite: "—",
    description: "Quando faz uma investida, você pode aumentar sua penalidade em Defesa pela investida para –5 para receber um bônus de +1d8 na rolagem de dano deste ataque." },
  { id: "pele-de-aco", name: "Pele de Aço", category: "classe", classId: "barbaro", prerequisite: "Pele de Ferro, 8º nível de bárbaro",
    description: "O bônus de Pele de Ferro aumenta para +5." },
  { id: "pele-de-ferro", name: "Pele de Ferro", category: "classe", classId: "barbaro", prerequisite: "—",
    description: "Você recebe +2 na Defesa, mas apenas se não estiver usando armadura pesada." },
  { id: "sangue-dos-inimigos", name: "Sangue dos Inimigos", category: "classe", classId: "barbaro", prerequisite: "—",
    description: "Enquanto está em fúria, quando faz um acerto crítico ou reduz um inimigo a 0 PV, você recebe um bônus cumulativo de +1 em testes de ataque e rolagens de dano, limitado pelo seu nível, até o fim da cena." },
  { id: "superstição", name: "Superstição", category: "classe", classId: "barbaro", prerequisite: "—",
    description: "Você odeia magia, o que faz com que seja mais resistente a ela. Você recebe resistência a magia +2." },
  { id: "totem-espiritual", name: "Totem Espiritual", category: "classe", classId: "barbaro", prerequisite: "Sab 13, 4º nível de bárbaro",
    description: "Você soma seu bônus de Sabedoria no seu total de pontos de mana. Escolha um animal totêmico: Coruja (lança Orientação), Corvo (lança Visão Mística), Falcão (lança Detectar Ameaças), Grifo (lança Primor Atlético), Lobo (lança Concentração de Combate), Raposa (lança Imagem Espelhada), Tartaruga (lança Armadura Arcana) ou Urso (lança Vitalidade Fantasma). Você pode lançar a magia definida pelo animal escolhido (atributo-chave Sabedoria)." },
  { id: "vigor-primal", name: "Vigor Primal", category: "classe", classId: "barbaro", prerequisite: "—",
    description: "Você pode gastar uma ação de movimento e 1 PM para recuperar 1d12 pontos de vida. Para cada 2 PM extras que você gastar, cura +1d12 PV (pode gastar 3 PM para recuperar 2d12 PV, 5 PM para recuperar 3d12 PV e assim por diante)." },
];

// ── Bardo ─────────────────────────────────────────────────────────────────────

export const BARDO_LEVELS: ClassLevelRow[] = [
  { level: 1, text: "Inspiração +1, magias (1º círculo)" },
  { level: 2, text: "Poder de bardo, eclético" },
  { level: 3, text: "Poder de bardo" },
  { level: 4, text: "Poder de bardo" },
  { level: 5, text: "Inspiração +2, poder de bardo" },
  { level: 6, text: "Magias (2º círculo), poder de bardo" },
  { level: 7, text: "Poder de bardo" },
  { level: 8, text: "Poder de bardo" },
  { level: 9, text: "Inspiração +3, poder de bardo" },
  { level: 10, text: "Magias (3º círculo), poder de bardo" },
  { level: 11, text: "Poder de bardo" },
  { level: 12, text: "Poder de bardo" },
  { level: 13, text: "Inspiração +4, poder de bardo" },
  { level: 14, text: "Magias (4º círculo), poder de bardo" },
  { level: 15, text: "Poder de bardo" },
  { level: 16, text: "Poder de bardo" },
  { level: 17, text: "Inspiração +5, poder de bardo" },
  { level: 18, text: "Poder de bardo" },
  { level: 19, text: "Poder de bardo" },
  { level: 20, text: "Artista completo, poder de bardo" },
];

export const BARDO_FEATURES: ClassFeature[] = [
  { name: "Eclético", level: 2, description: "A partir do 2º nível, você pode gastar 1 PM para receber todos os benefícios de ser treinado em uma perícia por um teste." },
  { name: "Artista Completo", level: 20, description: "No 20º nível, você pode usar Inspiração como uma ação livre. Enquanto estiver sob efeito de sua Inspiração, qualquer habilidade de bardo (incluindo magias) que você usar tem seu custo em PM reduzido pela metade (após aplicar quaisquer outras habilidades que reduzam o custo)." },
];

export const BARDO_POWERS: Power[] = [
  { id: "arte-magica", name: "Arte Mágica", category: "classe", classId: "bardo", prerequisite: "—",
    description: "Enquanto você estiver sob efeito de sua habilidade Inspiração, a CD para resistir a suas magias de bardo aumenta em +2." },
  { id: "aumentar-repertorio", name: "Aumentar Repertório", category: "classe", classId: "bardo", prerequisite: "—",
    description: "Você aprende duas magias de qualquer círculo que possa lançar. Elas devem pertencer às escolas que você sabe usar, mas podem ser arcanas ou divinas. Você pode escolher este poder quantas vezes quiser." },
  { id: "cancao-assustadora", name: "Canção Assustadora", category: "classe", classId: "bardo", prerequisite: "—",
    description: "Você pode gastar uma ação padrão e 1 PM para forçar todas as criaturas a sua escolha em alcance curto a fazer um teste de Vontade (CD Car). Uma criatura que falhe fica abalada até o fim da cena. Uma criatura que passe se torna imune a esta habilidade até o fim do dia." },
  { id: "danca-das-laminas", name: "Dança das Lâminas", category: "classe", classId: "bardo", prerequisite: "Esgrima Mágica, 10º nível de bardo",
    description: "Quando você lança uma magia com execução de uma ação padrão, pode gastar 1 PM para fazer um ataque corpo a corpo como uma ação livre." },
  { id: "esgrima-magica", name: "Esgrima Mágica", category: "classe", classId: "bardo", prerequisite: "—",
    description: "Sua arte mescla esgrima e magia, transformando dança em golpes. Enquanto estiver sob efeito de Inspiração, você pode substituir testes de Luta por testes de Atuação, mas apenas se estiver empunhando armas leves ou de uma mão." },
  { id: "estrelato", name: "Estrelato", category: "classe", classId: "bardo", prerequisite: "6º nível de bardo",
    description: "Suas apresentações o tornaram famoso, fazendo com que você seja reconhecido e bem tratado por aqueles que apreciam a arte. Por outro lado, pode ser difícil passar despercebido, especialmente em grandes cidades. Quando usa Atuação para impressionar uma plateia, o bônus recebido em perícias baseadas em Carisma aumenta para +5." },
  { id: "fascinar", name: "Fascinar", category: "classe", classId: "bardo", prerequisite: "—",
    description: "Você pode gastar uma ação padrão e 1 PM para fascinar uma criatura a sua escolha em alcance curto. Faça um teste de Atuação oposto pelo teste de Vontade da criatura. Se você passar, ela fica fascinada enquanto você se concentrar (uma ação padrão por rodada). Se a criatura passar, fica imune a este efeito por um dia." },
  { id: "fascinar-em-massa", name: "Fascinar em Massa", category: "classe", classId: "bardo", prerequisite: "Fascinar",
    description: "Quando usa Fascinar, você pode gastar 2 PM extras. Se fizer isso, afeta todas as criaturas a sua escolha em alcance curto (você faz um único teste de Atuação, oposto pelo teste de Vontade de cada criatura)." },
  { id: "golpe-elemental", name: "Golpe Elemental", category: "classe", classId: "bardo", prerequisite: "Golpe Mágico", magic: true,
    description: "Enquanto estiver sob efeito de Inspiração, sempre que você acertar um ataque corpo a corpo, pode gastar 1 PM para causar 1d6 de dano adicional de ácido, eletricidade, fogo ou frio, a sua escolha. Para cada quatro níveis que possuir, pode gastar +1 PM para aumentar o dano em +1d6." },
  { id: "golpe-magico", name: "Golpe Mágico", category: "classe", classId: "bardo", prerequisite: "Esgrima Mágica", magic: true,
    description: "Enquanto estiver sob efeito de Inspiração, sempre que você acertar um ataque corpo a corpo em um inimigo, recebe 2 PM temporários. Você pode ganhar um máximo de PM temporários por cena igual ao seu nível. PM temporários desaparecem no final da cena." },
  { id: "inspiracao-marcial", name: "Inspiração Marcial", category: "classe", classId: "bardo", prerequisite: "—",
    description: "Quando você usa Inspiração, você e seus aliados aplicam o bônus recebido em rolagens de dano (além de testes de perícia)." },
  { id: "lendas-e-historias-bardo", name: "Lendas e Histórias", category: "classe", classId: "bardo", prerequisite: "Int 13",
    description: "Você possui um acervo mental de relatos, canções e folclore, sendo um arquivo vivo de assuntos gerais. Além de outros benefícios a critério do mestre, você pode gastar 1 PM para rolar novamente um teste recém realizado de Conhecimento, Misticismo, Nobreza ou Religião para informação, identificar criaturas ou identificar itens mágicos." },
  { id: "manipular", name: "Manipular", category: "classe", classId: "bardo", prerequisite: "Fascinar",
    description: "Você pode gastar 1 PM para forçar uma criatura que esteja fascinada a fazer um teste de Vontade (CD Car). Se a criatura falhar, sofre o efeito da magia Enfeitiçar até o fim da cena. Se passar, fica imune a esta habilidade por um dia. Usar esta habilidade não conta como uma ameaça à criatura fascinada." },
  { id: "manipular-em-massa", name: "Manipular em Massa", category: "classe", classId: "bardo", prerequisite: "Fascinar em Massa, Manipular, 10º nível de bardo",
    description: "Quando usa Manipular, você pode gastar 2 PM extras. Se fizer isso, afeta todas as criaturas a sua escolha em alcance curto." },
  { id: "melodia-curativa", name: "Melodia Curativa", category: "classe", classId: "bardo", prerequisite: "—",
    description: "Você pode gastar uma ação padrão e 1 PM para gerar um efeito curativo. Você e todos os seus aliados em alcance curto recuperam 1d6 PV. Para cada 2 PM extras que você gastar, cura +1d6 PV (ou seja, pode gastar 3 PM para recuperar 2d6 PV, 5 PM para recuperar 3d6 PV e assim por diante)." },
  { id: "melodia-restauradora", name: "Melodia Restauradora", category: "classe", classId: "bardo", prerequisite: "Melodia Curativa",
    description: "Quando você usa Melodia Curativa, pode gastar 2 PM extras. Se fizer isso, escolha uma das condições a seguir: abalado, apavorado, alquebrado, atordoado, cego, confuso, esmorecido, exausto, fatigado, frustrado ou surdo. Você remove a condição escolhida de quaisquer aliados a sua escolha afetados pela Melodia Curativa." },
  { id: "mestre-dos-sussurros", name: "Mestre dos Sussurros", category: "classe", classId: "bardo", prerequisite: "Car 13, treinado em Enganação e Investigação",
    description: "Você é dissimulado, atento para rumores e ótimo em espalhar fofocas. Quando faz um teste de Investigação para obter informação ou um teste de Enganação para intriga, você rola dois dados e usa o melhor resultado. Além disso, pode fazer esses testes em ambientes sociais (taverna, festival, corte...) sem custo e em apenas uma hora (em vez de um dia)." },
  { id: "parodia", name: "Paródia", category: "classe", classId: "bardo", prerequisite: "—",
    description: "Uma vez por rodada, quando vê alguém lançando uma magia em alcance médio, você pode pagar 1 PM e fazer um teste de Atuação (CD 15 + custo em PM da magia). Se passar, até o final de seu próximo turno você pode lançar essa magia." },
  { id: "prestidigitacao", name: "Prestidigitação", category: "classe", classId: "bardo", prerequisite: "—",
    description: "Quando faz uma ação padrão qualquer, você pode aproveitar seus gestos para lançar uma magia de ilusão. Faça um teste de Atuação (CD 15 + custo em PM da magia). Se passar, você lança a magia como uma ação livre. Outros personagens só percebem que você lançou uma magia se passarem num teste de Misticismo (CD 20). Se falhar, a magia não funciona, mas você gasta os PM mesmo assim." },
];

// ── Bucaneiro ─────────────────────────────────────────────────────────────────

export const BUCANEIRO_LEVELS: ClassLevelRow[] = [
  { level: 1, text: "Audácia, insolência" },
  { level: 2, text: "Evasão, poder de bucaneiro" },
  { level: 3, text: "Esquiva sagaz +1, poder de bucaneiro" },
  { level: 4, text: "Poder de bucaneiro" },
  { level: 5, text: "Panache, poder de bucaneiro" },
  { level: 6, text: "Poder de bucaneiro" },
  { level: 7, text: "Esquiva sagaz +2, poder de bucaneiro" },
  { level: 8, text: "Poder de bucaneiro" },
  { level: 9, text: "Poder de bucaneiro" },
  { level: 10, text: "Evasão aprimorada, poder de bucaneiro" },
  { level: 11, text: "Esquiva sagaz +3, poder de bucaneiro" },
  { level: 12, text: "Poder de bucaneiro" },
  { level: 13, text: "Poder de bucaneiro" },
  { level: 14, text: "Poder de bucaneiro" },
  { level: 15, text: "Esquiva sagaz +4, poder de bucaneiro" },
  { level: 16, text: "Poder de bucaneiro" },
  { level: 17, text: "Poder de bucaneiro" },
  { level: 18, text: "Poder de bucaneiro" },
  { level: 19, text: "Esquiva sagaz +5, poder de bucaneiro" },
  { level: 20, text: "Poder de bucaneiro, sorte de Nimb" },
];

export const BUCANEIRO_FEATURES: ClassFeature[] = [
  { name: "Evasão", level: 2, description: "A partir do 2º nível, quando sofre um ataque que permite um teste de Reflexos para reduzir o dano à metade, você não sofre dano algum se passar. Você ainda sofre dano normal se falhar no teste de Reflexos. Esta habilidade exige liberdade de movimentos; você não pode usá-la se estiver de armadura pesada ou na condição imóvel." },
  { name: "Esquiva Sagaz", level: 3, description: "No 3º nível, você recebe +1 na Defesa. Esse bônus aumenta em +1 a cada quatro níveis. Esta habilidade exige liberdade de movimentos; você não pode usá-la se estiver de armadura pesada ou na condição imóvel." },
  { name: "Panache", level: 5, description: "A partir do 5º nível, sempre que faz um acerto crítico em combate ou reduz um inimigo a 0 PV, você recupera 1 PM." },
  { name: "Evasão Aprimorada", level: 10, description: "A partir do 10º nível, quando sofre um ataque que permite um teste de Reflexos para reduzir o dano à metade, você não sofre dano algum se passar e sofre apenas metade do dano se falhar. Esta habilidade exige liberdade de movimentos; você não pode usá-la se estiver de armadura pesada ou na condição imóvel." },
  { name: "Sorte de Nimb", level: 20, description: "No 20º nível, você pode gastar 5 PM para rolar novamente um teste recém realizado. Qualquer resultado 11 ou mais na segunda rolagem será considerado um 20 natural." },
];

export const BUCANEIRO_POWERS: Power[] = [
  { id: "abusar-dos-fracos", name: "Abusar dos Fracos", category: "classe", classId: "bucaneiro", prerequisite: "Flagelo dos Mares",
    description: "Quando ataca uma criatura sob efeito de uma condição de medo, seu dano aumenta em um passo." },
  { id: "amigos-no-porto", name: "Amigos no Porto", category: "classe", classId: "bucaneiro", prerequisite: "Car 13, 6º nível de bucaneiro",
    description: "Quando chega em uma comunidade portuária, você pode gastar 2 PM para fazer um teste de Carisma (CD 10). Se passar, encontra um amigo para o qual pode pedir um favor (veja a perícia Diplomacia) ou que pode ajudá-lo como um aliado por uma cena." },
  { id: "aparar", name: "Aparar", category: "classe", classId: "bucaneiro", prerequisite: "Esgrimista",
    description: "Uma vez por rodada, quando é atingido por um ataque corpo a corpo, você pode gastar 1 PM para apará-lo. Faça um teste de ataque. Se o resultado do seu teste for maior que o do oponente, você evita o ataque. Você só pode usar este poder se estiver usando uma arma leve ou ágil." },
  { id: "apostador", name: "Apostador", category: "classe", classId: "bucaneiro", prerequisite: "Treinado em Jogatina",
    description: "Você pode gastar um dia para encontrar e participar de uma mesa de wyrt ou outro jogo de azar. Escolha um valor e faça um teste de Jogatina contra a CD correspondente: T$ 100 (CD 15), T$ 250 (CD 20), T$ 500 (CD 25), T$ 1.000 (CD 30), T$ 2.500 (CD 35) e assim por diante. Se passar, você ganha o valor escolhido (ou um item ou favor equivalente, a critério do mestre). Se falhar, você perde esse mesmo valor. A critério do mestre, o lugar onde você está pode impossibilitar o uso deste poder ou limitá-lo a uma vez por semana ou mês." },
  { id: "ataque-acrobatico", name: "Ataque Acrobático", category: "classe", classId: "bucaneiro", prerequisite: "—",
    description: "Quando se aproxima de um inimigo com uma pirueta ou pulo (em termos de jogo, usando Acrobacia ou Atletismo para se mover) e o ataca no mesmo turno, você recebe +2 em seu teste de ataque e na rolagem de dano." },
  { id: "aventureiro-avido", name: "Aventureiro Ávido", category: "classe", classId: "bucaneiro", prerequisite: "—",
    description: "Uma vez por rodada, você pode gastar 5 PM para realizar uma ação padrão ou de movimento adicional. Se possuir o poder Surto Heroico, em vez disso seu custo diminui em –2 PM." },
  { id: "bravata-audaz", name: "Bravata Audaz", category: "classe", classId: "bucaneiro", prerequisite: "—",
    description: "Você jura fazer uma façanha específica, como roubar o tesouro de Sckhar ou ganhar um beijo do príncipe e da princesa até o fim do baile (uma Bravata deve envolver um desafio real, com ND igual ou maior que o seu nível; falhar ou desistir faz perder todos os PM até o próximo dia). Se cumprir a bravata, seu limite máximo de PM aumenta em +2d6 até o fim da aventura." },
  { id: "bravata-imprudente", name: "Bravata Imprudente", category: "classe", classId: "bucaneiro", prerequisite: "—",
    description: "Na primeira rodada de um combate, você pode jurar derrotar seus inimigos com uma restrição a sua escolha, como lutar com uma mão nas costas, de guarda aberta (desprevenido), de olhos vendados (cego) etc. — o mestre tem a palavra final sobre a validade da restrição. Você sofre a penalidade durante todo o combate, mas, se vencer, recebe +2 nos testes de ataque e na margem de ameaça até o fim da aventura." },
  { id: "en-garde", name: "En Garde", category: "classe", classId: "bucaneiro", prerequisite: "Esgrimista",
    description: "Você pode gastar uma ação de movimento e 1 PM para assumir postura de luta. Até o fim da cena, se estiver usando uma arma leve ou ágil, você recebe +2 na Defesa e na margem de ameaça." },
  { id: "esgrimista", name: "Esgrimista", category: "classe", classId: "bucaneiro", prerequisite: "Int 13",
    description: "Quando usa uma arma leve ou ágil, você soma seu bônus de Inteligência nas rolagens de dano (limitado pelo seu nível)." },
  { id: "flagelo-dos-mares", name: "Flagelo dos Mares", category: "classe", classId: "bucaneiro", prerequisite: "Treinado em Intimidação",
    description: "Você aprende e pode lançar Amedrontar (atributo-chave Carisma). Esta não é uma habilidade mágica e provém de sua capacidade de incutir medo em seus inimigos." },
  { id: "foliao", name: "Folião", category: "classe", classId: "bucaneiro", prerequisite: "Car 13",
    description: "Você tem facilidade em criar amizades durante festas, de noitadas em tavernas a bailes na corte. O mestre define exatamente o que você pode fazer com este poder. Como regra geral, a atitude de todas as pessoas em relação a você durante uma festa melhora em uma categoria." },
  { id: "grudar-o-cano", name: "Grudar o Cano", category: "classe", classId: "bucaneiro", prerequisite: "Treinado em Luta, Pistoleiro",
    description: "Quando faz um ataque à distância com uma arma de fogo contra um oponente adjacente, você não sofre a penalidade de –5 no teste de ataque e aumenta seu dano em um passo." },
  { id: "pernas-do-mar", name: "Pernas do Mar", category: "classe", classId: "bucaneiro", prerequisite: "—",
    description: "Você está acostumado à superfície oscilante do convés. Você recebe +2 em Acrobacia e Atletismo e não fica desprevenido quando está se equilibrando ou escalando." },
  { id: "pistoleiro", name: "Pistoleiro", category: "classe", classId: "bucaneiro", prerequisite: "—",
    description: "Você recebe proficiência com armas de fogo e +2 nas rolagens de dano com essas armas." },
  { id: "presenca-paralisante", name: "Presença Paralisante", category: "classe", classId: "bucaneiro", prerequisite: "Car 13",
    description: "Você soma seu bônus de Carisma em Iniciativa." },
  { id: "ripostar", name: "Ripostar", category: "classe", classId: "bucaneiro", prerequisite: "Aparar, 12º nível de bucaneiro",
    description: "Quando usa a habilidade aparar e evita o ataque, você pode gastar 1 PM. Se fizer isso, pode fazer um ataque corpo a corpo imediato contra o inimigo que o atacou (se ele estiver em alcance)." },
  { id: "touche", name: "Touché", category: "classe", classId: "bucaneiro", prerequisite: "Esgrimista, 10º nível de bucaneiro",
    description: "Quando se aproxima de um inimigo e o ataca com uma arma leve ou ágil no mesmo turno, você pode gastar 2 PM para aumentar seu dano em um passo e receber +5 na margem de ameaça." },
];

// ── Caçador ───────────────────────────────────────────────────────────────────

export const CACADOR_LEVELS: ClassLevelRow[] = [
  { level: 1, text: "Marca da presa +1d4, rastreador" },
  { level: 2, text: "Poder de caçador" },
  { level: 3, text: "Explorador, poder de caçador" },
  { level: 4, text: "Poder de caçador" },
  { level: 5, text: "Caminho do explorador, marca da presa +1d8, poder de caçador" },
  { level: 6, text: "Poder de caçador" },
  { level: 7, text: "Explorador, poder de caçador" },
  { level: 8, text: "Poder de caçador" },
  { level: 9, text: "Marca da presa +1d12, poder de caçador" },
  { level: 10, text: "Poder de caçador" },
  { level: 11, text: "Explorador, poder de caçador" },
  { level: 12, text: "Poder de caçador" },
  { level: 13, text: "Marca da presa +2d8, poder de caçador" },
  { level: 14, text: "Poder de caçador" },
  { level: 15, text: "Explorador, poder de caçador" },
  { level: 16, text: "Poder de caçador" },
  { level: 17, text: "Marca da presa +2d10, poder de caçador" },
  { level: 18, text: "Poder de caçador" },
  { level: 19, text: "Explorador, poder de caçador" },
  { level: 20, text: "Mestre caçador, poder de caçador" },
];

export const CACADOR_FEATURES: ClassFeature[] = [
  { name: "Explorador", level: 3, description: "Escolha um tipo de terreno entre aquático, ártico, colina, deserto, floresta, montanha, pântano, planície, subterrâneo ou urbano (a partir do 11º nível, também área de Tormenta). Quando estiver no tipo de terreno escolhido, você soma seu bônus de Sabedoria (mínimo +1) na Defesa e nos testes de Acrobacia, Atletismo, Furtividade, Percepção e Sobrevivência. A cada quatro níveis, escolha outro tipo de terreno para receber o bônus ou aumente o bônus em um tipo já escolhido em +2." },
  { name: "Caminho do Explorador", level: 5, description: "No 5º nível, você pode atravessar terrenos difíceis sem sofrer redução em seu deslocamento e a CD para rastrear você aumenta em +10. Esta habilidade só funciona em terrenos nos quais você tenha a habilidade Explorador." },
  { name: "Mestre Caçador", level: 20, description: "No 20º nível, você pode usar a habilidade Marca da Presa como uma ação livre. Além disso, quando usa a habilidade, pode gastar +5 PM para aumentar sua margem de ameaça contra a criatura em +2. Se você reduz uma criatura contra a qual usou Marca da Presa a 0 pontos de vida, recupera 5 PM." },
];

export const CACADOR_POWERS: Power[] = [
  { id: "ambidestria", name: "Ambidestria", category: "classe", classId: "cacador", prerequisite: "Des 15",
    description: "Se estiver usando duas armas (e pelo menos uma delas for leve) e fizer a ação atacar, você pode fazer dois ataques, um com cada arma. Se fizer isso, sofre –2 em todos os testes de ataque até o seu próximo turno." },
  { id: "armadilha-arataca", name: "Armadilha: Arataca", category: "classe", classId: "cacador", prerequisite: "—",
    description: "A vítima sofre 2d6 pontos de dano de perfuração e fica agarrada. Uma criatura agarrada pode escapar com uma ação padrão e um teste de Acrobacia ou Atletismo (CD Sab). (Regras de Armadilha: preparar gasta uma ação completa e 3 PM; afeta uma área de 3m de lado adjacente a você, acionada pela primeira criatura que entrar nela.)" },
  { id: "armadilha-espinhos", name: "Armadilha: Espinhos", category: "classe", classId: "cacador", prerequisite: "—",
    description: "A vítima sofre 6d6 pontos de dano de perfuração. Um teste de Reflexos (CD Sab) reduz o dano à metade." },
  { id: "armadilha-laco", name: "Armadilha: Laço", category: "classe", classId: "cacador", prerequisite: "—",
    description: "A vítima deve fazer um teste de Reflexos (CD Sab). Se passar, fica caída. Se falhar, fica agarrada. Uma criatura agarrada pode se soltar com uma ação padrão e um teste de Força ou Acrobacia (CD Sab)." },
  { id: "armadilha-rede", name: "Armadilha: Rede", category: "classe", classId: "cacador", prerequisite: "—",
    description: "Todas as criaturas na área devem fazer um teste de Reflexos (CD Sab) para não ficarem enredadas. Uma vítima pode se libertar com uma ação padrão e um teste de Acrobacia ou Atletismo (CD 25). Além disso, a área ocupada pela rede é considerada terreno difícil." },
  { id: "arqueiro", name: "Arqueiro", category: "classe", classId: "cacador", prerequisite: "Sab 13",
    description: "Se estiver usando uma arma de ataque à distância, você soma seu bônus de Sabedoria nas rolagens de dano (limitado pelo seu nível)." },
  { id: "bote", name: "Bote", category: "classe", classId: "cacador", prerequisite: "Ambidestria, 6º nível de caçador",
    description: "Se estiver empunhando duas armas e fizer uma investida, você pode pagar 1 PM para fazer um ataque adicional com sua arma secundária." },
  { id: "camuflagem", name: "Camuflagem", category: "classe", classId: "cacador", prerequisite: "6º nível de caçador",
    description: "Você pode gastar 2 PM para usar a perícia Furtividade para se esconder mesmo sem cobertura disponível." },
  { id: "chuva-de-laminas", name: "Chuva de Lâminas", category: "classe", classId: "cacador", prerequisite: "Des 19, Ambidestria, 12º nível de caçador",
    description: "Quando usa Ambidestria, você pode pagar 2 PM para fazer um ataque adicional com sua arma primária." },
  { id: "companheiro-animal", name: "Companheiro Animal", category: "classe", classId: "cacador", prerequisite: "Treinado em Adestramento",
    description: "Você recebe um companheiro animal (veja o quadro na página 62 do livro)." },
  { id: "elo-com-a-natureza", name: "Elo com a Natureza", category: "classe", classId: "cacador", prerequisite: "Sab 13, 3º nível de caçador",
    description: "Você soma seu bônus de Sabedoria em seu total de pontos de mana e aprende e pode lançar Caminhos da Natureza (atributo-chave Sabedoria)." },
  { id: "emboscar", name: "Emboscar", category: "classe", classId: "cacador", prerequisite: "Treinado em Furtividade",
    description: "Você pode gastar 2 PM para realizar uma ação padrão adicional em seu turno. Você só pode usar este poder na primeira rodada de um combate." },
  { id: "empatia-selvagem-cacador", name: "Empatia Selvagem", category: "classe", classId: "cacador", prerequisite: "—",
    description: "Você pode se comunicar com animais por meio de linguagem corporal e vocalizações. Você pode usar Adestramento com animais para mudar atitude e pedir favores (veja Diplomacia)." },
  { id: "escaramuca", name: "Escaramuça", category: "classe", classId: "cacador", prerequisite: "Des 15, 6º nível de caçador",
    description: "Quando se move 6m ou mais, você recebe +2 em Defesa e Reflexos e +1d8 nas rolagens de dano de ataques corpo a corpo e à distância em alcance curto até o início de seu próximo turno. Você não pode usar esta habilidade se estiver vestindo armadura pesada." },
  { id: "escaramuca-superior", name: "Escaramuça Superior", category: "classe", classId: "cacador", prerequisite: "Escaramuça, 12º nível de caçador",
    description: "Quando usa Escaramuça, seus bônus aumentam para +5 em Defesa e Reflexos e +1d12 em rolagens de dano." },
  { id: "espreitar", name: "Espreitar", category: "classe", classId: "cacador", prerequisite: "—",
    description: "Quando usa a habilidade Marca da Presa, você recebe um bônus de +1 em testes de perícia contra a criatura marcada. Esse bônus aumenta em +1 para cada PM adicional gasto na habilidade e também dobra com a habilidade Inimigo." },
  { id: "ervas-curativas", name: "Ervas Curativas", category: "classe", classId: "cacador", prerequisite: "—",
    description: "Você pode gastar uma ação completa e uma quantidade de PM a sua escolha (limitado pelo seu bônus de Sabedoria) para aplicar ervas que curam ou desintoxicam em você ou num aliado adjacente. Para cada PM que gastar, cura 2d6 PV ou remove uma condição envenenado afetando o alvo." },
  { id: "impeto-cacador", name: "Ímpeto", category: "classe", classId: "cacador", prerequisite: "—",
    description: "Você pode gastar 1 PM para aumentar seu deslocamento em +6m por uma rodada." },
  { id: "inimigo-de-criatura", name: "Inimigo de (Criatura)", category: "classe", classId: "cacador", prerequisite: "—",
    description: "Escolha um tipo de criatura entre animal, construto, espírito, monstro ou morto-vivo, ou duas raças humanoides (por exemplo, orcs e gnolls, ou elfos e qareen). Quando você usa a habilidade Marca da Presa contra uma criatura do tipo ou da raça escolhida, dobra os dados de bônus no dano. O nome desta habilidade varia de acordo com o tipo de criatura escolhida (Inimigo de Monstros, Inimigo de Mortos-Vivos etc.). Você pode escolher este poder outras vezes para inimigos diferentes." },
  { id: "olho-do-falcao", name: "Olho do Falcão", category: "classe", classId: "cacador", prerequisite: "—",
    description: "Você pode usar a habilidade Marca da Presa em criaturas em alcance longo." },
  { id: "ponto-fraco", name: "Ponto Fraco", category: "classe", classId: "cacador", prerequisite: "—",
    description: "Quando usa a habilidade Marca da Presa, seus ataques contra a criatura marcada recebem +2 na margem de ameaça. Esse bônus dobra com a habilidade Inimigo." },
];
