// Star Wars: Além da Fronteira — os 28 planetas de origem, cada um com uma Habilidade Natal (+5 em perícias)

export interface Planet {
  id: string;
  name: string;
  description: string;
  naturalAbility: { name: string; description: string; skills: string[] };
}

export const PLANETS: Planet[] = [
  { id: "coruscant", name: "Coruscant", description: "Capital galática coberta de ponta a ponta por uma única cidade-planeta: arranha-céus se perdem entre nuvens de tráfego aéreo, enquanto os níveis inferiores escondem um submundo que nunca vê a luz do sol. Centro do poder político, financeiro e cultural de toda a galáxia.", naturalAbility: { name: "Cidadão da Capital", description: "+5 em Diplomacia ou Conhecimento Galáctico ao lidar com instituições e governos.", skills: ["diplomacia", "conhecimento_galactico"] } },
  { id: "alderaan", name: "Alderaan", description: "Mundo verdejante de montanhas nevadas, lagos cristalinos e cidades sem armas, erguido sobre séculos de tradição pacifista e educação refinada. Berço de diplomatas e artistas, é lembrado como símbolo de elegância e resistência não violenta.", naturalAbility: { name: "Diplomata Nato", description: "+5 em Diplomacia e Persuasão durante negociações pacíficas.", skills: ["diplomacia", "persuasao"] } },
  { id: "corellia", name: "Corellia", description: "Planeta industrial de céus cortados por estaleiros orbitais e cidades erguidas ao redor de fábricas navais, onde as ruas respiram velocidade e engenhoca. Terra natal de contrabandistas lendários e de alguns dos melhores pilotos da galáxia.", naturalAbility: { name: "Sangue Corelliano", description: "+5 em Pilotagem Espacial e Mecânica envolvendo naves.", skills: ["pilotagem_espacial", "mecanica"] } },
  { id: "chandrila", name: "Chandrila", description: "Planícies douradas e colinas suaves cercam cidades-jardim de arquitetura elegante, onde políticos e acadêmicos debatem o destino da galáxia sob céus claros. Tradição de governo justo atravessa gerações.", naturalAbility: { name: "Influência Política", description: "+5 em Diplomacia e Persuasão com autoridades e oficiais.", skills: ["diplomacia", "persuasao"] } },
  { id: "anaxes", name: "Anaxes", description: "Mundo-fortaleza dominado por estaleiros militares, bases de treinamento e frotas ancoradas em órbita; o horizonte é recortado por torres de comando e hangares blindados. Disciplina militar define cada cidade.", naturalAbility: { name: "Treinamento Militar", description: "+5 em Liderança durante combate ou comando de tropas.", skills: ["lideranca"] } },
  { id: "naboo", name: "Naboo", description: "Planeta de lagos espelhados, cidades submersas dos Gungans e cúpulas de mármore que brilham ao pôr do sol, com vastos oceanos subterrâneos povoados por criaturas gigantescas. Equilíbrio raro entre natureza intocada e tecnologia refinada.", naturalAbility: { name: "Elegância Naboo", description: "+5 em Persuasão e Diplomacia com educação e protocolo.", skills: ["persuasao", "diplomacia"] } },
  { id: "cato_neimoidia", name: "Cato Neimoidia", description: "Cidades-ponte suspensas entre penhascos rochosos, conectadas por arcos monumentais que sustentam palácios e mercados neimoidianos. Riqueza ostensiva e comércio agressivo movem cada canto do planeta.", naturalAbility: { name: "Instinto Comercial", description: "+5 em Diplomacia e Persuasão em compras, vendas e acordos.", skills: ["diplomacia", "persuasao"] } },
  { id: "rendili", name: "Rendili", description: "Céus riscados por estruturas de estaleiros orbitais gigantescos, onde cruzadores da República são erguidos peça por peça. Cidades funcionais crescem à sombra das docas navais, vivendo do ritmo da indústria bélica.", naturalAbility: { name: "Engenharia Naval", description: "+5 em Mecânica e Computação em grandes naves espaciais.", skills: ["mecanica", "computacao"] } },
  { id: "bothawui", name: "Bothawui", description: "Mundo de savanas douradas e cidades discretas, onde cada conversa pode esconder um segredo; os Bothans cultivam redes de informação que alcançam toda a galáxia. Aparência tranquila esconde uma das maiores potências de espionagem conhecidas.", naturalAbility: { name: "Rede de Informações", description: "+5 em Investigação e Enganação ao obter ou esconder informações.", skills: ["investigacao", "enganacao"] } },
  { id: "kashyyyk", name: "Kashyyyk", description: "Floresta vertical de árvores wroshyr que se erguem centenas de metros, com cidades wookiees construídas entre os galhos e ligadas por pontes suspensas. Abaixo da copa, sombras escondem predadores lendários que testam até os mais fortes.", naturalAbility: { name: "Filho da Selva", description: "+5 em Sobrevivência e Percepção em ambientes naturais.", skills: ["sobrevivencia", "percepcao"] } },
  { id: "dantooine", name: "Dantooine", description: "Planícies onduladas cobertas de campos cultivados e antigas ruínas de pedra, onde o vento carrega o silêncio de um templo Jedi esquecido. Vida simples de fazendeiros convive com ecos de uma história mais profunda.", naturalAbility: { name: "Mente Serena", description: "+5 em Percepção e Conhecimento da Força em reflexão ou meditação.", skills: ["percepcao", "conhecimento_forca"] } },
  { id: "ithor", name: "Ithor", description: "Mundo-jardim de florestas primitivas e \"cidades-hastes\" suspensas no ar para não perturbar o solo sagrado; os Ithorianos vivem em harmonia quase religiosa com cada criatura e planta. Um dos ecossistemas mais preservados da galáxia.", naturalAbility: { name: "Guardião da Natureza", description: "+5 em Ciências e Sobrevivência envolvendo fauna e flora.", skills: ["ciencias", "sobrevivencia"] } },
  { id: "malastare", name: "Malastare", description: "Planeta vulcânico de gases tóxicos e pântanos de metano, onde cidades se erguem sobre plataformas elevadas acima da atmosfera pesada. Pistas de corrida cortam a paisagem, e o rugido dos pods ecoa constantemente.", naturalAbility: { name: "Piloto Competitivo", description: "+5 em Pilotagem Atmosférica em corridas e manobras de alta velocidade.", skills: ["pilotagem_atmosferica"] } },
  { id: "tatooine", name: "Tatooine", description: "Dois sóis castigam dunas intermináveis e rochedos escaldantes, onde cidades de barro se agarram à sobrevivência entre contrabandistas, caçadores de recompensa e o domínio dos Hutts. Pouca lei existe além da força e da sorte.", naturalAbility: { name: "Sobrevivente do Deserto", description: "+5 em Sobrevivência e Atletismo em ambientes hostis.", skills: ["sobrevivencia", "atletismo"] } },
  { id: "mandalore", name: "Mandalore", description: "Planeta outrora verdejante, hoje marcado por crateras de guerra e cidades-domo reconstruídas sobre as cinzas de conflitos antigos. Tradição guerreira e código de honra moldam cada clã que reivindica o nome mandaloriano.", naturalAbility: { name: "Espírito Guerreiro", description: "+5 em Armas de Energia e Intimidação durante combates.", skills: ["armas_energia", "intimidacao"] } },
  { id: "mon_cala", name: "Mon Cala", description: "Oceano infinito pontilhado por cidades submersas de coral bioluminescente, onde Mon Calamari e Quarren dividem as profundezas em relativa harmonia. Estaleiros submarinos produzem algumas das naves mais elegantes da galáxia.", naturalAbility: { name: "Mestre das Naves", description: "+5 em Pilotagem Espacial e Mecânica em espaçonaves.", skills: ["pilotagem_espacial", "mecanica"] } },
  { id: "ryloth", name: "Ryloth", description: "Mundo árido de penhascos e cavernas profundas, onde cidades Twi'lek se escondem da luz solar escaldante em vales sombreados. História marcada por escravidão e resistência forjou um povo adaptável e resiliente.", naturalAbility: { name: "Resiliência", description: "+5 em Atletismo e Sobrevivência para resistir a ambientes extremos.", skills: ["atletismo", "sobrevivencia"] } },
  { id: "rodia", name: "Rodia", description: "Selvas densas e pântanos venenosos cobrem a maior parte da superfície, cruzados por cidades-colmeia erguidas em espiral. Caçar é tradição e sobrevivência ao mesmo tempo, moldando rodianos desde a infância.", naturalAbility: { name: "Instinto de Caçador", description: "+5 em Percepção e Investigação durante rastreamentos.", skills: ["percepcao", "investigacao"] } },
  { id: "geonosis", name: "Geonosis", description: "Planeta desértico avermelhado, perfurado por colmeias subterrâneas onde geonosianos zumbem entre linhas de montagem industriais. Fábricas gigantescas produzem armamento em escala quase incompreensível.", naturalAbility: { name: "Engenheiro Industrial", description: "+5 em Computação e Mecânica para construir ou reparar máquinas.", skills: ["computacao", "mecanica"] } },
  { id: "felucia", name: "Felucia", description: "Selva psicodélica de fungos gigantes e plantas bioluminescentes em tons impossíveis, onde cada passo pode revelar uma criatura nova e perigosa. A vida prolifera de forma quase agressiva, hostil a quem não conhece o terreno.", naturalAbility: { name: "Adaptação Selvagem", description: "+5 em Sobrevivência e Ciências em ambientes alienígenas.", skills: ["sobrevivencia", "ciencias"] } },
  { id: "christophsis", name: "Christophsis", description: "Superfície coberta por formações de cristal que refletem luz em cores vivas, tornando cada cidade um espetáculo visual e um campo de batalha estratégico. Riqueza mineral tornou o planeta alvo recorrente de conflitos armados.", naturalAbility: { name: "Veterano de Guerra", description: "+5 em Liderança e Intimidação em confrontos militares.", skills: ["lideranca", "intimidacao"] } },
  { id: "ord_mantell", name: "Ord Mantell", description: "Cidades de sucata e mercados improvisados se espalham entre destroços de naves abandonadas, atraindo mercenários, sucateiros e negociantes de todo tipo. Pouco é desperdiçado — e quase tudo tem um preço.", naturalAbility: { name: "Improvisador", description: "+5 em Computação e Mecânica usando recursos limitados.", skills: ["computacao", "mecanica"] } },
  { id: "lothal", name: "Lothal", description: "Planícies douradas cortadas por rios e formações rochosas altas, onde fazendas simples convivem com bases industriais crescentes. Vida selvagem abundante e céus abertos tornam o mundo um refúgio para quem busca recomeçar.", naturalAbility: { name: "Espírito Explorador", description: "+5 em Percepção e Investigação ao explorar novos locais.", skills: ["percepcao", "investigacao"] } },
  { id: "jedha", name: "Jedha", description: "Luas gêmeas iluminam um deserto sagrado de templos antigos e cidades de pedra escavadas na rocha, onde peregrinos de dezenas de tradições ligadas à Força ainda se reúnem. O ar carrega um peso espiritual quase palpável.", naturalAbility: { name: "Eco da Força", description: "+5 em Conhecimento da Força e Percepção relacionados à Força.", skills: ["conhecimento_forca", "percepcao"] } },
  { id: "ilum", name: "Ilum", description: "Planeta gelado coberto por glaciares e cavernas de cristal, onde o silêncio é cortado apenas pelo eco de ventos gelados. Cristais kyber brutos nascem nas profundezas do gelo, atraindo quem busca uma conexão mais profunda com a Força.", naturalAbility: { name: "Sintonia Kyber", description: "+5 em Conhecimento da Força e Domínio da Força envolvendo cristais kyber.", skills: ["conhecimento_forca", "dominio_forca"] } },
  { id: "onderon", name: "Onderon", description: "Florestas densas cercam cidades fortificadas erguidas em platôs rochosos, protegidas por muralhas contra as bestas selvagens que vagam pela selva abaixo. Tradição guerreira e orgulho cívico definem seu povo.", naturalAbility: { name: "Guerreiro Nato", description: "+5 em Atletismo e Intimidação em confrontos físicos.", skills: ["atletismo", "intimidacao"] } },
  { id: "dxun", name: "Dxun", description: "Lua selvagem coberta por selva impenetrável e ruínas Sith esquecidas sob a vegetação, onde predadores gigantes dominam a cadeia alimentar. Poucos se aventuram além das margens sem pagar um preço alto.", naturalAbility: { name: "Predador", description: "+5 em Furtividade e Sobrevivência em caçadas.", skills: ["furtividade", "sobrevivencia"] } },
  { id: "ossus", name: "Ossus", description: "Ruínas de uma antiga civilização Jedi se espalham por florestas silenciosas e bibliotecas soterradas, guardando conhecimento perdido sob camadas de poeira e tempo. Estudiosos ainda vasculham o solo em busca de fragmentos de sabedoria esquecida.", naturalAbility: { name: "Erudito Jedi", description: "+5 em Conhecimento Galáctico e Conhecimento da Força ao estudar ruínas.", skills: ["conhecimento_galactico", "conhecimento_forca"] } },
];

export const PLANET_BY_ID: Record<string, Planet> = Object.fromEntries(
  PLANETS.map((p) => [p.id, p])
);
