// ─── TORMENTA 20 — Origens (Tabela 1-18) ─────────────────────────────────────
// Regra simplificada (o próprio livro sugere, pág. 84: "se preferir regras mais
// rápidas, escolha apenas perícias"): cada origem concede um item inicial e um
// número fixo de perícias treinadas, escolhidas dentro do conjunto listado.
// O poder único da origem é mostrado como referência na ficha, mas não é
// obrigatório escolher — mantém o padrão enxuto usado no Guia do Mestre.

export interface Origin {
  id: string;
  name: string;
  skillPool: string[]; // ids de perícia (Tabela 1-18)
  chooseCount: number;  // quantas perícias do pool são treinadas
  powerName: string;
  powerDesc: string;
  items: string;
  description: string;
}

export const ORIGINS: Origin[] = [
  { id: "acolito", name: "Acólito", skillPool: ["cura", "religiao", "vontade"], chooseCount: 2,
    powerName: "Membro da Igreja", powerDesc: "Você consegue hospedagem e informação em qualquer templo de sua divindade, para você e seus aliados.",
    items: "Símbolo sagrado, traje de sacerdote.",
    description: "Ingressou cedo em uma ordem religiosa, por fé, tradição familiar ou acolhimento." },
  { id: "amigo-dos-animais", name: "Amigo dos Animais", skillPool: ["adestramento", "cavalgar"], chooseCount: 2,
    powerName: "Amigo Especial", powerDesc: "Você recebe +5 em testes de Adestramento com animais comuns. Além disso, possui um animal de estimação que o auxilia e fornece +2 em uma perícia a sua escolha (exceto Luta ou Pontaria), sem contar em seu limite de aliados.",
    items: "Cão de guarda, cavalo, pônei ou trobo (escolha um).",
    description: "Cavalariço, criador de gado, ginete ou apenas alguém com facilidade natural para lidar com animais." },
  { id: "amnesico", name: "Amnésico", skillPool: ["acrobacia","adestramento","atletismo","atuacao","cavalgar","conhecimento","cura","diplomacia","enganacao","fortitude","furtividade","guerra","iniciativa","intimidacao","intuicao","investigacao","jogatina","ladinagem","luta","misticismo","nobreza","oficio","percepcao","pilotagem","pontaria","reflexos","religiao","sobrevivencia","vontade"], chooseCount: 1,
    powerName: "Lembranças Graduais", powerDesc: "Durante suas aventuras, em determinados momentos a critério do mestre, você pode fazer um teste de Sabedoria (CD 10) para reconhecer pessoas, criaturas ou lugares que tenha encontrado antes de perder a memória.",
    items: "Um ou mais itens somando até T$ 100, possivelmente pistas da sua vida antiga.",
    description: "Perdeu a maior parte da memória; só seus companheiros atuais são a família que conhece." },
  { id: "aristocrata", name: "Aristocrata", skillPool: ["diplomacia", "enganacao", "nobreza"], chooseCount: 2,
    powerName: "Sangue Azul", powerDesc: "Você tem alguma influência política, suficiente para ser tratado com mais leniência pela guarda, conseguir uma audiência com o nobre local etc.",
    items: "Joia de família (T$ 100), traje da corte.",
    description: "Nasceu na nobreza, com educação sofisticada em política, academia ou cavalaria." },
  { id: "artesao", name: "Artesão", skillPool: ["oficio", "vontade"], chooseCount: 2,
    powerName: "Frutos do Trabalho", powerDesc: "Quando passa em um teste de Ofício para sustento, você recebe o dobro do dinheiro.",
    items: "Kit de ofício (qualquer), um item que possa fabricar de até T$ 50.",
    description: "Treinado por família, mestre, escola ou guilda para fabricar itens importantes." },
  { id: "artista", name: "Artista", skillPool: ["atuacao", "enganacao"], chooseCount: 2,
    powerName: "Dom Artístico", powerDesc: "Quando usa a perícia Atuação para fazer uma apresentação e passa no teste, você ganha o dobro de tibares.",
    items: "Kit de disfarces ou instrumento musical.",
    description: "Possui talento nato (ou muito treino) para música, dança ou atuação." },
  { id: "assistente-laboratorio", name: "Assistente de Laboratório", skillPool: ["oficio", "misticismo"], chooseCount: 2,
    powerName: "Esse Cheiro...", powerDesc: "Você recebe +2 em Fortitude e passa automaticamente em testes de Ofício (alquimia) para identificar itens alquímicos.",
    items: "Kit de Ofício (alquimia).",
    description: "Ex-ajudante de alquimista, inventor ou mago, exposto a substâncias e experimentos perigosos." },
  { id: "batedor", name: "Batedor", skillPool: ["furtividade", "percepcao", "sobrevivencia"], chooseCount: 2,
    powerName: "À Prova de Tudo", powerDesc: "Você não sofre penalidade em deslocamento e Sobrevivência por clima ruim e por terreno difícil natural.",
    items: "Barraca, uma arma simples ou marcial de ataque à distância.",
    description: "Guia experiente de caravanas, exploradores ou caçadores de recompensas." },
  { id: "capanga", name: "Capanga", skillPool: ["luta", "intimidacao"], chooseCount: 2,
    powerName: "Confissão", powerDesc: "Você pode usar Intimidação para obter informação sem custo (como a perícia Investigação).",
    items: "Tatuagem ou adereço de gangue (+2 em Intimidação), uma arma simples corpo a corpo.",
    description: "Ex-\"músculo\" de bandido ou quadrilha, grande, forte ou mal-encarado." },
  { id: "charlatao", name: "Charlatão", skillPool: ["enganacao", "jogatina"], chooseCount: 2,
    powerName: "Alpinista Social", powerDesc: "Você pode substituir testes de Diplomacia por testes de Enganação.",
    items: "Joia falsificada (aparência de T$ 100, sem valor real), kit de disfarces.",
    description: "Trapaceiro nato que resolve problemas através da conversa, sincera ou não." },
  { id: "circense", name: "Circense", skillPool: ["acrobacia", "atuacao", "reflexos"], chooseCount: 2,
    powerName: "Truque de Mágica", powerDesc: "Você pode lançar Explosão de Chamas, Hipnotismo e Transmutar Objetos, mas apenas com o aprimoramento Truque. Esta não é uma habilidade mágica — os efeitos provêm de prestidigitação.",
    items: "Traje de artista, três bolas coloridas para malabarismo, um baralho.",
    description: "Artista circense treinado em acrobacia, malabarismo ou mágica de palco." },
  { id: "criminoso", name: "Criminoso", skillPool: ["enganacao", "furtividade", "ladinagem"], chooseCount: 2,
    powerName: "Punguista", powerDesc: "Você pode fazer testes de Ladinagem para sustento, como a perícia Ofício.",
    items: "Kit de ladrão ou kit de disfarces.",
    description: "Ex-bandido de rua, batedor de carteiras ou membro de guilda de ladrões." },
  { id: "curandeiro", name: "Curandeiro", skillPool: ["cura", "vontade"], chooseCount: 2,
    powerName: "Médico de Campo", powerDesc: "Quando você faz primeiros socorros em um personagem com 0 ou menos PV, ele recupera 1d6 PV.",
    items: "Bálsamo restaurador, kit de medicamentos.",
    description: "Treinado em cura por remédios e tratamentos naturais, sem magia." },
  { id: "eremita", name: "Eremita", skillPool: ["misticismo", "religiao", "sobrevivencia"], chooseCount: 2,
    powerName: "Busca Interior", powerDesc: "Quando você e seus companheiros estão diante de um mistério, incapazes de prosseguir, você pode gastar 1 PM para meditar sozinho e receber uma dica do mestre.",
    items: "Barraca, kit de medicamentos.",
    description: "Viveu isolado da sociedade, por exílio, busca espiritual ou clausura monástica." },
  { id: "escravo", name: "Escravo", skillPool: ["atletismo", "fortitude", "furtividade"], chooseCount: 2,
    powerName: "Desejo de Liberdade", powerDesc: "Ninguém voltará a torná-lo um escravo! Você recebe +5 em testes contra efeitos que possam aprisioná-lo, como a manobra agarrar ou a magia Imobilizar.",
    items: "Algemas, uma ferramenta pesada (estatísticas de maça).",
    description: "Ex-escravo, nascido em cativeiro ou capturado, agora liberto ou fugitivo." },
  { id: "estudioso", name: "Estudioso", skillPool: ["conhecimento", "guerra", "misticismo"], chooseCount: 2,
    powerName: "Palpite Fundamentado", powerDesc: "Você pode gastar 2 PM para substituir um teste de qualquer perícia originalmente baseada em Inteligência ou Sabedoria por um teste de Conhecimento.",
    items: "Um livro aprimorado (+2 em Conhecimento, Guerra ou Misticismo), outros três livros comuns.",
    description: "Passou anos estudando livros e pergaminhos em algum campo do conhecimento." },
  { id: "fazendeiro", name: "Fazendeiro", skillPool: ["adestramento", "cavalgar", "oficio", "sobrevivencia"], chooseCount: 2,
    powerName: "Água no Feijão", powerDesc: "Você gasta apenas metade da matéria-prima para testes de Ofício (cozinheiro).",
    items: "Uma ferramenta agrícola (estatísticas de lança), 10 rações de viagem, um animal não combativo.",
    description: "Trabalhou a terra ou criou animais antes de ser atraído pela aventura." },
  { id: "forasteiro", name: "Forasteiro", skillPool: ["cavalgar", "pilotagem", "sobrevivencia"], chooseCount: 2,
    powerName: "Cultura Exótica", powerDesc: "Por sua diferente visão de mundo, você pode gastar 1 PM para fazer um teste de perícia somente treinada, mesmo sem ser treinado nela.",
    items: "Um diário de viagens, um traje de viagem estrangeiro, um instrumento musical exótico.",
    description: "Veio de terras distantes, com cultura desconhecida no Reinado." },
  { id: "gladiador", name: "Gladiador", skillPool: ["atuacao", "luta"], chooseCount: 2,
    powerName: "Pão e Circo", powerDesc: "Por seu treino em combates de exibição, você pode escolher causar dano não letal sem sofrer a penalidade de –5.",
    items: "Uma arma marcial ou exótica, um item sem valor recebido de um admirador.",
    description: "Ex-combatente de arena, em duelos até a morte ou encenações de exibição." },
  { id: "guarda", name: "Guarda", skillPool: ["investigacao", "luta", "percepcao"], chooseCount: 2,
    powerName: "Detetive", powerDesc: "Você pode substituir testes de Percepção e Intuição por testes de Investigação.",
    items: "Apito, insígnia da milícia, uma arma marcial.",
    description: "Ex-agente da lei de vila ou cidade, com treino em investigação e combate." },
  { id: "herdeiro", name: "Herdeiro", skillPool: ["misticismo", "nobreza", "oficio"], chooseCount: 2,
    powerName: "Herança", powerDesc: "Você herdou um item de preço de até T$ 1.000. Você pode escolher este poder duas vezes, para um item de até T$ 2.000.",
    items: "Um símbolo de sua herança (anel de sinete, manto cerimonial) que permite ser reconhecido por sua descendência.",
    description: "Nascido em linhagem tradicional de nobres, mercadores, conjuradores ou família de destaque." },
  { id: "heroi-campones", name: "Herói Camponês", skillPool: ["adestramento", "oficio"], chooseCount: 2,
    powerName: "Amigo dos Plebeus", powerDesc: "Você consegue hospedagem gratuita, para você e seus aliados, em famílias ou comunidades plebeias.",
    items: "Kit de ofício ou uma arma simples, traje de plebeu.",
    description: "Campeão local amado pelo povo por atos de heroísmo em sua vila natal." },
  { id: "marujo", name: "Marujo", skillPool: ["atletismo", "jogatina", "pilotagem"], chooseCount: 2,
    powerName: "Passagem de Navio", powerDesc: "Você consegue transporte marítimo gratuito para você e companheiros, desde que todos paguem com trabalho (um teste de perícia adequado durante a viagem).",
    items: "T$ 2d6 (último salário), corda.",
    description: "Ex-tripulante de embarcação, marítima ou até mágica/exótica." },
  { id: "mateiro", name: "Mateiro", skillPool: ["atletismo", "furtividade", "sobrevivencia"], chooseCount: 2,
    powerName: "Vendedor de Carcaças", powerDesc: "Você pode fazer testes de Sobrevivência para sustento, como a perícia Ofício.",
    items: "Uma barraca, um arco curto, 20 flechas.",
    description: "Caçador experiente de comunidades que sobrevivem da caça de animais selvagens." },
  { id: "membro-guilda", name: "Membro de Guilda", skillPool: ["diplomacia", "enganacao", "misticismo", "oficio"], chooseCount: 2,
    powerName: "Rede de Contatos", powerDesc: "Graças à influência de sua guilda, você pode usar Diplomacia para obter informação sem custo.",
    items: "Kit de ladrão ou kit de ofício.",
    description: "Membro ativo (ou ex-membro) de uma grande guilda de artesãos, mercadores, magos ou criminosos." },
  { id: "mercador", name: "Mercador", skillPool: ["diplomacia", "intuicao", "oficio"], chooseCount: 2,
    powerName: "Negociação", powerDesc: "Você pode vender itens 10% mais caro (não cumulativo com barganha).",
    items: "Uma carroça, um trobo, mercadorias para vender no valor de T$ 100.",
    description: "Comerciante experiente, seja em tenda, caravana ou bazar." },
  { id: "minerador", name: "Minerador", skillPool: ["atletismo", "fortitude", "oficio"], chooseCount: 2,
    powerName: "Escavador", powerDesc: "Você se torna proficiente em picareta e não sofre penalidade em deslocamento por terreno difícil em masmorras e subterrâneos.",
    items: "Gemas preciosas (T$ 100), picareta.",
    description: "Mergulhou nas profundezas da terra em busca de metais ou gemas preciosas." },
  { id: "nomade", name: "Nômade", skillPool: ["cavalgar", "pilotagem", "sobrevivencia"], chooseCount: 2,
    powerName: "Mochileiro", powerDesc: "Você não sofre a penalidade de armadura e a redução de deslocamento por transportar carga pesada.",
    items: "Bordão, bússola.",
    description: "Nunca pertenceu a um só lugar; vida em constante viagem por caravana ou peregrinação." },
  { id: "pivete", name: "Pivete", skillPool: ["furtividade", "iniciativa", "ladinagem"], chooseCount: 2,
    powerName: "Quebra-Galho", powerDesc: "Em cidades ou metrópoles, você pode comprar qualquer item não superior ou mágico por metade do custo normal (itens velhos/sujos/furtados, não podem ser revendidos).",
    items: "Kit de ladrão, traje de plebeu, um animal urbano (cão, gato, rato ou pombo).",
    description: "Criança de rua que aprendeu a sobreviver por conta própria em grandes cidades." },
  { id: "refugiado", name: "Refugiado", skillPool: ["fortitude", "reflexos", "vontade"], chooseCount: 2,
    powerName: "Estoico", powerDesc: "Sua recuperação de PV e PM com descanso aumenta em uma categoria (normal em condições ruins, confortável em condições normais e assim por diante).",
    items: "Um item estrangeiro de até T$ 100.",
    description: "Sobrevivente de alguma grande guerra ou tragédia que assolou Arton." },
  { id: "seguidor", name: "Seguidor", skillPool: ["adestramento", "oficio"], chooseCount: 2,
    powerName: "Antigo Mestre", powerDesc: "Você ainda mantém contato com o herói que costumava servir. A critério do mestre, em uma emergência, você pode receber alguma ajuda dele.",
    items: "Um item recebido de seu mestre de até T$ 100.",
    description: "Ex-ajudante ou escudeiro de um verdadeiro herói aventureiro." },
  { id: "selvagem", name: "Selvagem", skillPool: ["percepcao", "reflexos", "sobrevivencia"], chooseCount: 2,
    powerName: "Vida Rústica", powerDesc: "Você come coisas que fariam um avestruz vomitar e consegue descansar nos lugares mais desconfortáveis: mesmo dormindo ao relento, sua recuperação de PV e PM nunca é inferior a seu nível.",
    items: "Uma arma simples, um pequeno animal de estimação (pássaro ou esquilo).",
    description: "Criado por tribo bárbara, eremita, animais ou origem sobrenatural." },
  { id: "soldado", name: "Soldado", skillPool: ["fortitude", "guerra", "luta", "pontaria"], chooseCount: 2,
    powerName: "Influência Militar", powerDesc: "Onde houver acampamentos ou bases militares, você pode conseguir hospedagem e informações para você e seus aliados.",
    items: "Uma arma marcial, um uniforme militar, uma insígnia de seu exército.",
    description: "Ex-soldado de um grande exército, alistado ou convocado." },
  { id: "taverneiro", name: "Taverneiro", skillPool: ["diplomacia", "jogatina", "oficio"], chooseCount: 2,
    powerName: "Gororoba", powerDesc: "Você prepara comidas em uma categoria de tempo menor (ex.: uma hora para comidas de até T$ 10). Pode sofrer –5 no teste de Ofício para diminuir mais uma categoria.",
    items: "Rolo de macarrão ou martelo de carne (estatísticas de clava), uma panela, um avental, uma caneca, um pano sujo.",
    description: "Dono, filho do dono ou empregado de taverna frequentada por aventureiros." },
  { id: "trabalhador", name: "Trabalhador", skillPool: ["atletismo", "fortitude"], chooseCount: 2,
    powerName: "Esforçado", powerDesc: "Você não teme trabalho duro nem prazos apertados. Você recebe +2 em todos os testes de perícias estendidos.",
    items: "Uma ferramenta pesada (estatísticas de maça ou lança, à escolha).",
    description: "Origem humilde de trabalho braçal pesado, sem grandes chances na vida." },
];

export const ORIGIN_BY_ID: Record<string, Origin> = Object.fromEntries(
  ORIGINS.map((o) => [o.id, o]),
);
